### PR TITLE
[New Sheet] Roll for Shoes

### PR DESCRIPTION
**Pull request by joshforisha**
# Submission Checklist

## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: Roll for Shoes
- The publisher of this game is: independent (public domain)
- The name of this game system/family is: Roll for Shoes

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: [rollforshoes.com](https://rollforshoes.com)
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

### CODE REVIEW

**Comment by NorWhal** [comment]
Hello @joshforisha,

I see you've ticked the "This sheet has been made on behalf of, or by, the game's publisher" box on this PR but you don't list the publisher's name. Do you have authorization from the author to make this sheet official, with their name attached? If you don't that's not against any rules, we just can't make this an official sheet.

If you're able to provide proof of authorization, we can proceed as-is, but otherwise we'll need to make this a community sheet instead.

**Comment by joshforisha** [comment]
@NorWhal Well, I effectively *am* the publisher, since I own and operate the website for the game. I've added a Creative Commons license for it. The original ideas (linked to from the site) are from an ambiguous forum post long ago, so I'm not sure if that complicates things.

**Comment by NorWhal** [comment]
Hey @joshforisha 

Thanks for the clarification!  Generally, we try and keep the official sheet designation to sheets that are clearly directly created or approved by the system's author.  That does get a little complex when it comes to systems with ambiguous sources, or basic rulesets originated in a public forum and adapted into a more formal context.

In this case, we'd ask that you mark this sheet as unofficial, and leave it as a community sheet.  We'd encourage you to link your website in the sheet.json's instructions, though, to provide an intro to those new to the system!

Let us know if you have any questions here

**Comment by joshforisha** [comment]
@NorWhal That makes sense, thanks!

I've unchecked the "official" box, and added a link to the instructions markup.

**Pull request merged**
