### PR TITLE
[Hack the Planet] Fix Fortune Roll Bug

### PR DESCRIPTION
**Pull request by DarkLavenderVoid**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
Pretty sure removing all of the sheetworkers will break something, and not just fix some bug.

**Comment by DarkLavenderVoid** [comment]
> Pretty sure removing all of the sheetworkers will break something, and not just fix some bug.

The Sheet Workers are in the .js file. The Sheet Workers that were in this html file were redundant. I've tried it this way on the Mortally Bankrupt sheets. But that was two years ago. I'm open to the concept that something has changed.

**Comment by DarkLavenderVoid** [comment]
Yep. I checked that sheet and it's not working. That's bizarre. Added the sheet workers back into the .html file.

**Comment by Anduh** [comment]
> The Sheet Workers are in the .js file. The Sheet Workers that were in this html file were redundant. I've tried it this way on the Mortally Bankrupt sheets. But that was two years ago. I'm open to the concept that something has changed.

Sheetworkers must be on the html file, there are no other method of adding them to roll20.

**Pull request merged**
