### PR TITLE
[Chronicles of Darkness] Organization / Krewe Sheet

### PR DESCRIPTION
**Pull request by PrimalZed**
## Changes / Comments

Adding an option for an Organization sheet or Krewe sheet, based on new rules detailed in Geist: The Sin-Eaters Second Edition.

[Screenshot of Settings changes](https://imgur.com/pdUmmiH)

[Screenshot of Sin-Eater Krewe sheet](https://imgur.com/09CTP71)

These changes re-use existing attributes where there are clear analogies, such as the Health attributes for Membership/Congregation and the Potency (power) attributes for Standing/Esotery.

Includes several styling updates, such as:
* New "entity" attribute to distinguish between `corporeal` (the standard character sheets) and `organization`. Planning for this to eventually include `ephemeral`.
* Placing the top array of nine text fields into a CSS grid rather than an HTML table.
* Placing the "Skills" and "Other Traits" into CSS Flex rather than using float.
* Placing "Merits" and "Other" (Disciplines) into CSS Flex rather than an HTML table.
* Replacing several uses of transparent `input[type="radio"]` and `span` labels for "dots" with buttons and `input[type="hidden"`. Since it uses the same attr name and values, no data migration is necessary.
* Replace `input[type="radio"]` and `span` labels for health boxes and Changeling 2 Clarity with buttons and `input[type="hidden"]`. Since it uses the same attr name and values, no data migration is necessary.

### Data Migration

The display of "-1 -2 -3" wound penalties was simplified to three attributes rather than 16. It is recalculated in sheet version 2 migration, but there doesn't seem to be a way to clean up values of deprecated attributes.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Reonin** [comment]
Hi @PrimalZed it looks like you're trying to make a change to an official Roll20 Character sheet. We're reviewing the PR.

**Comment by PrimalZed** [comment]
@Reonin Thanks! I'm happy to discuss my goals and approach. I've been unsuccessful in attempts to contact anyone on the team maintaining this official Roll20 sheet, so I've simply been submitting PRs. This is certainly the most notable so far, because it's actually adding a new feature to the sheet.

On a similar note, I logged an issue #6188 because changes from my previous PRs have not made it to the community release of the sheet. I understand that it may need more careful discussion and review - the issue is mainly just one of my attempts to get in touch with the team and start that conversation.

**Comment by PrimalZed** [comment]
@Reonin Are there any updates on this? It's gone through 3 rounds of Monday Review with no status updates, feedback, or questions.

**Comment by Reonin** [comment]
Hey @PrimalZed sorry for the very delayed response on this PR. The current iteration of this sheet with the named 'by Roll20' attached to it isn't in the community character sheet repo. I want to push for this to be brought back into the communities hands with your pull request. For now can you remove the 'By Roll20' mentions in the files and I will try and get this merged and pushed for next week provided I can get approval internally.

**Comment by Reonin** [comment]
Hey @PrimalZed I have a quick update. Good news, there’s an ongoing conversation started on your PR. It’s part of a potential policy change that should allow for this sheet and others like it to make it in. The bad news is it might take a few more weeks for that to go into effect.

**Comment by AdolfoDomingues** [comment]
I'm so excited about this!
It's been a while that the Geist book was released and ever since then didn't have any updates on the character sheets. Also, there wasn't any sheet for organizations or ephemeral beings!
Thank you very much for the effort you put on it Zed!

**Comment by PrimalZed** [comment]
@Reonin Are you able to share any further updates?

**Comment by Reonin** [comment]
Yep! It was on the top of my list of things to check back on today. I believe we should be able to finally merge this into the community sheets next week. The older one that still has the "by Roll20" tag will remain there until we finalize what we are doing with it. Thank you @PrimalZed for having patience through this.

**Comment by PrimalZed** [comment]
@clevett Do you want me to commit the changes to "Chronicles of Darkness by Roll20" without changing the sheet/directory name, or do you want me to create a new "Chronicles of Darkness" directory separate from "Chronicles of Darkness by Roll20"?

**Comment by PrimalZed** [comment]
@clevett Since the commit to change the directory/sheet name was the 2nd-most-recent, I just reset the branch to a previous commit. (Then I created a new commit to re-do the most recent change.)

Does this satisfy your request?

In case it's unclear, I changed the directory/sheet name at @Reonin's [suggestion above](https://github.com/Roll20/roll20-character-sheets/pull/6212#issuecomment-626920558). I'm not sure if you guys are coordinating on this, or how you'd like to transition this from a "by Roll20" sheet to a community sheet.

**Comment by Reonin** [comment]
My apologies for the confusion here @PrimalZed . @clevett thankfully found the issue in the PR that in my excitement for it finally going out I missed. So this new sheet will be standalone and not override/delete the other two that are in the repository; and with that in mind it wouldn't need the "By Roll20" in it's title or file structure. 

Feel free to ping me on the upcoming PR so we can finally get this live

**Comment by PrimalZed** [comment]
@Reonin I created !6777. In the new PR, I just took a copy of the 'Chronicles of Darkness by Roll20' to a new directory 'Chronicles of Darkness' and then applied my Organization / Krewe Sheet changes on it.

I'm sure you've realized, but the 'Chronicles of Darkness by Roll20' sheet has already received updates I've submitted - !6031 and !6121. If you want that sheet to match the public release, then those changes will need to be reverted.

At this point, I'm wondering why the 'by Roll20' sheets are in the public repository at all. Maybe keep the folder, but only leave the README.md that indicates maintenance of the sheet is handled in a private repository? My own experience here was strangely difficult to figure out what to do. If community contributors simply cannot contribute to a 'by Roll20' sheet at all, that should probably be mentioned in the README. If there is still some means for a community contributor to suggest changes - albeit likely with greater rigor than normal community sheets - that can also be described.

From what I understand, the 'Chronicles of Darkness by Roll20' underwent the unusual scenario of silently losing any attention from the Roll20 team. Thanks for helping in transitioning it so that updates can still be made for new splats that get released for this game line.

**Comment by Reonin** [comment]
It's that very same unique case that we have are trying to ensure doesn't slip through the cracks! I looked over the new P. R and I will look at it again this weekend and pull it in for Monday. I don't think the new one has any issues but I'll keep you posted regardless, @PrimalZed

**Comment by Reonin** [comment]
The new PR has been merged. Closing this additional one. Thanks again for your patience @PrimalZed

**Pull request closed without merging**
