### PR TITLE
[Chronicles of Darkness by Roll20] - UC 384 - translation tags

### PR DESCRIPTION
**Pull request by Anduh**
## Changes
* adds translation tags to sheet and all roll templates
* minor readability adjustments of some sheet logos and background
* french translation by **Palanthis**

## Comments
* tested on firefox so far

### CODE REVIEW

**Comment by Anduh** [comment]
vampire

Just a thing I noticed at one point, if the translated name of a skill becomes too long, the radio buttons gets misaligned.

**Comment by Medieve** [comment]
I was going to do a tiny change to correct a spelling error but this seems a perfect opportunity. Before this gets merged can you correct **line 149** on the translations .json from:
 "manifistations":"**Manifistations**",
to
 "manifistations":"**Manifestations**",

**Comment by Medieve** [comment]
Oh, I was scrolling through the rest of the entries and noted another typo. 
Line 308 on translations.json
Werewolf: the Foresaken
should be
Werewolf: the Forsaken

**Comment by clevett** [comment]
Greetings @Medieve 

Thanks for finding those for us. :)

**Pull request merged**
