### PR TITLE
[Warhammer 4e Character Sheet] - More fixes in talents and localisation improvements

### PR DESCRIPTION
**Pull request by Robak132**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description

- Fixed visibility of Strider, StoutHearted & Trapper talents
- Divided DISTRACT into DISTRACT-TALENT and DISTRACT (item quality) due to localization problems

### CODE REVIEW

**Comment by Robak132** [comment]
@Djjus Found some more bugs and create more localization tags because DISTRACT has two polish translations depending on context.

**Comment by Djjus** [comment]
Great. I will look at adding logic to the now visible Talents, also Beat Blade is not on list yet either.
One small correction to the previous update, remove the max="1" for Wealthy Talent if you can.

**Comment by Robak132** [comment]
> Great. I will look at adding logic to the now visible Talents, also Beat Blade is not on list yet either. One small correction to the previous update, remove the max="1" for Wealthy Talent if you can.

Ok, also you can click on "Changed Files" and comment on my changes in specific lines so would be easier for me to locate what to change. If you "review changes->request changes" merging will be blocked so no one will accidentally merge code with errors.

**Review by Djjus — APPROVED** [review]
approved

**Comment by Djjus** [comment]
Cool. Thanks for your contributions, really apricate it. (I'm not Mad! ;))

**Pull request merged**
