### PR TITLE
[Level Up - Advanced 5th Edition] - Macro Wording Updates

### PR DESCRIPTION
**Pull request by talktocory**
# Submission Checklist
## Required

- [X] The pull request title clearly contains the name of the sheet I am editing.
- [X] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X] The pull request makes changes to files in only one sub-folder.
- [X] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [ ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by mperes** [comment]
Hey there @talktocory, this sheet is a official sheet, so in order to modify it I need to confirm you have permission from the publisher or is part of the development team. @seregrauko, are we good here?

**Comment by seregrauko** [comment]
i know nothing about this

**Comment by talktocory** [comment]
> i know nothing about this

@seregrauko and @mperes,

I didn't realize that this was an official character sheet and needed permission from the publisher to update it.  Sorry for the confusion.  If I should terminate the PR just let me know.

@seregrauko,

The PR has some wording enhancements that could be considered:
- Changed "Save" to "Roll" in ability check macro output.  I think the code was copied from the saving throw button and kept the same wording.
- Added player name to the title of the skill check macro output to keep it inline with the output from the ability/saving throw output.
- Prevent "()" from showing up in skill check output if no specialty exist.

Cory

**Review by seregrauko — APPROVED** [review]
These are good little bug fixes and improvements to the sheet - these changes can go live for the sheet this time

But please if you have any changes you want to do for the sheet please ask before submitting  we can test together and then submit the PR

**Comment by talktocory** [comment]
> These are good little bug fixes and improvements to the sheet - these changes can go live for the sheet this time
> 
> But please if you have any changes you want to do for the sheet please ask before submitting we can test together and then submit the PR

You got it @seregrauko!

**Pull request merged**
