### PR TITLE
Hexxen-1733-Ulisses-Spiele(Official) - New Feature (new role: parazoologist)

### PR DESCRIPTION
**Pull request by SeardnaSchmid**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <https://www.f-shop.de/hexxen-1733/regel-und-quellenbaende/3130/hexxen-1733-handbuch-der-parazoologie>
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description
I added the recently published role of parazoologist (translations only in german).

### CODE REVIEW

**Comment by mperes** [comment]
@Gorthian @CodenameSupreme @coolguyinlove are you folks food with this pull request?

**Comment by BronsonHall** [comment]
@Gorthian @CodenameSupreme @coolguyinlove Checking in one more time, we're gonna go ahead and merge this if there're no objections.

**Comment by Gorthian** [comment]
No objections from me, but I'm not in charge on this sheet.

**Comment by nmbradley** [comment]
I've asked our publisher relations team to reach out to Ulisses Spiele to get clarity on this given that nobody seems to know who authorizes on this sheet.

**Comment by nmbradley** [comment]
Got confirmation from Ulisses and they've authorized the change. 

> Not part of our team but the added role does exist and the change can be merged.

Internal reference: C7PJZKX1U

**Pull request merged**
