### PR TITLE
[Qin] Remove duplicate tao and fix height of equipment / deeds

### PR DESCRIPTION
**Pull request by Baleine82**
## Changes / Comments
Tao are duplicated five times over.
Also, quick fix to input height for equipment and deeds

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Baleine82** [comment]
@tzunder I wouldn't want to break things you did intentionally.

In my opinion, I think you made a mistake, as I can see that taos are repeted several times (can't fathom why it would be intentional).
As for the text inputs, I didn't got the reason for raising their height that much.

Please answer this if you are not welcoming my modifications

**Comment by tzunder** [comment]
Please do amend and improve.
I started from a previous version and just kept hacking until it seemed right.
My biggest issue was making the dice rolling work properly.
Your help with fixing the layout would be SO very welcome!!
Thanks..
If you tell me when you have a new version I am happy to test it in my account ..

**Comment by Baleine82** [comment]
Rest assured I'm glad you did your changes. The character sheet is a lot cleaner (and there's pictures, yay!).

Let me show you the problems with the taos :
Tao being repeated

As you may see, the tao are being repeated. That's not game-breaking, but a bit annoying :)

**Comment by tzunder** [comment]
> As you may see, the tao are being repeated. That's not game-breaking, but a bit annoying :)

Now I understand.
Yes that's due to my not understanding how repeating fields work on Roll20 character sheets!

By the way we found we had to make some house rules to make Qin work better as a tactical game on a VTT map.
The document is here:
https://docs.google.com/document/d/1SDW8GoJ3nVpi8YRcSWueLr3u3c8srezZuC8sgNySyMY/edit?usp=sharing

**Pull request merged**
