### PR TITLE
Dragoncry

### PR DESCRIPTION
**Pull request by JavierGarciaGarzon**
## Changes / Comments
Changed the text encoding to UTF-8

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [Yes] Does the pull request title have the sheet name(s)? Include each sheet name.
- [Yes] Is this a bug fix?
- [No] Does this add functional enhancements (new features or extending existing features) ?
- [No] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [No] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [No] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by clevett** [comment]
@JavierGarciaGarzon This pull requests has conflicts. These will need to be resolved before I can merge it.

**Comment by JavierGarciaGarzon** [comment]
I dont know how to resolve it, because when i update my local version the encoding is different than when i try the pull request, its posible to delete the character sheet and update as a new one?

**Comment by clevett** [comment]
@JavierGarciaGarzon 

You may need to update your fork with live. Just put in a pull request and use the compare across forks. You want to change the fork so its Roll20 master into your fork's master.

- Cassie

**Comment by JavierGarciaGarzon** [comment]
> @JavierGarciaGarzon
> 
> You may need to update your fork with live. Just put in a pull request and use the compare across forks. You want to change the fork so its Roll20 master into your fork's master.
> 
> * Cassie

The problem is that the comparator file use a different encoding than the real file, so in Roll20 fork's master, for example the world "MANÁ" its okey, but the comparator take it as "MANÃ" so when i update my fork take it as "MANÁ" here is the conflict.

**Pull request merged**
