### PR TITLE
Achtung! Cthulhu (CoC 7th) – Release v1.02 – Bugfixes

### PR DESCRIPTION
**Pull request by zedafty**
# Achtung! Cthulhu (CoC 7th) – Release v1.02

The changes made are _bugfixes_.

# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description

- Fix weapon damage bug (wrong value in macro)
- Fix unnamed weapon damage attribute missing
- CSS minor consistency changes

### CODE REVIEW

**Comment by NorWhal** [comment]
@zedafty looks like the changes you're describing in this PR aren't present, and you're changing the french translations instead. If you are looking to add translations to a sheet, the directions to add those are [right here](https://help.roll20.net/hc/en-us/articles/20495433257623-How-to-Contribute-to-RPG-Character-Sheet-Translations-on-Roll20). It cannot be done through github, as those changes will be overwritten.

**Comment by zedafty** [comment]
> @zedafty looks like the changes you're describing in this PR aren't present, and you're changing the french translations instead. If you are looking to add translations to a sheet, the directions to add those are [right here](https://help.roll20.net/hc/en-us/articles/20495433257623-How-to-Contribute-to-RPG-Character-Sheet-Translations-on-Roll20). It cannot be done through github, as those changes will be overwritten.
Hello @NorWhal !
No, no, the french translation addition was a mistake ! The second commit of the pull request reverts the first (by deleting this erroneous change) :)
And the bugfixes for weapon damage should be there in HTML, but no preview is available has the source code is too long to be displayed through GitHub (same thing for the CSS consistancy fixes).
I added the french translation for this sheet to CrowdIn last friday (2024-02-09).
If necessary this pull request can be deleted and I can create a more “clear” one, as you wish !

**Comment by BronsonHall** [comment]
Hey @zedafty 

Gotcha, thanks for clarifying.  Looks like that second [commit](https://github.com/Roll20/roll20-character-sheets/pull/12575/commits/fd8649eba1ab1388d8d4aa002f83ef16cee09443) might have reverted all your other changes as well though, not just the translation!  If you wouldn't mind making a new PR, I can get that merged through.

Thanks!

**Comment by zedafty** [comment]
Hello @BronsonHall !

Thank you for the reply ;)

It's done, will be much nicer with a new pull request 😅 

Just here : https://github.com/Roll20/roll20-character-sheets/pull/12605

The current pull request can be closed/deleted.

Have a nice day !

**Pull request closed without merging**
