### PR TITLE
[RuneQuest:Glorantha] Added translation tags

### PR DESCRIPTION
**Pull request by Lockbox313**
## Changes / Comments

Added Translation tags
Created translation.json

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Reonin** [comment]
Hi @Lockbox313 there seems to be some merge conflicts in your html. Please take a look and if resolved I can get these into next weeks push. It might help to rebase these changes onto the branch that was merged in prior. Cheers.

**Comment by Lockbox313** [comment]
How do I do this if the resolve conflicts button is disabled?

**Comment by Reonin** [comment]
Hi @Lockbox313 locally you can use either the Command line or if you'd like Using the github app locally and trying to resolve the conflicts there. For what it's worth the 'Resolve Conflicts' is also disabled on my end as well because apparently the change made are too complex for the web editor to handle.

**Comment by Lockbox313** [comment]
Can I do this from the web interface?

**Comment by Lockbox313** [comment]
Hopefully I have resolved this and opened a new pull request https://github.com/Roll20/roll20-character-sheets/pull/6447. I am not asking you to merge the new pull request can you just check it?

**Pull request closed without merging**
