### PR TITLE
RMSS- Major update (staging)

### PR DESCRIPTION
**Pull request by suldae**
Major update of the PRO-only Full-Calc-RMSS Sheet prior to pushing it to the main sheet.
Update includes:
Rewrite to use divs/spans instead of tables in most cases.
Added skill category and ranks to skill check rolls.
All-in-one macros updated to display skill category and ranks on the dropdown menu.
Removed most disabled inputs and replaced with read-only inputs for sheetworkers.
Added sheetworkers to total skills, copy stats to skills, copy category totals to skills, copy attack offensive bonus to combat page if attack names match, copy armor presets to active column, add coin-weight to encumbrance calculations, and force skill recalculations.
Additional CSS to support the divs/spans instead of tables as well as the checkboxes for the armor copy.
Added check boxes in Setup tab for OB copy and force skill recalculation.
Added rounding to equipment and power point fields.
Removed unnecessary sheet- from html classes.
Added 2 additional equipment location fields:  armor and a second "stash" location.
Added locations to coins for encumbrance calculations.
Added ability to change number of coins per pound.
Separated npc close section code from pc close section code.
Updated translation.json for new fields etc.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by suldae** [comment]
Did I manage to fix it?  I don't even know how that got in there; I forked a new repository before the first pull and it had all these Fallout Vaults changes and I never touched those files.  I tried not to include them, but obviously I missed one.  
If this didn't work, can you tell me how to get rid of that commit entirely and I will and try to redo it.  Or should I delete and refork again?

**Comment by Anduh** [comment]
Yeah, you managed to fix it. The trouble with the Fallout files should be fixed for the future, as a renaming fix was submitted this week.

**Comment by suldae** [comment]
Thanks. :)

**Comment by Anduh** [comment]
No wait, I misspoke. The fallout html file is still being removed.
Sorry, I looked at the checks being passed, not on the right thing.

**Comment by suldae** [comment]
So should I just delete my fork and start over again?  or will that mess things up even more?

**Pull request closed without merging**
