### PR TITLE
[Monster of the Week Official] Update translations/en.json

### PR DESCRIPTION
**Pull request by taralx**
For whatever reason, there's a big diff between translation.json and translations/en.json. Neither one looks better than the other, but en.json is full of duplicate list items and some obvious errors.

I've tried to make as small a fix as possible here, but this will potentially cause some confusion where people have picked the "wrong" version of a duplicate. Not sure how to fix that.

cc @fredhicks

### CODE REVIEW

**Comment by fredhicks** [comment]
The translations subfolder is, near as I can tell, automatically generated by something at some point, but I've given absolutely no attention to it.  The translation.json file outside of that folder-I've-never-touched is the authoritative source.

**Comment by Anduh** [comment]
> The translations subfolder is, near as I can tell, automatically generated by something at some point, but I've given absolutely no attention to it. The translation.json file outside of that folder-I've-never-touched is the authoritative source.

It's automatically generated, and *should* be automatic updated based on changes to `translation.json`, but occasionally this doesn't happen. I've seen it second hand a couple of times here, along with some other i18n related oddities that pop up now and then, so there is clearly some bugs or hiccups in the process in general.

It has likely to do with how the fan-submitted translation submitted through CrowdIn interacts with updates coming from github the same week. I've once or twice manually submitted translation fixes through CrowdIn when the updates from github get overwritten for some reason from things pulled from CrowdIn.

These past Issues might be tangentially relevant to these translation issues:
* #7509
* #7459
* #7386

**Comment by taralx** [comment]
So should I wholesale replace translations/en.json with translation.json?

**Comment by Anduh** [comment]
> So should I wholesale replace translations/en.json with translation.json?

No, do not replace the `en.json` with `translation.json` outright. But it seems it's not something that had gone completely right in #6997, where the `translation.json` was updated with a number of changes, but all of them might not have been propagated to the actual translation files, as  it can be seen that `en.json` still uses "Gender" while the `translation.json`-file have the later update of "Pronouns". I checked the live sheet, and it incorrectly displays "Gender" in English. I submitted an update through CrowdIn for "Gender-> Pronouns" and we'll see how it interact with your translation update for this week.

### How the translation stuff seems to work
Really, this is a bit of a mess, as Roll20 prefers translation changes to be submitted through CrowdIn(for a good reason), as when they are done on GitHub, Roll20's update scripts might or might not work properly to update everything, and there is a chance changes on CrowdIn on the same week might overwrite github-based translation fixes.

As @fredhicks just said, he haven't touched the `translation.json` since creation(apart from #6997 that might have not update the rest), so that is the file which is actually more out of date than `en.json`. And he have been reasonably cautions to update the core `translation.json` file, as updates to it could adversely propagate to the other translation files due to how Roll20's automation surrounding this works.

For the languages that haven't been translated at all, the .json file should ideally look like the `en.json`/`translation.json` files, but there seems to be a discrepancy between the three.

I'll inquire Roll20 about this translation files stuff now, as the number of smaller issues and uncertainties have been bothering me a while, maybe we'll get some better advice/guidelines on how to handle this in the future.

### About CrowdIn & Roll20

- If you want access to CrowdIn, email cassie@roll20.net about it and she'll get you access. It's a good thing to have access to as a sheet author, if your sheet have translation files. 
- Sometimes a bug with updating things through github persists/gets overwritten by Roll20 translation script/CrowdIn, so it might be better to submit a fix though there.
-  Roll20 encourage making translation changes there, instead of github, when possible. But think it only applies when you make updates to individual translations, not just 
- Although I think in most cases when you update the core i18n-string, it's easiest to manually also make these changes to the language-specific files, rather than painstakingly go through everything on CrowdIn
- Seems you can't update the core `translation.json` file on CrowdIn
- I submitted a CrowdIn update for "Gender-> Pronouns" for English, and suspect it should completely override any changes to the `en.json` submitted through GitHub the same week. If that happens, I'd be more certain on how Roll20 handles this

### Translation Stuff in general
I'll update https://wiki.roll20.net/Translation and the https://wiki.roll20.net/Character_Sheet_Translation pages with some new notes on how Roll20 handles CrowdIn, Sheet Translation updates, and the related things, so hopefully these things will be more clear in the future.

**Comment by fredhicks** [comment]
Well this mess is certainly convincing me that translation support is barely worth it. It either needs to _just work_ or I can _just drop it._

There's never any scenario where en.json should not just be a verbatim copy of translation.json. 100% of the time true; never not true.

**Comment by fredhicks** [comment]
I'm likely to be doing a number of small changes to the MOTW sheet this week. I keep a separate copy as the authoritative source because, to be frank, I don't trust the github environment not to fuck up my months of dedicated work (this translation mess tangentially qualifies, so, justified), nor to respect the idea that this is Evil Hat's official sheet implementation.

**Comment by Anduh** [comment]
Okay I just heard a little something that there will be a bigger update on these translation things in a week or two, so lets not stress on thing or put any massive effort on them for now.

**Comment by taralx** [comment]
Okay, I'll close this for now and we'll see what happens in a short while.

**Comment by Anduh** [comment]
Oh this one is small and fine, I was more talking about Fred postponing the thought to drop translation support to after we have more info.

AndI heard about this only  *after* I spent unnecessarily long on writing the comments here...

**Comment by fredhicks** [comment]
@Anduh Those comments were super interesting. I'd be curious about the findings too. Putting the en.json changes through this week as a way of testing that could be valuable info for all parties. But, this may intersect with my own coding time for MOTW *if* this Friday allows for it. Yesterday didn't (was working on other sheets); today's got some other stuff going on too.

**Comment by fredhicks** [comment]
Thanks for the heads-up!

**Comment by taralx** [comment]
Ok, well, hopefully someone suitably credentialed can let us know if this will be overwritten by CrowdIn or if it can be merged.

**Comment by mperes** [comment]
Hello @taralx ! Your Pull Request includes changes to translation files. We will not deny your Pull Request, but we would prefer sheet contributors use Crowdin for translations. Please email Cassie at cassie@roll20.net and she will get you an invite to our Crowdin. Be sure to include the languages you would like to translate, and please use Crowdin for future translation updates! Thanks for all you do!

**Comment by taralx** [comment]
*sigh* This was partly reverted by https://github.com/Roll20/roll20-character-sheets/commit/aeaff2102765799082d4b4f123ecf155dace896c -- not sure where that commit came from.

**Comment by Anduh** [comment]
Check out the recent changes in Translation stuff: https://app.roll20.net/forum/post/9382237/translation-and-crowdin-changes

I suggest you submit fixes for the translations through CrowdIn in the future: [Roll20 link to sign up](http://translate.roll20.net/join?h=gn0Hd%2Bl672qdPaGVSa81kzUgmSaMuP3Wq93UyCTtMkifXKUUhnw6f0tnKqoQ%0Aw6o%2BFyd0p5DDmmy1kEbYmkT2wOIk%2Bb3AVhS%2FoHMJE3Ghq%2FqcQBBcDrTZ3g1o%0AKY6z%2BlXK5K12hnidiSF4BrRZRmAnYLHTQqjL%2B70yYZzkGq2V1EzG%2BrnVk8Nk%0AL8CFCLqiXdOlm2%2BZ5PM3hCTzC26TZ84dEevV2j6nwVfQNdDpRhCqeSXIl0jr%0A%2Bu9bkn8%2FUBzuXMPRxil1NPVjEvF0%2FZFqpPl3EzQ%2Bkaid9j6EFkO1p1%2B2%2BYuF%0A%2B1dDmw%2FgZbtJfW4x7FnA%0A&uid=Roll20)

Community Wiki have some minimal guidance on how to [navigate CrowdIn for Roll20](https://wiki.roll20.net/CrowdIn#CrowdIn)

**Pull request merged**
