### PR TITLE
Add image from Imgur for  coc_7th_ed.html

### PR DESCRIPTION
**Pull request by titipucca1**
It's more simple...

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by titipucca1** [comment]
It's seems that tere is a problem with the translation, I don't know why, it's the same file for fr.json.

**Comment by Anduh** [comment]
It may seem more simple to have shorter image links, but it's way less stable to have external hosting for images than have them securely saved on GitHub. Saving images on GitHub is preferred and mentioned in the [Best Practice](https://wiki.roll20.net/Building_Character_Sheets#Best_Practices) section of Character Sheet guidelines.

**Comment by titipucca1** [comment]
@Anduh Yes, but I can't upload the images, I can't pull a request for uplaoding images on Github. I prefer that way too. How can I do it ?

https://drive.google.com/drive/folders/1lvboNcu-eaLQ2vVPwqDkhBjn3FRj-hWr?usp=sharing

**Comment by clevett** [comment]
Greeting @titipucca1 

You just need to put the images into the character sheet older. They can then be uploaded and linked from there.

Please put all changes for a single character sheet into one pull request. You'll want to combine #5290 and #5293 with this one into a single pull request. 

#5276 , #5279 , and #5278 also needed to be reverted and those updates will need to be submitted again to this single pull request.

Thanks,
Cassie

**Pull request closed without merging**
