### PR TITLE
Godbound Sheet

### PR DESCRIPTION
**Pull request by jfredett**
A Godbound character sheet. Now that I have something put together, I wanted to get a PR in in case anyone else was working on it as well.

Please let me know if there's anything special I need to do with a new sheet besides what's in the README. I also hope it's okay to open a PR pre-emptively, but I want to avoid any collision, as the game just released, I imagine there may be someone else working on this too.

-------

Still to-do before being ready to merge:

- [x] Additional CSS fixes (many of the elements are poorly aligned or badly organized
- [x] CSS Enhancements
  - [x] Fonts for title sections
  - [x] Horizontal Rules to add readability
  - [x] Background Image
- [x] Remaining autocalculation (primarily around where level factors into stats)
- [x] preview image for sheet.json
- [x] add repeating facts field (to accommodate level up facts)

### CODE REVIEW

**Comment by jfredett** [comment]
Oh -- specifically, there are a lot of "Attribute foo is based on a function of stat X, resource Y, and level", for instance -- saves are "15 minus the greater of two stats, minus your level less one" (in equation form: `15 - max(Stat_A, Stat_B) - (level - 1)`), I don't want to run afoul of the 'no automated advancement' rule in the official sheet, is there a brighter line someone could draw for me on what is and isn't okay? The 5e shaped sheet, for instance, automates a lot of 'level advancement'-y stuff, but it also has the benefit of the compendium and some special relationship w/ Roll20; so I don't know what's okay and what isn't.

**Comment by jfredett** [comment]
This is, as far as I'm concerned, ready for review to merge. Please let me know if you need me to do anything else. Thanks!

**Comment by pjbehr87** [comment]
In the past I've never done any "preemptive" commits as PRs, I just haven't had the need to, but that being said I'm not against the idea as long as you inform me in the commit so I don't try to push the sheet out before it's done. I can totally understand the need to do this with a brand new game system.

What can put pretty much whatever function you want for rolls, that should never be an issue. The "don't automate level advancement" stuff is due to game copyrights which usually cover stuff like "When character X reaches Y experience they earn level 3 and in turn earn earn the Z ability". So, don't have your sheet follow the character's exp and automatically make them level 3 and give them Z ability. Using a character's level as a reference for a spell is always okay.

There is an exception to this rule though, any sheet that uses an "open gaming license" can have whatever automation you want from their rules because the game creator has made that available to everyone. For instance, WotC released a OGL version of D&D 5e so any automation in the 5e sheet is based off of rules that are in the 5e OGL.

(Just FYI: I don't have time at the moment to review/merge this, I'll probably take care of it later today)

**Comment by jfredett** [comment]
@pjbehr87 Okay, I think I'm okay with what I've automated -- no abilities / etc get added automatically, only some math to calculate saves and the like. 

This sheet is ready for merge at your convenience (I finished it up last night). There's some work left for a second pass, but this is going to be plenty for people to start playing.

**Comment by pjbehr87** [comment]
Everything looks really good. Just 1 minor change, that I will make. The "authors" property in the sheet.json is looking for just a string, not an array. Don't worry about it, I'm going to fix it.

**Comment by jfredett** [comment]
Sure thing. Thanks @pjbehr87!

**Pull request merged**
