### PR TITLE
Initial Commit for d20 Modern

### PR DESCRIPTION
**Pull request by CoalPoweredPuppet**
Initial Commit for d20 Modern

### CODE REVIEW

**Comment by SteveKoontz** [comment]
Your sheet.json has some errors. There is a typo on the css reference and no file extension on the preview picture.

**Comment by CoalPoweredPuppet** [comment]
Alright, I will see about fixing it.

**Comment by CoalPoweredPuppet** [comment]
I think its fixed now, not sure.

**Comment by CoalPoweredPuppet** [comment]
Hooray!  Thanks again!

**Pull request merged**
