### PR TITLE
Call_of_cthulhu_7th_ed extention

### PR DESCRIPTION
**Pull request by orphs**
## Changes / Comments

• Added a new button designated for Bouts of Madness, Common Dicerolls and Body Hit Location.

• Moved ''Mana Points'' to the left under ''Luck'', so ''Bouts of Madness'' could fit under ''Sanity''

• Added ''Bouts of Madness'' with relevant roll Templates to avoid games halting and losing pace.

• Added ''Dice Rolls'' Section with most used dicerolls, A custom diceroll input and Body Hit Location with rolltemplates and buttons.

• Added Background Color and made the font Bold.

• Reduced Textboxes' height. (they rarely see use of more than 2-3 lines).

• Added necescary Translations.

• **DID NOT** update the sheet.json

### CODE REVIEW

**Comment by orphs** [comment]
Hey Clevett. I noticed you changed the translation in the en.json, removing ''Bouts of Madness'' , ''Dice Rolls'' , ''Stable'' and ''Custom''. This makes the Headers and Placeholders in the char sheet appear in brackets and red. Is it a mistake or a specific reason behind this?

**Comment by clevett** [comment]
Greetings @orphs 

Translations are an automated process. I looked over your PR again and noticed you added new keys to the en.json instead of the translation.json. The process uses the translation.json as a source and creates the children languages files from that. My best educated guess is that updating only the en.json caused those entries to be removed since the keys are not in the translation.json. 

If you update the translation.json with new keys it will update all the language .jsons with the new entries.

Thanks,
Cassie

**Comment by orphs** [comment]
Ooooh I see. I thought the en.json should be updated since it showed having undergone the latest updates. Thank you very much for your time. :)

**Comment by clevett** [comment]
You're welcome. Also sorry for the trouble and this is something I'll add to my notes. I'm still learning the translation process as well.

**Comment by orphs** [comment]
You're not serious right :P ? Im the one who should be apologising for bugging you with silly questions. And while i'm at that, should I make a new Pull Request for the Changes in the Translation.json or will the changes Merge Automatically?

**Comment by clevett** [comment]
You'll want to make a new pull request. Just add those same keys you did to the en.json to the translation.json. I'll double check it after I run them next week to make sure they are added correctly.

**Comment by orphs** [comment]
Sure thing. Thanks alot again, and leme know if you wanna play any Cthulhu :p

**Comment by clevett** [comment]
I actually do. I really really do. :) I've so many games so little time. I think I've booked myself till June.

**Pull request merged**
