### PR TITLE
Le donjon de naheulbeuk 2.8

### PR DESCRIPTION
**Pull request by Kaias26**
## Changes / Comments
- Bug fix after removing Buffs
- add new UI for guns
- add support for Compendium (google sheet)
- add nightMod
- remove spell import (json)
- improve inventory UI

### CODE REVIEW

**Comment by Kaias26** [comment]
**I dont know why update v 2.7 is in this pull request since it was already merged 2weeks ago ??**

I dont know why gitHub found conflicts beetween my own code...
i resolved all the conflicts but he created a weird merge (master into master) with other games commits inside @_@

@clevett tell me if this pull request is too weird i dont realy know what's going on :s

**Comment by clevett** [comment]
Did you update your master fork before working on this? I squash and merge the commits before deploying them. It is likely GitHub attempting to resolve your fork's commit history with the Roll20 Master repository. 

You'll want to pull the Roll20 Master into your fork by creating a pull request and selecting your fork on the left hand menu.

**Comment by Kaias26** [comment]
hum, I never updated my fork, that must be it...
i've pulled the "upstream" is it good enough for you to merge ?
otherwise, i'll delete my fork, create a new one and redo my comits again...

**Comment by clevett** [comment]
You should go to the **Files Change** tab on this pull request and look over your commits here to see if you've overwritten your 2.7 changes in a negative way. From a brief glance this pull request looks okay to me but I do not know your code well enough to be sure. 

They key to merging in commits that have been squashed is just syncing your fork's commit history with master. I think "upstream" pull may help but to be honest I'm still learning Git myself. :)

**Comment by Kaias26** [comment]
Yeah the Files change is good 👍

**Comment by clevett** [comment]
Cool. Git sometimes has the happen when the history are off and it needs to synch. As long as everything looks as it should then we'll proceed as planned. :)

**Comment by Kaias26** [comment]
@clevett i couldn't figure it out how to create a pull request FROM your base to my fork, and I've found a nice tuto, if anyone struggle like me :D
https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser

As you can read, the steps are easy but a little bit silly...

**Comment by clevett** [comment]
@Kaias26 

Thanks for sharing that link. This came up recently on the forums and I wanted to update the GitHub wiki we have. This link will be very helpful. :)

**Pull request merged**
