### PR TITLE
[Monster of the Week Official] CSS bug workaround and additional playbook

### PR DESCRIPTION
**Pull request by fredhicks**
## Changes / Comments

Roll20 has a rendering bug on production that makes the css render very slightly differently from the custom-sheet testing game. Details here:

https://app.roll20.net/forum/post/8867346/production-has-a-css-rendering-bug/

This update contains a workaround to the .css bug by putting in a dummy style as a buffer between the problem and the actual functional stylesheet.

Also included is a new Spooktacular playbook for folks to use and playtest! (By the time this pull request is merged in, I may have another playbook added as well.)

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix? **see above**
- [x] Does this add functional enhancements (new features or extending existing features) ? **new playbook**
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? **no**
- [x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ? **no changes to existing attribute structure**
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ? **not a new sheet**

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by fredhicks** [comment]
Not sure what this business is about "conflicts", those are just diffs showing the updates that, indeed, I made.

**Comment by Anduh** [comment]
> Not sure what this business is about "conflicts", those are just diffs showing the updates that, indeed, I made.

The conflicts likely stems from your fork and it's branches not being up to date to roll20's repo, and the git workflow you have. 

When you continued working on the MotW sheet in your `Evil-Hat-Official-Work` branch without updating it to Roll20's master branch, it resulted in your branch being "behind". When you continued adding new commits after the ones accepted in last week's PR/merge, and now made a new PR from the same branch, it resulted in some way that your PR is essentially trying to resubmit the whole sheet again + your update. The sheet and your previous commits already exists in the Roll20 repo, so the conflict likely comes from your PR trying to resubmit same changes again.

How to avoid this in the future:

- Keep your fork up-to-date against Roll20 repository 
- When starting to work on a new sheet update, create a new branch from your master branch(that should be up to date with Roll20's master branch).
- When the work is done, the PR is created & later merged, update your repo and create a new branch when working on the next update.

You can check out the two guides we have for this, tailored for interacting with the Roll20 repository:

- https://wiki.roll20.net/Github Beginner's Guide to GitHub
- https://wiki.roll20.net/Git Short Git Guide

**Comment by fredhicks** [comment]
Thanks @Anduh. I thought I was doing what you describe, but clearly I wasn't. I think I've missed a step somewhere about how to get my computer-local copy to "update to the master branch" — and misread the Roll20 github instructions as "you can just keep working on it!"

**Comment by fredhicks** [comment]
Closing this out as @Anduh took care of doing the same work in 6839 but without my (inexperience-induced) conflicts in the picture.

**Pull request closed without merging**
