### PR TITLE
[Chronicles of Darkness] Homebrew

### PR DESCRIPTION
**Pull request by PrimalZed**
### Homebrew
Add Homebrew 1st Edition and Homebrew 2nd Edition sheet types. These give input boxes for the user to enter custom labels of various sections:
* Virtue
* Vice
* Age
* Faction
* Group Name
* Abilities
* Rank
* Resource

### Styling
Completed various styling cleanup. Notably, the CSS used to display / hide based on sheet type has been simplified to a subtractive approach, demonstrated below:

#### Old
Apply `display: none !important;` to all game-line elements and override it with `display: <value> !important;` if it has a class corresponding to the current sheet type

```css
.sheet-mortal,
.sheet-vampire {
  display: none !important;
}

input.sheet-game-line[value="mortal"] ~ * .sheet-mortal,
input.sheet-game-line[value="vampire"] ~ * .sheet-vampire {
  display: inline-block !important;
}

input.sheet-game-line[value="mortal"] ~ * div.sheet-mortal,
input.sheet-game-line[value="vampire"] ~ * div.sheet-vampire {
  display: block !important;
}

input.sheet-game-line[value="mortal"] ~ * table.sheet-mortal,
input.sheet-game-line[value="vampire"] ~ * table.sheet-vampire {
  display: table !important;
}
```

#### New
Apply `display: none;` to elements with class `game-line` and without a class corresponding to the current sheet type.

```css
input.sheet-game-line[value="mortal"] ~ * .sheet-game-line:not(.sheet-mortal),
input.sheet-game-line[value="vampire"] ~ * .sheet-game-line:not(.sheet-vampire) {
  display: none;
}
```

### Misc
* Hide resource checkboxes for Mummy and Beast sheets - these were unlabeled, and are not used in those splats.
* Show Conditions section for Organization sheets.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by clevett** [comment]
Greetings @PrimalZed 

We do not typically accept homebrew content into the repository. Is this a popular home brew rule set somewhere? Is it readily available online?

- Cassie

**Comment by PrimalZed** [comment]
@clevett This isn't applying any particular homebrew, it's letting end-users enter labels for their own homebrew character type in Chronicles of Darkness, or use a World of Darkness translation.

It's a new sheet type (rather than selecting Chronicles of Darkness, Vampire the Requiem, etc) that adds a new section in the Settings page for users to enter in custom labels for particular attributes. In the page 1, it's just like the "Chronicles of Darkness" sheet type except it displays the Rank and Resource section (like most of the sheet types use) and the labels entered on the Settings page are used rather than translation-keyed values.

There are no new calculations or sheet variations to support any particular "homebrew". It's just relabeling attributes.

Here's some screenshots to help illustrate it:

# Settings
image

# Sheet (page 1)
image

**Comment by clevett** [comment]
Thanks for the clarification. :)

**Comment by PrimalZed** [comment]
@clevett Since this wasn't merged in today, will it get left for next week's review?

**Pull request merged**
