### PR TITLE
Added NoReturn Character Sheet

### PR DESCRIPTION
**Pull request by Tealk**
## Changes / Comments

Added NoReturn Character Sheet

### CODE REVIEW

**Comment by Tealk** [comment]
Hello @clevett,

it makes sense to use tables if it is a tabular view?

**Comment by Tealk** [comment]
Hi @clevett 

> relatively responsibly

what's that supposed to mean? What can be improved?

Yes, I see far too many websites that are still completely written in tables, there you get attacks.

Thanks for the fast processing and reply.

**Comment by clevett** [comment]
@Tealk 

Your whole sheet is not tables, only one section. 👍 Also you are not using a lot of inline styles on that table. 

Due to the built in styles of ```<table>```  people often put in a LOT of inline styles to overwrite code.  We're working to reduce [sheet submissions like this](https://github.com/Roll20/roll20-character-sheets/blob/master/Fairytail/FairytailRPG.html).

**Comment by Tealk** [comment]
I closed the tab in fright ;)

I will convert in the next update the tables also into div.

**Comment by clevett** [comment]
Awesome! That would be appreciated. I'll merge this sheet and get it on the drop down list. It should be live in ~25 hours.

**Comment by Tealk** [comment]
@clevett 

one thing i don't understand now, why don't i get a menu with the `<fieldset>`?
image

**Comment by clevett** [comment]
I will have to look into the code. ```<fieldsets>``` have a lot of special handling for repeating sections. They are delicate snow flakes.

**Comment by Tealk** [comment]
There is still the <Fieldsets> problem but now you can take a look at the whole code.

**Comment by Tealk** [comment]
@clevett 
can you help me with the fieldset?

**Comment by clevett** [comment]
@Tealk 

Greetings! My apologies that I have not had time to look into this. I would suggest posting on the character sheet forums, https://app.roll20.net/forum/category/277980 . There are veteran sheet authors who will likely know more than I. :)

**Pull request merged**
