### PR TITLE
Coriolis: Add rolls, roll template, English translation and styling

### PR DESCRIPTION
**Pull request by antila**
Added rolls for all abilities and skills.
Added a roll template to show if you pass the Coriolis style of skill check.
Added some CSS to make the sheet look a bit better.
Converted the HTML to UTF-8 since some browsers had problems with Swedish "Å", "Ä" and "Ö".
Added localization provided by @aunderwo, made English the base language and moved the Swedish translation to the translation folder.

### CODE REVIEW

**Comment by antila** [comment]
I just rebased this on top of the localization work done by @aunderwo here: https://github.com/Roll20/roll20-character-sheets/pull/2387

**Comment by agjwilson** [comment]
I just spent yesterday reworking this sheet. Namely to translate the whole thing, but also to add some design elements that were missing from the original layout. Would it be a good idea to bash heads together and see if we can make some more improvements? 

https://github.com/agjwilson/roll20-character-sheets/tree/master/Coriolos%20English

**Comment by aunderwo** [comment]
It makes sense to work on this together - happy to collaborate

**Comment by agjwilson** [comment]
Do you enjoy the look of having the graphical gifs as background images in the divs. Or is that too busy for the look of the sheet you have created?
I think that the divs should be set to a determined width to avoid dragging over if the sheet is expanded (stretched out) probably trivial to you, however in the rare case it does happen its good to have everything aligned into a static space. 
The logo I created just incorporated a stretch of blank transparency and set to align left, in order to give the illusion of being centred. I couldn't achieve the sheet to maintain an absolute position for both the NPC and PC sheet.

Most my skills are within Graphics not coding, it was just coincidence that I began translating the Coriolis sheet into English while "butchering" or editing some of the code. I am not a great coder, I do tend to butcher the code somewhat. So I'll just put ideas to you. 

**I'll have some time next week to mess around with the code and submit ideas to you firstly.** Perhaps if you like making sheets you could assist me making a sheet for a game which I have been longing for a decent character sheet. I could fill you in at a later date on that.

Antilas sheet looks the best and his could be very well deserved of some appreciation. If you need help or suggestions let me know.

**Comment by antila** [comment]
I agree that the design aspect of the sheet needs some love and there's lots of room for improvement there. Any help and collaboration would be highly appreciated!

@aunderwo and @agjwilson , do we have any plan on what is left to do and what would be the best way to collaborate? I think I fixed all of the missing localization stuffs and bugs I could find, but we should probably double check it, and see if there's any bugs with the rolls.

Maybe we can focus on getting this merged if it's good enough, and then start collaborating on an improved version together?

**Comment by agjwilson** [comment]
I think that's a good plan. Get the sheet merged firstly it offers the best translation and its what players want.

**Comment by agjwilson** [comment]
Earlier I said I butcher code. I just wanted to check on this graphic change to make sure I have not broken any fundament designs needed. I just swapped some tables around so that they rest of different layers. 

```
<table class="sheet-table-thin sheet-table-graphic">
                    <tr class="sheet-table-dark sheet-bb">
                        <td colspan="2">
                            <h3 data-i18n="attributes">Grundegenskaper</h3>
                        </td>
                    </tr>
                    <tr class="sheet-table-bb">
                        <td>
                            <h4 data-i18n="strength">Styrka</h4>
                        </td>
                        <td class="sheet-value">
                            <button type='roll' value='&{template:coriolis} {{name=Styrka}} {{roll=[[@{sty}d6>6]]}}' name='roll_str'></button>
                            <input type="number" name="attr_sty" value="0">
                        </td>
                    </tr>
```

**Comment by aunderwo** [comment]
How do you guys test the changes you make? I currently don't have a Pro account

**Comment by agjwilson** [comment]
I am not going to make any formal changes, I will pass it by Antila first because he knows what he is doing more than I. However I use my pro account for testing. :-) Sorry I can't be of more help with that one.

**Comment by agjwilson** [comment]
So anyway, I have updated Antila's sheet with graphics to represent the original character sheet. This time I was very very careful to add code and replace code without making a mess.

https://github.com/agjwilson/roll20-character-sheets/tree/master/Coriolos%20English

**Comment by agjwilson** [comment]
preview

 Also somewhere along the way the top left options to switch sheet have turned to black font instead of white. Not sure how this happened or if there is a way to change it without changing all the fonts.

**Comment by agjwilson** [comment]
I've also added. So that the weapon tables scroll with the rest of the sheet horizontally.

```
.sheet-weapons {
    border: 0px none;
    margin: 0 auto;
    padding: 0px;
}
```

and

```
.sheet-ship-weapons {
    border: 0px none;
    margin: 0 auto;
    padding: 0px;
}
```

**Comment by agjwilson** [comment]
I've changed the top left character sheet text next to the radio buttons to display white. I also made a small change to the translation file in regards to this also so that it displays "Character Sheet" rather than "Character"

**Comment by pjbehr87** [comment]
Thank you for working together to include everyone's updates. That makes my job a whole lot easier.

**Comment by aunderwo** [comment]
Looks really nice - I had a go at translating the roll templates. Please could someone test it.
https://github.com/Roll20/roll20-character-sheets/pull/2423

Thanks

**Comment by agjwilson** [comment]
@pjbehr87 where on GitHub do I save the image files?

**Comment by pjbehr87** [comment]
Just toss them in the Coriolis folder, just like we do [here](https://github.com/Roll20/roll20-character-sheets/tree/master/5th%20Edition%20OGL%20by%20Roll20). After I accept the PR, you can then update your sheet code to link to the RAW version of the image right on GitHub.

**Pull request merged**
