### PR TITLE
Mutants &masterminds 3e

### PR DESCRIPTION
**Pull request by Project462**
Updates requested by the community.

### CODE REVIEW

**Comment by wing-it** [comment]
This pull request also seems to contain changes to the AD&D 2E sheet that you've already included in another pull request. If you could please remove those files from this request, I could go ahead and merge this one. Thanks!

**Comment by Project462** [comment]
Not sure how to do that short of picking through the code by hand looking for changed lines... The readme is easy, but the html changes are a bit trickier. Is there a way to to separate this stuff when creating a new branch? It would seem I did it wrong.

**Comment by wing-it** [comment]
Generally, to make managing multiple branches easier, it's helpful to keep a 'master' branch that you don't change, and base any new branches off of that. Does that make sense? So, you would have the master branch, the AD&D branch, and a Mutants and Masterminds branch. That way, you can keep the branches from 'contaminating' each other.
For now, if you're sure that the AD&D files are the correct, up-to-date versions that you want included, it will do no harm if they were to overwrite the files from the other pull request. I wouldn't normally want to do that since I have no easy way to compare the files in this request with the other one. Otherwise, if you aren't sure, you might just close this request, delete everything, pull down a fresh copy of the repository, and re-submit your changes.
However, if you sure all of these changes are correct I'll go ahead and just merge this one.

**Comment by Project462** [comment]
Ok, that makes sense. Yeah, the changes are 100% the same. I checked to be sure. (Provided Patch 2 is implemented after Patch to Fix Bugs). Sorry about the mixup. I'm still learning how to use GitHub as odd as that sounds (with my commit record). If you don't mind waiting about 10 minutes, I can go ahead and create a new fork and resubmit though, just to be sure nothing breaks.

**Comment by wing-it** [comment]
A new pull request would be preferable, I'm not in a rush so I can come back to this when you're done.
GitHub definitely isn't very straightforward and takes a while to learn well. I use git every day and still regularly have to ask questions about how to do certain things. If you ever have any questions about how to do something or just general best practices, feel free to ask!

**Pull request closed without merging**
