### PR TITLE
Update for Vampire V5 sheet

### PR DESCRIPTION
**Pull request by chrisleaptrott**
Cleaned up formatting for future edits,
added a section for specialities. Added a Gear Tab with sections for equipment, weapons, and armor.

### CODE REVIEW

**Comment by chrisleaptrott** [comment]
This has been updated to reflect the merger of this sheet and the sheet noted in pull request: #4059 
All files have been updated to reflect this merger and the API script required for roll support has been included.

**Comment by Kirintale** [comment]
^_^

**Comment by TheGrandCoterie** [comment]
Awesome!

**Comment by chrisleaptrott** [comment]
@clevett I will have to quickly check with the co-authors to see what we can work out to ensure that the sheet's rolls work without the script.

**Comment by chrisleaptrott** [comment]
Added a repeating field with non-scripted rolls to accommodate this request.

**Comment by Kirintale** [comment]
Hi Cassie,

The sheet as written requires the API script as it provides added visualisation as well as logic.

I've seen on some sheets such as the DnD one there is a worker script. If functionality were moved to there instead, would this be acceptable?

**Comment by clevett** [comment]
@Kirintale @chrisleaptrott 

Having an optional companion API script is excellent and can be very helpful for adding additional functionally. However an API script should not be required to use a sheet found in this repository. Sheets added here are usable by all Roll20 members regardless of subscription level but APIs are only available to members with Pro access. As it is right now the majority of this sheet's roll buttons currently do not function without the API script which would make for a sad experience for our basic members.  :(

I'll have to request that the sheet be updated to be usable without the API. You're welcome to add in a checkbox or other type of input to toggle on API functionality should a user choose to. 

Sorry for the extra work this causes. Please understand its for the greater good. :)

Thanks,
Cassie

**Comment by chrisleaptrott** [comment]
@clevett The latest commit should add non-scripted functionality in line with the previous WoD and nWoD sheets.

**Comment by Kirintale** [comment]
Hi Cassie I understand about it being script free.  Good idea on the checkbox. 

There is something I am confused about.  You mentioned it can't use the separate Api script, but will it work with the text/worker script in tbe html file

**Comment by chrisleaptrott** [comment]
@clevett The major issue with this sheet in its current form (pre-update) and the sheet with the script is that those rolls in the new system, much like the very recently approved Wraith and Glory 40k sheet (also one that requires a script for roll functionality), need calculations the default inline systems built into roll20's sheets do not provide.

The issue is that you have a stat that essentially replaces the dice you are rolling to provide massively different results (how you crit and crit fail basically), but the dice pool cannot exceed the originally rolled amount. Example:
Basic Dice Pool: Strength + Athletics = 3 dice
Hunger (the modifying stat): Hunger = 4 dice
All dice rolled: 3 Hunger Dice replace the three Basic Dice.

Normal functions in Roll20's inline systems allow for some basic subtraction (what the non-updated sheet very crudely did), but when the Hunger exceeds the Dice Pool the systems break and you have to know that you're only looking at the first X number of dice for it to make sense.

The first rolling system was basically, as I stated on the old pull request, a bit of a stop-gap until scripts could be developed.

Now, the question @Kirintale is asking too is would it be possible to imbed the script into the sheet. I know that normally Roll20 disabled the script tags by default as a protection...so I'd doubt that's the course of action you guys would want to take....

At this point, though, judging by other sheets that are listed in the catalog and the addition of the 'crude' non-scritped roller, I feel like this sheet meets what you've requested....though I'd still argue it would be best served as these other sheets that are 'API-required'.

Thanks for looking into this, though. Sorry to add to your workload.

**Comment by clevett** [comment]
Greetings!

We're happy to help. :) We want to assist your team in finding the elegant balance here. Your comments & concerns have been passed along and our resident Vampire enthusiast has some ideas. We're going to take a look at the rule set and come up with a few potential solutions to offer. I'll be in contact in the near future. 

Thanks,
Cassie

**Comment by chrisleaptrott** [comment]
So, we have a solution thanks in massive part to Barry S. who did the W&G sheet providing us with his method of toggling rolls. Its tested and works....now we've just got to put the time into changing the buttons over.

I will attempt to find the time to do this tonight or across the next couple of days and submit the completed sheet in a new commit.

**Comment by chrisleaptrott** [comment]
@clevett I am very proud to announce that the sheet has been altered to provide a toggle between API and Inline rolls, as with the Wrath and Glory sheet (many thanks to him for that code help).

@Kirintale did the absolute lionshare of the work in getting the sheet up to spec.....so make sure he get's that Sheet Author Tag, haha....this guy's earned it through fire and flames. 

Anyway. Everything should be up to the spec as you've requested. And as a side note....the sheet's looking great. I think people are going to LOVE it.

**Comment by Kirintale** [comment]
Haha thanks man and thanks for your hard work as well. 

Next up! Bug fixes as people find them ^_^

**Comment by Anduh** [comment]
He gets an author tag if his roll20 id is added to the author section in sheet.json 

Good job with collaborating on this one btw.

**Comment by Kirintale** [comment]
It has been. ^_^ I did work on the sheet and did the API.

Thank you, its been a tough but fun project and @chrisleaptrott  has been great to work with.

**Comment by chrisleaptrott** [comment]
@Anduh It was an absolute pleasure to work with someone as focused, humble, and nice as Kirintale on this sheet. I think that the users of it will find an amazing sheet with a lot of love poured into it.

**Comment by Kirintale** [comment]
@clevett Hey. Just to say the updates have been made and this branch is ready for a pull you think it's all good.

**Comment by clevett** [comment]
Hello team,

You've a number of image files going into /Banners . Can you verify these are going inside the vampire-v5/Banners folder ?

Thanks,
Cassie

**Comment by Kirintale** [comment]
Hi, 

They go there, but they aren't used directly. They are kept there as a repo of the current banners rather than used as part of the API.

**Comment by Kirintale** [comment]
*Apprehensive drumroll*

**Comment by clevett** [comment]
@Kirintale I believe you can indeed link to other such sites per the [rules on the wiki](https://wiki.roll20.net/Building_Character_Sheets#Patreon_and_Tipeee_Linking_Rules_for_Community_Sheet_Contributors).

Are these current banners images on yours sheets? I do not mind housing the images on the /Roll20/roll20-character-sheets but they would need to be in a subfolder so we know to which project/sheet they are being used it with. If you were to move them to vampire-v5/Banners/ that would be perfectly fine.

Thanks,
Cassie

**Comment by Kirintale** [comment]
Ace. I'll check the wiki.

The banners are in the sheet via url. I think they are already in a subfolder. If it will cause any issues or anything else needs to be done at the moment I would say just ignore them in the pull, if you can. (Apologies at work and can't do any changes).

**Comment by chrisleaptrott** [comment]
Sorry, I see what happened. The Banners Folder somehow got tossed in my clone of the R20 repo. I'll commit up and fix that.

**Comment by Kirintale** [comment]
Ahh that is why I am confused

**Comment by chrisleaptrott** [comment]
@clevett That should be fixed now. Sorry, that was my fault. Not sure how that happened, to be honest. Anything else that found its way to the root folder instead of the sheet's folder was unintentional.

**Comment by clevett** [comment]
Thanks for getting on top of that so quickly. I'll go ahead and merge this request in for this week.

**Comment by Kirintale** [comment]
Wooo!! Thank you

**Comment by clevett** [comment]
Hey team,

Fyi the current sheet on live has a few issues with some of the translation keys. I looked over your code and I believe this is on my end related to our translator tool. I'll be diligent to make sure this gets fixed this week. I apologize for the inconvenience. :(

We ran into issues with the sheet.json for this pull. It had the wrong image for the preview as well as the html & css file names listed. I fixed these manually so the sheet would go out. You'll want to check over the sheet.json to make sure it is accurate.

Thanks,
Cassie

**Comment by chrisleaptrott** [comment]
@clevett Thanks for the help in getting this in. I did notice the translation errors when loading up the sheet. Thankfully that's nothing too bad. Thank you for your work in getting this up and running.

**Pull request merged**
