### PR TITLE
[Shadowrun 5th] fix warnings

### PR DESCRIPTION
**Pull request by Stexinator**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Arkundar** [comment]
Hi there,
When clicking "modify", I cannot reorder the items in equipment list. 
Tried this in Chrome and Firefox but no success.
A white arrow appears 
but nothing can be moved. Is there a trick?

Also, the sheet seems to be unable to import Chummer contacts and Lifestyles.
Equipment reordering

**Comment by Stexinator** [comment]
Currently the sheet does not provide functionality for contacts and SINs. You can open separate issues for each.
I can reorder without problems on firefox. Drag and Drop the three lines in front.

**Comment by Arkundar** [comment]
I tried and re-tried drag and drop, as any typical drag-drop gesture, with no result,
Except that sometimes, when I try and try, an item "magically" moves elsewhere on the sheet (as on the attached jpeg). Weird...
2021-02-03 07_14_23-Kowalski — Mozilla Firefox

**Comment by Arkundar** [comment]
A clip of the drag-drop problem. Nothing moves. I disabled all my add-ons and tried on Chrome and Firefox. Not working.

SR5_item_reorder1

**Comment by Stexinator** [comment]
@Arkundar this is not the right place. Open an issue for your problem

**Pull request merged**
