### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by suntzu777**

### CODE REVIEW

**Comment by suntzu777** [comment]
found some missing brackets

**Comment by pjbehr87** [comment]
This all looks good! Looks like you've figured out the whole Git thing.

**Comment by pjbehr87** [comment]
This looks good except one small thing. Can you move the mc3 code to it's own folder for me? Currently it's the loose files in the root folder. Thanks!

**Comment by suntzu777** [comment]
can you explain how to move the code to where it is supposed to be ?

thanks

Rob

**Comment by suntzu777** [comment]
i cant seam to create a folder

**Comment by pjbehr87** [comment]
create the folder, mc3.
then use "git mv mc3.html mc3" for each file to move them to the mc3 directory in git.

Here are the docs for git mv: https://git-scm.com/docs/git-mv

**Comment by pjbehr87** [comment]
You don't create the folder on github, you do that on your local copy. If you're on windows just create a folder inside your checked out directory and then a git status should show that a new folder is being added.

**Comment by suntzu777** [comment]
well i am on a mac for starters , but when i upload by dragging and dropping to the main screen nothing is uploaded unless i drop the files directly in to the browser , if they are inside a folder nothing is uploaded

**Comment by pjbehr87** [comment]
I'll explain the regular workflow for working with the code directly on your computer:

1. First create a new directory on your mac to store all of your code. "mkdir ~/repos" (this will give you a good place to keep all of your git code, in your use directory)
2. After you've created your fork (you've done this already), when viewing it on GitHub you should see a green button up at the top right of the window, "Clone or Download". This will give you the repo's url. Which you will use in the next step.
3. Go to your repo folder. "cd ~/repos" and use the git command "git clone <repo's url from step 2>". This will copy everything from GitHub and create a copy on your computer to work with inside folder ~/repos/roll20-character-sheets
4. Now, inside of this new folder, cd branch-name, we want to keep this branch up-to-date with all the changes everyone else it making so we need to run some commands to add the main repo as your "upstream". "git remote add upstream https://github.com/Roll20/roll20-character-sheets". Then before you do any work, always run "git fetch upstream" and this will pull any changes I've made and keep you up to date.
5. If you run "git status" it should say everything is up-to-date because it's brand new and you haven't changed anything, this should also include all of your current changes.
6. Now you can "mkdir mc3" then "git mv mc3.html mc3" for all of your mc3 files. After you've done this you can run "git status" again and it should say something about mc3 files being deleted (only because you are moving them and they no longer exist where they are expected) and a new folder that isn't being tracked.
7. Add the new folder to git, this will also add all of the files in that folder. Do "git add ." (the period on the end means add _everything_). If you do git status again is should show all the new files, in green, as being moved to the new folder.
8. Now you can commit your changes. "git commit -m 'your commit message here'"
8. Then push your changes to GitHub. "git push origin master"
9. Check everything. "git status" should say everything is up to date again.
10. If you go to your branch on GitHub and refresh it should show the new folder with all the files in it.
11. Now you can create the pull request again, and it should show the 2 extra changs plus the new folder with the mc3 sheet inside.

**Comment by suntzu777** [comment]
hi phil  ,had a little read of the help on the git howto’s and it seamed to have worked , well it looks like it from my side of things

heres what i got from the howto
1 fork the repository , which i have done
2 go to my fork
3 create a file ending in a “/“ this creates a folder
4 go to that folder
5 copy/paste files into that folder
6 hit commit
and that seams to work and is simple and i can check my forks directory structure and everything seams to be present

lets hope that works

Rob

**Pull request closed without merging**
