### PR TITLE
[Blade Runner (Community)] New sheet 

### PR DESCRIPTION
**Pull request by dwarfwing**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: Blade Runner
- The publisher of this game is: Free League Publishing
- The name of this game system/family is: Year Zero Engine

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

This is a Community created sheet for Blade Runner the Roleplaying Game, a game published by Free League Publishing. This sheet should be called "Blade Runner (Community)" in the Roll20 sheet repository, according to best practices for community created sheets.  

The sheet is fully functional, but lacking translations (i18n) in this first release. Translation support will be added in a future update to the sheet. EDIT: This has now been added. 
Next version of this will replace the async versions of the getAttrs and setAttrs methods. 

Please let me know if you have any questions or concerns about this PR. 
/Richard

### CODE REVIEW

**Comment by dwarfwing** [comment]
I have since posting this PR also added i18n in the html file and added to the translation.json accordingly.

**Comment by nmbradley** [comment]
A quick note that this is currently under review. We'll have a response for you shortly.

**Comment by dwarfwing** [comment]
Thanks for the update!

If you need more discussion feel free to reach me on Roll20, the userId is in the sheet.json file.

**Comment by bhuesemann** [comment]
Cool, looking forward to this sheet

**Pull request closed without merging**
