### PR TITLE
Ethereal Winds playtest, initial upload

### PR DESCRIPTION
**Pull request by OoznynKoo**
A custom character sheet for Ethereal Winds, starting the first phase of playtesting. Version 1.1 alpha.

## Changes / Comments
Ethereal Winds is the name of a new RPG now being playtested.
This initial upload includes the character sheet html, css and image files.
To the best of my knowledge, the character sheet follows the standards for character sheet building.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by OoznynKoo** [comment]
I'm still seeing Character Sheet Validation check failing, but I don't know where the error is. If anyone can help, it would be much appreciated.

**Comment by Anduh** [comment]
On a quick skim, I can't find anything wrong with the submission. The Verification isn't perfect, and do seem to fail sometimes without a clear reason, so your sheet might be accepted anyway.

**Suggestion:** Change the link on the sheeet.json file's "description to hide the long url with markdown, something like `[Game rules](https://drive.google.com/file/d/15v0GmOZsuxSQctrFcjAnnDoK3O79AzRj)`

**Comment by mperes** [comment]
Hello @OoznynKoo , we normally only make sheet available for published games or in, in a case by case, homebrew systems that have a well documented set of rules publicly available for anyone to grab. I have tried look for Ethereal Winds but could find any information about it. Could you point us out to a site where we can read more about it? Thanks for all the work you do!

**Comment by OoznynKoo** [comment]
Okay, thanks for the heads up. 
Ethereal Winds is new, it is definitely homebrew and it's only getting started with playtesting, which is why it would be great if that could be done over Roll20.
I don't have a website to showcase the game, but the rules document is available to view/download [through this link](https://drive.google.com/file/d/15v0GmOZsuxSQctrFcjAnnDoK3O79AzRj). For now, it's just a pdf-file and it's still incomplete in places, but it's there nonetheless.

**Comment by mperes** [comment]
Hello @OoznynKoo I got a green flag to merge you sheet. Please add the link to the documentation you mentioned on the sheet.json instructions when time allows you ;)

**Pull request merged**
