### PR TITLE
5e roll template updates

### PR DESCRIPTION
**Pull request by chibigoku04**
Unfortunately, I don’t have a method for testing. So, beware….

### CODE REVIEW

**Comment by SteveKoontz** [comment]
What do you mean, you don't have a method for testing these changes?

**Comment by chibigoku04** [comment]
I don't have a Pro account to test these out in the full Roll20 environment. If there is an available demo environment where I can test these changes at, please let me know. I'll be the first to admit I probably didn't dig deep enough into Roll20's developer space.

**Comment by mlenser** [comment]
I believe Actoba already fixed these - I suggest picking them up from there.

**Comment by chibigoku04** [comment]
I actually see very little change in @Actoba's changes from where it was. Again, I didn't test the changes, but I know the way it was caused "roll2" to incorrectly calculate the additional attack metrics.

**Comment by pjbehr87** [comment]
You've got merge conflicts, and github is saying that you are changing every single line of the html which probably means your line-endings are different. Please fix these 2 things, and then I'll take a look at it.

**Pull request closed without merging**
