### PR TITLE
Pathfinder

### PR DESCRIPTION
**Pull request by vince-roll20**

### CODE REVIEW

**Comment by vince-roll20** [comment]
Not sure why this keeps coming up with conflicts.  I used winmerge to check each html, chose the appropriate code and copied it back over my local clone, saved and sent PR

**Comment by plutosdad** [comment]
i still see the javascript is old

**Comment by plutosdad** [comment]
try copying from the main trunk here https://raw.githubusercontent.com/Roll20/roll20-character-sheets/master/Pathfinder-Neceros/pathfinder-neceros.html

**Comment by plutosdad** [comment]
everything starting with <script type="text/worker"> down

**Comment by vince-roll20** [comment]
I did it off the last closed PR.  I'll try again taking code from main trunk

**Comment by plutosdad** [comment]
maybe winmerge is ignoring the script tag since the html looks correct.
 i use trusty notepad++ :) since it's really just pasting over the bottom half of the sheet.

**Comment by vince-roll20** [comment]
Still shows as having conflicts...

**Comment by vince-roll20** [comment]
I'll make a clone of the latest.  Make my changes and add a new PR.  I thought git was supposed to solve these kind of problems...?

**Comment by plutosdad** [comment]
it looks good now!

**Comment by vince-roll20** [comment]
what about the warning?

**Comment by vince-roll20** [comment]
This branch has conflicts that must be resolved

**Comment by plutosdad** [comment]
that is fine, "conflicts" just means you last told gitHub you wanted to get the latest before Riley merged my latest code in. but since you manually merged it, we are fine, just tell Riley to  entirely overwrite the current.

**Comment by plutosdad** [comment]
then you can eliminate conflicts after he is done with the merge in the git desktop by clicking "update from roll20/master"

**Comment by vince-roll20** [comment]
I would never "tell" Riley to do anything...  :-)

**Comment by vince-roll20** [comment]
I'll send him a PM to merge it.

**Comment by plutosdad** [comment]
yes git can solve it but it the desktop app doesn't play nicely. usually i have to go to the gear icon and choose "open in shell" then type some funny commands like 
cd to the directory
git add pathfinder-necerose.html
git merge
then it may ask you to manually merge and it has some + and - rows, which you are supposed to open in an editor and delete one choice and keep the other, (or just paste over with something you merged in another tool). 
then i think 
git commit
git push

and between everything i run
git status
which tells me ... stuff ... 
it is a pain

**Comment by vince-roll20** [comment]
Normally, I make a branch for PF, submit my initial PR and then all other changes are commits to that PR.  If I notice you have also submitted a PR, I have taken your code and added the changes to mine in the hopes of avoiding conflicts.  I believe git handles changes differently, taking historical snapshots of changes or something to that effect, so that even when the code "appears" to be the same it isn't...

**Comment by vince-roll20** [comment]
PM sent to Riley

**Comment by plutosdad** [comment]
yes i think it doesn't try to compare if the dates aren't matching it just yells "conflict! conflict!"

**Comment by rileydutton** [comment]
Okay let me know if that looks right.

**Comment by plutosdad** [comment]
grabbed latest, looks good to me.

**Comment by vince-roll20** [comment]
THANKs Riley

**Comment by rileydutton** [comment]
Okay, pushing to live.

**Pull request merged**
