### PR TITLE
New Sheet pull request: GENERATION

### PR DESCRIPTION
**Pull request by Cacealeos**
## Changes / Comments
SHEET-SUBMISSION
GENERATION is not a published table-top and is my own creation.
Screenshot_2020-12-30 GEN Roll20.png
genCharR20sheet.css
genCharR20sheet.html
sheet.json

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Cacealeos** [comment]
I created a fork, uploaded files, and then made a pull request in my clone repository. If I missed anything, please comment

**Comment by mperes** [comment]
Hey @Cacealeos , in order for us to allow new character sheets to be added to our public sheet repo there needs to be access to the game rules somewhere for players. This means having the rules to play the game available for free or for purchase. Typically on places like Drivethroughrpg, Reddit, a personal website, or something similar. We unfortunately aren't currently equipped to handle an influx of homebrew games and systems. If you could provide us a link to where new players can find a PDF/rules to play Generation, we'll be better able to help get your game listed.

**Comment by Cacealeos** [comment]
Right now I have a link with the Core Ruleset available as a public post on
my Patreon (for free) :
https://www.patreon.com/Portakin?fan_landing=true
<https://www.patreon.com/Portakin?fan_landing=true>
Those who I will be testing the game with can also join my discord where it
is also available. Is this sufficient? Or does there need to be a more
public place to get it?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mperes** [comment]
Hello @Cacealeos I got a  green flag to merge you sheet. Please add the link to the documentation you mentioned on the sheet.json instructions when time allows you ;)

**Comment by Cacealeos** [comment]
Awesome, thanks! I will

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request merged**
