### PR TITLE
NEW SHEET / OFICIAL / MEDIEVO OSCURO

### PR DESCRIPTION
**Pull request by VJRolmasters**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: < Medievo Oscuro >
- The publisher of this game is: <  Medievo Oscuro >
- The name of this game system/family is: < Medievo Oscuro  >

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] This sheet has been made by, the game's publisher.

# Changes / Description

This is the official character sheet for Medievo Oscuro. I'm an author of the game and I'm working on the Sheet for Roll20.

The game, Medievo Oscuro, is currently only available in Spanish. For now there is no support for other languages, hence the lack of translations.

You can find more information about this game at: [medievooscuro.es](http://medievooscuro.es/)

Image from the front sheet
medievooscuro

Image from tehe reduced version of the sheet when de PNJ option is selected
medievooscuro_pnj

### CODE REVIEW

**Comment by VJRolmasters** [comment]
Hi masters

The sheet is ready for review. It's my first "new sheet" for Roll20,  please let me know if there's something wrong o missing. All Medievo Oscuro members are expecting to play soon the game in Roll20 ;D.

Thanks in advance!

**Comment by NorWhal** [comment]
Hello, @VJRolmasters!

Absolutely beautiful sheet, I'm very excited to see it submitted! There are just a couple of changes that need to be made in order to align with [our standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository):

1. There are three `.png` files outside of the "Medievo Oscuro" file that are not allowed to be there. They seem to be duplicates of files you already have in your project folder
2. You use `<table>` elements as a layout in two sections, which is not allowed for new sheets. We recommend using css `display: grid` or `display: flex` to get similar effects (in your case, I suggest the first). More details can be found in the link above. I also found an [article](https://lenguajecss.com/css/maquetacion-y-colocacion/grid-css/) in Spanish that I hope you will find helpful (I was never formally taught, so I'm mostly relying on loan words and what I've learned from friends).

Agradeciéndole de Antemano su cooperación y Hazme saber si tienes alguna pregunta,
Nora

**Comment by VJRolmasters** [comment]
Hi Nora,

Images deleted and tables changed to divs. I hope the sheet is ready to play this weekend :D

Thanks a lot!

> Hello, @VJRolmasters!
> 
> Absolutely beautiful sheet, I'm very excited to see it submitted! There are just a couple of changes that need to be made in order to align with [our standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository):
> 
> 1. There are three `.png` files outside of the "Medievo Oscuro" file that are not allowed to be there. They seem to be duplicates of files you already have in your project folder
> 2. You use `<table>` elements as a layout in two sections, which is not allowed for new sheets. We recommend using css `display: grid` or `display: flex` to get similar effects (in your case, I suggest the first). More details can be found in the link above. I also found an [article](https://lenguajecss.com/css/maquetacion-y-colocacion/grid-css/) in Spanish that I hope you will find helpful (I was never formally taught, so I'm mostly relying on loan words and what I've learned from friends).
> 
> Agradeciéndole de Antemano su cooperación y Hazme saber si tienes alguna pregunta, Nora

**Comment by VJRolmasters** [comment]
Thanks a lot Nora!!!

I can't understand how this files went there. Just deleted.

Can't wait to check the sheet on game.

Thanks for your work and helping me to take this out!

**Comment by NorWhal** [comment]
Glad I could help!

**Pull request merged**
