### PR TITLE
Hexxen-1733-Ulisses-Spiele(Official) - New Feature - Adds new skill animal handling (Abrichten) to the skill list

### PR DESCRIPTION
**Pull request by SeardnaSchmid**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

Adds new skill animal handling (Abrichten) to the skill list.
Animal handling (Abrichten) is a general skill that is mentioned in the core game rules, but not represented in the skills list.
So i added it, because multiple players in my group always have to write it into a open text field to keep track of it... and can't roll the dice for it.

I tried to paste it in alphabetically order in the sheet

### CODE REVIEW

**Comment by NorWhal** [comment]
Hi @SeardnaSchmid 
Everything looks good here, we just need to reach out to our partner at Ulisses Spiel and confirm approval with them.

**Comment by BronsonHall** [comment]
Hey @SeardnaSchmid ,

We've got approval from Ulisses Spiel, just one quick fix we need before we can merge this PR:  
You've currently got the new skill listed in your `translation.json` as well as all the individual translation files in your `translations/` directory.   All the files in `translations/` are actually auto-generated by Crowdin, and tend to cause conflicts when they're edited manually.  You only ever need to change `translation.json` itself, and the individual translation files will update shortly thereafter once the change is merged.  

If you can remove the changes to all files within the `translations/` folder, this PR will be good to go!  Thanks!

**Comment by NorWhal** [comment]
@SeardnaSchmid, If you can make the changes requested above by Thursday this week we can get this merged in, but we'll need to reject this request otherwise

**Comment by NorWhal** [comment]
Closing this request, for reasons listed above. Please feel free to open a new PR with these changes applied

**Pull request closed without merging**
