### PR TITLE
New Character Sheet: The Uplifted Universe

### PR DESCRIPTION
**Pull request by Scruffy518**
# Submission Checklist
## Required

- [ x] The pull request title clearly contains the name of the sheet I am editing.
- [ x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [ x] The pull request makes changes to files in only one sub-folder.
- [ x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <  The Uplifted Universe >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <  Aaron David Lewis Livingstone > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <  The Uplifted Universe > _(i.e. Dungeons & Dragons, FATE)_

- [ x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ x] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ x] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

This is a new system that is in the final stages of development and will be published in the future.

### CODE REVIEW

**Comment by Scruffy518** [comment]
New Character Sheet: The Uplifted Universe

**Comment by NBrooks-Roll20** [comment]
Hi @Scruffy518!

We don't allow character sheets for games that are not (yet) publicly accessible. To move forward with this character sheet, the rules will need to be either purchasable or publicly available somewhere such as a Google Doc, website post, or storefront. A preorder storefront would be acceptable.

It also seems like you've added a blank `roll20-character-sheets` folder to the root level of the repo, which will need to be deleted.

**Comment by BronsonHall** [comment]
Hey @Scruffy518 

Checking back in here, as Nicole mentioned this is blocked until the rules are either publicly accessible or there's a publicly accessible 'pre-order' or 'coming soon' page somewhere - just any way that a player who sees this sheet on roll20 can decipher what game it represents and where they can get the rules when they're available.  

If that's something you're not adding quite yet, might it be possible to either close this PR for now or convert it into a draft? 

Thanks!

**Comment by NorWhal** [comment]
Hey @Scruffy518 

We're going to close this for now. Please feel free to re-submit this to our repository once the above issue has been addressed!

**Pull request closed without merging**
