### PR TITLE
[New Sheet] Everyone is John

### PR DESCRIPTION
**Pull request by Tealk**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: Everyone is John
- The publisher of this game is: Michael B. Sullivan
- The name of this game system/family is: Everyone is John

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: https://1d4chan.org/wiki/Everyone_Is_John
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

- add new EIJ sheet

### CODE REVIEW

**Comment by nmbradley** [comment]
Hi @Tealk 

Unfortunately there is already a character sheet for this game in the repository. It has been Roll20 policy for the last few years to not accept additional sheets where there is already one existing for this game. If you feel that this sheet is a significant improvement upon the existing sheet, please feel free to contribute to that existing one, taking care to preserve user data wherever possible.

**Comment by Tealk** [comment]
Hello @nmbradley 

I have made a new sheet because the old one is not very clear and some of the variables do not make sense. If I change the variables, previous entries are destroyed.

**Comment by Tealk** [comment]
What would be your suggestion how I should proceed? @nmbradley

**Comment by Tealk** [comment]
Well, since no one comments on it, I'll keep the bow for myself.
Who wants to use it must include it as a custom, you can find it here: https://codeberg.org/tealk-roll20-character-sheets/Everyone_is_John

**Pull request closed without merging**
