### PR TITLE
Bruxo - Pacto das sombras

### PR DESCRIPTION
**Pull request by jarbascjunior2**
New Sheet - Bruxo Pacto das sombras by 101 games

# Submission Checklist
## Required

- [X] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _Bruxo Pacto das sombras_
- The publisher of this game is: <   > _(101 Games)_
- The name of this game system/family is: <   > _(Solo10)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: < https://www.101games.com.br/product-page/bruxo-pacto-das-sombras-1 >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by NBrooks-Roll20** [comment]
Hi @jarbascjunior2!

This is fine to merge, but I wanted to give you the opportunity to fix the `roll20userid` field before we merge. That has to be the number associated with your profile, not your name. If you open your profile and look at the URL, you should be able to see it there - `https://app.roll20.net/users/<<ROLL20USERID>>/<<NAME>>`. The name you have here won't give you the sheet author badge.

If you don't want to or don't have the time to fix it, that's fine too. It's not a problem for the sheet itself.

**Comment by jarbascjunior2** [comment]
Hi, I checked this and I think it's ok.
[image: image.png]

Em qui., 1 de ago. de 2024 às 14:50, Nicole Brooks ***@***.***>
escreveu:

**Comment by jarbascjunior2** [comment]
[image: image.png]

Em qui., 1 de ago. de 2024 às 14:54, Jarbas Carneiro junior <
***@***.***> escreveu:

**Comment by jarbascjunior2** [comment]
Thank you.

Em qui., 1 de ago. de 2024 às 15:11, Kayla Fischer ***@***.***>
escreveu:

**Pull request merged**
