### PR TITLE
Shadowrun 5ème Edition ( Français )

### PR DESCRIPTION
**Pull request by Ocxyde**
Fiche de Personnage Française, traduite du travail de Jens 'xyro' ayant fait la version d'origine en Anglais.

## Changes

I've take Character Sheet from Jens 'xyro' and his work.
I translate it to French language. That's all for now.
Some translation are on the way and need to be done.

## Additional comments

shadowrun5th-fr

Provide a few comments about what you have changed. 

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by Anduh** [comment]
Are you aware that the [Readme says](https://github.com/Roll20/roll20-character-sheets#internationalization--translations):
> Sheets that are duplicated and translated manually rather than using this translation process will not be accept.

The prefered method of creating translations of character sheet is to [include i18n-tags into the existing sheet.](https://wiki.roll20.net/Character_Sheet_i18n)

Also, the other [Shadowrun 5th sheet does have french translations already](https://github.com/Roll20/roll20-character-sheets/tree/master/Shadowrun5thEdition), so maybe it's something to use?

**Comment by Ocxyde** [comment]
OK, thank you to let me know.
I'll start to work on the same CS with translation possibilities next week, with i18-n tags.

**Comment by dyvim** [comment]
Oxcyde, you don't have to create a new sheet. You have to update the existing one by adding data-i18n tags and if you have a pro account you have to generate the translation.json file.
It's a long and fastidious task so I wish you courage!
You have copied the Shadowrun5th sheet from Darkxyro but a new one (Shadowrun5thEdition) has been released by clevett a few days ago with all the good data-i18n tags and so this one can be translated. I've began the work but it's long and you have to compare the english and french character sheets to be sure you're using the good terms.
I'll see if your files can help me in the work...

**Comment by clevett** [comment]
Greetings,

I'm going to close this Pull Request for the reasons stated by Anduh & dyvim. If you have further questions let me know. 

Thanks,
Cassie

**Pull request closed without merging**
