### PR TITLE
[Ryuutama][Fix] Fix hot using deep fog mod value

### PR DESCRIPTION
**Pull request by aduyko**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [ ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by aduyko** [comment]
I can't add reviewers, 
@jlvgit would you be the right person to mention on this PR?

**Comment by nmbradley** [comment]
I'm going to leave this open if you are seeking reviewers. Reach out if you no longer feel that's necessary.

**Comment by nmbradley** [comment]
@aduyko Did you want me to merge this or are you still waiting on someone to review?

**Comment by aduyko** [comment]
Hi @nmbradley , sorry about the late response, I missed the notification for your first message.
It isn't obvious to me if there is anyone actively maintaining this sheet available for review.

I think it's a small change and would like to see it merged, just not sure what standard operating procedure is for this kind of situation.

**Pull request merged**
