### PR TITLE
Update fr translation Pathfinder 2E

### PR DESCRIPTION
**Pull request by Vindikaell**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by clevett** [comment]
Greetings,

Translations for official sheets must be done in Crowdin now. JSON for these files found in this repository will no longer update the official sheets.

**Comment by Vindikaell** [comment]
Crowdin is not free...

**Comment by clevett** [comment]
It is free for translators to use. Are you being prompted to pay?

 - Cassie

**Comment by Vindikaell** [comment]
Dam Oo I have think it was all the thing it was not free. Sorry. 

So, I already have translate some word, but it was not save. How it's work? I translate a word, I click on save, and next? How I save all what I translate? How I send you that?

**Comment by clevett** [comment]
In Crowdin just translate the word then click Save.

Let me know an example of a word that you have tried to change which has not saved. 

"by Roll20" translations cannot be done in this repository any longer.

**Comment by Vindikaell** [comment]
No, I just have a link in the up of my screen who said something like that
"2days before end"

I use it this afternoon and it was work. But, all of thing I have already
do was not save. How I must use it?

I select an word, I translate it, I click on "Save", and after that?

Le lun. 28 oct. 2019 à 02:29, Cassie Levett <notifications@github.com> a
écrit :

**Comment by Vindikaell** [comment]
I translate "Shield" in "Bou", bcause"bouclier" was to long.

Le lun. 28 oct. 2019 à 19:44, Cassie Levett <notifications@github.com> a
écrit :

**Pull request closed without merging**
