### PR TITLE
Aria: new character sheet

### PR DESCRIPTION
**Pull request by anis**
## Changes / Comments

This is a new character sheet for the RPG [`Aria` by Elder Craft](https://www.elder-craft.com/copie-de-print), released only one week ago.

I believe it has been made following all good practices.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [X] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [X] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Review by Anduh — CHANGES_REQUESTED** [review]
You have multiple sections in the sheet design made with `<table>` which the Roll20 guideline explicitly mentions to not use.

I my experience, this is among the top 3 reasons new character sheets gets delayed or rejected. [Here is an example](https://github.com/Roll20/roll20-character-sheets/pull/6988#pullrequestreview-451871807) of a PR that was rejected due to using `<table>` in the html.

**Comment by anis** [comment]
Oh, OK, I read about that in the guidelines but I though using table for building.... actual tables would still be accepted?

**Comment by mperes** [comment]
Greetings @anis
We no longer accept characters sheets with layouts built in <table>, https://roll20.zendesk.com/hc/en-us/articles/360037773453

These elements will need to be replaced to meet the require programming standards.

**Comment by anis** [comment]
I'll wait for a definitive review and comply to it but I still stand my case: the requirements states that `As a general standard a <⁠table> element should only be used for tabular data` which is my case.
I use two tables for... tabular data ! 😄

**Comment by Solarswordsman** [comment]
@anis The code standards are just fine here; as you've mentioned, you are using block elements and flexbox for layout and tables for tabular data.  This is perfectly fine.

However, another sheet for this has already been submitted, and we don't allow alternative versions of character sheets.  That sheet has been merged with this pull request: https://github.com/Roll20/roll20-character-sheets/pull/7485

If possible, could you work with the author of that sheet to determine the best way forward? (e.g. modifying and improving that sheet, or switching to this sheet if it is more fully featured and/or easier to maintain)

Thanks!

**Comment by wing-it** [comment]
Closing this PR. If you are able to work something out with the other author, you can re-submit. If you do, please leave a comment describing the solution.

**Comment by anis** [comment]
Sorry I let this PR pending.
Actually we've been in touch for weeks ago (before I opened this PR), and we agreed we were heading towards very different directions with our two sheets, and that was OK (in the sense his is kinda minimalistic while mine offers more automation for rolls and more).
He's not interested in using my sheet, I'm not interested in using his, and we don't think there's an easy opportunity to merge our works anyway.
I understand the policy of "no alternative version" (quite sad about it though) and I'll keep working on my sheet and reserve it to my own games.
Thanks.

**Pull request closed without merging**
