### PR TITLE
[Emysfer] new sheet Codeupdate

### PR DESCRIPTION
**Pull request by surfandko**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by clevett** [comment]
A number of your files are in the root folder. You need to move them into the game folder.

**Comment by surfandko** [comment]
hi, is it ok now ?

________________________________
De : Cassie Levett <notifications@github.com>
Envoyé : samedi 9 mai 2020 17:08
À : Roll20/roll20-character-sheets <roll20-character-sheets@noreply.github.com>
Cc : surfandko <surfandko@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Roll20/roll20-character-sheets] Codeupdate (#6410)


A number of your files are in the root folder. You need to move them into the game folder.

**Comment by Reonin** [comment]
Hello @surfandko thanks for taking the time to remove the tables from your initial pull request it adheres to our standards much better. You have duplicates of many of your files _outside_ of your main folder. If you can remove the ones outside the folder including 'Emysfer-preview.png' we can get this added :D. I will close the other related repos because this seems to be the one were working off of now. Thanks

**Comment by surfandko** [comment]
@Reonin  I done it, is it ok ?

**Comment by Reonin** [comment]
Hey @surfandko the files i mentioned above are the ones that need to be deleted

**Comment by surfandko** [comment]
@Reonin  I already done it ... I have to make a new pull request ????

**Comment by Reonin** [comment]
Nope no worries @surfandko we merged in the changes. I updated the title of the PR to include the game name. Thanks for making the changes. This sheet should be online tomorrow

**Comment by surfandko** [comment]
thank you very much :)

**Pull request merged**
