### PR TITLE
Wild Talents 2nd Edition Edits

### PR DESCRIPTION
**Pull request by Kumatei**
## Changes / Comments

Added more power slots
switch to dice matching

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Kumatei** [comment]
Well, I have no idea how to fix this. It seems to want to merge commits that are already on roll20, and is giving me errors about the changes that aren't.

**Comment by Kumatei** [comment]
Yeah I'm not really sure what went wrong. Most of those changes are already live. Do you know how to only pull certain commits, rather than whatever it's trying to do now?

**Comment by clevett** [comment]
It looks like the merge with master helped. You're just trying to update these two files, correct?

**Comment by Kumatei** [comment]
That's right, the other changes are weird because they are already live.

**Pull request merged**
