### PR TITLE
(HITOS) Create hitos.html

### PR DESCRIPTION
**Pull request by kinower**

### CODE REVIEW

**Comment by kinower** [comment]
yes, I created them in other pull

**Comment by kinower** [comment]
https://github.com/kinower/roll20-character-sheets/tree/master/Hitos

**Comment by Anduh** [comment]
You mean you have the rest in another branch? That's not a link to a pull request here, but a link to your own fork. Did you forget to make a PR from there?

Anyway, it's easier for roll20 if you submit all the files in the same pull request, instead of splitting them up.

**Comment by kinower** [comment]
mmm I do not know how to send all the files together

**Comment by kinower** [comment]
I have created a new folder with a complete character sheet on my own fork and I want to upload it to the community

**Pull request closed without merging**
