### PR TITLE
[Salvage Union] Character Sheet overhaul for version 1.2 of Salvage Union

### PR DESCRIPTION
**Pull request by chuckzee**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <Salvage Union>  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <Leyline Press> _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <Quest> _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

- Addition of tabs to manage Pilot, Mech, Cargo
- Added rollers for all standard rolls needed for the game
- Roll templates added for pilot abilities, inventory, mech systems and modules
- Sheetworkers to manage character attributes and calculate cargo cap
- Tooltips for assistance in filling out sheets

### CODE REVIEW

**Comment by BronsonHall** [comment]
Hey @chuckzee ,

This is a pretty significant update!  Want to double check a couple things:
First, it looks like you've removed a number of roll templates - have these rolls been unified into your new 4 roll templates?  Same for sheet workers, there's quite a bit removed here, just want to ensure that's intentional and accounted for with the additions.

Second, this is your first update to this sheet, and its last edit is within our window to consider it under active development.  @Stexinator , if you're not aware of this overhaul, would it be possible for you to review these changes and provide any necessary instructions for the author of this PR?  

We generally permit 21 days for the original author to respond before we might proceed with merging this PR.  

Thank you both!

**Comment by Stexinator** [comment]
Hey @BronsonHall ,
I am currently not activly developing the sheet. If @chuckzee wants to take it over I got no objections

**Comment by chuckzee** [comment]
Hello @BronsonHall ! Thanks for your comments. Also thanks @Stexinator for your initial work on the beta version. 

So with roll templates I have consolidated them to:

- A general Salvage Union roll template - this handles anytime we roll a d20 for the system, and this was re-used for the 8 'standard' rolls the book prescribes
- "Show" templates which will drop details for Inventory, systems and modules, pilot abilities. 

A notable departure from the original beta version of the sheet is fewer calculations of attributes determining legal rolls, and actually fewer context-driven rolls on individual abilities and systems. Part of the reason for this is that abilities, systems, and modules do not fit a perfect archetype. Some roll on tables. A lot do not. Some use energy, some do not. Some have multiple tables they roll on. So in light of that, I opted for context-driven "Show info" style buttons with the rollers along the top of the page to be used as needed. It avoided a lot of unnecessary cruft when you have a fully loaded mech or pilot.

What I would **really like** to do at some point is provide some kind of roll template for users to drop into a repeatable field & supply it with the custom strings/text from the ability or module. Decided it was a tad out of scope for this.

**Comment by BronsonHall** [comment]
Spectacular!  
Thanks Stexinator for the quick response, and thanks chuckzee for clarifying!
Unblocking this and merging now

**Pull request merged**
