### PR TITLE
halo mythic 3.5 live patch 1

### PR DESCRIPTION
**Pull request by michaelvanweelde**
## Changes / Comments
:green_square: 1 change speech bubble
:green_square: 2 fix infographic not switching to display on first load
:green_square: 3 fix sheet description in R20 to not show 
:green_square: 4 fix melee weapon br pts displaying?00 on load
:red_square: 5 create game settings options for global sheet selection
:green_square: 6 change damage roller desc to hits
:green_square: 7 expose hit mod in roller
:green_square: 8 fix odd tab in placeholder ability text
:green_square: 9 automate calculation of fatigue
:green_square: 10 fix Spts being assigned the value of fatigue in roller
:green_square: 11 improve placeholder for size?
:green_square: 12 add repeating armor desc section to sheet
:green_square: 13 add nav air land space
:green_square: 14 added repeating skills section to NPC sheet

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [yes] Does the pull request title have the sheet name(s)? Include each sheet name.
- [yes] Is this a bug fix?
- [yes] Does this add functional enhancements (new features or extending existing features) ?
- [no] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [only missing attributes were created from defunct attributes] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by michaelvanweelde** [comment]
updated this push after not being able to add default sheet settings

**Comment by MadCoder253** [comment]
@Reonin It appears something weird happened to line feeds for these three files. I think the line endings were somehow set to **\r**. I just did a git merge upstream/master and I have windows so my setting is to pull with CR LF and push using LF (unix style). After the merge, now these three files are showing as being modified, even though I never touched these files before. I also can't Discard the changes, I can't push this to github because it will show that I changed these when I didn't. 

This will probably happen to anyone else trying to do an merge upstream/master. Do you have an idea how to resolve this issue?

**Comment by Reonin** [comment]
Hey @MadCoder253 have you tried rebasing the upcoming branch so your newer changes are sitting on top?

**Comment by MadCoder253** [comment]
Thanks @Reonin. I tried doing:

`git rebase upstream/master`

But I get an error

`error: cannot rebase: You have unstaged changes.
error: Please commit or stash them.`

I was able to discard changes for Halo_Mythic_3dot5/HaloMythic3dot5.html, but not the other two. I tried `git stash`, got the following message, but it still shows the other two files as being modified. Maybe they were committed using CR LF?

`
git stash
warning: CRLF will be replaced by LF in Halo_Mythic_3dot5/HaloMythic3dot5.css.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in Halo_Mythic_3dot5/sheet.json.
The file will have its original line endings in your working directory
Saved working directory and index state WIP on master: ae1653d85 Merge remote-tracking branch 'upstream/master'
`

**Comment by Reonin** [comment]
@MadCoder253 if your worried the lines being changed in the PR for future updates it shouldn't be a problem. But if you don't have any local changes look into potentially

```
git fetch --all
git reset --hard origin/master
```

Which should pull down the latest changes and **overwrite** your local version. If the line endings are still there then it's very likely they were committed at some point. I hope this might point you in the right direction!

**Comment by MadCoder253** [comment]
@Reonin that worked! I'm saving those command lines. Thanks a million.

**Comment by MadCoder253** [comment]
@Reonin Still something wrong. I tried to do `git merge upstream/master` and I have the same problem again. It shows that sheet.json, HaloMythic3dot5.html, and HaloMythic3dot5.css were modified. I have no issues with the other 181 files.

**Comment by MadCoder253** [comment]
@Reonin Oh wait, is it because they are new files? I'm just trying to push up to my fork.

**Comment by Reonin** [comment]
Yep in this very PR that was merged those three files got changed and updated which might be what you are seeing as you try and push your changes to your new branch.

**Comment by MadCoder253** [comment]
Thanks @Reonin that must be it. Sorry for wasting your time!

**Pull request merged**
