### PR TITLE
lest see if this works

### PR DESCRIPTION
**Pull request by suntzu777**

### CODE REVIEW

**Comment by pjbehr87** [comment]
Looks like it clicked! These all look good!

**Comment by pjbehr87** [comment]
I've looked at the sheets and they all look really nice, you've done a really good job on them. A couple quick notes. I had to make a few quick fixes for the sheet.json files for the 3 sheets, to escape some quotes in the description string, so you'll want to make sure to pull my changes before you make too many changes or you'll have merge issues. Second, I think you have the wrong banner for the Conan sheet, it's using the Infinity banner, but in the preview image it says Conan instead. That should be a really easy fix, I would do it myself, but i don't know the file name for the Conan banner.

**Comment by suntzu777** [comment]
No problem Phil , will correct the link tomorrow and do another pull request

Rob

**Comment by suntzu777** [comment]
hi phil , i actually used the wrong file for conan 2d20 , new pull request created with the correct one

Rob

**Pull request merged**
