### PR TITLE
fallout : corrected 1 formula + added 1

### PR DESCRIPTION
**Pull request by laresgod**
corrected the hidden "action points" formula: it didn't add the +5 value it stated
added the "base ac" formula: base AC = AG

### CODE REVIEW

**Comment by pjbehr87** [comment]
You are making changes to the Fallout 3.html (this is correct), but you are also adding a copy of the file to the root directory. Please remove this extra file and pull again.

**Comment by laresgod** [comment]
ok, I am still confused when I pull request in what space I am.

2016-06-14 20:29 GMT+02:00 Phil <notifications@github.com>:

**Comment by pjbehr87** [comment]
When you are going to create a Pull Request it will show you the exact files you are changing. The correct Fallout 3.html file you are changing will say "Fallout/Fallout 3.html", notice the "Fallout" folder in the file name. The one that is being created in the root shows up as just "Fallout 3.html" with no folder at the beginning. You should check for this every time you make a PR.

**Comment by laresgod** [comment]
understood, thanks.

2016-06-14 22:10 GMT+02:00 Phil <notifications@github.com>:

**Pull request closed without merging**
