### PR TITLE
[Call_of_Cthulhu_7th_Ed]  Expansion for other Eras and Settings

### PR DESCRIPTION
**Pull request by orphs**
## Changes / Comments

• Expanded to include options for other Eras, and the Pulp addition.  (Most changes in skills are still unfinished.)
• Added an optional Companions/Vehicles/NPC section (toggled on/off from options on-top of char-sheet).
• Added Major Wound Pop-up section for their bookeeping.
• Made Dice Rolls Section optional (toggled on/off from options on-top of char-sheet).
• Added an optional Armor section under Weapons List (toggled on/off from options on-top of char-sheet).

• Made Era and Pulp selections possible only out-of game Settings.

### CODE REVIEW

**Comment by Lockbox313** [comment]
What do mean by  Made Dice Rolls optional.?

**Comment by orphs** [comment]
An collapsable Options Section is added to the top of the Char sheet. There, there are checkboxes toggling on/off the Dice Rolls Section, the Armor Section and the Companions section.

**Comment by clevett** [comment]
Greetings @orphs 

Since this a big change to a popular sheet be sure to check your changes tomorrow afternoon to ensure they are working as intended. Let me know if you have any emergency hot fixes.

Thanks,
Cassie

**Comment by orphs** [comment]
Hey @clevett 
 All changes seem to be working as intended. However I have found no way of testing if the Out-of-game Options are working. Is there any way to do so ?

**Comment by clevett** [comment]
@orphs 

Not at this time. These changes will go live tomorrow and you can test them then. I'll get any hotfixes needed out ASAP. Its not the ideal solution but its what we currently have.

Thanks,
Cassie

**Comment by orphs** [comment]
Gotcha, Thank you very much :)

**Comment by orphs** [comment]
Hey @clevett 
 I think there might be some mistake in what files got merged in the Call of Cthulhu 7th Ed file. There appers to be a NightWitches .json in place of the .json i commited.

**Comment by clevett** [comment]
@orphs 

These changes are live. Let me know if you have any issues.

**Comment by orphs** [comment]
@clevett 
Hey man. The sheets in-game seem fine. I cant find the out-of-game options though.

**Comment by clevett** [comment]
Out of game options were you select a sheet. Go to the game -> **Settings** -> **Game Settings**

**Comment by orphs** [comment]
@clevett 

Turns out the Out-of-game Options are not working. Toggling any of them does nothing to the in-game sheet. Im trying to find out what went wrong there.

**Comment by clevett** [comment]
Keep me posted.

**Comment by orphs** [comment]
It also appears that only the End Times Era Checkbox can be selected. (from the era Selection.). If any other Era is selected, it reverts back to its default 1920 Era Option.

**Comment by orphs** [comment]
The Era selection problem is easily avoidable for the time. I can make the checkbox selections visible in the char sheet so it is selectable from in-game (works fine in tests i run). I cannot find any reason why it is not working from the Settings though, unless there are other parameters i cant see.

**Comment by orphs** [comment]
Ok, so the first time you create the game and make an Era selection, it will register. However if you attempt to change the Era after the first time, it will revert to Classic 1920's, unless End Times is selected, in wich case End times will register.

**Comment by clevett** [comment]
@orphs @Lockbox313 

It looks like users are having some issues with the [Pulp hit point box](https://github.com/Roll20/roll20-character-sheets/commit/9906bc762f2d379b0dd062c563d6b0758b4eeb71). If you can get this fixed and put in a pull request I'll get it merged for you. 

Thanks,
Cassie

**Comment by orphs** [comment]
Hey , @clevett 
 I have another version ready where all the options appear in the sheet in-game. In this version, everyhting appears to work as intended, no idea why the out of game options are not responsive. Will make a new pull req asap.

**Comment by clevett** [comment]
It may depend on how you are setting the sheet change. The out of game options do not trigger a **change:** but instead just set an attr_. This should work fine if you're using CSS that is using **value=["other_sheet"]** to _display:_ none or show.

**Comment by romelwell** [comment]
@orphs what vetting process did you use to ensure these changes and the updated UX of the sheet were something the community asked for or even wanted?

**Comment by orphs** [comment]
Hey @romelwell  
 The changes were vetted by various people I play CoC with in roll20. However no official vetting proccess was done through roll20's forums/community. Looking back I understand it would have been much more preferable to have done so. I am sinserely sorry for any inconvenience caused. 
 Could you please mention what UI and UX changes were radical for you or your players? 
 I am planning on making a forum post for this particular matter.

**Comment by romelwell** [comment]
Thank you for the replies!  In full disclosure, my weekly group tried out
the sheet last night and was pleased overall.  So while I raised concern
about ensuring community-driven development remains community-driven (i.e.
discussing proposed changes, and not bug fixes, in the Community Forums
before implementation) we were pleased with the updates.  There is no
nerd-rage here, just a concern that I wanted to raise, should another user
in the community also wish to implement their UI/UX.

I really appreciate the forethought put into the changes you made to the
sheet. The two biggest topics of discussion within our group was the
decision to use a gray background (some felt made the sheet easier to read,
others felt it made the sheet dull, cold), and that weapon statics were not
ported over when we opened the sheet for the first time. The players had to
enter in this data again (weapon, skill, damage) on the new sheet before
they could use the associated dice rollers.

**Pull request merged**
