### PR TITLE
[Quantum Black] added custom character sheet for Quantum Black

### PR DESCRIPTION
**Pull request by CrankySkink**
## Changes / Comments

I have added a custom character sheet I developed for the game Quantum Black, at the game's author's request.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by nmbradley** [comment]
Hi @CrankySkink 

Thanks for your submission to the repository. Could you please ensure that your Pull Request features a valid preview image of your character sheet (i.e. a screenshot). The image currently attached appears to the game system logo.

**Comment by CrankySkink** [comment]
@nmbradley I have corrected the issue--that was a misunderstanding on my part. Thank you for the clarification.

**Comment by nmbradley** [comment]
No worries, thanks for the quick response. I'll get you merged up ASAP.

**Comment by CrankySkink** [comment]
The Quantum Black character sheet doesn't appear to be working properly. Is
the sheet.json not being parsed correctly? I used tab characters on each
newline, and it appears that other sheets use two spaces instead. Is this
causing an issue?

Jeremy.

**Pull request merged**
