### PR TITLE
Song of Fire and Ice, button update

### PR DESCRIPTION
**Pull request by CoalPoweredPuppet**
## Changes / Comments

Adjusting buttons, added Journal.
Link to conversation: https://app.roll20.net/forum/post/7032912/a-song-of-ice-and-fire-sheet-need-help-with-roll-template
No attribute name changes

### CODE REVIEW

**Comment by CoalPoweredPuppet** [comment]
...now I have no idea what the hell just happened.  How did my Mekton stuff end up here?

**Comment by clevett** [comment]
If you click **Commits** at the top you can see you merge in the Mekton stuff on 13th December.

**Comment by CoalPoweredPuppet** [comment]
Apparently I am having trouble understanding the Github Desktop's interface.  

Moving on.  "This branch has conflicts that must be resolved" popped up for me.  Is this a thing for me to fix (I think it is) or can only you fix it.  And, if it is mine to fix, how do I do that?

**Comment by clevett** [comment]
Greetings @CoalPoweredPuppet 

You'll need to fix the merge requests. You could revert the commit for the Mekton Z. Alternatively you could close the request, save your changes as a back ups outside the repo folder, and reset the roll20 fork to the master copy.

**Comment by CoalPoweredPuppet** [comment]
I cannot identify what is causing the conflicts.  I will do as you suggested and close this request and try another on (after resetting this thingy-ma-bob)

**Pull request closed without merging**
