### PR TITLE
Starfinder HUD fix for sheet not working as dropdown sheet

### PR DESCRIPTION
**Pull request by Kurohyou**
This should fix the sheet not working as a drop down sheet.

I believe the issue was that the dropdown sheets are limited to ~13000 lines. I had forgotten this. Can't find the forum post on it atm.

### CODE REVIEW

**Comment by wing-it** [comment]
sorry i missed this earlier!

**Comment by Kurohyou** [comment]
Np, is the fix live yet? or is the system still using the old one that was
too long?

**Comment by Kurohyou** [comment]
Hi Wing-it,

Looks like one of the final updates before the sheet went live broke the buff handling feature of the sheet, if I submit a pull request, would it be possible to get it merged before the usual merge day?

Thanks for all your help,

Scott

**Comment by wing-it** [comment]
I can probably get one more update out in the next day or two if you can get the pr submitted.

**Comment by Kurohyou** [comment]
ok, pr submitted: #3490

**Pull request merged**
