### PR TITLE
[Ironsworn][Feature] More localization and moves shortcuts

### PR DESCRIPTION
**Pull request by idispatch75**
- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description

Added more translation support (stats, roll templates, some buttons).
Added Pay the price and Ask the Oracle shortcuts in the Moves tab.
In Move roll template:
- moved Burn momentum icon to the right to avoid confusion with the actual result
- moved Move title to the header and character name to the subheader

See also #10859

### CODE REVIEW

**Comment by nmbradley** [comment]
@aureyia Can I get you to look over this PR and approve whether it is wanted/useful for this publisher sheet? Thanks!

**Comment by idispatch75** [comment]
Hello,
to elaborate on the changes:
- localization: everything is in the issue
- shortcuts in Moves: the general idea is to reduce the number of clicks for common actions, such Pay the Price or Ask the Oracle which are ussually the moves you do when you Miss on a Move: instead of having to go to the Ask the Oracle or Pay the Price moves to click the roll button, you  just click the shortcut, without leaving your current move. This prevents having to go back and forth between moves (in Ironsworn you miss a lot). Ask the Oracle is also a move that is often used to build the story.
image
- Move the Burn momentum icon to the right: when a roll is performed the outcome (strong hit, weak hit, miss) is highlighted at the bottom of the roll with a colored badge. But the outcome can be modified if you have enough Momentum, and in this case the new line is added at the bottom of the roll indicating the outcome if you decide to consume Momentum, and this is highlighted with the same kind of badge as the actual outcome. This often result in "Oh cool, a Strong hit, ... oh no, it's actually a Weak hit, I have to spend momentum to get a strong hit). Moving the momentum highlight at another position prevents confusion: the actual outcome becomes more visible than the potential outcome.
Before: 
image
After: 
image
- Invert Move name and character name in the roll template: the move name is more important, so it's now the header of the template. This is in line with the sheet Ironsworn-Starforged made recently by Ayethin based on this sheet. You can see the difference in the 2 pictures above.

**Comment by idispatch75** [comment]
Does the "publisher" status of the sheet impose more constraints on the PRs? Because if it means the publisher commissioned the sheet, it does not seem it's the case or at least it's not specified in the sheet's wiki. Also the game is free and published under a Creative Commons license: https://www.ironswornrpg.com/licensing

**Comment by aureyia** [comment]
Changing the roll template will break all previous rolls that were done: like this: 
image

Can we ensure that these are retained like was done with the legacy styling in `legacy/roll-templates.styl`

**Comment by aureyia** [comment]
@nmbradley Looks all good 👍 @idispatch75 while the sheet isn't "publisher" sheet the delve expansion / ui revamp was done in collaboration with Shawn directly. Also awesome work  💯

**Comment by idispatch75** [comment]
*Your* work is awesome. I'm just adding some quality of life features.

BTW, would it be possible to merge squash this PR? There are many commits that are not very interesting (mostly fixes to the original PR).

**Pull request merged**
