### PR TITLE
Agone-french new version

### PR DESCRIPTION
**Pull request by Orchal**
## Changes / Comments

I fixed several issues and complety stop using tables. All the sheet has been rewritten with CSS grid.
However, I did changed all the attribute name so the new version is not compatible with the old one. Users won't lose the attributes but these will only be available on the last tab 'Attributes & Abilities' of their sheets.
My advice is to copy the sheets on another game or paper and clean the old attributes.

I won't change the whole attributes anymore, I translated them in order to prepare a translation in the future.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
> However, I did changed all the attribute name so the new version is not compatible with the old one. Users won't lose the attributes but these will only be available on the last tab 'Attributes & Abilities' of their sheets.
> My advice is to copy the sheets on another game or paper and clean the old attributes.

That would mean people would basically lose their attributes, and would come unexpected for everyone using the sheet. Have you considered creating sheetworkers that could be used to migrate the old stats to the new stats? I don't remember a quick example on how to create one, but the magnitude of changed all the stats quite big.

On the other hand, if Roll20 looks up how may games that are using this sheet and sees that is almost zero it might be fine, but I'd say it's likely this update will get delayed due to the attribute changes.

If the sheet 's looks changed due to the refactoring, you could update the preview image to reflect better on how it currently looks.

**Comment by Orchal** [comment]
> That would mean people would basically lose their attributes, and would come unexpected for everyone using the sheet. Or have you informed the people playing it in the relevant communities?

I'm gonna send an email to explain that on the relevant mailing list. But I can't be sure that everybody subscribed to it.

> Have you considered creating sheetworkers that could be used to migrate the old stats to the new stats? I don't remember a quick example on how to create one, but the magnitude of changed all the stats quite big.

I didn't think about that. I'll take a look as fast as I can. It shoud be possible!

> On the other hand, if Roll20 looks up how may games that are using this sheet and sees that is almost zero it might be fine, but I'd say it's likely this update will get delayed due to the attribute changes.

I don't know, this RPG is mainly popular in France... The editor went bankrupt so it's discontinued.
There is an english version, I managed to find the corebook so I should be able to translate the sheet later. I have no idea if english people do use this french version of the sheet.

> If the sheet 's looks changed due to the refactoring, you could update the preview image to reflect better on how it currently looks.

There are so minor changes but the overall sheet hasn't really changed. I will do that!

> It's very nice to see a sheet author pick up and update their sheet after such a long time, this is a rare sight 😄

Thanks !

**Comment by Orchal** [comment]
Hmm this is not easy for the repeating_sections, but I think I can do something to help...
I'm gonne close this pull request and work harder :p

**Comment by Anduh** [comment]
It's still possible they would approve it, I brought it up so you wouldn't be surprised if it happens.

**Comment by Orchal** [comment]
> It's still possible they would approve it, I brought it up so you wouldn't be surprised if it happens.

Sure, but I don't want to mess players' games!
I managed to make the sheet worker conversion, I'm gonna make a new pull request!

**Pull request closed without merging**
