### PR TITLE
Starfinder (simple) CSS update

### PR DESCRIPTION
**Pull request by Acyd69**
## Roll20 Requests

*Include the name of the sheet you made changes to in the title.*

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by Acyd69** [comment]
I mistakenly forgot to push the update to the CSS. This has resulted in the sheet's new check boxes not functioning. I know it is not normally done, but I would greatly appreciate if this update could get merged individually.

**Comment by clevett** [comment]
Let me see what I can do. Since its a CSS update that is a pretty easy merge but I do have to get a bit of help from the powers that be. :)

Thanks,
Cassie

**Comment by Acyd69** [comment]
Thank you so much for checking.

**Comment by clevett** [comment]
The new code should be live.

**Comment by Acyd69** [comment]
I see that it is. Thank you so much for pushing this. The sheet just looked awful.

**Comment by clevett** [comment]
You're welcome. :)

**Pull request merged**
