### PR TITLE
add translation code and Swedish translation.json file to match origi…

### PR DESCRIPTION
**Pull request by aunderwo**
I have made the changes necessary to make this sheet translatable. The translation.json is in the original Swedish. How would I provide an English translation.json?

### CODE REVIEW

**Comment by agjwilson** [comment]
I have actually just created a separate English version of the Coriolis Sheet in English without seeing that you are writing up a translation file. I have also added some graphics and changed some of the texts.

**Comment by aunderwo** [comment]
Hi @agjwilson. Unfortunately roll20 do not accept separate sheets in a different language any longer see https://github.com/Roll20/roll20-character-sheets/pull/2278. That's why I went down this route

**Comment by antila** [comment]
@aunderwo I added your work to the bigger overhaul of the sheet I'm doing here: https://github.com/Roll20/roll20-character-sheets/pull/2398
Good job! 👍

**Comment by pjbehr87** [comment]
Thank you @aunderwo, for doing the translation. I'm going to close this PR and will take @antila 's  (#2398) instead, since it now includes these changes.

**Comment by agjwilson** [comment]
I just managed to finish the graphics overhaul. Worth getting that sheet in though, just for the translation alone.

**Comment by pjbehr87** [comment]
I'm still working on the PRs. If you push your stuff out in the next hour or so, I can grab that too

**Comment by agjwilson** [comment]
Great will do. Need help to know if I am Pull Request properly though.

**Pull request closed without merging**
