### PR TITLE
Chroniques Galactiques (new french sheet) + Chroniques Oubliees v1.4

### PR DESCRIPTION
**Pull request by NathaTerrien**
New character sheet  for "Chroniques Galactiques" (french scifi RPG).
And adjustments for Chroniques Oubliées v1.4

### CODE REVIEW

**Comment by pjbehr87** [comment]
Does this new sheet fall under a specific rpg system, for grouping purposes? (Like all the Dungeons & Dragons games are grouped together) I usually look this up myself, but since this is a French game and I don't speak French I am not able.

**Comment by NathaTerrien** [comment]
Yes in fact it's the same base rules as Chroniques Oubliées (already a sheet for that on Roll20 that I've done.

**Comment by pjbehr87** [comment]
What is the name of the system? So I can group them together.

**Comment by NathaTerrien** [comment]
"Chroniques Oubliées" in fact.
The first sheet (named Chroniques Oubliées) was for "Chroniques Oubliées Fantasy" (if you can rename it). I should have named it this way at first.

**Comment by pjbehr87** [comment]
Yup, I can do that. Thanks for the info, and for the quick response.

**Comment by NathaTerrien** [comment]
You're welcome and thanks for paying attention to this kind of details!

**Pull request merged**
