### PR TITLE
Starcraft Changes Revised

### PR DESCRIPTION
**Pull request by jweweiler**
I have no idea what I'm doing, but I think it should be up to date this time.

### CODE REVIEW

**Comment by wing-it** [comment]
Almost! Just rename your file to `starcraft.html` instead of `html.text` and I'll be able to review your request!

**Comment by jweweiler** [comment]
There! I renamed the file, and deleted the copy I didn't mean to make.

**Comment by jweweiler** [comment]
I know you usually only review once per week, but it's such a small change, and I really need those changes in before Sunday (that's when we're supposed to start our campaign). I'm begging you to make an exception!

**Comment by wing-it** [comment]
You missed our normal update time by about 30 minutes, but we got you in. Have fun with your game this weekend!

**Comment by jweweiler** [comment]
Thank you so much

**Pull request merged**
