### PR TITLE
Agon Sheet 

### PR DESCRIPTION
**Pull request by G-G-G**
Added a bunch of upgrades - reorganised sheet layout to make it more readable and user-friendly, fixed some non-working inputs, added two extra sheets for NPCs and Minions, added Roll Buttons for each Ability, and added sheet workers to handle injury penalties.

### CODE REVIEW

**Comment by Solarswordsman** [comment]
Hi @G-G-G, this is a pretty large overhaul of the sheet-- are you handling upgrading character attributes from the previous version in a sheet worker / using the same attributes in order to prevent data loss?  Will a user using the sheet currently experience a smooth transition when this sheet is pushed live, replacing the existing sheet?

If so, I can go ahead and merge.  Otherwise, we might discuss deprecating the old sheet and replacing it with this.

Thanks,
Jeff

**Comment by G-G-G** [comment]
I'm using the same attributex- it's purely additive. Characters made in the previous version need no changes.

**Comment by G-G-G** [comment]
Oh! I just realised I did remove one section - the weapon attributes, and replaced them with a repeating fieldset. This shouldn't pose a problem though - agon's entire weapon list only has 5 weapons, and they are very simple stats (just 2 stats, damage and range). People should have no problem re-adding them manually - anyone who plays the game will have those memorised.

**Comment by G-G-G** [comment]
I've figured out how gracefully convert the old weapon attributes to the new ones, so if you'd like me to withdraw this pull request to add that, I can do it.

**Comment by Anduh** [comment]
You don't have to withdraw a pull request to update it, just commit the thing you figured out to the same branch the pull request is made from.

**Comment by G-G-G** [comment]
I've pushed a new update, with a worker to migrate weapons, among other features. users of the old sheet (if there are any!) will no have no issues with the update.

**Comment by clevett** [comment]
G-G-G

Thanks for including that update. We'll merge it.

**Pull request merged**
