### PR TITLE
Vampire-v5: Translated into Spanish

### PR DESCRIPTION
**Pull request by AdrianSkar**
I started with https://github.com/Kirintale/roll20-character-sheets/pull/1 and then found this repo.
Not sure about lines 78, 109, 110 & 111

### CODE REVIEW

**Comment by Kirintale** [comment]
Hi clevett could you please ignore this. I'll have a chat with AdrianSkar.

**Comment by clevett** [comment]
I'll ignore this and let you work it out with @AdrianSkar . 

I'm still pretty new to the translation side. I only vaguely know how that is handle and do not know for certain about any sort of tag for translators. That's something I'll have to ask around about.

**Comment by Kirintale** [comment]
Hey Adrian all the ones missing on my one were removed because they don't exist on the sheet. I'd recommend just closing this issue.

The changes you did to my fork are being merged with my commit.

**Comment by AdrianSkar** [comment]
@Kirintale Ok, I'll close this one then. Good luck!

**Pull request closed without merging**
