### PR TITLE
[TheWitcher] make joint attacks roll two times

### PR DESCRIPTION
**Pull request by Stexinator**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Stexinator** [comment]
Whoever wants to merge, @Leothedino wants to review this one first

**Comment by mperes** [comment]
Not sure if I got your comment @Stexinator. May I merge this one?

> Whoever wants to merge, @Leothedino wants to review this one first

**Comment by Stexinator** [comment]
@mperes not yet, Leo didnt have a change to review it yet. I guess he will leave a comment when it can be merged

**Comment by Leothedino** [comment]
All good with me, approved!

**Comment by mperes** [comment]
@Stexinator, there is a conflict within this one, could you fix it? Thanks!

**Comment by nmbradley** [comment]
@Stexinator There appears to be further conflicts, probably caused by the other PR that I just merged. Apologies. Please, feel free to highlight me when you're ready.

**Comment by Stexinator** [comment]
@nmbradley I am done :)

**Pull request merged**
