### PR TITLE
Initial commit to add a plüsch, power & plunder character sheet

### PR DESCRIPTION
**Pull request by andernath**
## Changes / Comments
Added a new simple character sheet for [Plüsch, Power & Plunder] with dice roll for properties and skills. 
Plüsch, Power & Plunder is an old but I guess not so popular german pen and paper. 
https://de.wikipedia.org/wiki/Pl%C3%BCsch,_Power_%26_Plunder

- ppp.css
- ppp.html
- ppp_preview.png
- sheet.json
- translation.json

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
The translation file must be named exactly `translation.json`, not "translation**s**.json" like you have currently.

Look at any other existing sheet with translations.

**Comment by andernath** [comment]
Can someone give me a hint, why I still get failed checks by Character Sheet Validation? :/
I thought adding a newline at the bottom of each file would fix it.

Maybe you have an idea @Anduh ? Btw thanks for your advice for correct file naming.

**Comment by Anduh** [comment]
The Validator isn't perfect, so your submission might be fine otherwise.

And yeah, it's pretty annoying that the Validator doesn't say anything about what is wrong, so it's pretty much a blackbox for us regular users. You'll just have to wait until it gets manually reviewed.

Now thinking about it, I'm not sure if the check ever works on new sheet submissions. If you check the other open PRs, all the new sheet submissions have failed the check, while the updates haven't.

They really ought to update the validator.

**Comment by mperes** [comment]
Hey @andernath there is nothing wrong with you PR, we just need to manually do one last step on our side before this validation error goes away and the sheet is published. We are working on update the documentation to reflect that.

**Comment by mperes** [comment]
Dear @andernath, could you remove the special character (ü and &) from the folder name? I believe this may be causing some issues with the validator script. Thanks!

**Comment by andernath** [comment]
@mperes as you wish :)

**Comment by Anduh** [comment]
> @mperes as you wish :)

You also need to remove the old file versions from the PR, now all files are submitted both in the "clean" folder, as well as the the "old" folder.

**Comment by andernath** [comment]
@Anduh 
Nice! Thanks. Next time I will add a new folder, copy content, delete old one...

**Comment by mperes** [comment]
Thanks @andernath , that did the trick!

**Pull request merged**
