### PR TITLE
Sabre RPG Character Sheet (New Sheet, Dragonsbane Entertainment)

### PR DESCRIPTION
**Pull request by Savant1974**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by Savant1974** [comment]
New sheet with corrected code referencing preview image.

**Comment by NorWhal** [comment]
Hello, @Savant1974!

Thanks for submitting this, it looks great! One request before we can approve it: we're not sure which edition this is for. Please edit the description of this pull request to include the following information in their appropriate fields:
- the sheet's name (including edition number)
- system name 
- a link to the Core Rulebook on DTRPG
Once that's done, ping me here and I can get your sheet merged in!

Thanks again,
Nora

**Comment by Savant1974** [comment]
This character sheet is for the Sabre RPG system, 3rd edition, linked here:
(https://www.drivethrurpg.com/en/product/423136/Sabre-RPG-3e-Fantasy-Players-Manual)

**Comment by Savant1974** [comment]
Thanks! I added a comment to the request with the link, system name and
edition. I hope that's where you wanted it, I didn't see any other place to
put this information. I'm a total Github newbie!

**Comment by Savant1974** [comment]
@NorWhal I think it's done!

**Comment by NorWhal** [comment]
> Thanks! I added a comment to the request with the link, system name and edition. I hope that's where you wanted it, I didn't see any other place to put this information. I'm a total Github newbie!

No worries 😄
I've merged in the code and set up all the permissions to register you as the owner of the official sheet. Please allow about ~15mins for the site to update before it's visible!

**Comment by Savant1974** [comment]
Thank you so much! Very exciting!

**Pull request merged**
