### PR TITLE
Fixing V20.html bugs after live test

### PR DESCRIPTION
**Pull request by JackNexus**
Noticed some errors on the new i18n formatted sheet and i'm fixing them.

### CODE REVIEW

**Comment by Solarswordsman** [comment]
Hey @JackNexus, these changes look good, great job getting translation support started on this sheet.  We'll do a proper review and should be merging mid-week as usual, but I thought I'd point you to [this thread](https://app.roll20.net/forum/post/5225433/v-tm-20th-anniversary-edition-sheet) in case you wanted to see if there are any other issues you can fix, or let folks know that you have fixes coming down the pipe.  That's up to you.

**Comment by wing-it** [comment]
@JackNexus I apologize, this is on me. I went to double check that everything loaded correctly, but it seems I checked the original v: tm and not the 20th anniversary edition. Very sorry!

**Comment by JackNexus** [comment]
Oh ok lol no problem, always better than bugging a sheet for everyone like
i did >.<

Il 2 lug 2017 21:28, "wing-it" <notifications@github.com> ha scritto:

@JackNexus <https://github.com/jacknexus> I apologize, this is on me. I
went to double check that everything loaded correctly, but it seems I
checked the original v: tm and not the 20th anniversary edition. Very sorry!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Roll20/roll20-character-sheets/pull/2744#issuecomment-312511907>,
or mute the thread

**Comment by wing-it** [comment]
I'll pull this down and check it Monday. That way, if changes are still needed, you'll have more time to fix them before we push it to the live server. We'll make sure this gets fixed this week and doesn't end up waiting any longer.

**Comment by JackNexus** [comment]
One thing is that all the files in the folder translations need to be
redone (cause of the change in the main translation.json) except for the
it.json one that i fixed myself.
I found today another little text visualization issue in the italian
translated sheet, but nothing more than that.
I also asked for other potential issues on the thread you linked, so if
there are any others i'll fix them asap.

**Pull request merged**
