### PR TITLE
Runequest 3rd Edition character Sheet

### PR DESCRIPTION
**Pull request by Lockbox313**
First Release

### CODE REVIEW

**Comment by Lockbox313** [comment]
Phil,

Here we go again. the Runequest 3 sheet just merged is throwing an error
with a sheet worker:-

tarting up WEB WORKER
sheetsandboxworker.js?20160926:292 SyntaxError: missing ) after argument
list
    at eval (<anonymous>)
    at messageHandler (sheetsandboxworker.js?20160926:266)
sheetsandboxworker.js?20160926:293 SyntaxError: missing ) after argument
list
    at eval (<anonymous>)
    at messageHandler (sheetsandboxworker.js?20160926:266)
sheetsandboxworker.js?20160926:250 Starting up WEB WORKER
sheetsandboxworker.js?20160926:292 SyntaxError: missing ) after argument
list
/js/d20/sheetsandboxworker.js?20160926:293 SyntaxError: missing ) after
argument list
    at eval (<anonymous>)
    at messageHandler (
https://app.roll20.net/js/d20/sheetsandboxworker.js?20160926:266:6)
app.js?1487867137:38 Final page load.
app.js?1487867137:48 Refresh jukebox List!


I copied the source down from Github to make sure I did not commit the
wrong version and used it on a custom sheet.  It did not throw  any errors.
I have know way of finding out what the issue on the live system.

**Comment by pjbehr87** [comment]
I'm looking into it. I'll let you know when I find something.

**Comment by Lockbox313** [comment]
Phil,

Thanks.  there are semicolons missing off the end of a bunch of sheet
workers, could this cause it.

**Comment by pjbehr87** [comment]
No, semicolons in JS are actually pretty useless at this point. It just makes it faster for the browser to parse. I figured out the issue, though. You either need to change the file encoding to UTF-8 or remove the "The Aaron Sheet" console logs on 3501+3502. They have special characters that are breaking the eval of the sheet.

As for why it's breaking one way and not the other, I couldn't say for sure. Probably because one is loaded directly from the database and the other is loaded from a file, so one breaks on encoding and the other does not.

**Comment by Lockbox313** [comment]
Phil,
Thanks I did both to be on the safe side.

**Pull request merged**
