### PR TITLE
Vampire 5th Edition Updated translation and layout fixes

### PR DESCRIPTION
**Pull request by Kirintale**
Apologies again and thank you for all your hard-work.

Hopefully the display issues is just linked to me not understanding how translation works. 

Please keep up the great work.

### CODE REVIEW

**Comment by clevett** [comment]
You're welcome. Thanks for the help & patience. :)

**Comment by Kirintale** [comment]
No thank you. You have been great!

**Comment by Kirintale** [comment]
Huh not sure why there is a conflict. It should read Spent Experience however.

**Comment by clevett** [comment]
That is on me. I had to do a pull request for another project & during that process went ahead and updated the vampire 5e translations to hopefully fix those issues you were seeing from the Tuesday update. You'll want to pull down those updates that I just did less than an hour ago. Its likely what is causing the merge conflict.

**Comment by Kirintale** [comment]
Thanks I'll give it a go.

Yell if there is anything I can do to make your job easier.

**Comment by clevett** [comment]
Ha. It took me a few times to get the hang of it. :) This should be pretty easy. Just go to roll20 folder in Github. Do the Configure a remote for a fork then do the fetch the upstream directions. Provided those two go well you can push the updates to your fork. 

You may need to make sure your code for this push is not in that roll20 folder as it could cause a merge conflict. This might be the rage quit spot. ;)

**Comment by Kirintale** [comment]
Ok I think that's my last commit for this week.

Thank you so much for spending time to fix the translation issue. It is really appreciated. I was dreading that people would see the poorly formed issue all week. I hope I haven't messed it up with the last commits.

**Comment by clevett** [comment]
This looks good. :) Hopefully this week is smoother for the vampire world.

**Comment by Kirintale** [comment]
Hopefully I didn't break the translations....

**Pull request merged**
