### PR TITLE
[carbon-2185-quickstart] Create char sheet for new game

### PR DESCRIPTION
**Pull request by wizardeddas**
## Changes / Comments
Create new character sheet for the quickstart rules for the game Carbon 2185, which is based on D&D 5E. Carbon 2185 recently finished a very successful kickstarter campaign.
Quickstart rules can be downloaded by signing up at www.carbon2185.com
Full rules expected to be released in July.

## Roll20 Requests

*Include the name of the sheet you made changes to in the title.*

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by wizardeddas** [comment]
Thank you Cassie,

I have fixed that.

Thanks,
Chris

**Comment by clevett** [comment]
You're welcome. I signed up for the Quickstart rules. This is a cool looking system that I'll keep my eye on.

**Comment by wizardeddas** [comment]
Glad to hear it. I backed the game on kickstarter, and can't wait for the
full system to come out.

**Comment by clevett** [comment]
FYI,

The line endings were set to Windows. You'll want to update your code to use Unix (LF). Your text editor should be able to do this and a quick google search will tell you how.

Thanks,
Cassie

**Comment by wizardeddas** [comment]
Oy, Sorry, I thought I had changed that.

I've got it changed now, and (think) I have the changes committed. This is
my first experience with git/github, so I'm not 100% sure it uploaded.

Thank you,
Chris

**Pull request merged**
