### PR TITLE
[Mouse Guard 2e] new character sheet

### PR DESCRIPTION
**Pull request by darkseji**
## Changes / Comments
Mouse Guard 2e character sheet basen on an existing Mouse Guard 1e sheet.

Changes against Mouse Guard 1e character sheet:
+aligned condition top to bottom as per original character sheet
+added Level 2 trait checkbox
+added a separate Wises section
+added Manipulator skill
+marked patrol skills with [p] (for Winter Session)

-removed Healthy condition
-removed surplus pass/fail checkboxes for skills and abilities
-removed Deceiver skill

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
Mouse Guard 2e
- [ ] Is this a bug fix?
No.
- [ ] Does this add functional enhancements (new features or extending existing features) ?
No - it's a rework of an existing Mouse Guard 1e sheet as a completely new, separate sheet.
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
No.
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
Does not interfere with existing Mouse Guard 1e sheets - it's a new sheet
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?
Yes I did - at least I tried. :) I'm new at this.

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
This doesn't comply with [minimum requirements for new sheet submissions](https://wiki.roll20.net/Building_Character_Sheets#2._Good_Code). It contains `<table>` elements. (Old sheets are obviously grandfathered into this and doesn't have to comply to this rule)

**Comment by darkseji** [comment]
> This doesn't comply with [minimum requirements for new sheet submissions](https://wiki.roll20.net/Building_Character_Sheets#2._Good_Code). It contains `<table>` elements. (Old sheets are obviously grandfathered into this and doesn't have to comply to this rule)

Thanks. I can try removing tables but it will take significant time. I was hoping on adding just a few quick amendments. The current 1e sheet is a bit cumbersome while playing 2e. :/

**Comment by Reonin** [comment]
Hi @darkseji when you get the the new HTML update in without the tables we can merge it in that upcoming week.  Thanks!

**Comment by darkseji** [comment]
Hi @Reonin. I'll try making required changes next week. Not enough free time, unfortunately.
A question, as I'm pretty new to Github - should I cancel this request and submit a new one with amendments or is there a way to incorporate changes to an existing pull request? Thanks!

**Comment by Reonin** [comment]
You can keep this same pull request open! And as you make changes and commit then to this same pull request it will refresh to the latest version. If you feel like it's at a good state you can leave a comment or I'll check through it regardless next week.

**Comment by Medieve** [comment]
Hey @darkseji, 
I have a 2E Mouseguard sheet I was planning on submitting. I don't want to pull the rug from underneath you so let me know if you'd be cool with me posting.

**Comment by darkseji** [comment]
Hi @Medieve. Sure, go on and submit! I'll bet it is far better than mine quick and dirty rework of the 1e sheet. :) Thanks!

**Comment by Anduh** [comment]
Medieve have now submitted his Mouseguard 2E PR #6276, so this could be closed @darkseji.

You should see a **"comment and close"**-button at the bottom, next to the **"comment"** button.

**Comment by darkseji** [comment]
Closing request as agreed.

**Pull request closed without merging**
