### PR TITLE
Earthdawn (FASA Official) Fixed probable bug and moved more styles to css

### PR DESCRIPTION
**Pull request by ChrisDDickey**
## Roll20 Requests

*Include the name of the sheet you made changes to in the title.*

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by ChrisDDickey** [comment]
I must have done something very wrong in the pull request, but I have no idea what. 
All I know about github is what I have read in https://wiki.roll20.net/Beginner%27s_Guide_to_GitHub.
I apologize if this is basic, but maybe you can guide me through resolving this. If I am not the only person having troubles like this, mayhaps a few additional sections in the beginners guide to github could help people like me? Or maybe just a reference that holds suggestions for where to read more?

What I think might be the basis of the problem is that when I create a pull request, it insists on listing all the commits to the entire repository I have ever done. (when doing an API script - it even insists on listing commits to a different script). I suspect that re-pulling commits that have already been pulled are confusing it, but I can't figure out how to tell it I only want to it to pull the most recent commit. How should I have done the pull request right?

In any case, it is saying that there are conflicts, but for some reason it seems to have highlighted each and every one of the 221 updates that I made, and said it was a conflict. It seems to me it should not be any conflict, it should be an update. Use the new stuff, overwrite the old.  No conflict at all. (ie: a conflict is when two development tracks are merged, an update is when an old version is replaced). What I am doing is not merging two development tracks, I am updating! However there does not seem to be a button that just says 'approved, use the new stuff'.

Even if the program wants to insist that each and every one of the 221 'conflicts' have a human eye look at them and approve, there does not seem to be any buttons that let you approve them. 
https://help.github.com/en/articles/resolving-a-merge-conflict-on-github
seems to say that for each of the 221 changes I am supposed to go through and manually edit out the old code and the conflict markers that it put in, but that seems silly and very, very likely to introduce errors of it's own. Why would there not be a button for each 'conflict' that would automate such a menial task with much reduced chance of introducing errors? 

So anyway, it is clear that I did something horribly wrong, and it is interpreting each of my updates as a 'conflict' and I the only way I have found to 'resolve' the conflict seems almost designed to reintroduce bugs back into the code!   

How am I supposed to be doing this? Any guidance as to how I should have handled this pull request would be very much appreciated. And like I said, the beginners guide to github could probably do with a few more practical suggestions because this all seems very confusing to me.   Thanks, and sorry for the confusion.

**Comment by ChrisDDickey** [comment]
Arg!!! 
I did not mean to close the pull request. I thought the button that said "Close and comment" just closed the comment editor.

**Comment by Anduh** [comment]
Yeah the guide could be better, but it's not a simple thing to improve on it. I'm self-taught in git/github, and the guide didn't play a large role, as it only points out a few things about GitHub, but never really adresses the underlying Git or how it functions, and basicly all confusion about how things work or don't work stems from not understanding how version control works.

We really should add links to all the other guides that exist about Git and GitHub, as there exist a few good ones that explains the principle better and gives a better grasp of what's going on.

I understand the fundementals, but not we'll enough that I'd be able to distill everything necessary into a simple and coherent guide, and that is likely the case for those who know things better.

**Comment by clevett** [comment]
Greetings @ChrisDDickey 

Sorry for the confusion with Git. The tutorial we offer is pretty limited as Anduh explained. It looks like you were able to resolve the conflicts and I was not getting that loop with this iteration. I'll set the sheet back to active on live and test there.

Thanks,
Cassie

**Comment by ChrisDDickey** [comment]
@clevett 
Thank you very much!

**Pull request merged**
