### PR TITLE
7th Sea 2e Patch 6

### PR DESCRIPTION
**Pull request by BluSponge**
## Changes / Comments
– Updated color scheme and logo
– Include Backgrounds and Arcana info
– Removed Roll Template for better representation of the system’s die roll (easier for sorting raises)
– Internal die roll formula changes 
– Ship record includes support for Expanded Ship Rules PDF
– Minor formatting and content changes to all pages
– Hero Points counter goes to 9
– Wound/Dramatic Wound tracker update

## Roll20 Requests

*Include the name of the sheet you made changes to in the title.*

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by Anduh** [comment]
You included extra versions of the html and css files outside the 7th Sea folders, if you delete those, the PR should be good.

**Comment by BluSponge** [comment]
Are you sure?  I only see the recent updates.  When I check the history, it shows that the old versions were deleted.

How do I double check?  For future reference.

Tom

**Comment by Anduh** [comment]
Go to the `files changed (6)` tab on this PR(It's on the row with the `Conversation (2)`, `Commits (7)` and `Checks (0) Files` tabs ).

You see it says you have made changes to 6 files. Look at the name of each one of your changes. The first two files are in the root directory of this repo, and not in the `7th Sea 2e` folder like the rest.

**Comment by BluSponge** [comment]
So it should look like this?

**Comment by BluSponge** [comment]
Great!  Thank you!  Yeah, its been almost 4 years since I submitted my last sheet and really haven't looked at GitHub since then.  VERY rusty.

**Comment by Anduh** [comment]
GitHub is a bit tricky to understand with that long of a break, and especially if you aren't too familiar with how the [underlying Git](https://stackoverflow.com/questions/13321556/difference-between-git-and-github) functions.

**Comment by BluSponge** [comment]
Re: CCP, I was in contact with him prior to my previous attempt at submission (about 6 months ago).  But not since.  I will contact him and see if I can put together a more comprehensive list of changes.  That'll give me more practice here.

**Comment by Anduh** [comment]
@CoalPoweredPuppet What you think of the improvements, any opinion?

**Comment by BluSponge** [comment]
It doesn’t help that the web client for GitHub looks completely different from the desktop client, and the mac desktop client doesn’t appear to match the instructions on R20.

So your help has been HUGELY appreciated.  Thank you.

**Comment by BluSponge** [comment]
Yes!  What do you think?

(Sorry I had to ditch the Dice Roll Template.  But I kept the code in there in case anyone needs it for something.)

**Comment by CoalPoweredPuppet** [comment]
**Short**: didn't look it, don't play the game, know nothing on how its suppose to work.  I say *cool beans* to BluSponge and people can yell at me if things go bad.

**Long**: I am in the middle of school, and a bucket of personal items and do not have sufficient time to look over the changes.  I have never played the game, so I I have no experience to draw upon to make the right adjustments.  As BluSponge has done so much work, I am inclined to encourage my name be removed from the project, especially if the players of the game enjoy the improved sheet.  Rolepalying is a labour of love, and who am I to stand in the way of that?

However, if people are are looking for me to give my approval so they are not blamed for any errors, I give my approval, without looking at it.  BluSponge has gone through a lot of effort to contact me, contact the actual Roll20 folks, work on the sheet, and never once mentioned "updating to the better edition because no one uses that old stuff", which was the problem last time.  So, I am comfortable placing my name on the blame line and pushing the sheet forward.

With that in mind, I am no way officially recognized as part of the Roll20 crew, so I have no part of the the trademark name.  So if people decide to yell at you, I can't stop it.  If I have time this weekend, I will look into it.  But I am not promising anything.

Good Job, BluSponge.

**Comment by Anduh** [comment]
Oh that's fine, if you have no investment in this sheet or system, you don't have to look into this further.

**Comment by CoalPoweredPuppet** [comment]
I just want people to have fun and game.  That's all.  Roll20 folks allow that to happen.  So, whatever I can do to further that goal, let me know.

**Comment by BluSponge** [comment]
While I appreciate his sentiments, CCP’s name should absolutely NOT be removed from the project. He basically developed the entire framework I built upon. It’s his work as much as mine. As a professional in a creative field, attribution is very important to me. As far as I’m concerned, his name stays.

The only errors in the sheet came from his inexperience with the system. He built it on spec for another player. So if my update field gave the impression I do not appreciate his contribution (or his feedback), that was not my intent.

And Any post update errors are likely mine, so...

Thanks, CCP. See you in the trenches.

Tom

**Comment by Anduh** [comment]
Don't know if it can be applied on GitHub PRs, but at least 'git diff -w' option can ignore whitespace changes while checking diff.

**Comment by BluSponge** [comment]
Cassie,

This is possibly because I replaced the entire code of the sheet with my own modified code, not line by line.  So yes, the whole sheet WAS changed.

By line endings, do you mean “new lines”?  As in "/r/n”?  Or “\n/“?  I can’t find any reference to the former, only the latter.  Since I edited the code in Roll20’s online editor and then transferred it via TextEdit (I use a mac), I don’t understand why this would be an issue.  I’ve googled the issue and everything I get back tells me to use Windows apps that don’t run on my machine, or that it shouldn’t be an issue since my OS is already Unix based.  I need more clarification on this issue.

Thank you,
Tom

**Comment by clevett** [comment]
Greetings,

I gotcha. TextEdit may be the cause along with the copy/paste approach. I would recommend using a code editor for sheet development. Text Wrangler is a good free option for Mac.

I'll merge it next week and check the difference.

Thanks,
Cassie

**Comment by BluSponge** [comment]
Cassie,

Okay.  Thank you!  I can tell you there will probably be a *bunch* of minor differences that don’t amount to much more than cleaning up the code in the editor.

I use the Roll20 editor for everything.  If it helps things along, I can cut and paste the code directly from there and into the github file.  I don’t *think* it will make a difference, but you tell me.

Tom

**Comment by clevett** [comment]
Greetings @BluSponge ,

The line endings on this were indeed incorrectly set. I have updated them to the correct LF. You'll want to use a text editor like Text Wrangler to ensure your line endings are set correctly.

Thanks,
Cassie

**Comment by BluSponge** [comment]
Thank you, Cassie. I’ll make a note and do that in the future. Thanks for your patience and for your guidance. I really appreciate it.

Tom

**Comment by clevett** [comment]
You're welcome. :) Always happy to help.

**Pull request merged**
