### PR TITLE
Fallout: Vaults & Deathclaws

### PR DESCRIPTION
**Pull request by Skyeris**
## Changes / Comments
Same thing as the Fallout PnP 4.0. All the files of it 4.0 were remade into Vaults & Deathclaws which is now the official name of the system. Sorry if this made it a hassle to put onto roll20.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [X] Does the pull request title have the sheet name(s)? Include each sheet name.
- [X] Is this a bug fix?
- [X] Does this add functional enhancements (new features or extending existing features) ?
- [X] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [X] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [X] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
A few questions:

1. Is this rule system "readily available", as per one of the [Minimum Requirements](https://wiki.roll20.net/Building_Character_Sheets#3._A_Satisfactory_Experience)?
2. Was there any particular reason for renaming it from previous "Fallout 4.0 PnP"?

Searching for "Fallout: Vaults & Deathclaws" or "Fallout: V&D" didn't bring up anything, so I don't quite see why the system was renamed if it can't be found or isn't provided a link to the ruleset. Doing a few more searches didn't give me any connection between "Fallout 4.0 PnP" and "Fallut V&D", even knowing there should be something.

**Comment by Skyeris** [comment]
@Anduh The system is readily available. And the reason why I renamed it because I want it to stand as its own system for what I plan to do with it later down the line. I added the link to the rulebook in instructions.

**Comment by clevett** [comment]
@Skyeris Is the only thing happening here is renaming the Fallout PnP 4.0 ? I can just rename it in the approve.yaml for the select. You can just update any text on the sheet.

Is there any reason to keep Fallout PnP 4.0  around ?

**Comment by Skyeris** [comment]
@clevett I renamed it and did a small hotfix for it. Don't keep Fallout PnP 4.0. I've already deleted it on my end. Also, how long does it typically take for it to go live on the roll20?

**Comment by clevett** [comment]
@Skyeris We need to handle this differently based on what you want to do here. We don't want to add a second copy of essentially the same character sheet into the repository. 

If you are not worried about what shows up in this GitHub repository, you can just add your hot fix to the Fallout PnP4.0 code and then I'll update the character sheet select to show "Fallout: Vaults & Deathclaws" when a user selects it.

If you care about the name of the folder in this repository, then you need to do is put in a pull request to rename the Fallout PnP 4.0 folder. Then add your hotfix into that. When that PR is merge in I will update the approved.yaml to reflect these change.

**Comment by Skyeris** [comment]
@clevett Since I care about the name, do I then have to change the names of the files then do a pull request? Because I removed the files on my end and just reuploaded them with the hotfix and new names.

**Comment by Anduh** [comment]
@Skyeris this PR still contains conflicts that need to be resolved

**Comment by Skyeris** [comment]
I literally did what was told to change the names to match, re-add, etc. What else do I need to do? I'm confused.

**Comment by clevett** [comment]
@Skyeris Check the Files in this PR on the tab above. It has the files named Fallout 4.0. Is this intentional? Do you want them to be named "Fallout 4.0" instead of "Fallout: Vaults & Deathclaws" ?

Per our last conversation you wanted the file to be named with 'Fallout: Vaults & Deathclaws'. If that was done successfully it would show up something like "**Fallout: Vaults & Deathclaws/Fallout 4.0.css**"

To use this new name you needed to take the old **Fallout PnP 4.0** files & folders and just rename them to your chosen name. Add your hot fix that you did. Then submit a PR for that change.

**Pull request closed without merging**
