### PR TITLE
(New Sheet) Shadow of the Weird Wizard

### PR DESCRIPTION
**Pull request by karifaevt**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <  Shadow of the Weird Wizard >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <  [Schwalb Entertainment](https://schwalbentertainment.com/) > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < Shadow of the Weird WIzard  > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: < [drivethrurpg](https://www.drivethrurpg.com/en/publisher/8782/schwalb-entertainment/category/46428/shadow-of-the-weird-wizard)  >
- [x] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by NorWhal** [comment]
Hi @karifaevt, it looks like you put your rolltemplate in your css file on accident, so I'm gonna hold off on merging this until you have a chance to fix it!

**Comment by karifaevt** [comment]
Thankyou for the heads up, I have fixed this issue and replaced it with the
actual CSS file.

Not sure how I managed that one

**Comment by NorWhal** [comment]
Thanks @karifaevt!
Our Partner Relations team is currently reaching out to confirm your authorization, I'll keep an eye out and merge this in as soon as we hear back!
Nora

**Comment by NorWhal** [comment]
@karifaevt, 

We heard back from the publisher and it appears they need a bit more information before this can be made an official sheet. I reached out to you over DM on roll20 with their email so that you two can figure things out! In the meantime, we'll approve this as a community sheet.

Best,
Nora

**Pull request merged**
