### PR TITLE
Blades in the Dark v1.4

### PR DESCRIPTION
**Pull request by joesinghaus**

### CODE REVIEW

**Comment by Solarswordsman** [comment]
How will this affect existing players using the previous version?  There seems to be significant changes to some attributes, will this transition smoothly to the new version, and if it doesn't, how significant of an impact will it have?  You might consider writing a sheet worker to update older sheets.

**Comment by joesinghaus** [comment]
It's all covered, there's an update sheet worker. I try to be very careful and never break anyone's old sheets.

**Comment by joesinghaus** [comment]
Also, you're not Phil, hi there new Roll20 person :).

**Comment by Solarswordsman** [comment]
Ah, my mistake!  I see you've got that handled.  Also, hi there :)!  I'm Jeff.

**Pull request merged**
