### PR TITLE
Changes for Basic Roleplaying, RENAISSANCE and the Void

### PR DESCRIPTION
**Pull request by Lockbox313**

### CODE REVIEW

**Comment by pjbehr87** [comment]
You've got merge conflicts. Please resolve these and reopen the Pull Request. I think it's because I had to make some changes to the sheet.json and replace the preview image. It's a good habit to update from the master branch before creating your pull request each time.

**Comment by Lockbox313** [comment]
I did a sync with the master it will not bring down the changes you made.

**Comment by Lockbox313** [comment]
The only way I could get changes was to deleted by local repository and clone the master again.  Now when I make commiits I am being told by github that I do not have permission to publish

Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

WARNING: posh-git support for PowerShell 2.0 is deprecated; you have version
2.0.
To download version 3.0, please visit
https://www.microsoft.com/en-us/download/details.aspx?id=34595
For more information and to discuss this, please visit
https://github.com/dahlbyk/posh-git/issues/163
To suppress this warning, change your profile to include 'Import-Module
posh-git -Args $true'.
C:\Users\David\Documents\GitHub\roll20-character-sheets [master ↑]> git status
On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
C:\Users\David\Documents\GitHub\roll20-character-sheets [master ↑]> git push
remote: Permission to Roll20/roll20-character-sheets.git denied to Lockbox313.
fatal: unable to access 'https://github.com/Roll20/roll20-character-sheets.git/'
: The requested URL returned error: 403
C:\Users\David\Documents\GitHub\roll20-character-sheets [master ↑]>.

**Comment by pjbehr87** [comment]
You don't want to "clone" the repo, you need to "fork" it. Cloning is pulling the actual repo down locally on your computer, and you don't have permission to modify the repo directly. Forking the repo will create an exact copy of the repo, or a branch, that you have permission to edit. A Pull Request is when you ask permission to merge changes from your branch into our master branch. If you delete your old branch (create a local copy of your new sheet first so it doesn't get deleted), then create a new fork you can add your new sheet back to that branch then create a new PR.

If you have any more questions please let me know.

**Pull request closed without merging**
