### PR TITLE
BECMI D&D initial pull

### PR DESCRIPTION
**Pull request by allenmaher**
Still a long way to go, but quite a bit of progress so I am submitting this old school sheet with a modern look and feel for all those old gamers who remember this fondly from the 80's.

### CODE REVIEW

**Comment by SteveKoontz** [comment]
You say this sheet is rough, is it ready to go out for people to use? Also, you reference a preview image that isn't among these files.

**Comment by allenmaher** [comment]
The players sheet is complete, still some work to do on NPC and Mass combat
sections, but yes it is usable as is. I will have the rest done in a few
days

**Comment by SteveKoontz** [comment]
Can you add the preview image and I'll get it merged in and out to your players.

**Comment by allenmaher** [comment]
I am having an issue with commiting it. (fatal: cannot do a partial commit
during a merge.) Any suggestions?

**Comment by allenmaher** [comment]
I will cancel this so I can get the file added and then resubmit

**Pull request closed without merging**
