### PR TITLE
Fallout V&D - New Burst Buttons

### PR DESCRIPTION
**Pull request by Skyeris**
# Submission Checklist
## Required

- [ ] The pull request title clearly contains the name of the sheet I am editing.
- [ ] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [ ] The pull request makes changes to files in only one sub-folder.
- [ ] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [ ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

New Burst Buttons have been implemented. Damage has been split between Dice and Flat.

### CODE REVIEW

**Comment by NBrooks-Roll20** [comment]
Hi @Skyeris!

Unfortunately, we'll have to reject this PR, as you've made some changes to the attributes that will be destructive to the end user's data. To fix this, you'll need to write sheet workers to transition the data gracefully from the old attribute to the new attributes. Other than that, this PR is fine, so feel free to make a new one once you've done that work.

**Comment by Skyeris** [comment]
Hello @NBrooks-Roll20 

The only change that was made that would remove user data is the weapon_damage-1 and weapon_damage-2 to divide in to dice and flat damage. Our community is fine with this change as we've told them ahead of time before implementing this.

Is their another attr that was missed or is that the only one?

**Comment by NBrooks-Roll20** [comment]
Okay, in that case, we'll merge this, but for future reference if you're making a destructive change like this but have a good reason for it, a link to that notification or telling us in advance would speed up this process. Thanks! :)

**Comment by Skyeris** [comment]
@NBrooks-Roll20 I will do that for the future. Thank you. We have a problem and I don't know who else to turn to about it. The sheets appearance was altered in a strange way. I posted it in issues. Nothing in the appearance was altered for this update and I have no idea what to do.

**Pull request merged**
