### PR TITLE
Pathfinder Official Sheet  - Russian Tranlsation 

### PR DESCRIPTION
**Pull request by azorko9695**
## Changes / Comments
It's almost full translation of Pathfinder official (aka Pathinder by Roll20). 
I'll complement it from time to time
I hope to see it in Roll20 in my games ;) !

### CODE REVIEW

**Comment by clevett** [comment]
Excellent. Thanks for taking the time. :) I'll have to check it out in Russian.

**Comment by azorko9695** [comment]
It's still in english in my game

**Comment by azorko9695** [comment]
it's still in english :018.12.2018, 07:12, "Cassie Levett" <notifications@github.com>:Merged #4503 into master.

**Comment by clevett** [comment]
They changes were only merged. They are not live on the site for about ~5 hours.

**Pull request merged**
