### PR TITLE
[AGE System] Updated for more games

### PR DESCRIPTION
**Pull request by caderaspindrift**
Support for more AGE System games; removed 'old' tab; added new skins.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.

AGE System

- [x] Is this a bug fix?

Partial bug fix for a few long-standing bugs.

- [x] Does this add functional enhancements (new features or extending existing features) ?

Adds new dice totalling, rolltemplates, support for Modern AGE, folds in changes from The Expanse sheet.

- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 

Yes, adds new options for colors/skins.

- [x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?

Allowed option for players to automatically convert from old money system to new currency system (not required).

- [ ] If this is a new sheet, did you follow [Building Character Sheets standards (https://wiki.roll20.net/Building_Character_Sheets#Roll2 0_Character_Sheets_Repository) ?

n/a

### CODE REVIEW

**Comment by Anduh** [comment]
Great update! Would it be possible you'd update the wiki page for the sheet with the new changes, then they go live?
https://wiki.roll20.net/AGE_System

**Comment by caderaspindrift** [comment]
> Great update! Would it be possible you'd update the wiki page for the sheet with the new changes, then they go live?
> https://wiki.roll20.net/AGE_System

The wiki is updated! Save for the lack of a link to the new changes.

**Comment by caderaspindrift** [comment]
(I'm unable to update the image on the wiki page.)

**Comment by Anduh** [comment]
Yeah I can update with images sometime after the update goes live.

**Comment by caderaspindrift** [comment]
When does update go live? Some of the people on the AGE discord have asked.

**Comment by Anduh** [comment]
You where late for this week's deadline, this gonna be checked next Monday and go live on Tuesday.
https://github.com/Roll20/roll20-character-sheets#contributing

**Pull request merged**
