### PR TITLE
Baker Street rpg

### PR DESCRIPTION
**Pull request by Lockbox313**
Sheet for Fearlight Games Baker Street game.  Also some graphics for Runequest Glorantha character sheet in preparation for an upgrade

### CODE REVIEW

**Comment by Anduh** [comment]
In the future you might want to separate pull request by character sheet, so if there would be problems with edits/addition on one, it wouldn't affect the other sheets updates. But this doesn't seem to have any problem though.

**Comment by Lockbox313** [comment]
I would love to do that but as I have replied before anytime I have done
that github merges multiple pull requests into one request.

On 5 Jun 2018 12:48, "Anduh" <notifications@github.com> wrote:

In the future you might want to separate pull request by character sheet,
so if there would be problems with edits/addition on one, it wouldn't
affect the other sheets updates. But this doesn't seem to have any problem
though.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Roll20/roll20-character-sheets/pull/3823#issuecomment-394680068>,
or mute the thread

**Comment by Anduh** [comment]
Your repository don't seem to have branches, that might be the cause, or some weird setting that merges your branches? If you submit new request from the same branch or continue working on the branch after you made a request, the new things will automatically update to the request made.

**Comment by Solarswordsman** [comment]
Since you just seem to be adding a bunch of images to the other sheet, I'll go ahead and merge this.  But I encourage you to become familiar with git's command line interface or otherwise  find some way to create separate branches on your repository so that you can create unique pull requests.  Once you get a hang of it, it's really very straightforward!  Here's a great resource: http://try.github.io/

**Pull request merged**
