### PR TITLE
First publish for Enyllion

### PR DESCRIPTION
**Pull request by mailare49**
## Changes / Comments
It's my first publish for a personal game.
I don't know why the checks are not good because I have create the good sheet.json file.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mailare49** [comment]
Hello,
Thanks I will see that to try to rewrite this part.

PS : Sorry if my English isn't perfect I'm French.

**Comment by mailare49** [comment]
I have change my HTML code and replace the table part by an other method but not CSS Grid because I don't understand how does it work.

**Comment by oliviakristiansen** [comment]
The checks are failing because there is invalid json in your sheet.json file - this is caused by an extra comma at the end of the `instructions`. Please remove it and it should work. Also, we are working to fix the checks so it will return the correct error for invalid json in the future. Thanks!

**Comment by mailare49** [comment]
Thanks @oliviakristiansen  I have do this.

**Pull request merged**
