### PR TITLE
Added Tesoro-y-Gloria-LEGACY

### PR DESCRIPTION
**Pull request by greatkithain**
# Submission Checklist
## Required

- [x ] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: < Tesoro y Gloria  >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <  Telmo Arnedo  > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <  Tesoro y Gloria > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

This sheet is based on a old version of the Tesoro-y-Gloria sheet by Telmo Arnedo to be still used in legacy campaigns as the current version is not working with the data already created.

### CODE REVIEW

**Comment by agviegas** [comment]
Hi, have you checked [this one](https://github.com/Roll20/roll20-character-sheets/tree/master/Tesoro-y-Gloria-1E)?

**Comment by greatkithain** [comment]
Hi @agviegas ! 

Yes, I know that version, we used the original one created by Telmo  but after the commit 74c205d055fec3ab85b054ff1a46618a8b4d052d it started to fail as I show you.
captura1
captura2
captura3

In this request, I put the previous commit that works as another branch/sheet.

Also we comment this issue in the TyG Discord :(

I would be happy to check whatever is needed to have our campaign sheets working :)

Thanks!
Andres

**Comment by agviegas** [comment]
I know, I raised [this issue](https://github.com/Roll20/roll20-character-sheets/issues/11489) but got no response. I've spoken to you in Discord.

**Comment by greatkithain** [comment]
Hi @mperes  and @agviegas ! I'm very disappointed with the outcome of this PR. I would prefer to keep it on hold until see if @agviegas really solve the issue with the css. What I want, what the users of roll20 TyG campaigns is having the sheet fixed, no matter how. We can go ahead with my proposal and once solved we can merge and provide the easiest solution for managing the sheets. This new sheet is a workaround, don't expect to be the definitive  

But the facts is that since January, 12th the TyG sheet is not working for a campaign started on 2019 with a lot of material. No rollback, not a real fix. I'm trying to help but if there is nothing we can do and the sheet is useless, we will think about moving to another platform :(

@mperes , please let me know if you will approve or reject a new PR with same content that this one closed.


Regards,
Andres

**Comment by agviegas** [comment]
@greatkithain sent you a PM in discord!

**Comment by greatkithain** [comment]
Thanks, @agviegas ! We will continue the discussion privately and we will fix it sure :)

**Pull request closed without merging**
