### PR TITLE
[Deadlands Classic Anniversary Improved] New character sheet

### PR DESCRIPTION
**Pull request by Baledin**
## Changes / Comments

Rebuild (practically from the ground up) of the Deadlands Classic Anniversary character sheet. Enough has changed that I figured a new sheet (instead of an update) was required.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [X] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [X] Does this add functional enhancements (new features or extending existing features) ?
- [X] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [X] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Medieve** [comment]
Haha, what funny timing. My group is wrapping up our last session of Deadlands this week. I looked at the sheet preview image, particularly the change and I can't help but comment why you decided on going from a tighter sheet to using like 30px fonts.

**Comment by Baledin** [comment]
This will be my first time running and our entire group is new to it
otherwise (I've only played twice but have long wanted to go back).

As far as the sheet goes, the preview of the current Anniversary sheet
looks decent (a bit plain imo) but had a number of inconsistencies
that made it a bit overwhelming on first read. I tried to really separate
elements out on my sheet while also keeping in mind that we only have so
much real estate. I'm a graphic designer by trade with a ton of web-work
under my belt as well, so I leaned heavily on white space around separate
elements--for example the space around each Trait as well as inside the
border whereas the older sheet has them scrunched right to the side and no
space between things (where there is space, it's a lot of space and doesn't
seem intentional). Regarding the font-sizes themselves, I barely touched
them in the CSS so it's mostly standard Roll20 sizes but they probably
could be tuned down some. The display font that I'm using does come across
as a bit bulky but I liked the aesthetic of it and it falls apart at
smaller font sizes. I wanted to get feedback from my players first but we
haven't been able to get everyone online to actually play in the last
couple of weeks.

Ideally, I would like to be able to have multiple columns (my original
intent was fate chips down the left side and wounds down the right) but I
designed this for smaller screens first THEN realized media queries didn't
work. Yes, this is in the Building Sheets page, but I hadn't read that
yet--mea culpa. I have reviewed it since and followed the advice in there.

More importantly, when diving into the current Anniversary sheet, there are
a number of errors that I came across including re-used field names (two
fields that are unrelated) and broken die roll buttons (that re-use other
rolls instead of the correct roll)--it looks like a lot of copy/paste that
didn't get corrected. It's a lot of HTML to debug in here, especially with
the workflow that I use so I don't envy whomever built the original sheet.

There's a bit more I want to add to this sheet down the road but I felt it
was in a good spot for launching and I will continue to work on the project
as needed.

**Comment by Reonin** [comment]
Hi @Baledin as you mentioned in your post there is another sheet for this game and edition and the other Deadlands classic Anniversary sheet had updates going to it as of a month ago. Your new sheet has some significant changes have you reached out to the maintainers of the other sheet so you can have your fixes applied ?

**Comment by Baledin** [comment]
I have not reached out to them. I considered it but the changes that I
wanted to make rebuilt much of the structure as well as adding
functionality. I felt it was enough of an overhaul that most people
wouldn't want me to make the changes to their sheets. I will be submitting
issues to those maintainers however so that the duplication issues that I
mentioned can be fixed. If you look at the live preview (not just the
image) of my sheet, you will see considerable changes to some sections,
particularly the Arcane section. Further down the road I will be adding
auto-calc for new users (making sure that they don't overspend points for
example) and a number of other additions.

**Comment by Baledin** [comment]
Hopefully one of the other sheet's authors sees this... Roll20 is giving me "Not authorized to post" messages when I try to send them PMs. /shrug

**Comment by Medieve** [comment]
Sorry, that was me that updated the sheet a month ago. Mostly cosmetic with a few ability changes, as you pointed out the attributes are not 100%. The last update before that was the initial creation a little more than a year ago, I would consider the sheet otherwise abandoned.

**Comment by Baledin** [comment]
I'm new to contributing to others' repos... if I wanted to help update a sheet, should I just fork, branch and pull as normal? I always assumed more communication would be necessary and don't want to step on toes.

**Pull request merged**
