### PR TITLE
The One Ring 2e - 2.0.0 - initial release

### PR DESCRIPTION
**Pull request by bhuesemann**
## Changes / Comments
This is a new character sheet for The One Ring 2e. It is a complete rewrite (CSS, HTML, Sheetworkers, Roll-Templates, Parsed-Rolls) and revamps the look&feel to the official 2e character sheets and core rules. The existing sheet "The One Ring Second Edition (Basic)" is deprecated and may be incompatible to this new sheet. Its developer (@Aragent ) has joined this development. This sheet was also developed by @dwarfwing who contributed and merged his other 2e charsheet with this. So this is now the joined effort of everybody working on the 2e sheet.

This release now includes two sheets: player characters and adversaries (which was not in the (basic) 2e but in the 1e version).

The sheet has new extended support for all typical rolls (including attributes from selected tokens), toggles for combat stance, parry/protection options, bonus dice, wear/miserable conditions, and illfavoured/favoured rolls. By using Parsed-Rolls the game setup doesn't need custom roll tables anymore (although it can toggle/fallback to table based rolls). Parsed rolls present results in a brand-new roll-template.
All translation files from the subdirectory have been excluded from the build (although we could reuse some of the existing translations for 1e/2e basic).

Data from existing "The One Ring 2 (Basic)" games will be migrated (if possible), but may not be complete.

We've read and followed the numerous wiki related articles including the standards for character sheets.

Links to previous rejected 2e PRs (https://github.com/Roll20/roll20-character-sheets/pull/9989, https://github.com/Roll20/roll20-character-sheets/pull/9970). 

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by nmbradley** [comment]
Glad to see you have all worked out your various issues. In this instance given the significance of the update, I am allowing this duplicate sheet submission to the repo, and will deprecate basic. 

In future, it would be preferable if the work could have picked up the torch that sheet, particularly given the original developer is working with you, but I understand that's not always possible.

**Comment by bhuesemann** [comment]
@nmbradley Thanks for understanding our situation. The problem is, that a newly created game now is showing a broken roll-template, although every Testbox, Testgame we have and had before works like a charm. The charactersheets are ok but the roll-template is broken and I don't see any issues (like http errors) in the network debugging. 
image
Any suggestion how to analyse the root cause?

**Comment by dwarfwing** [comment]
Hi Nic, I have done some testing as well, and the sheet in the roll20/roll20-character-sheets works in a custom sheet sandbox and when loaded as a Custom sheet in a normal game. However, the rolls show up with no linked styles in the production environment. 
I have tried in custom sheet sandbox, production using a Custom sheet (adding html, css and translation), and selecting the new sheet - the only place it doesn't work is the released production sheet. 
I have also tried using a manual roll with the same template and pasting it in the chat, this works in the sandbox but does not work in the released sheet in production.  
No apparent difference in the F12 Console output between any of these tests that would point to an error. 

All I can think of is that somehow the rolltemplate CSS is not loaded in Production when running the parsed roll, perhaps due to some security or parsing that is done differently there (and done in the background).

**Comment by bhuesemann** [comment]
Hi Nic, 

I've just seen, that now the roll-template is fixed but the translation file seems to be missing.
image

**Comment by bhuesemann** [comment]
Hi Nic, the roll template is broken again but translation is back.

**Pull request merged**
