### PR TITLE
Mongoose Traveller 2E - Minor typo in non-breaking space

### PR DESCRIPTION
**Pull request by brookesi**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [x] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

- Removed errant nbsp on options checkbox
- Added skill speciality into new roll templates

### CODE REVIEW

**Comment by BronsonHall** [comment]
Hey @brookesi 

      All looks good here, just double checking - you mentioned adding skill specialty into roll templates in your Changes/Description here, but I'm not seeing that in the code.  Was that left out intentionally?

**Comment by brookesi** [comment]
Hi Lucas,
Umm...thats odd...
Line 5058 should have:
<td colspan="4">{{skill}}: {{spec}}</td>
I added the {{spec}} item...is that not there?
Thanks,Si
    On Thursday, 25 January 2024 at 21:05:16 GMT, Lucas Hall ***@***.***> wrote:  
 
 


Hey @brookesi

All looks good here, just double checking - you mentioned adding skill specialty into roll templates in your Changes/Description here, but I'm not seeing that in the code. Was that left out intentionally?

**Comment by brookesi** [comment]
Hi there, I've forced another commit, should be there now, might not have pushed the change...

**Comment by brookesi** [comment]
There were two commits in this pull request...second should have had the addition of {{spec}} at line 5058...

**Comment by BronsonHall** [comment]
Yep, I see it now as well!  
Merging, thanks!

**Pull request merged**
