### PR TITLE
[NoReturn]fixes and features

### PR DESCRIPTION
**Pull request by Tealk**
## Changes / Comments

fix repeating problem
add injury modifier
editable & hidable macro templates
self-calculating injury modifier

### CODE REVIEW

**Comment by clevett** [comment]
Greetings @Tealk ,

This pull request currently has a merge conflict which will need to be resolved before it can be added into the repo.

Thanks,
Cassie

**Comment by Tealk** [comment]
Hello @clevett :)
Unfortunately I don't know how to fix the conflict, because I didn't do anything else than extend the css file.

**Comment by clevett** [comment]
@Tealk 

I'm not sure what changed but with the conflict it cant be merged. You may want to close this pull request then make sure to save the branch and/or backup the files your changes. 

Then in Github merge this repository into your fork. Update your local repository with a git pull. From there you can add back your changes and hopefully that will resolve the conflict.

Thanks,
Cassie

**Comment by Tealk** [comment]
Fixed @clevett 
I didn't realize you renamed a file.

**Comment by clevett** [comment]
My apologies. I usually try reply in the pull request when I change something but sometimes it is lost in the hustle and bustle of code merge.

**Comment by Tealk** [comment]
No problem, everything is fine now :)

**Pull request merged**
