### PR TITLE
New Sheet: Shadowbane Inquisition

### PR DESCRIPTION
**Pull request by ChtiKenny**
## Changes / Comments

Forked the Only War Enhanced character sheet by Jason Lee.

This is intended to be used for the Shadowbane Inquisition custom rules of Warhammer 40K: Dark Heresy 2ed.

Because this is a new sheet and not a modification to the old one, I have followed the roll20 Building Character Sheets standards to the best of my ability, and would welcome any recommendations to improve.

Thanks for your consideration

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
Hello there @ChtiKenny , could you give me a few more details about this sheet? I've tried look for this custom set of rules and I could not find anything through an internet search for neither Shadowbane Inquisition or Colby W. (author). Is this a a custom set of rules for DMing on a single table? How much do they differ from the Dark Heresy 2ed set of rules? I am asking those question because while there have been duplicate public sheets allowed in the past, going forward Roll20 wants to limit this practice. Thanks for all the work you do and I look forward to hearing back from you.

**Comment by ChtiKenny** [comment]
hello @mperes ,
as I'm not one of the GM for the games I'll try to answer to the best of my abilities, until I can get in contact with Colby W. (as he live in Australia, he should be asleep right now).
the Shadowbane Inquisition is a discord sever of over 250 player and currently 3 (soon to be 5) GM.
The rules, as I understand them, have the Dark Heresy 2ed set of rules (with all the expansions ie: Enemy Within, Without, etc ...) and includes rules from other Warhammer 40K RPGs (Rogue Trader, Only War, etc ...) but with modification on the psychic abilities, degrees of success/failures calculations and some character creation rules

**Comment by ChtiKenny** [comment]
I just got in touch with Colby W. he is currently polishing up a write-up of the differing rules, which will be available by the time he has players using the sheet

**Comment by ChtiKenny** [comment]
Hello @mperes , do you have any idea when sheets approvals will happen?
Because the GMs have a lot of games planned for January.
At least 11 different campaigns played weekly (with 9 more to be added) and 6 to 12 one shoot games per weeks.
And we have 250 players waiting for this sheet and about 100 of whom are waiting for the new sheets so they can make their PCs without doing them twice.
Wish you good end of the year festivities.

**Comment by mperes** [comment]
Hello @ChtiKenny, sorry for the time it took me to reply and merge your PR. Because this is a homebrew I had to pass it through our internal team. Thanks for all the work you do!

**Comment by ChtiKenny** [comment]
Thank you

**Pull request merged**
