### PR TITLE
Initial commit of a new character sheet for Free League Publishings' The Lord of the Rings™ Roleplaying 5E

### PR DESCRIPTION
**Pull request by brookesi**
# Submission Checklist
## Required

- [X] The pull request title clearly contains the name of the sheet I am editing.
- [X] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X] The pull request makes changes to files in only one sub-folder.
- [X] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: **The Lord of the Rings™ Roleplaying 5E**   _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: **Free League Publishing**  _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is:  **Dungeons & Dragons 5E** _(i.e. Dungeons & Dragons, FATE)_

- [X] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ X] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description
This is an initial commit of a fan made character sheet for Free League Publishings' The Lord of the Rings™ Roleplaying 5E supplement. It is based on the Darkest Dungeon sheet and has attributions to that and to the copyright-free border images which have been used.

### CODE REVIEW

**Comment by brookesi** [comment]
> @brookesi we have some copyright-related concerns with the logos and assets used in this sheet. We'll get back to you as soon as we know whether you need to make changes or if this can be merged as-is.



> @brookesi we have some copyright-related concerns with the logos and assets used in this sheet. We'll get back to you as soon as we know whether you need to make changes or if this can be merged as-is.

Hi there, sure thing. The logo uses a public font called Ringbearer One, can re-do banner with map if required…

**Comment by nmbradley** [comment]
Hi @brookesi 

That's useful context. Would you be able to provide a link or other attribution for the copyright-free UI kit? That would help in these efforts. 

We're still going to reach out to the publisher, just as a courtesy. So, apologies, but there'll still likely be a delay on getting this merged in. We'll come back to you with answers ASAP. 

Thank you for your patience 🙏

**Comment by brookesi** [comment]
> Hi @brookesi
> 
> That's useful context. Would you be able to provide a link or other attribution for the copyright-free UI kit? That would help in these efforts.
> 
> We're still going to reach out to the publisher, just as a courtesy. So, apologies, but there'll still likely be a delay on getting this merged in. We'll come back to you with answers ASAP.
> 
> Thank you for your patience 🙏

Sure, no problem, the UI kit is: <a href="https://www.freepik.com/free-vector/set-square-ui-game-frames-medieval-borders_34359993.htm">Image by upklyak</a> on Freepik

**Comment by brookesi** [comment]
Hi Team,

Have just added a PDF with more information about attribution etc. Plus details of a sanitised banner and logo, if that helps. Apologies for adding more work!

**Comment by nmbradley** [comment]
Hi @brookesi 

I am sorry to be the bearer of bad news, but Free League has flatly rejected the idea of including this sheet, or any derivatives, in the repository. Nor have they provided any guidelines by which we might work together to modify this sheet to be compliant. 

It is not the outcome we were hoping for, and if it were our decision we'd have provided a different answer. Unfortunately, we have to be respectful of the publisher's wishes in this regard.

**Pull request closed without merging**
