### PR TITLE
Fixes hability rolls checks and removes duplicated 3det folder

### PR DESCRIPTION
**Pull request by jcemelanda**

### CODE REVIEW

**Comment by jcemelanda** [comment]
Hi Cassie!

I got a little confused here.

You mean the 3D&T version without the & in the name was deprecated (the one
I removed)?

If so, that's nice, and I'll fix things here so we can have it deployed.

One more thing. It'd be nice to have both regular 3D&T ALPHA and Tormenta
ALPHA under a 3D&T folder as both use the 3D&T ALPHA system.

Thanks!

Julio Cesar Eiras Melanda
-------------------------------------------------------------------------------------
Universidade Federal de Itajubá
Bacharel em Ciência da Computação
-------------------------------------------------------------------------------------
Skype: jcemelanda
cel/whatsapp: +55 12 99150 7808
-------------------------------------------------------------------------------------
blog: http://programeempython.com.br <http://programeempython.blog.br>
github: https://github.com/jcemelanda
slideshare: http://www.slideshare.net/jcemelanda
-------------------------------------------------------------------------------------
twitter: @jcemelanda
-------------------------------------------------------------------------------------
Linux user: #498290
Fedora User
[image: icone: Facebook] <https://www.facebook.com/jcemelanda>  [image:
icone: Linkedin] <http://www.linkedin.com/in/jcemelanda>  [image: icone:
Twitter] <https://twitter.com/jcemelanda>  [image: icone: Google+]
<https://plus.google.com/103969569904784103570/posts>


Em ter, 14 de ago de 2018 às 11:22, Cassie Levett <notifications@github.com>
escreveu:

**Comment by clevett** [comment]
Hello Julio,

"3DeT_ALPHA" is listed as "hidden" in the approved.yaml. This means it has been deprecated so GMs can no longer select it from the drop down in Game Settings. Games that currently use this sheet will still have access to it but new games will not. You'll want to fix the pull request to not delete the files for "3DeT_ALPHA" because it would break these older games who still may be using the deprecated sheet.

Thanks for letting me know about Alpha & Tormenta. In the near future, I am tasked to overhaul the way we sheets are grouped. I'll put this in my notes for when that task comes around.

Thanks,
Cassie

**Comment by jcemelanda** [comment]
Thanks Cassie! I should be able to fix it in the weekend ;)

best,

Julio Cesar Eiras Melanda
-------------------------------------------------------------------------------------
Universidade Federal de Itajubá
Bacharel em Ciência da Computação
-------------------------------------------------------------------------------------
Skype: jcemelanda
cel/whatsapp: +55 12 99150 7808
-------------------------------------------------------------------------------------
blog: http://programeempython.com.br <http://programeempython.blog.br>
github: https://github.com/jcemelanda
slideshare: http://www.slideshare.net/jcemelanda
-------------------------------------------------------------------------------------
twitter: @jcemelanda
-------------------------------------------------------------------------------------
Linux user: #498290
Fedora User
[image: icone: Facebook] <https://www.facebook.com/jcemelanda>  [image:
icone: Linkedin] <http://www.linkedin.com/in/jcemelanda>  [image: icone:
Twitter] <https://twitter.com/jcemelanda>  [image: icone: Google+]
<https://plus.google.com/103969569904784103570/posts>


Em sex, 17 de ago de 2018 às 13:29, Cassie Levett <notifications@github.com>
escreveu:

**Comment by clevett** [comment]
Greetings @jcemelanda 

I'm going to close this pull request as it has not been updated in a month. Per our previous conversation please submit your changes but leave the duplicates for now as the are deprecated sheets.

Thank you,
Cassie

**Pull request closed without merging**
