### PR TITLE
Minor FIxes

### PR DESCRIPTION
**Pull request by CoalPoweredPuppet**
I am trying just the Iron Kingdom stuff.  I re-read the instructions, compared them to what I (currently) have.  And I re-read them again, just to be sure.

I double checked the .json (spell checked it), validated it, and insured the files listed there matched the files I am submitting.

I checked the .css and .html files, and made sure they were both the correct file types.

I checked the .png file, changed the image, and made sure the file type was .png.

If there is a problem with this, I would really appreciate an explanation on what and where.  Use small words and big pictures; I'm not seeing the problem.

### CODE REVIEW

**Comment by SteveKoontz** [comment]
John, so this still failed the .JSON parser. I can tell you exactly why. In your Requiem sheet.json instructions you use quotation marks "" which confuses the .JSON file into thinking that halfway through your instructions you're adding a different .JSON element.

Before you submit you need to run your .JSON files through a validator like this one:
http://jsonlint.com/

You paste in the text of your .JSON file and then click the Validate button. If it's valid it will tell you do, if it isn't it will tell you where in the .JSON it threw an error.

I've manually fixed it for you this time.

**Comment by CoalPoweredPuppet** [comment]
...Okay, but that's not right.  I was only trying to push forward the Iron Kingdoms stuff, not the Requiem sheet.  I was trying to settle that issue, first, then figure out everything else.  

Which is why the Requiem sheet.json wasn't put through the validate process; I wasn't trying to fix that yet.

Thank you, anyway.  Yer awesome.

**Comment by CoalPoweredPuppet** [comment]
I'm not sure why the Requiem sheets went to you, but thanks.

**Comment by SteveKoontz** [comment]
Well, that makes me very nervous because I'm not sure about your changes now, if there is a lot included you didn't intend. I think it would be safer to close this pull request and walk you through the process of submitting only exactly what you need. Why don't you send me a join link to a campaign in Roll20 and give me a time and I'll talk you through it. Just let me know.

**Comment by CoalPoweredPuppet** [comment]
Well, I free most days, so...what time is good for you?

It may be my limited understanding of the Github-for-windows program.

Here <https://app.roll20.net/join/405619/WbL81Q>is my personal Iron Kingdom
campaign on Roll20

**Pull request closed without merging**
