### PR TITLE
AD&D 1E: Added optional colors to the header of the General Template

### PR DESCRIPTION
**Pull request by shdwjk**
I asked Vince if he minded the addition and he said it was great. =D

### CODE REVIEW

**Comment by vince-roll20** [comment]
Actually I said...

" Absolutely not. (that I don't mind)  lol
That's cool.  I would like to see how you do that.  ;-) "

lol.  Nice addition to the sheet.  Thanks

**Comment by vince-roll20** [comment]
thanks Phil

**Comment by shdwjk** [comment]
@Vince I was summarizing!  (It was confusing enough when you said it to me, I didn't want to bother Phil with it! =D )

**Comment by vince-roll20** [comment]
lol
I was thinking of playing a "Confusionist" it my next game.  ;-P

**Pull request merged**
