### PR TITLE
Update Coriolis.css

### PR DESCRIPTION
**Pull request by agjwilson**

### CODE REVIEW

**Comment by pjbehr87** [comment]
If you make all of your changes to a single branch before opening a PR, you can include all of the files in a single commit.

**Comment by agjwilson** [comment]
I did, and they all went to a fork of Mark Lenser. Everytime I clone roll20/charactersheets it points me to a fork of Mark Lensers sheets, and that seems to be getting in the way of pushing these requests to you guys at roll20.

**Comment by agjwilson** [comment]
Okay I will try that. Thanks

**Comment by agjwilson** [comment]
everytime I do that it gives me the directory mlenser/roll20-character-sheets and when I send a Pull Request it does to him.

**Comment by pjbehr87** [comment]
Can you give me a link to the exact page you see when you for our repo?

**Comment by agjwilson** [comment]
Okay I think I may have done it correctly.

**Comment by agjwilson** [comment]
I needed to make a small adjustment to the sheet.json after I sent the pull request from my directory would it make a difference?

**Comment by pjbehr87** [comment]
Any changes you make after creating the PR are automatically added to the existing PR. You can check it and make sure everything is there:
https://github.com/Roll20/roll20-character-sheets/pull/2415

**Comment by agjwilson** [comment]
That's good.

**Pull request merged**
