### PR TITLE
Black Crusade Advanced API Bug Fix

### PR DESCRIPTION
**Pull request by Pixizz**
## Changes / Comments

I am trying to fix a bug created during the last merge that duplicated the content of the .css and .html files. 
I have cleared the files and replaced the contents with a single clean instance of the code.

**I updated the .json instructions : i have added several scripts that are needed for the sheet to work properly.** 

Please ask me if i have forgotten anything of note. 

Pixizz.

### CODE REVIEW

**Comment by Pixizz** [comment]
I don't understand how to resolve those merge conflicts - they are all changes to the sheet that are needed, and the only way i see on how to resolve them would be to revert them entirely to match the master branch ... but then there would be no change, the bug & the instruction fix wouldn't be taken into account.

Anyway, i'm pretty terrible at Github and the tutorials they have don't really explain me why it's borked, i would be grateful if you could explain.

Sorry about that,
Sebouh K.

**Comment by oliviakristiansen** [comment]
When you click on the "Resolve conflicts" button, you will be taken to an editor where you will manually delete the code that is conflicting - the code you do not want. Be sure to remove the merge markers as well. Once these are removed, the conflict is resolved. Please visit [here](https://docs.github.com/en/enterprise/2.13/user/articles/resolving-a-merge-conflict-on-github) for more info.

**Comment by Pixizz** [comment]
Thanks a lot, i'll check it out.

**Comment by clevett** [comment]
Greetings,

I'm going to close this pull request due to it having been open unresolved for over a month. Feel free to open a new on with the conflicts resolved.

Thank you,
Cassie

**Pull request closed without merging**
