### PR TITLE
[Pokemon Tabletop Adventure] Sun & Moon update

### PR DESCRIPTION
**Pull request by AdrienGAIRE**
The last update for Pokemon Tabletop Adventure changed quite a lot of things:
 - the trainer stats changed
 - the addition of the trainer skills
 - the benefits from getting a class changed
 - some classes changed
And other changes I'll describe as minor compared to these one.

As such, I'd like to make another sheet, so the GM can stay on the old system if they want to.

### CODE REVIEW

**Comment by AdrienGAIRE** [comment]
@wing-it 
It seems I have missed the moment you validated the pull requests yesterday, is there a schedule or something?

**Comment by Anduh** [comment]
Usually he processes the pull-requests on tuesdays, sometimes starts with some a day earlier.

**Comment by Solarswordsman** [comment]
Since this does seem significant enough to warrant a different sheet, I'll merge this in and add it as a new one.  

I will note that it could be very helpful of you to have some sheet workers that 'convert' from the prior version of the game, should a game owner change their sheet.  As it is, many attributes are similar but some will get dropped or behave strangely (from what I can tell).

**Comment by AdrienGAIRE** [comment]
Oups, forgot to answer that ^^'

The thing is, there's no real transition from the prior version to the new one: the player woulds have to create new characters.

**Comment by Anduh** [comment]
Well, if there are no backlash from people using it, I guess it doesn't matter as much. I myself renamed an repeating attribute(correcting spelling) and had people within 24h on the forums and other channels commenting on data going missing and all that, and I changed it back the next week but it left a mark on some's opinion of me, maybe rightly so. The community around this and sheet might be more forgiving, and fewer in numbers.

**Pull request merged**
