### PR TITLE
[WOIN] Removed background

### PR DESCRIPTION
**Pull request by Ghostroo**
Removed background colour from OLD version for clearer reading

## Changes / Comments
OLD version of sheet difficult to read (feedback from players), removed tan background.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [Y] Does the pull request title have the sheet name(s)? Include each sheet name.
- [N] Is this a bug fix?
- [N] Does this add functional enhancements (new features or extending existing features) ?
- [Y] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [n/a] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [n/a] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Ghostroo** [comment]
Correcting errors

**Comment by CoalPoweredPuppet** [comment]
They could have just changed it to "New" and no coding changes would need to be done.

**Comment by Ghostroo** [comment]
I suggested that but the Conditions for OLD and NEW are different. I suspect updated versions of OLD will probably move to the NEW conditions list and system, then there can be one sheet.

 

What I’d really like to do is have a pick list so players can choose their own background, at night the plain white can get a bit harsh. I am still learning so I’m not sure how to effect that elegantly.

**Comment by CoalPoweredPuppet** [comment]
Well, if this change gives them what they want, that is fine.  Just caught me off guard.

**Pull request merged**
