### PR TITLE
Shadowrun Advanced Update Take2

### PR DESCRIPTION
**Pull request by darkxyro**

### CODE REVIEW

**Comment by darkxyro** [comment]
ok i think that should have done it.
sorry first time actually using github

**Comment by pjbehr87** [comment]
This PR is trying to change 143 files, which means you are still using an old branch. Please 1. Make a local copy of just your sheet. 2. Delete your branch. 3. Fork the master repo from scratch. 4. Add your sheet changes to the new branch. 

When you create your PR you can view the files and the specific lines that are changing. You should see just the changes that you are trying to make, and nothing more.

**Comment by darkxyro** [comment]
i redownloaded the master folder and just replaced all files with the freshly downloaded ones and after that there were no more conflicts.
Ill try to do what you suggested, but failed twice already.
Im sure it is a pretty stupid mistake but for some reason the desktop application always downloads the old version with the same 5 conflicts

**Comment by pjbehr87** [comment]
Don't use the desktop application, it's kind of terrible. You can do everything directly on GitHub for a simple project like this. After you've deleted the branch and created the new one. Navigate, on the website, to your branch's folder for your sheet. Drag your modified files onto the web page and it should upload them in the place of the old ones, and it should show as only changing a few lines of code since the files should be almost identical.

**Comment by pjbehr87** [comment]
I know a lot of people have not used Git/GitHub before, if you would like more detailed instructions I don't mind walking you through the process in more detail. Just let me know.

**Pull request closed without merging**
