### PR TITLE
PF Community v1.736 - header_image toggle added 

### PR DESCRIPTION
**Pull request by vince-roll20**
- set all roll template header images to on/off from the settings|header image section.
- added the option on the game's sheet setting page as well.
- setting the header images will no affect any existing custom URL images all ready set on the sheet by the user.

### CODE REVIEW

**Comment by vince-roll20** [comment]
Not intended.  Actually I don't recall changing the sheet.json when I renamed the sheet's directory. ..
On my phone working.  I'll see if I can make the edit/commit. Thanks

**Comment by vince-roll20** [comment]
I think I did it.  Not fun using my phone with github. Lol

**Comment by vince-roll20** [comment]
Sorry Cassie.  That should be it for the sheet.json  I even did a search for "neceros". ;-)

**Comment by vince-roll20** [comment]
Thanks Cassie.

**Comment by clevett** [comment]
You're welcome.

**Pull request merged**
