### PR TITLE
First version of Talessya sheet

### PR DESCRIPTION
**Pull request by jorsermar**
## Changes / Comments
This is the first version of the sheet for Talessya setting for D&D 5ed

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
Hey there @jorsermar , before I proceed with merging you PR, I need to ask you: Are there any major difference in the rules between Talessya and the other versions of the 5e sheets that already exist in our repo? I am asking you that because while there have been duplicate public sheets allowed in the past, going forward Roll20 wants to limit this practice. Thanks for all the work you do!

**Comment by jorsermar** [comment]
Hi, 
The main difference is the inclusion of different features coming from the reign of origin of the characters that will join race, class and other feature sources. Also characters will have arcane tattos that will grant them another full family of features, both temporal and permanent.

Regards,

**Comment by mperes** [comment]
Hi @jorsermar, it sounds to me that the features you've mentioned above could be added on top of a existing sheet and toggled on/off in the way Piety (a rule only available at the Theros settings) can be turned on/off in the options tab of the official 5e sheet. Would you kindly consider following that route? Thanks for all the work you do!

**Comment by jorsermar** [comment]
There is also a cosmetic factor, which is quite important to the author, in the form of the dragons that appear in the background, the shape of boxes and stat inputs... and of course, the fact that it might be confussing for the players having to use a sheet with a different name.

**Comment by nmbradley** [comment]
I'm willing to back this sheet entering the repository as it's in support of specifically published content, and the precedent has been set by the likes of Esper Genesis to split into secondary sheets for substantially changed work. 

Merging this now.

**Pull request merged**
