### PR TITLE
D6StarWars v2.34 - Graphical update

### PR DESCRIPTION
**Pull request by Moondancer83**
## Changes / Comments
- Enhance Player Core info section's layout
- Reformats Player Secondary Info section
- Enhance Attributes & Skills section's layout
- Enhance Weapons & Armors section's layout
- Enhance Force section's layout
- FIX: cleaning up HTML code
- FIX: removes invalid CSS code
- FIX: Resist Pain effect works as expected

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Kevak** [comment]
You broke the bloody sheets. All of the bloody sheets. Every single one of the sheets. All the numbers are fucked, some of the weapons and armors players have are straight up missing. Did you not test this at all?

Not to mention how bloated the UI is now. It takes thrice the space of the original now.

**Comment by Kevak** [comment]
You have made no effort to preserve player data. This is under the roll20 definition of changing stats via sheet PR's. You done fucked up.

**Comment by Kevak** [comment]
Here's the actual fucking changelog, having dug through the code with a couple other coders.

-Every single stat and skill block has had their value set to a default, manually, this doesn't matter for new games, but tough fucking luck to any current  games! Say bye to all your stats and weapons and armors for every character including NPC's and vehicles!
-If sheets are popped out into other windows, there is now a chance to re-initialize your sheet and reset all stats to default! Permanently! This is an unforgivable coding sin! Well done!
-The px signifier has been removed from sheet sizes, not only making every sheet more obfuscated and fucking the sizes, but also making the sheet incompatible with normal roll20! 
-Instead of setting the sizes of entire categories like a sane person, every single block has it's size set INDIVIDUALLY! This means you can run out of blocks you can input text in and experience overflow!
-Absolutely no steps were taken to preserve player attributes and skills. A violation according to R20 coder conduct!

**Comment by Kevak** [comment]
@Anduh Give this shit a fucking look. It's a fucking trainwreck.

**Comment by Anduh** [comment]
an update is under work

see https://github.com/Moondancer83/roll20-character-sheets/tree/swd6-v2-41/D6StarWars for the latest dev version

**Comment by Kevak** [comment]
> an update is under work
> 
> see https://github.com/Moondancer83/roll20-character-sheets/tree/swd6-v2-41/D6StarWars for the latest dev version

This does not appear to unfuck the sheets in any way shape or form.

**Comment by nmbradley** [comment]
@Kevak I understand the frustration, but please refrain from addressing people in such a manner. Obviously, nobody attempted to do this deliberately; they were just trying to help. There are _real people_ on the other side of the screen. 

That said @Anduh and @Moondancer83 I'm going to escalate this issue. This should absolutely not have happened based on the code changes in this instance.

**Comment by Moondancer83** [comment]
We have a lead on the real cause.

I am able to reproduce the 3D to 1D teansition if and only if the default value is used, so the value is not persisted.

**Comment by Kevak** [comment]
There were multiple other transitions.

**Pull request merged**
