### PR TITLE
[Chronicles of Darkness] Updated Portuguease translation

### PR DESCRIPTION
**Pull request by AdolfoDomingues**
## Changes / Comments

Added things related to Demon the fallen on the translation and changed composure and resolve to better match what was officially released on Brazil

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
Chronicles of Darkness
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by AdolfoDomingues** [comment]
I just fixed the English translation file as well. It was showing two dots twice everywhere. Now it's matching the actual translation file that we work on while creating the character sheets

**Comment by Anduh** [comment]
In the future, submit translations through CrowdIn rather than github: https://app.roll20.net/forum/post/9382237/translation-and-crowdin-changes

**Comment by AdolfoDomingues** [comment]
> In the future, submit translations through CrowdIn rather than github: https://app.roll20.net/forum/post/9382237/translation-and-crowdin-changes

Sure, I wasn't aware of this procedure. Thank you!

**Comment by AdolfoDomingues** [comment]
I was looking at the Crowdin and I realised that the file of translations there is wrong. It has the two dots after each name at the header of the sheet even on the normal character sheet, while it shouldn't. This problem is being replicated through all translations.
My Commit here fixes this problem on the English translation file, but how will it work?

**Comment by mperes** [comment]
Hello @AdolfoDomingues ! Your Pull Request includes changes to translation files. Unfortunately, we no longer accept translations submitted outside of Crowdin. To learn more about Crowdin and how to submit translations through Crowdin, please see our article on How to Become a Translation Volunteer. Thanks for all you do!

**Pull request merged**
