### PR TITLE
[TheWitcher] incorporate crit into roll and add fumble to rolltemplate

### PR DESCRIPTION
**Pull request by Stexinator**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Stexinator** [comment]
@mperes if the change to translation.json is necessary please inform me

**Comment by Leothedino** [comment]
@Stexinator I believe it was something to do with changing the individual translation files. Do you remember what happened? Because (and I am not an expert), I think you just change the very base translation.json file, and the service automatically edits/changes the others. Doing it any other way causes an error/conflict.

**Comment by Stexinator** [comment]
It was merged and then reverted. So I have no clue what exactly the problem is. I still have the changes to the translation.json locally so I can re-apply them anytime.

This https://wiki.roll20.net/Character_Sheet_Translation opts for changing the translation.json, but I want to wait for clarification, due to it being in the old wiki

**Comment by mperes** [comment]
@Stexinator this one is good, it is fine to makes changes to the translation.json file, which is not allowed is making changes to the language files, like pt.json, en.json, etc. I am gonna merge this one. Thanks for all the work you've put into this!

**Pull request merged**
