### PR TITLE
Savage Worlds Tabbed v3.8 (sheet.json only)

### PR DESCRIPTION
**Pull request by gronyon**
## Changes / Comments
Another attempt at fixing sheet.json.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by gronyon** [comment]
Hi @clevett,
This is the pull request which isolate sheet.json from the main SWT 3.8 commit.

I did some changes in it : I searched for what could have been a problem, and changed what I could.
If this version doesn't work, I will really need some help, like the logs of what crashes, or some test environment where I can quickly test new changes (however I have no idea of what can be the issue).

Finger-crossed :)

**Comment by Anduh** [comment]
a `sheet.json` at +2000 lines? Damn I better check this out when it's live, and see if you have some Default Settings I'd could use in my sheets.

Smart move to separate PRs by feature.

**Comment by gronyon** [comment]
Hi Andrew,

I wanted to give the ability to customize the 35ish skills from the Game Settings, so the number of lines grow up pretty quickly :)

And to be honest at some point we will have to verify and clean it a bit. The sheet got a major overhaul recently, and I'm sure we left some old/unused options there that shall be removed.

**Comment by gronyon** [comment]
> Smart move to separate PRs by feature.
Well it's not exactly split by feature.

The main PR has the feature (ability to link skills to a different attribute).
This side PR adds on top of the main PR to allow setting those linked attributes directly from the game settings.
So the main PR can work alone. The side PR is a bonus. It does require the Main PR to work though.

**Comment by gronyon** [comment]
Hi @clevett ,

Could you also approve and integrate this branch. I have change all I could I felt could have provoked an error on the server. 
It's in a separate branch so that you can rollback just that one, in case of emergency, without having to rollback all 3.8 features.

Thank you.

**Comment by clevett** [comment]
Greetings @gronyon !

You're code found an interesting scenario in our parser. Your translation.json was throwing errors because " are being used. Even when they are escaped with \" it was still causing an error. The simplest fix for us for now was to double escape like this **"test": "this is a \\"test\\""**. 

We fixed the issue in the character sheets. Make sure you update your fork. In the future when working JSON use **'** instead of **"** inside your strings. We've added a ticket to our backlog to better handle this scenario in our parser for the future.

This is probably the issue your sheet.json was having as well.

Thanks,
Cassie

**Comment by finderski** [comment]
So, when will this sheet.json go live? and am I ok to do my pull request to update my Master Branch now?

**Comment by gronyon** [comment]
Not sure. I don't see the changes on live.

The other pull request (the one without the sheet.json) was merged, but I
got a message from Cassie saying she has reverted it due to a " going not
right in the translation file or something like that. I'm gonna have to
check that out :(
The sheet html, css and both EN and FR translations are working fine in a
custom game.

Le mar. 17 sept. 2019 à 19:14, finderski <notifications@github.com> a
écrit :

**Comment by gronyon** [comment]
Hi again,

Well. The changes are in Roll20/Master I see them.

However, games that use that Savage Worlds Tadded sheet no longer load.
No obvious error (or at least error that I can understand) in javascript
console.

I merged Roll20/master into my Gronyon/Roll20 repo, master branch.
I changed my game to "custom" sheet, and
handpicked SWTRedesign.html, SWTRedesign.css, and fr.json as custom html,
css and translations.
Now the game loads, but translations not. (all is [translationkey] in red).

I switched to my 3.8 branch, picked fr.json from there, and loaded it in my
custom settings. Everything works fine.

I'll have to compare roll20/master and Gronyon/3.8 branch and see what's
the problem.

Could you tell me the line the translation key that was changed in 3.8 to
make it "work" on the servers ?

**Comment by Anduh** [comment]
> However, games that use that Savage Worlds Tadded sheet no longer load.
> No obvious error (or at least error that I can understand) in javascript
> console.

Yeah, I suspect as well something went wrong with the update of the `sheet.json`, as described in the[ bug forum thread](https://app.roll20.net/forum/post/7774845/cannot-load-into-my-game-i-created-and-dm-for/?pageforid=7774931#post-7774931)

**Comment by clevett** [comment]
@gronyon 

Pull request #5462 broke the Savage World sheet due to **"** being used inside the strings in the translation.json. The JSON is valid but it caused our parser to throw errors. This is likely what was also breaking your sheet.json 

I replaced the current code in master with a copy from 5 days ago of 3.7 (before #5462 was merged). This code tested as stable so users can play their games. 

You need to update your fork and remove all " from any JSONs in the update you want to submit. I would really recommend backing up your changes then starting a fresh branch after reseting your master and add your changes back in small chunks that are more manageable. 

- Cassie

**Comment by gronyon** [comment]
" were already there in previous version.
Those file work when I set them as custom sheet.

I seriously doubt there " is the issue.

Le mar. 17 sept. 2019 à 23:02, Cassie Levett <notifications@github.com> a
écrit :

**Comment by clevett** [comment]
It's true that it may not be ". We tried to fix these and roll out a change during code push but at last it was still broken hence the roll back. 

Something in the 3.8 update is causing an error when the VTT tries to load the sheet. Unfortunately the update touches 21 files with 6,288 additions, 5,702 deletions in the HTML alone so I'm unable to really troubleshoot what may be going on here. :(

**Comment by gronyon** [comment]
Hello,

The update touches 1 html file and 1 translation.json file, focus on those,
the other files are country related translation.
Compare by ignoring white space/tabs and end of line characters ? (the
files were using a mix or tabs/spaces, and a mix of windows/linux eol
chars).
it's 178 changes.
It's 3 bug fixes, 2 mini-feature improvements, and 1 main feature. It's way
smaller than usual version changes :(

This update DOES work when files are set as custom character sheet in a pro
game.
Why it doesn't work on the live server ?

Let's imagine I thrash my work, and try to reimplement everything, I will
test it, eventually it will work on my game (happy to have a PRO account
else couldn't even do that), then I'll commit it, and odds that that it
will fail on live server.
I can't just push a few lines once per week hoping that maybe those lines
are correct.

What can I do to prevent that ? I have strictly no clue, no starting point
from where to explore.
Can you at least provide me with some log, error trace, or similar that
could help me find out that could go wrong ?
When does the loading process fails ? Before loading i18n ? after ? During
some javascript event ? Which one ?
Do you have a development server or VM I could have access to ?

You know how the server works, what are the difference in file loading
process between GIT deployed and set in text area on the custom setting
page ?
Can it be an encoding issue ? (I use UTF-8 / with Linux eof).
The parser is different between both processes ?
The process to load translation file is different ? First ime I use
"data-i18n-dynamic" are you aware of issues related to this feature on
official servers ?

I can try and force me to redo everything I implemented, but can I commit
them bits after bits, and you deploy them on test servers, until we get it
complete and working, and all of this within a few days instead of testing
on live once every week ?


Le mer. 18 sept. 2019 à 16:51, Cassie Levett <notifications@github.com> a
écrit :

**Comment by clevett** [comment]
Greetings,

Unfortunately I cannot tell you why exactly its failing when being loaded into the live VTT. As mentioned previously we though it was an issue with " in the .jsons. We attempted to fix this on your behalf during the code push there appeared to still be an error. Troubleshooting the issue it outside my ability and permissions level at this time. Investigating the cause was added to the backlog for our devops team but I do not have an ETA on it.

When I was testing your first pull requests the loading process was failing on the sheet.json. In the last pull request we remove that file and no error was thrown on my local environment. On live an error this time appeared to be in the translation .JSONs when the sheet was being loaded into the VTT. I know this isn't helpful amount of information for troubleshooting but we're at an impasse when it comes to the 3.8 update. 

We can put the update on hold until the issue in the backlog is investigated and fixed or we can break the ticket down into smaller updates to be released every week in order for us to potentially find where the error may be. In the UC team we limit our updates to ~200 lines of code changed so that we can do code reviews. Yes, this would be a slow process because the merging happens weekly. Developing in this way makes it much easier catch issues early and isolate them.

- Cassie

**Comment by gronyon** [comment]
Hello

Ok, thank you for this information.

I'll see to remake and republish my changes without the quality-improvement
of cleaning all tabs into spaces to limit the changeset.
However it won't be this week, nor the next.

I hope the developer team will find what makes it fail on live while it
works on custom.

See you soon then :)


Le jeu. 19 sept. 2019 à 16:01, Cassie Levett <notifications@github.com> a
écrit :

**Comment by clevett** [comment]
I'll keep an eye on the Dev ticket. Sorry again for the hassle. As a fellow sheet author I sympathize.

**Comment by clevett** [comment]
Greetings, 

I'm going to go ahead and close the Pull Request since finderski has been doing updates. We'll just need a new one when this update is ready.

Thanks,
Cassie

**Pull request closed without merging**
