### PR TITLE
[New Sheet] NoReturn 2nd Edition

### PR DESCRIPTION
**Pull request by Gorthian**
Official sheet for NoReturn 2nd Edition by Manifest Games

# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <NoReturn 2nd Edition>  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <Manifest Games> _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <NoReturn> _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

Erste Version des Charakterbogens für das aktuelle Crowdfunding von NoReturn 2nd Edition

### CODE REVIEW

**Comment by mperes** [comment]
Hey there @Gorthian, at the current moment we do not support external fonts hosted outside Google fonts. Even though they will work on a dev sandbox game, they will break once the sheet is moved to production.

Maybe that is not as well documented as it should, I will see what we cand do on our side to make this clearer. Is this something you could work around?

**Comment by Gorthian** [comment]
We did hope it would work if we host the font files on the GitHub and link to them.
I planned to change the URL as soon as the files are part of the repository.

Would that be possible?

**Comment by NorWhal** [comment]
Unfortunately, we cannot have the font hosted through github: It must be hosted in Google Fonts. We've got a [document](https://docs.google.com/document/d/1nZiUHkWcQNeoypMzVpAWPC63TafmRCQXy6NxdQ7S8mY/edit) that could be a good place to start looking for alternatives, but feel free to look through https://fonts.google.com/ as well

**Comment by Gorthian** [comment]
OK,. Thanks for your help.

Would it be a problem if we leave the font definition of the original fonst in the css file, and remove only the includes of the font files?
So you could install the fonts on your local pc.
Of course we would implement a fallback to a google font for those browsers without the local fonts.

**Comment by nmbradley** [comment]
Hi @Gorthian 

That is a good solution. Thanks for your understanding.

**Comment by Gorthian** [comment]
OK.
It will take a while before I can change this.
Don't know if you want to let the merge requests open until then.

For me it's OK if you close it.

**Comment by nmbradley** [comment]
I have marked it as draft. You should be able to remove that status when you're ready to merge :)

**Pull request merged**
