### PR TITLE
Add a new sheet for the MEGALOS RPG

### PR DESCRIPTION
**Pull request by astralfrontier**
# Submission Checklist
## Required

- [X] The pull request title clearly contains the name of the sheet I am editing.
- [X] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X] The pull request makes changes to files in only one sub-folder.
- [X] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: MEGALOS  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: matara _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: MEGALOS _(i.e. Dungeons & Dragons, FATE)_

- [X] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [X] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <https://mataramg.itch.io/megalos>
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

This is a new sheet, made with the permission and collaboration of the game system designer/publisher. Permission has been explicitly granted to include game material: https://twitter.com/Gahostan/status/1635133213202067456?s=20

The sheet data is auto-generated from a separate repository, found here: https://github.com/astralfrontier/megalos-roll20

### CODE REVIEW

**Comment by nmbradley** [comment]
Hey @astralfrontier 

We're not sure that this tweet covers this specific use case, so we're referring to our content team. We'll update you as soon as we hear back. Apologies for the delay.

**Comment by astralfrontier** [comment]
> Hey @astralfrontier
> 
> We're not sure that this tweet covers this specific use case, so we're referring to our content team. We'll update you as soon as we hear back. Apologies for the delay.

Feel free to just contact the author directly as well if you want to be sure. You should be able to confirm their identity from the Itch page, as well as their Twitter profile.

**Comment by astralfrontier** [comment]
> > Hey @astralfrontier
> > We're not sure that this tweet covers this specific use case, so we're referring to our content team. We'll update you as soon as we hear back. Apologies for the delay.
> 
> Feel free to just contact the author directly as well if you want to be sure. You should be able to confirm their identity from the Itch page, as well as their Twitter profile.

Checking in to see if there's anything I can do to help out, such as asking the author to just directly post explicit approval for this sheet. That said, the people most interested in playing right now are Pro subscribers so can just load the sheet directly into a game, and I absolutely understand letting process play out, so either way works for me.

**Comment by nmbradley** [comment]
Hi @astralfrontier 

Apologies for the wait, our licensing team got involved, and then there were some legal questions, then we swallowed a spider to chase the lawyers... you get the idea. 

Contact has been made with the publisher, we're all waiting to see their response.

We should have news soon, hopefully!

**Comment by astralfrontier** [comment]
> Hi @astralfrontier
> 
> Apologies for the wait, our licensing team got involved, and then there were some legal questions, then we swallowed a spider to chase the lawyers... you get the idea.
> 
> Contact has been made with the publisher, we're all waiting to see their response.
> 
> We should have news soon, hopefully!

I asked Matty and they haven’t heard anything, so I’m curious who you contacted. Itch.io?

**Comment by nmbradley** [comment]
Hi @mataraMG, glad to hear from you. I believe you were contacted at the email we have on file at DTRPG, which doesn't match the one you just provided. I don't want to share it publicly for obvious reasons but I've passed your message on to our Partner Relations team and they should be in touch shortly.

Sorry for any confusion!

**Comment by mataraMG** [comment]
Hello Nic,

I haven't heard from your Partner Relations team yet, but Bill (Astral, the
person working on the character sheet) was wondering if it was likely the
sheet will be accepted during this upcoming week's "cycle".

Let me know if you need me to reach out to anyone. 😁

-Matty

**Comment by nmbradley** [comment]
Thanks for the confirmation, I just got the same info from Adam. The sheet will be approved in just a few moments. Sorry for the delay, everyone, we just wanted to make sure everyone's rights were being respected.

**Comment by astralfrontier** [comment]
> Thanks for the confirmation, I just got the same info from Adam. The sheet will be approved in just a few moments. Sorry for the delay, everyone, we just wanted to make sure everyone's rights were being respected.

@nmbradley I'm grateful for the due diligence and happy with how your teams have handled the onboarding process for a new sheet. Thanks so much :)

**Pull request merged**
