### PR TITLE
QoL change to line 50

### PR DESCRIPTION
**Pull request by GBeavis**
## Changes / Comments

Line 50 had a typo

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by GBeavis** [comment]
Does this also need to be added to each .json translation file?

**Comment by Anduh** [comment]
No, it should appear there automatically when Roll20 runs their update things for the translation files.

**Comment by GBeavis** [comment]
By mistake I opened a second pull request with the .json change, so this thread can be deleted

**Comment by Anduh** [comment]
Think only you can close it yourself. There should be a "close Pull Request button" at the bottom of this page.

**Pull request closed without merging**
