### PR TITLE
NEW SHEET/OFICIAL/VIKINGOS

### PR DESCRIPTION
**Pull request by VJRolmasters**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: VIKINGOS el juego de Rolf
- The publisher of this game is: VIKINGOS el juego de Rolf
- The name of this game system/family is: VIKINGOS el juego de Rolf - BRP

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] This sheet has been made by the game's publisher.

# Changes / Description
This is the official character sheet for Vikingos el juego de Rolf.

The game, is currently only available in Spanish. For now there is no support for other languages, hence the lack of translations.

You can find more information about this game at: http://rolfelvikingo.es/

Image from the front sheet

vikingos

### CODE REVIEW

**Comment by VJRolmasters** [comment]
Hi masters from Roll20!

The sheet is ready for review. Let me know if there's something wrong o missing.

Thanks in advance!

**Comment by BronsonHall** [comment]
Hey @VJRolmasters !

Sorry, looks like this one slipped through the cracks in our earlier merges.  The sheet looks great, but we have one small request before it's good to merge: We ask that sheet workers <script> elements, for codebase consistency, be placed at the very end of your sheet's html file, rather than being interspersed within the html at relevant sections.  

If you can move that to the bottom of the file, it'll be all set - thanks!

**Comment by VJRolmasters** [comment]
Hey BronsonHall 

I have made the changes that you ask for.

Thank's for your review. Waitting to see the sheet ready to play very soon.

**Comment by BronsonHall** [comment]
Hey @VJRolmasters 

Awesome - just noticed one other thing though, it looks like you've got CRLF line endings in your css and html.  The repo requires all .css, .htm, and .json files to LF line endings.  How you'd correct this will depend on your IDE/text editor of choice, but we do require all files to be proper line endings before they can be merged.  Otherwise, other authors will wind up with phantom changes, resetting these files, that prevent them from merging their own changes to different sheets (due to the single-sheet rule).

Let me know if you have any questions here.

**Comment by VJRolmasters** [comment]
Hi BronsonHall

How can I detect, eliminate or solve this CRLF endings?

I don't understand what you are asking for. 

Thanks in advance

**Comment by BronsonHall** [comment]
Hey @VJRolmasters 

[This article](https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/) explains line endings quite well, and why they're trouble for git in particular.  Our repo does have automated normalization set up, to make sure every file goes in with LF line endings - but uploading files via web GUIs can bypass this automation.  That said, setting up proper line endings is usually a one-time-fix.  

The way in which you'd watch for this depends on what you use to write/edit this code.  VSCode, for instance, can display the line endings at the bottom right in a file, while Notepad++ will display a CR and/or LF at the end of each line if a setting is toggled on.  
You should be able to find a method of detecting and changing line endings for a file for your environment specifically.

**Comment by VJRolmasters** [comment]
Hi BronsonHall

I hope now it's ok! I changed the configuration to LF (Unix) and saved the chtml document and the CCS again before upload the files here.

Thank's

**Comment by BronsonHall** [comment]
Yep, perfect!  Thanks so much!

**Pull request merged**
