### PR TITLE
[Blades in the Dark] Update es.json

### PR DESCRIPTION
**Pull request by WallaceMcGregor**
Update translation and minor corrections.

## Changes / Comments

*Provide a few comments about what you have changed.*

## Roll20 Requests

*Include the name of the sheet you made changes to in the title.*

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by joesinghaus** [comment]
Hi @WallaceMcGregor, what's the state of the Spanish translation? Is it more or less complete?
If yes, I can add a flag on the sheet that will allow the roll template titles to be in Spanish as well.

**Comment by WallaceMcGregor** [comment]
Hi @joesinghaus 

The Spanish translation is completed with the official Spanish version of Blades in the Dark (released six days ago). That means the Alternate Iruvian Playbooks keeps in English (there is no translation of any kind). This PR is just a minor corrections and changes made after seeing the sheet translated (there was things I didn't know  the function on the sheet).

It will be awesome if you can make the roll template titles shows in Spanish. I was wondering how to made it, but I saw their were png archives so I dropped it.

**Comment by joesinghaus** [comment]
Nice! I'll add the titles (as text, not PNGs), there is a setting for that.

**Comment by joesinghaus** [comment]
Okay, #4624 should do it.

**Pull request merged**
