### PR TITLE
Warhammer v2 french

### PR DESCRIPTION
**Pull request by Phoxounet**
Added repeating sections for weapons and advanced skills. Near all the
sheet now have automated rolls with a custom roll template, except
initiative. Just add the total DMG bonus for weapons, the macro already
consider the 1D10 in the attack roll.

### CODE REVIEW

**Comment by pjbehr87** [comment]
This looks good, thanks for fixing the conflict for me! I'm always happy to help. If ever you have sheet/git questions let me know.

**Comment by Phoxounet** [comment]
Thx Phil !

However, the sheet does not appear in the scroll down list when managing 
a game or creating a new one. Is it normal ? :)

Regards :)

Le 18/05/2016 à 19:42, Phil a écrit :
>
> Merged #1636 
> <https://github.com/Roll20/roll20-character-sheets/pull/1636>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/Roll20/roll20-character-sheets/pull/1636#event-664748803>
>


-- 
Cordialement,
Yannick Hondarrague

**Comment by pjbehr87** [comment]
screen shot 2016-05-19 at 8 28 49 am

It should be there

**Comment by Phoxounet** [comment]
It is not. For example, there is a piece of code regarding weapons as a 
repeating section in the roll20 master (line 298 to line 352) and it is 
still the previous version in the drop down list when creating a new 
game or managing one (there are no roll buttons, no added repeating 
sections, only 3 melee and 3 ranged weapons lines). Moreover, the 
displayed json file when creating a new game is the old one, and not the 
one located in the Roll20 master.

Did I missed something ?

Le 19/05/2016 à 16:29, Phil a écrit :
>
> screen shot 2016-05-19 at 8 28 49 am 
> <https://cloud.githubusercontent.com/assets/4982464/15397007/c280b548-1d9b-11e6-9a6a-6a003dfa98ee.png>
>
> It should be there
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/Roll20/roll20-character-sheets/pull/1636#issuecomment-220341514>
>


-- 
Cordialement,
Yannick Hondarrague

**Comment by pjbehr87** [comment]
Oh, I haven’t pushed out the new sheets yet this morning. I want to finish up some other things first so I can do all of it at once.

**Comment by Phoxounet** [comment]
Ok :) I was afraid something went bad. Alright ! Thx for all :)

Le 19/05/2016 à 18:04, Phil a écrit :
> Oh, I haven’t pushed out the new sheets yet this morning. I want to 
> finish up some other things first so I can do all of it at once.
> > On May 19, 2016, at 10:03 AM, Phoxounet <notifications@github.com> 
> wrote:
> >
> > It is not. For example, there is a piece of code regarding weapons as a
> > repeating section in the roll20 master (line 298 to line 352) and it is
> > still the previous version in the drop down list when creating a new
> > game or managing one (there are no roll buttons, no added repeating
> > sections, only 3 melee and 3 ranged weapons lines). Moreover, the
> > displayed json file when creating a new game is the old one, and not 
> the
> > one located in the Roll20 master.
> >
> > Did I missed something ?
> >
> > Le 19/05/2016 à 16:29, Phil a écrit :
> > >
> > > screen shot 2016-05-19 at 8 28 49 am
> > > 
> <https://cloud.githubusercontent.com/assets/4982464/15397007/c280b548-1d9b-11e6-9a6a-6a003dfa98ee.png>
> > >
> > > It should be there
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/Roll20/roll20-character-sheets/pull/1636#issuecomment-220341514>
> > >
> >
> >
> > --
> > Cordialement,
> > Yannick Hondarrague
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub 
> <https://github.com/Roll20/roll20-character-sheets/pull/1636#issuecomment-220371636>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/Roll20/roll20-character-sheets/pull/1636#issuecomment-220372030>
>


-- 
Cordialement,
Yannick Hondarrague

**Pull request merged**
