### PR TITLE
SWN Revised v2.4.4

### PR DESCRIPTION
**Pull request by Karlinator**
## Changes / Comments

A few fixes.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by joesinghaus** [comment]
@Karlinator I already merged this last week :D. I merged roll20/master into karlinator/master and almost all the diffs went away.

The translation diffs are still there since they were helpfully reverted by the automatic translation tool. I already pinged Cassie on another PR - the translations need to be regenerated from scratch so that it does not keep overwriting the fix for Initiative.

**Comment by Karlinator** [comment]
Right, guess I didn't see that. When I made this it still showed diffs on all the files I think. So you're saying I can just close this?

**Comment by joesinghaus** [comment]
Yes, I saw all the diffs and was confused why they were there, so I merged explicitly.

Let's leave it open so we make sure that the issue with translations is handled somehow?

**Comment by clevett** [comment]
@joesinghaus 

What would you like me to do for this request? I think I saw your notification in another ticket but I cannot find it now.

**Comment by joesinghaus** [comment]
Thanks Cassie.
Whenever the translations are updated from Crowdin (?), they overwrite this change to Initiative for all the language-specific translation files (it's been fixed in translation.json for a while). Could you fix this?

**Comment by joesinghaus** [comment]
I fixed it by changing the key instead. This can now be closed.

**Comment by Karlinator** [comment]
Cool

**Pull request closed without merging**
