### PR TITLE
1800 el ocaso de la humanidad

### PR DESCRIPTION
**Pull request by Hornwar**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Hornwar** [comment]
Hello. First of all, sorry for not answering before, i have been very busy with work last months and i didnt see the mesages in github.
Yesterday i did the process step by step with a colkegue who worked  with githubbefore, and i am sorry if there was a mistake, i clicked on edit file on the html file, and copied the corrected code (i dont know any other way to do it, sorry).
Yesterday i looked into it and i changed 2 more things that were still broken, now it should be allright.

**Comment by pwilson-roll20** [comment]
Hello,

I'm still unable to merge your pull request due to existing conflicts within git. If you need help resolving these, please consult the following link for additional information: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

**Comment by Hornwar** [comment]
Greetings @clevett

I have updated my fork with the pull tool. Do I need to do another pull
request now? From my branch to roll20 master?

Thanks guys for your support

hornwar

**Comment by clevett** [comment]
@Hornwar It looks like this PR is coming from a branch. You'll need to update that branch. You can do this by merging in master of your fork and resolving the merge conflicts.

**Comment by Hornwar** [comment]
To be honest, I have no clue why this branch is existing xDD I think is outdated, cause my master branch is updated, and last pr there is from 14 days ago, and actually changes have been done in roll20 already, and this branch has the last commit 23 days ago.
I need to do some additional work on the character sheet, and I think it would be easier to close this pr and I will do a new one in the future.

**Comment by samus** [comment]
As requested by the author, closing this PR.

**Pull request closed without merging**
