### PR TITLE
RWBY RoC Minor update v2.01

### PR DESCRIPTION
**Pull request by Kasenai3**
Hello. Minor update in response to problems reported on reddit.
I fixed semblance rolls and replaced chat message for reduced phial rolls level 2 and 3.

I also added a "Level" filed besides the character name field and updated the change log to include these 3 changes.

### CODE REVIEW

**Comment by Anduh** [comment]
This PR seems to have some conflicts, which you need to fix before any changes can be considered or approved.

**Comment by Kasenai3** [comment]
Ok, I resolved the conflicts. This was a first for me so I had to look up what's what and how it's done.
I think conflicts happened because my pull request included precedent changes (which were already merged to r20 master). 
Or am I wrong?

**Comment by Anduh** [comment]
Yeah, that's likely the case. Good work fixing it!

**Comment by Kasenai3** [comment]
Thanks !

**Pull request merged**
