### PR TITLE
Lames du Cardinal - french

### PR DESCRIPTION
**Pull request by Phoxounet**
Pretty simple sheet for quick reference. Card based system, so no dice and no automation.

### CODE REVIEW

**Comment by pjbehr87** [comment]
The file names do not match the references in the sheet.json. I'll fix it because it's a super simple fix, but just keep an eye out in the future. Thanks for all of your work on our French sheets!

**Comment by Phoxounet** [comment]
My bad... Sorry about this. I'll be more cautious next time. And thx for 
the changes. :)

Regards !
Yannick

Le 31/05/2016 à 20:52, Phil a écrit :
>
> The file names do not match the references in the sheet.json. I'll fix 
> it because it's a super simple fix, but just keep an eye out in the 
> future. Thanks for all of your work on our French sheets!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Roll20/roll20-character-sheets/pull/1672#issuecomment-222784666>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/APMaktJPRErGLVMO5EdKLTaKLuwR9GEeks5qHIODgaJpZM4IquDR>.
>


-- 
Cordialement,
Yannick Hondarrague

**Comment by Phoxounet** [comment]
Hi again !

I have a question about submitting character sheets : do we have to 
submit only one sheet at once or can we submit several sheets at the 
same time ?

Regards,

Yannick

Le 31/05/2016 à 20:52, Phil a écrit :
>
> The file names do not match the references in the sheet.json. I'll fix 
> it because it's a super simple fix, but just keep an eye out in the 
> future. Thanks for all of your work on our French sheets!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Roll20/roll20-character-sheets/pull/1672#issuecomment-222784666>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/APMaktJPRErGLVMO5EdKLTaKLuwR9GEeks5qHIODgaJpZM4IquDR>.
>


-- 
Cordialement,
Yannick Hondarrague

**Comment by pjbehr87** [comment]
I prefer if you can split them into separate PRs, it makes it easier for me to test/verify, but you can definitely submit more than one at a time.

I just did a quick test of this one, and there are some issues. In the top right box I am only able to select the inputs in the last column, and cannot click the other 3 columns. I'm going to go ahead and leave it up and you can fix it whenever.

**Pull request merged**
