### PR TITLE
fix(Stars_Without_Number_Revised): add adventurer option to class selection dropdown

### PR DESCRIPTION
**Pull request by trevor-coleman**
# Submission Checklist
## Required
- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

N/A

# Changes / Description

This PR adds the "Adventurer" option to the class selection dropdown on the **Stars Without Number - Revised** sheet.

The class is supported in the autofill and other sections of the code, but seems to have been overlooked in this menu.

## Screenshots

Before:
CleanShot 2024-07-07 at 09 02 23@2x

After:
CleanShot 2024-07-07 at 09 00 21@2x

### CODE REVIEW

**Comment by trevor-coleman** [comment]
@Karlinator @joesinghaus  - I'm not able to request reviews, so tagging you so you see this PR. 

It adds new options for the Adventurer subclasses, with autofills.

Thanks for making such a great sheet! It's been working great so far. 🙌🏻

**Comment by trevor-coleman** [comment]
@svmnotm -- would you mind reviewing these changes? Mostly just looking for a general sense check. I've tested it pretty well and it's working great.

Asking because you are the only contributor in the list with any github activity in the last 12 months. 😅

_(I don't think anyone's made any changes to this sheet in ~4 years)_

**Comment by NorWhal** [comment]
Hey @trevor-coleman! 
We're going to mark this as under review until @svmnotn gets back to you!

**Comment by trevor-coleman** [comment]
> Hey @trevor-coleman! 
> 
> We're going to mark this as under review until @svmnotn gets back to you!

OK, I'm not optimistic, but let's hope! 🤞🏻

I did test it pretty thoroughly, but it's always good to get a second set of eyes on it.

**Review by svmnotn — APPROVED** [review]
Looks good! Thanks for the improvements!

**Comment by trevor-coleman** [comment]
Brilliant!

**Comment by trevor-coleman** [comment]
I'm happy to be a contributor/maintainer for at least the next year or two. I'm running a campaign and using the sheet pretty heavily so SWN will be on my mind.

**Comment by Karlinator** [comment]
Oh, hey, looks pretty neat @trevor-coleman! I don't remember why I didn't do autocomplete here, thanks for adding it.

Feel free to contribute more! As you noticed I haven't for a while now, mostly due to no longer running a SWN campaign on Roll20, so I ran out of motivation for it.

**Pull request merged**
