### PR TITLE
UESTRPG sheet redone

### PR DESCRIPTION
**Pull request by EnricoDandolo1**
## Changes / Comments

Redid the sheet from scratch after encountering a bunch of issues over the past versions. Tried to stick more closely to the original 5e OGL sheet this time, to make up for the fact that idk what I'm doing. Also used the opportunity to restore spell slot tracking for ease of use with NPC spellcasters alongside the magicka / spell point system for PCs.

## Roll20 Requests

*Include the name of the sheet(s) you made changes to in the title.*

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- Is this a bug fix?
- Does this add functional enhancements (new features or extending existing features) ?
- Does this add or change functional aesthetics (such as layout or color scheme) ? 
- Are you intentionally changing more that one sheet? If so, which ones ?
- If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by clevett** [comment]
Greetings @EnricoDandolo1 

This pull request has merge conflicts in it and I will be unable to merge your sheet until you have resolved those. Due to the size of this sheet it will need to be done locally in your fork's repository on your workstation.

Thanks,
Cassie

**Comment by EnricoDandolo1** [comment]
I'm sorry, I've spent the last 40 minutes googling without finding an answer (ignoring my lecturer's thoughts on early dynastic Sumer) and I can't figure out how to do that. I've tried both Git Bash (which doesn't find the repository to begin with), Git GUI (which I can't figure out), but neither will seemingly give me the option to choose what changes to commit ... :'(

**Comment by kreuvf** [comment]
> I'm sorry, I've spent the last 40 minutes googling without finding an answer (ignoring my lecturer's thoughts on early dynastic Sumer) and I can't figure out how to do that. I've tried both Git Bash (which doesn't find the repository to begin with), Git GUI (which I can't figure out), but neither will seemingly give me the option to choose what changes to commit ... :'(

Some pointers:
* `git add --patch <filename>` to select which changes in a file should go into the commit.
* `git add <filename>` to select files to go into a commit.
* `git clone` to get the repository locally, probably needed for Git Bash

**Comment by EnricoDandolo1** [comment]
I confess I don't even understand what to do with those. I've got the repository forked and downloaded locally, and did the commit using GitHub Desktop. The idea is to completely replace the three existing files on live, is there no way to do that? Sorry for the noobiness, I feel like at this point I need some handholding :')

**Comment by kreuvf** [comment]
It looks like you fixed it on your own. One thing, though, you should consider trying the current version of the sheet and see whether it still works. 

> Sorry for the noobiness, I feel like at this point I need some handholding :')

No need to be sorry ;) What you want, could have been achieved by doing the following (not best practice :P):

* Get copies of the final version of your files and save them somewhere outside the reach of Git.
* You have already forked the Roll20 repository "roll20-character-sheets". Please note: _Forking_ is a GitHub thing. Usually, that is called _cloning_.
* Create a new branch on your fork (online). Use a descriptive name.
* Edit the files, iirc you can do this online: Paste the contents of your saved final versions.
* Make a commit with the changes.
* Make a new pull request (use your new branch as source for the pull request).

Then, you could close this pull request here. For the next time.

My personal recommendation: Learn Git. It's an invaluable skill, even outside software engineering. I used the book [Pro Git](https://git-scm.com/book/en/v2) and when doing stuff just googling found everything I needed, most of it on [Stack Exchange](https://stackexchange.com/).

**Comment by EnricoDandolo1** [comment]
Thanks for the advice, will definitely bear that in mind for the future. The changes seem to work, at least until I encounter the next bug. Learning Git is definitely on my list, right behind gaining a modicum of understanding of music theory and continuing to study cuneiform languages lol Cheers!

**Comment by Anduh** [comment]
The wiki have [links some good resources](https://wiki.roll20.net/Beginner%27s_Guide_to_GitHub#Git_and_Github_for_Poets_Youtube_Tutorial) that explains the basics well IMO.

**Pull request merged**
