### PR TITLE
new game, Aquelarre

### PR DESCRIPTION
**Pull request by kinower**
hi, I request the upload of the character sheet for the game Aquelarre, thanks and regards

### CODE REVIEW

**Comment by clevett** [comment]
Greetings @kinower 

Your sheet.json has an extra ",' on the last line. That comma will need to be removed.

You've also have changes to a Dungeon World sheet in this pull request. Is that intention? We generally like to keep pull request to 1 game system per request to make it easier to review.

Thanks,
Cassie

**Comment by kinower** [comment]
ok, thanks, it's already solved

**Comment by clevett** [comment]
@kinower 

Thanks for fixing the Json. You still have the changes to the Dungeon World sheet in the pull request. Were the changes intended?

**Comment by kinower** [comment]
I think that you already create a new pull for each of the failures you commented on
[https://github.com/Roll20/roll20-character-sheets/pull/4178](url)
and [https://github.com/Roll20/roll20-character-sheets/pull/4179](url)

**Comment by clevett** [comment]
Greetings @kinower 

I am sorry for the confusion. We normally request 1 sheet be change per request. This can be done by using multiple branches in Git. This helps me know the changes to a sheet are intentional. Some people accidentally submit changes to other games. If you do create a pull request updating more than one sheet that is okay. You will just want to leave a comment.

Thanks,
Cassie

**Comment by clevett** [comment]
Just so you know. All of your changes should be getting merged in. I had to do a little work around to fix the pull request but everything will be added to the repo. Disculpe para confusión.

**Comment by kinower** [comment]
thanks, you Clevett, know when my character sheet will be available?¿?¿

**Comment by clevett** [comment]
It should be available in 2-3 hours. :)

**Comment by kinower** [comment]
great, what speed.
I would also like to know if you are also ready for the Character Sheet Template in roll20. thanks!!!!!

**Comment by clevett** [comment]
I had to manually update your sheet.json. You will want to pull down those updates from the repo. This character sheet is now live.

**Pull request merged**
