### PR TITLE
[Woin] Enable one decimal place for equipment weight

### PR DESCRIPTION
**Pull request by Ghostroo**
## Changes / Comments
Firefox and Chrome threw visible errors (although the calculation was correct) when equipment weight or weight total had a fractional component (decimal place). This update enables 1 decimal place for both weight numbers. Tested successfully on both platforms.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [Y] Does the pull request title have the sheet name(s)? Include each sheet name.
- [Y] Is this a bug fix?
- [N] Does this add functional enhancements (new features or extending existing features) ?
- [N] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [N/A] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [N/A ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Ghostroo** [comment]
Hi Cassie,

I don't understand, the conflict listed is the change I want to make. The identified lines should be different by virtue of step="0.1" being added. I am not sure what I should have done, I am still learning how github works with Roll20. I have tested the change by pasting the html into my test game and it works. Can you please point me in the right direction?

Regards,

Ghostroo

**Comment by Ghostroo** [comment]
Hi Cassie,

I have removed the unwanted lines, tested the code in my test game and it
works. I have submitted a commit merge request with the updated file
WOIN.html. It was indeed easy to do in Github.

I don't understand one part of the process, when I submitted changes to
this file the first few times, I did not receive a conflict. This time I
did receive a conflict but the changed lines that Github did not like were
exactly the changes I wanted. Did I submit the update incorrectly? Are the
old and new lines too similar and thus the error resulted?

Thank you in advance, you have been very helpful so far and these questions
must seem basic understanding to you.

Regards,

Ghostroo

**Comment by clevett** [comment]
Greetings Ghostroo,

Are you keeping your fork up to date? It's possible that your fork is out of sync which GitHub then returns conflicts.

**Comment by Ghostroo** [comment]
Hi Cassie,

I think that was the issue. I have merged the upstream into my fork and
I'll resubmit the last changes as they are not reflected in the current
production WOIN sheet.

Regards,

Ghostroo

**Pull request merged**
