### PR TITLE
FABDOFS: New Sheet

### PR DESCRIPTION
**Pull request by Rorrik**
# Submission Checklist
## Required

- [X] The pull request title clearly contains the name of the sheet I am editing.
- [X] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X] The pull request makes changes to files in only one sub-folder.
- [X] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: FABDOFS
- The publisher of this game is: The RPG Sage
- The name of this game system/family is: FABDOFS

- [X] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [X] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

This is a complete addition of the FABDOFS system. The sheet used the existing BECMI sheet as a starting point with modifications to attribute modification up to attributes of 100, how saves were grouped and calculated, a new Social tab including Personality Traits, Social Skills, and Strain, changes to the appearance of the whisper for thief skills, removal of armor type from encumbrance, new armor type list, recalculation of inventory weight to allow access to encumbrances for use in speed calculations for the added Knight, Barbarian, and Mystic classes.

A future change will include the last modification needed, a change to the Wrestling system.

### CODE REVIEW

**Comment by Rorrik** [comment]
Is adding it to the approved.yaml something I do? Or do I wait?

**Comment by Djjus** [comment]
No the admin team does that..

**Comment by Rorrik** [comment]
> No the admin team does that..

Thanks, that makes sense.

**Comment by kfroll20** [comment]
Hello @Rorrik! 

Thank you for your submission! For new sheets, we require that rules be publicly available. Once you provide a link to the rules, we can move forward with getting this merged.

Thank you!

**Comment by Rorrik** [comment]
The creator isn't ready to make the rules public and will be using this sheet for ongoing testing. I'll withdraw the change and continue working on my fork. Thank you!

**Pull request closed without merging**
