### PR TITLE
Add a new Savage Worlds sheet

### PR DESCRIPTION
**Pull request by olivier-grech**
This is a new Savage Worlds sheet. The existing one was a bit too busy for my taste, so I made this one.

This sheet has no script or auto-roll buttons, as I am still inexperienced with this. However, I have taken great care in making sure it is pleasant to look at and easy to use.

I also tried to stick to the best practices described in the wiki:
- Attribute names are in lowercase
- There is only one `!important` in the CSS (I don't think it is possible to do without it)
- I didn't repeat `-sheet` for the CSS classes in the HTML file
- I used ``spellcheck="false"`` for `textareas`
- No inline styles
- I used i18n to make sure the sheet is fully translatable

What could be improved:
- Obviously add sheet workers and auto-roll buttons, though I believe given how the sheet is made, it will be tricky
- The skull icon is hosted on imgur, and is not present in the files because I am not sure how to do that
- A minimum `width` should be set

I am concerned about making this sheet as good as possible (though I don't want it to be a scripted monstrosity with 3 tons of "shortcuts" that only confuse the player), so please don't hesitate to give your feedback.

### CODE REVIEW

**Comment by Anduh** [comment]
The new Shadowrun Sheet was made by Cassie, who is part of the Roll20 team, so I 'm not that really works as a counter-example.

But yeah don't get too discouraged by my unsubstantiated claim, just know it's a possibility. You'll know at latest on Monday, when cassie makes the rounds and checks the new PRs.

**Comment by olivier-grech** [comment]
Sure, thanks for the information.

**Comment by clevett** [comment]
Greetings @olivier-grech and @Anduh 

We do attempt to keep sheets per system down to a minimum. We regularly take 2-3 sheets for popular systems like D&D, Shadowrun, Warhammer, Savage Worlds...There are currently four sheets active for Savage Worlds. Due to the number we currently have, we will likely not be adding additional Savage World sheets but if a sheet of high quality was to come along we are open to looking at replacing one of the four. Particularly one of the two which have not receive updates in 2+ years.

As a note, this was the process followed for my Shadowrun 5th Edition & Anarchy sheets. We replaced older sheets that were no longer receiving support & updates. I hold myself to the same standards as other sheet authors. :)

As for your sheet Olivier, you are off to a really good start! Here are some additions which will raise the quality of the sheet.

- Roll buttons - [minimum requirement](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository). You might look at the other Savage World sheets for examples
- Remove `id=""`. Character sheets cannot use the ID element.
- Img needs to be on GitHub. Download it from imgur and put it in the folder where your sheet is. Then upload it to your fork on github. You can right click the image on GitHub and get the address to link to it in your HTML.
- Set a width `.charsheet {width: 850px;}` . This will add a scroll bar at the bottom when the sheet collapses rather than it smushing together. Alternatively you can do other designs like [Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).
- textareas, I would include `resize: vertical;`. This will stop them from resizing horizontally into its neighbor.

I would suggest loading the simple *Savage Worlds* character sheet into a game and familiarizing yourself with its functionality. You'll want your sheet to be able to do everything it can at a minimum. [The code](https://github.com/Roll20/roll20-character-sheets/blob/master/SavageWorlds/SavageWorlds.html) is outdated by our current standards but updating it could be an alternative.

**Comment by Anduh** [comment]
Thanks for the quick reply even if we didn't ping you :)

Was the written mention of trying to avoid having multiple sheet for each system removed from the guidelines? Even if the recommendation is looser now, it could still be good to have it mentioned somewhere.

Anyway, I'll cite your reply here in the future, so I don't come of as a madman with [citation needed] written on my forehead, when this topic comes up next time.

**Comment by clevett** [comment]
Greetings Anduh,

The old rule was removed to to avoid it being cited. ;) It was occasionally cited in a way that was discouraging to budding sheet author looking to try their hand at development. Yet we've maintained a loose rule for the benefit of users as we want to keep options per game to a small selection of the best sheets possible. Finding the right balance is a tricky task. 

You are correct that it would be best that the temporary guidelines be posted. I'll look at adding my reply here to our documentation.

**Comment by olivier-grech** [comment]
Thanks for your detailed answer @clevett.

Except for roll buttons which will take a bit more work, I have taken care of the issues you mentioned.

I'll try to take some time to implement the roll buttons now in order to best emulate the features of the other sheets, as you suggested.

**Comment by Anduh** [comment]
Well I guess it was a good idea to remove it, if it was too black and white.

I was likely among those who cited it most frequently, even if I didn't like it too much.

**Comment by olivier-grech** [comment]
I added the roll buttons for attributes and skills.
I'm still missing some features from the other sheet, notably the damage roll buttons.

I added a bennies counter as well since I forgot about that.

**Comment by clevett** [comment]
Greetings,

It looks like this Pull Request is deleting some graphics for Runequest. If this is unintentionally you'll want undo these changes. 

For now I am going to close this pull request since its still a work in progress. While its open its emailing a notification to every sheet author when you do updates. ;) When you've got the damage buttons up and are ready for it to go live you can submit another pull request. 

Thanks,
Cassie

**Pull request closed without merging**
