### PR TITLE
[Das_Schwarze_Auge_5_Tsa_Edition] initialisation of the nl.json

### PR DESCRIPTION
**Pull request by dyvim**
translation provided by the official dutch translation team for oogdesmeister

## Changes / Comments

all german terms are replaced by their dutch translation

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards]

### CODE REVIEW

**Comment by Stexinator** [comment]
If i remember correctly translation have to be done via Crowdin

**Comment by dyvim** [comment]
> If i remember correctly translation have to be done via Crowdin
Yes i know.
If my pull request is not accepted i'll use it but it's really quicker that way and i have no access to the dutch language...

**Comment by mperes** [comment]
Hello @dyvim ! Your Pull Request includes changes to translation files. Unfortunately, we no longer accept translations submitted outside of Crowdin. To learn more about Crowdin and how to submit translations through Crowdin, please see our article on [How to Become a Translation Volunteer.](https://help.roll20.net/hc/en-us/articles/360058423993-How-to-Become-a-Translation-Volunteer) Thanks for all you do!

**Comment by dyvim** [comment]
> Hello @dyvim ! Your Pull Request includes changes to translation files. Unfortunately, we no longer accept translations submitted outside of Crowdin. To learn more about Crowdin and how to submit translations through Crowdin, please see our article on [How to Become a Translation Volunteer.](https://help.roll20.net/hc/en-us/articles/360058423993-How-to-Become-a-Translation-Volunteer) Thanks for all you do!

Hello. I am already a translator in Crowdin. I'll use the tool but it will take more time.

**Pull request closed without merging**
