### PR TITLE
Buffy RPG Update 1.03

### PR DESCRIPTION
**Pull request by MattBx8**
Updated html and readme files

### CODE REVIEW

**Comment by wing-it** [comment]
Hi there! GitHub is showing some conflicts on these files that are a little more complicated than I'd like to try resolving myself. Could you please resolve these so I can merge this request? Thanks!

**Comment by MattBx8** [comment]
Hello wing-it,

I don’t understand what is in conflict. Is it the purple toned lines that have @@ symbols? I don’t know what they mean. Any assistance is appreciated!

/Matt

**Comment by wing-it** [comment]
I'm not sure what is causing the conflict, but you can just click the `Resolve Conflicts` button below the comment section of the website and use the web interface (if you are using GitHub Desktop, I will be of less help to you as I don't use that myself).

The conflicts will appear marked by git in this format:

```
<<<<<<< Buffy-3
                <th><button type='roll' class="sheet-skillbutton" value="/e attacks with @{Stake_name-1}, rolling [[@{Stake_attack_rating-1} + d10]] to hit and [[(@{Stake_damage_base-1})]] damage (add 2 x Success Levels to damage)."></button></th>
=======
                <th><button type='roll' class="sheet-skillbutton" value="/e attacks with @{Stake_name-1}, rolling [[@{base-Dexterity} + @{mod-Dexterity} + @{Stake_attack_rating-1} + d10]] to hit and [[(@{Stake_damage_base-1})*(@{Stake_damage_type-1})]] damage (add 2 x Success Levels to damage)."></button></th>
>>>>>>> master
```

You will need to pick which code is correct and delete everything else between the `<<< >>>`, so that it looks something like this:

```
                <th><button type='roll' class="sheet-skillbutton" value="/e attacks with @{Stake_name-1}, rolling [[@{Stake_attack_rating-1} + d10]] to hit and [[(@{Stake_damage_base-1})]] damage (add 2 x Success Levels to damage)."></button></th>
```

I'm not sure why you're getting these marked as conflicts, normally this would just update automatically. You may need to check your text editor's line ending settings and make sure it's set to Unix line endings (\n), and NOT Windows line endings (\r\n). This might be causing the conflicts as our system will automatically convert line endings to Unix, which may be the source of these conflicts, though it's difficult to tell in the web interface. Another thing you can do is for future changes, delete your branch and pull down a fresh copy of the code to base your changes on.

**Comment by MattBx8** [comment]
Hello wing-it,

I’ll make corrections soon, this weekend at the latest. Thanks!

/Matt

**Pull request merged**
