### PR TITLE
[Aria] Update sheet to avoid using absolute placement for each field

### PR DESCRIPTION
**Pull request by Baleine82**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [ ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

The existing sheet was placing almost everything with an absolute location.
I tried to make it a bit more clean

### CODE REVIEW

**Comment by PixelReveur** [comment]
Suite à cette mise à jour, la méthode 2 pour le calcul des compétences ne semble plus fonctionner.

Following this update, method 2 for calculating skills no longer seems to work.

**Comment by Baleine82** [comment]
Mince, je suis désolé. J’ai probablement omis de vérifier cette partie, vue que je ne m’en suis pas servi. Je vais voir ça rapidement et en profiter pour régler un petit problème dans le CSS où les labels pour le nom de l’arme et ses dégâts sont inversés. Merci pour avoir vu et partagé l’info.
---
Damn, sorry for that. I may have overlooked this method, since I didn’t used it. I’ll check that soon. Also, I noticed an error in the CSS, where the labels for weapon name and damage are reversed. Thank for sharing.

**Comment by Baleine82** [comment]
Actually, it's way worse than that. Clicking on method 1 calculate skills with method 2…
And the button for method 2 is broken. I'll fix that ASAP. Expect a new PR this weekend.

Really sorry for this inconvenience

**Comment by Baleine82** [comment]
@PixelReveur Tu aurais du temps pour valider que ces modifications corrigent le problème rencontré et n'en produisent pas d'autres ? https://github.com/Roll20/roll20-character-sheets/compare/master...Baleine82:roll20-character-sheets:aria/FixSkillCalculation

**Pull request merged**
