### PR TITLE
Adding new sheet

### PR DESCRIPTION
**Pull request by momentumx**
# Submission Checklist
## Required

- [ x] The pull request title clearly contains the name of the sheet I am editing.
- [x ] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x ] The pull request makes changes to files in only one sub-folder.
- [ x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: < Forge >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: < Ricky Martinez  > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < Forge > _(i.e. Dungeons & Dragons, FATE)_

- [ x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x ] This sheet has been made on behalf of, or by, the game's publisher.
- [ x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at:    < ForgeRPS.com  >
- [x ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

Adding new Forge character sheet

### CODE REVIEW

**Comment by mperes** [comment]
Hey there @momentumx, just to double check: This is the official sheet for the game, right?

**Comment by momentumx** [comment]
Yes it is.

**Comment by momentumx** [comment]
Hi y'all! Just wanted to make sure everything was alright. I think I read something about Tuesdays being the review for most pull requests, and I see a red x on mine, so I wasn't sure if y'all were waiting on me. No rush, just wanted to check in

**Comment by nmbradley** [comment]
Hi @momentumx 

Apologies for the slow response; the preview image for the character sheet needs to be a screenshot of the character sheet. 

Once this is corrected, we can merge the sheet.

Thanks!

**Comment by momentumx** [comment]
Ok, I updated the photo, pulled in master and pushed my branch. Should I
make a new pull request or is the old 1 still good?

**Comment by mperes** [comment]
Hi @momentumx it seems your pull request contains changes to multiples sheets (folders) at once. If that was intentional, please break the change into one PR per sheet. Otherwise check for files that were modified by mistake and remove them from your original PR.

**Pull request closed without merging**
