### PR TITLE
[Old School Essentials AAC] - adding missing translation terms

### PR DESCRIPTION
**Pull request by Greyblade**
adding missing translation terms

### CODE REVIEW

**Comment by BronsonHall** [comment]
Hey @Greyblade !

This sheet is another official publisher sheet - though it's a small (and important) change, we do require approval from the publisher, in case they keep an internal copy of the sheet, for instance.  I believe the sheet you originally submitted this change to earlier today is a (now-hidden) earlier community version of the sheet, not accessible anymore in created games.  

I know the original author of this official sheet used to keep an active repo for issues & suggestions, but it looks like it was archived in 2022.  I'll check on our side how Necrotic Gnome would prefer changes to this sheet to be made these days.  Blocking this for now, but I'll get back to you soon!

**Comment by Greyblade** [comment]
No worries at all, let me know :)

**Comment by Greyblade** [comment]
Hi @BronsonHall any news from Necrotic Gnome?

Have a great day

**Comment by BronsonHall** [comment]
Hey @Greyblade 
  Nothing new on this yet, apologies!
Thanks for your patience!

**Comment by Greyblade** [comment]
> Hey @Greyblade 
>   Nothing new on this yet, apologies!
> Thanks for your patience!

Any news since then?

**Comment by BronsonHall** [comment]
Hey @Greyblade!

Just got a reply this morning - it's approved and I'm merging this now!  Thanks again for your patience, and continued effort to improve the sheets on this repo!

**Pull request merged**
