### PR TITLE
[Supersix] Little update + question

### PR DESCRIPTION
**Pull request by Zakarik**
## Changes / Comments
Hello,
I was contacted by Eric Blaise (mentioned in the creators of the sheet).

He wonders why his card is hidden.
He has tried to contact someone, but no one is answering him.
The little change I'm making here will probably have no impact on anything, but it allows me to contact you.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [X] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
You should also update the filename if you change to link in the sheet.json. if they don't match exactly, the sheet won't show up properly.

The sheet might have been removed from the dropdown due to very low usage, and not having been edited in 3 years.

**Comment by Zakarik** [comment]
I renamed the file as well, as you can see in the modified files.

**Comment by Zakarik** [comment]
Can this sheet be made available again?

**Comment by Reonin** [comment]
Hi @Zakarik I believe the lower usage is why it was removed from the list. I will merge in this update and remove the flag preventing it from showing up. Hopefully it continues to get some updates going forward.

**Pull request merged**
