### PR TITLE
RolemasterUnified Official: CRP Skills and other minor updates.

### PR DESCRIPTION
**Pull request by nashidau**
The headline feature of this weeks release is using CRP (Custom Roll Parsing) for skill rolls. This means we have a lot more descriptive text and information in skill rolls; similar to attacks and spells.

Experimental support for custom spells has been added, and there is a way you can turn a sheet to a creature sheet.  More on that coming soon.

Othwise there are lot of nits; hiding stun effects when you don't have any; and show current ranks when you level up.  For both skills and spells.

- Skills:
  - Use CRP for rolls
  - Expand descirption and modifiers for use.
- Custom Spells now supported (experimental)
- Status effects like stun/staggered/bleed disappear if empty.
- Spell mastery masters magic; not manipulates (message change)
- Remove some injury debug.
- Religion is now an attribute.
- Compendium:
  - Evaporate Liquid is not 1, and it's 1000 cu ft, not 000 cu ft
  - Darkvision 10 + 5/tier. not 10+10
  - Golden throat 5/tier
  - Fix some minor grammar issues in some talent descriptions (.s and the like)
- Talents:
  - Fix costs with different per tier costs
  - Add placeholder support for spell lists.
- Optimisation: Reduce by ~3 number of API calls in updateSkils.
- Force ' ' for empty skills when there was a value.
- Attacks now have parry and 'other' modifiers (Long requested feature)
- Fix a bug stoppind stun penalies from applying to spells
- Levelup:
  - Spells persist their ranks (again)
  - Show current rank of simple skills
  - Show current rank of specialised skills.
  - Show current rank of spells
- Creatures:
  - Make creature loading more resiliant
  - Add a hidden way to turn a sheet into a creature
- Add a new preview image.

# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by kfroll20** [comment]
Hello @nashidau, 

Great work on the updates and thank you for providing details to those changes in your PR description. 

Before merging this, I wanted to check in about the attribute names including 'maneuver' in them. The spelling for 'maneuver' is corrected in a few places, but then on line 2051, the attribute name is changed from `attr_manpenalty` to `attr_manueverpenalty`. Once you're done updating the spelling in the attribute names to be consistent throughout the file, can you double check that the attribute name change is being handled correctly in the sheet workers? 

Thank you!

**Comment by nashidau** [comment]
The man penalty attribute was totally wrong.  It is also generated so on sheet load it will be updated to the correct name.

**Comment by nashidau** [comment]
BTW: It was totally wrong before, now it's less wrong.  In a few weeks I'm going to do an overhaul of the encumbrance system (Treasure Law support).

**Comment by nashidau** [comment]
The only time manpenalty occurs now is a comment.  Which tells you I should run a minimizer at some point ;-)

**Comment by nashidau** [comment]
@kfroll20 any chance we could send this today?  The compendium is about to go live.

**Comment by kfroll20** [comment]
Merged!

**Pull request merged**
