### PR TITLE
Jackals

### PR DESCRIPTION
**Pull request by totalgeekthe1st**
## Changes / Comments
This is an attempt to upload the character sheet I built for Osprey Games' Jackals.  I edited the Barebones Fantasy RPG sheet by Justin M. Gordon to create the sheet.  I have little to no experience with anything like this so if there are things to fix let me know and I will work on them.  
Everything is in a new folder called 'Jackals' which contains 'jackals.html' 'jackals.css' 'jackals.png' and 'sheet.json'.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
You should have used some other sheet as a template, bc that one does layout with `<table>`, which is one of the few requirements for character sheets submitted to the repo.

https://wiki.roll20.net/Building_Character_Sheets#2._Good_Code

**Comment by totalgeekthe1st** [comment]
> You should have used some other sheet as a template, bc that one does layout with `<table>`, which is one of the few requirements for character sheets submitted to the repo.
> 
> https://wiki.roll20.net/Building_Character_Sheets#2._Good_Code

Ok, if my Jackals sheet in ineligible because of using <table> for layout, then why is the Barebones Fantasy sheet eligible?  And if the answer is something like "That sheet was submitted before using <table> for layout was against the rules," then can I suggest that that information regarding current ineligibility be put somewhere where it is difficult to miss, like in the readme of the Barebones Fantasy sheet?  Something like that would have saved me a lot of time and effort while trying to learn how to make a Roll20 sheet.

**Comment by totalgeekthe1st** [comment]
Andreas - Thank you for reaching out, I know you didn't have to do that and it means a lot to me.  As you can probably tell web development and HTML and CSS coding is really not my field of expertise, and my frustration with being out of my element has colored this whole process.  I want to apologize for the way I responded to you, I have had a rough week and was annoyed by the curt response as well as being annoyed at myself for not doing my due diligence on the project, and it wasn't fair to lash out at you for that, so I am sorry.  And again thanks for reaching out to respond.

Thank you for the linked examples, I'll dive into those next week and I'm sure they will be very helpful, and thank you for your offer to help.  I'm going to try to fix the sheet myself and get it approved but if I get stuck I will definitely reach out.

>Yes, that's exactly the reason, old sheets submitted before 2018/2019 or whenever are grandfathered in, and the rules applies to *new* submissions.

I guessed that that might be the case.  Thank you for offering to add a disclaimer about "old sheets are grandfathered and don't have to hold up to submission standards" to the wiki, and for the information about "<table>" causing sheets to be rejected/delayed.  If it is simply a matter of grunt work to add something like "NB: This sheet uses the HTML table function for layout and therefore would not be accepted as a new Roll20 sheet today" to readmes, I might be able to work on that (although I recognize that someone with more familiarity with the process would almost certainly have found that information the normal way).  IDK, looking at it now something like that would have helped me but it probably wouldn't be that useful for most users.  We'll see how valuable my time is in the next few weeks, I certainly have a talent for the kind of grunt work it would take to look through lots of sheets and add disclaimers.

Again, thank you for reaching out and I'm sorry I snapped at you.  I'll see if I can figure out why you can't comment on the github and we can communicate more there.  I'll also send this on Github so that hopefully you see it one place or another.

-Arlen Walker

P.S.  I was looking at some other character sheets, and in particular the Spanish language Against the Darkmaster sheet is awful, by which I mean it's an imgur-linked image with text boxes named "text_box_1" "text_box_2" etc. laid over that image.  I'm actually also working on an Against the Darkmaster sheet based on this one: https://github.com/nogileyelsew/Against_The_Darkmaster and was wondering what the best way to replace the current sheet would be once I have the new sheet ready.  Is it just a matter of replacing the HTML, CSS, and sheet.json files on github?  I guess what I'm saying is that one of my annoyances was my discovery that that current sheet breaks the "Character Sheets must be standalone by default" and the feeling of an unfair double standard crept in and that's part of why I was annoyed.  Since you have much more experience with Roll20 sheets, perhaps you could tell me how it would be best to proceed on that front.

**Comment by totalgeekthe1st** [comment]
I assume that closing this and reopening it in a week or so with the new data is the best thing to do, please let me know if there's something else I should do before tinkering.

**Comment by Anduh** [comment]
(weird, now I'm able to comment here again)

> P.S. I was looking at some other character sheets, and in particular the Spanish language Against the Darkmaster sheet is awful, by which I mean it's an imgur-linked image with text boxes named "text_box_1" "text_box_2" etc. laid over that image.

Yes, there are many older sheets that are horrible in many ways, and some of the really bad ones that nobody uses aren't even visible in the sheet selection dropdown when using Roll20. Keep an eye on when sheets have been edited most recently, and on their edit history. If a sheet haven't been edited much in the last 3-4 years, it's extremely likely there are better sheets to use as an example.

> I'm actually also working on an Against the Darkmaster sheet based on this one: https://github.com/nogileyelsew/Against_The_Darkmaster and was wondering what the best way to replace the current sheet would be once I have the new sheet ready.

Oh yeah the [existing sheet](https://github.com/Roll20/roll20-character-sheets/tree/master/AgainstTheDarkMaster) looks bad and simplistic, and the other sheet you found is way better(looking at the code).

Generally, the preferred way would be for to improve and update existing sheets, rather than making new ones, but this is a good case where you should submit it as a new separate sheet.

You submit it as a new sheet, in a separate folder and don't touch the old one. In the PR you spell out what & why you're submitting it, and mention that this is a clearly better sheet which should replace the old one. They might accept the sheet to exist aongside the old one, or maybe even remove the old one from the dropdown, but they manage those things, and not something you can do directly.

If you want to go the extra mile to make the sheet translatable(so whoever is using the old spanish sheet can make translations for the new sheet), look at this page for how to insert that stuff: https://wiki.roll20.net/Character_Sheet_Translation 

>  I guess what I'm saying is that one of my annoyances was my discovery that that current sheet breaks the "Character Sheets must be standalone by default". 

"Character Sheets must be standalone by default" refers to sheet's must function without API scripts, but it's fine to integrate them optionally into sheets. I'm not sure what's going on with the API button use in some of the sheet's rolls, you should test and sheet if it works without some api, or reach out the the sheet author.  Might be the reason Wes never submitted this sheet to the repo.

>  and the feeling of an unfair double standard crept in and that's part of why I was annoyed

I don't see how that's a double standard whatsoever, as that wold otherwise mean some sheets wouldn't be usable by free and plus users even when in the dropdown menu. Making sheets possible to accommodate both isn't that much of a stretch, and there are only few sheets that are grandfathered into this rule.

Anyway, if you have more more questions, post in the [char sheet forums](https://app.roll20.net/forum/category/277980)

**Comment by totalgeekthe1st** [comment]
> > I guess what I'm saying is that one of my annoyances was my discovery that that current sheet breaks the "Character Sheets must be standalone by default".
> "Character Sheets must be standalone by default" refers to sheet's must function without API scripts, but it's fine to integrate them optionally into sheets. I'm not sure what's going on with the API button use in some of the sheet's rolls, you should test and sheet if it works without some api, or reach out the the sheet author. Might be the reason Wes never submitted this sheet to the repo.
> I don't see how that's a double standard whatsoever, as that wold otherwise mean some sheets wouldn't be usable by free and plus users even when in the dropdown menu. Making sheets possible to accommodate both isn't that much of a stretch, and there are only few sheets that are grandfathered into this rule.

Sorry, I wasn't clear.  What I was specifically annoyed about was contained in the next line: "All basic sheet functionality must be usable without external requirements such as images or fonts hosted outside Roll20."  Because of the way the current Against the Darkmaster sheet is designed with no labelling on anything, without the Imgur-hosted image as the background there's no way to tell what almost anything on the sheet is supposed to be.  It essentially becomes a collection of featureless text boxes without the background image.  I've attached 2 images:

Roll20currentVSDwithbackground

Roll20currentVSDwithoutbackground

to show you what I mean.  Without the background image it's totally nonfuctional, and the background image isn't hosted on Roll20, and therefore it seems to me that the sheet should not qualify under the "All basic sheet functionality must be usable without external requirements such as images or fonts hosted outside Roll20" requirement.  And that sheet was submitted in February 2021, so it's not like it's a grandfathered sheet.  That's what annoys me, not anything related to API scripts and how they interact with the sheets.

> No, this is absolutely pointless gruntwork.

> And roll20 doesn't approve editing more than one sheet per PR anyway, so you're looking for creating a massive pile of individual PRs making this change on each sheet separately.

Well that's good to know.

And I will post on the character sheet forum for help.  And the point about translation is a good one too.  I had a bit of experience with that trying to tinker with the Swords & Wizardry sheet but I will definitely read the linked page thoroughly.

**Pull request closed without merging**
