### PR TITLE
[Ironsworn: Starforged][Fix] Translations for the new assets and Field Fix

### PR DESCRIPTION
**Pull request by aureyia**
## Changes / Comments
- Translation keys were missing for the new assets
- Fields got renamed to Input in the data so this caused all the inputs to be hidden. Added a fix to re-enable them.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by nmbradley** [comment]
Hi @aureyia 

Your Pull Request includes changes to translation files. Unfortunately, we no longer accept translations submitted outside of Crowdin. They'll just get immediately overwritten by the next update from CrowdIn.

To learn more about Crowdin and how to submit translations through Crowdin, please see our article on [How to Become a Translation Volunteer.](https://help.roll20.net/hc/en-us/articles/360058423993-How-to-Become-a-Translation-Volunteer) 

My advice in this case is to make the changes to the root translation file, let the PR propogate to that service, and then update them via CrowdIn

**Comment by aureyia** [comment]
@nmbradley does this mean that existing keys that have had their values updated will also be triggered for a changes because all of the asset text was updated. We discussed it in discord and I didn't get a clear answer.

**Comment by aureyia** [comment]
I've reverted the files. To unblock the PR

**Comment by nmbradley** [comment]
@aureyia My understanding is that CrowdIn would update from the translation.json, propogate those changes to the language files, and then overwrite them anyway. If you have good translation files you can provide, I can probably directly upload them to CrowdIn.

**Pull request merged**
