### PR TITLE
adding new 3F sheet

### PR DESCRIPTION
**Pull request by Madisonw**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: 3F
- The publisher of this game is: Stewart McMaken
- The name of this game system/family is: 3F

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [x] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by NorWhal** [comment]
Hi @Madisonw ! 

Unfortunately, we are going to block this Pull Request from advancing on the basis that we do not accept new character sheets to the repository when the game rules are not publicly accessible. Per our policy, "publicly accessible" just means having the rules to play the game available for free or for purchase, typically on places like DriveThruRPG, Reddit, a personal website, or something similar.

If the rules are publicly accessible, please update this Pull Request and link to the rules in the body of the PR as requested. Otherwise, we will have to close this PR.

Many thanks!

**Comment by Madisonw** [comment]
@NorWhal 

That is sensible for sure, I was hoping to get this sheet up for my playgroup to actually playtest the system more effectively. Is there no way to make it private just to my roll20 ID for playtesting purposes?

If not thats ok, I think I can work with the author to get it published in some way or another, at least in alpha.

**Comment by aquaalex** [comment]
> @NorWhal
> 
> That is sensible for sure, I was hoping to get this sheet up for my playgroup to actually playtest the system more effectively. Is there no way to make it private just to my roll20 ID for playtesting purposes?
> 
> If not thats ok, I think I can work with the author to get it published in some way or another, at least in alpha.

If you are a paid member you can load the sheet as a custom sheet for your players

**Comment by NorWhal** [comment]
Thank you @aquaalex! For more details on how to set up a custom sheet for your campaign, you can follow [this link.](https://help.roll20.net/hc/en-us/articles/360037773373-Character-Sheet-Tips-and-Tricks#HowtoUseCharacterSheets-ForanExistingGame)

**Pull request closed without merging**
