### PR TITLE
[4d6 Morgalad Official Sheet] New-Sheet: Adding Official Sheets for the 4d6 Morgalad System

### PR DESCRIPTION
**Pull request by McnabbGames**
Adding Official Character Sheets for the 4d6 Morgalad TTRPG.

# Submission Checklist
## Required

- [ x] The pull request title clearly contains the name of the sheet I am editing.
- [x ] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x ] The pull request makes changes to files in only one sub-folder.
- [x ] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <  4d6 Morgalad >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <  McNabb Games LLC > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < 4d6 Morgalad  > _(i.e. Dungeons & Dragons, FATE)_

- [ x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x ] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

Adding Official Sheets for the 4d6 Morgalad System

### CODE REVIEW

**Comment by BronsonHall** [comment]
Hey @McnabbGames !

Sheet looks great, one small request before we can merge this: It looks like you've got some stray table/tr/td tags around the defense and movement inputs atop the file.  I'd wager a guess that these are remnants of an earlier change, as the starting tag's missing, but either way we'll need those cleaned up/removed, as we don't allow table elements for layout in new sheets as a rule.  Let me know if you have any questions!

**Comment by McnabbGames** [comment]
> Hey @McnabbGames !
> 
> Sheet looks great, one small request before we can merge this: It looks like you've got some stray table/tr/td tags around the defense and movement inputs atop the file. I'd wager a guess that these are remnants of an earlier change, as the starting tag's missing, but either way we'll need those cleaned up/removed, as we don't allow table elements for layout in new sheets as a rule. Let me know if you have any questions!

Table tags have been removed.
Thanks

**Comment by McnabbGames** [comment]
Table tags tr and td have been removed.

Thanks

**Comment by McnabbGames** [comment]
Thanks Lucas,
It looks like the short name for the sheet may be misspelled. Instead of
4d6morgaladofficial it is morgladofficial.

**Comment by BronsonHall** [comment]
Hey @McnabbGames 
We will occasionally abbreviate the shortname of new systems to fit our approved.yaml management tool.  The only requirement of the shortname is that it's unique to the system - and contains "official" for official sheets, though that's also a policy rather than hard rule.  
Importantly, the shortname isn't user-facing.  It'll be visible in the approved.yaml, but won't be shown in the sheet dropdown, or anywhere else on the site - the long name and system name are what matters there.  We've had some recent discussions about changing purpose or practices regarding shortnames, i.e. adjusting character limit or even dropping system context from the name in favor of a more generalized uuid, so this may well change in the near future.  
If you have any further questions there, let me know!

**Pull request merged**
