### PR TITLE
[NEW SHEET] Dirty System

### PR DESCRIPTION
**Pull request by ctotone**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <  Dirty System >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: < DCC  > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <  Dirty System > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

In collaboration with the creator of the Dirty System RPG, I created this character sheet.

The Dirty System RPG website is accessible at this address: [https://label-dcc.games/dirty-system/](https://label-dcc.games/dirty-system/)

This sheet is complete with the integrated data-i18n, a functional darkmode and custom rolltemplate.

The Dirty System is an originally French creation which is currently being deployed in a US version. So, for the moment, the vast majority of players who could use this sheet are FR.

The sheet and the translation file were created in US as recommended by the Roll20 guide and I also created a fr.json file. The problem being that the Crowdin Roll20 platform is currently on pause for an indefinite period. Could you manually integrate the fr.json file so that FR players can benefit from this sheet in its translated version.

Thanks in advance.

### CODE REVIEW

**Comment by NorWhal** [comment]
Bonjour, @ctotone!

We can absolutely manually update the translations for you, but I'm going to have to ask you to share them with us in a [gist](gist.github.com) and remove all the two-letter translation files from this PR. 

Thanks in Advance,
Nora

**Comment by ctotone** [comment]
Thank you for your reply.
I just deleted the translation folder.

However, I'm afraid I haven't understood the procedure to follow to offer you the translation (I'm only on my second contribution in terms of a character sheet). Do you have a link that details the procedure to follow so that I can convey all of this to you in the best possible way for you?

**Comment by NorWhal** [comment]
Desolée de vous avoir fait attendre!

I'm merging this now and adding you as an official author. Please feel free to drop a message here if you don't see the translations up by the end of the day.

**Comment by NorWhal** [comment]
@ctotone, the translations are now live!

**Comment by ctotone** [comment]
Thank you !!

**Comment by NorWhal** [comment]
Bonjour, @ctotone!
Your translations are now live! Very sorry to keep you waiting again on that.

**Pull request merged**
