### PR TITLE
L5r ffg sheet

### PR DESCRIPTION
**Pull request by rdefendi**
This includes updates for the final notes from developers for the beta testers. It also fixes one bit of broken text and includes a couple enhancement requests.

### CODE REVIEW

**Comment by wing-it** [comment]
GitHub is showing quite a few conflicts with this branch, these will need to be resolved before I can merge the request. Thanks!

**Comment by rdefendi** [comment]
This is the first time I’ve had conflicts. How can I tell what the
conflicts are. Basically, all I did was copy and paste a new form of the
html and all the translation pages in. I probably just did something
stupid, being new at this. It’s totally possible there’s a step I don’t
know about, since this is a first time I’ve changed the sheet instead of
just adding one.



*From:* wing-it [mailto:notifications@github.com]
*Sent:* Monday, January 22, 2018 19:43
*To:* Roll20/roll20-character-sheets <
roll20-character-sheets@noreply.github.com>
*Cc:* rdefendi <robert@robertjdefendi.com>; Author <
author@noreply.github.com>
*Subject:* Re: [Roll20/roll20-character-sheets] L5r ffg sheet (#3379)



GitHub is showing quite a few conflicts with this branch, these will need
to be resolved before I can merge the request. Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Roll20/roll20-character-sheets/pull/3379#issuecomment-359655472>,
or mute the thread

**Comment by wing-it** [comment]
I think the problem lies in the fact that I made some slight corrections to the sheet to make everything work properly (filenames had to be changed a bit, for example), yet the branch this pull request was made from did not have my changes, which resulted in these conflicts. GitHub displays the conflict error right here, directly below the comment section.

Basically, to avoid conflicts, you need to make sure you have the most up-to-date version of the code before making further changes. There are several ways to do this, but I think in this case the easiest thing to do would be close this pull request, delete your current branch (save a copy of the changes you were making somewhere), and basically restart  from the beginning by pulling in a new branch. This will ensure that you have the latest version of the code. Then you can re-apply your changes to the new branch and make a new pull request, which shouldn't have any conflicts.

Also, you don't need to add the other translation files (unless they have actual translations for that language). Those will be automatically generated as long as you have the translation.json done correctly.

Don't be too down on yourself, git/GitHub are pretty complicated and somewhat arcane, and can be frustrating/confusing even for people who work with it every day (like me!)

**Comment by rdefendi** [comment]
Oh, cool, so I just update translation.json and the others are done. So if
someone translates the French or German, then I add five lines to the end
of translation.json, does it just add those five lines to the end of the
French and German files at that point, or at that point do I need to do
them manually?



*From:* wing-it [mailto:notifications@github.com]
*Sent:* Tuesday, January 23, 2018 5:56
*To:* Roll20/roll20-character-sheets <
roll20-character-sheets@noreply.github.com>
*Cc:* rdefendi <robert@robertjdefendi.com>; Author <
author@noreply.github.com>
*Subject:* Re: [Roll20/roll20-character-sheets] L5r ffg sheet (#3379)



I think the problem lies in the fact that I made some slight corrections to
the sheet to make everything work properly (filenames had to be changed a
bit, for example), yet the branch this pull request was made from did not
have my changes, which resulted in these conflicts. GitHub displays the
conflict error right here, directly below the comment section.

Basically, to avoid conflicts, you need to make sure you have the most
up-to-date version of the code before making further changes. There are
several ways to do this, but I think in this case the easiest thing to do
would be close this pull request, delete your current branch (save a copy
of the changes you were making somewhere), and basically restart from the
beginning by pulling in a new branch. This will ensure that you have the
latest version of the code. Then you can re-apply your changes to the new
branch and make a new pull request, which shouldn't have any conflicts.

Also, you don't need to add the other translation files (unless they have
actual translations for that language). Those will be automatically
generated as long as you have the translation.json done correctly.

Don't be too down on yourself, git/GitHub are pretty complicated and
somewhat arcane, and can be frustrating/confusing even for people who work
with it every day (like me!)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Roll20/roll20-character-sheets/pull/3379#issuecomment-359781970>,
or mute the thread

**Comment by wing-it** [comment]
You shouldn't ever need to update the translation files themselves unless you're actually translating something. The translations are compared to the translation.json file and it handles new or changed keys automatically without overwriting existing translations.

**Pull request closed without merging**
