### PR TITLE
harnmaster

### PR DESCRIPTION
**Pull request by suntzu777**
updates

### CODE REVIEW

**Comment by pjbehr87** [comment]
Looks good!

**Comment by suntzu777** [comment]
Hi phil , i take it from that message that all my updates worked ?

Rob

**Comment by pjbehr87** [comment]
Yup! Everything worked perfectly, congrats. The new sheet will show up on the site probably later today. If you have more questions about how to make changes to your new sheet let me know.

**Comment by suntzu777** [comment]
ok thanks for all your help

Rob

**Pull request merged**
