### PR TITLE
Character sheet - Kuro (FR)

### PR DESCRIPTION
**Pull request by dilhansarica**
## Changes / Comments

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
**Yes**

- [x] Is this a bug fix?
**No**

- [x] Does this add functional enhancements (new features or extending existing features) ?
**No**

- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
**No**

- [x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
**No**

- [x] If this is a new sheet, did you follow [Building Character Sheets standards]
**Yes**

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
Hey there @dilhansarica , there is a already a sheet for Kuro, so why not translate that instead of creating a new sheet? I am asking because while there have been duplicate public sheets allowed in the past, going forward Roll20 wants to limit this practice. Thanks for all the work you do!

**Comment by dilhansarica** [comment]
Hi mperes, we try to use this sheet at the beginning, but there is a lot of incomplete features or bugs (as the author mentionned it in the readme) and so the sheet don't suit to play the game. I will gladly add a french translation, but this sheet doesn't work very well... For example, you can't add a second line in skills area, the calculation of a skill check is not correct...

So our proposal is a clean sheet without bugs that represents all the aspects of the game. We added initiative, differenciation between skills, specialities, special capacities, good calculations for the dice checks. We expect very much to play with this sheet with our players.

**Comment by mperes** [comment]
Hello @dilhansarica, could you contact the original author and check if he is ok with a complete rewrite of this work?

**Comment by dilhansarica** [comment]
Hello @mperes, I found its github & twitter profile, but there is no way to contact him unfortunately. I try to find other profiles in google, but nothing. Finally, I made a fake pull request to try to get an answer on this subject, but he has not a very active profile, I am not sure he will see it.

**Pull request closed without merging**
