### PR TITLE
Demon gate scripted

### PR DESCRIPTION
**Pull request by Deltayn**
## Changes / Comments
Added "Display Info" buttons to various spells and skills

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by oliviakristiansen** [comment]
Greetings,

We no longer accept characters sheets with layouts built in <table>, https://roll20.zendesk.com/hc/en-us/articles/360037773453

These elements will need to be replaced to meet the require programming standards.

Thank you,
Olivia

**Comment by Deltayn** [comment]
Can you explain what you mean by merge conflict please? I am the only person to have written anything for this

**Comment by Reonin** [comment]
Hey @Deltayn the "Demon Gate Scripted/Demon_Gate_Scripted.html" has a change in it that is preventing us from merging it in. I would recommend to pull down any changes on the branch before pushing up new changes to catch any conflicts earlier. It doesn't seem like you removed anything just added more but I would look closely to see what in that html file is causing this conflict.

**Comment by clevett** [comment]
Greetings @Deltayn,

As this pull request is over 20 days old and still has merge conflicts, I'm going to close it. Feel free to open a new one when the conflicts are resolved.

You may want to consider backing up these changes on a branch and updating your fork, https://github.com/Roll20/roll20-character-sheets/wiki . There is a Pull app in the wiki which makes it a lot easier to manage updates.

Thank you,
Cassie

**Pull request closed without merging**
