### PR TITLE
[Eoiles] new character sheet

### PR DESCRIPTION
**Pull request by eblaise**
## Changes / Comments

A new character Shet for Etoiles, a french indie roleplaying game inspired by Stargate SG1 adventures

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by oliviakristiansen** [comment]
Hi there! Could you provide a link to the RPG info? I'm not finding an RPG named "Etoiles" - I found a couple with "Etoiles" in the name, but I'm unsure if they are the correct one. I just need to be sure I'm inputting the correct information into our approved character sheets file. If you could link to a page with a description of this RPG, that would be greatly helpful. Thanks!

Olivia

**Comment by eblaise** [comment]
> Hi there! Could you provide a link to the RPG info? I'm not finding an RPG named "Etoiles" - I found a couple with "Etoiles" in the name, but I'm unsure if they are the correct one. I just need to be sure I'm inputting the correct information into our approved character sheets file. If you could link to a page with a description of this RPG, that would be greatly helpful. Thanks!
> 
> Olivia

Hi. First of all, thanks for your fast answer
The rpg is available on itch.io, link just above

https://erwik-jdr.itch.io/etoiles

**Comment by oliviakristiansen** [comment]
Awesome thank you!

**Comment by eblaise** [comment]
> Awesome thank you!

I don't understand. Etoiles is in the dropdown selection but the character sheet doesn't work. Nothing is displayed
I don't know why, code html and css work in local
Maybe can you help me?

**Comment by oliviakristiansen** [comment]
@eblaise I apologize! I made a small typo in our approved.yaml which is why its not showing up. We are hotfixing it and will be fixed momentarily. 

Olivia

**Pull request merged**
