### PR TITLE
Stars Without Number Improvements

### PR DESCRIPTION
**Pull request by jfredett**
@kevinsearle Hi! I believe you're the author of the SWN sheet. I don't know if you have the commit bit or not, but I figured I'd ping you regardless.

I've gone and added a bunch of things that are useful to me for macro-ing / ease of play in SWN. In particular, this PR adds:

* Roll buttons for all the listed skills
* Roll buttons for all saves
* Auto-sets the Max Strain to Unaltered CON
* Boxes to store each Attribute's bonus value[1]
* A Box to store your current AC (to allow target-macros + for easy reference)
* A button for rolling initiative. If you have your token selected, it will automatically add it to the turn tracker. 
* A section just below the Core Stats sheet for the above initiative macro/roll button (and any future buttons that might be useful)
* Buttons for rolling attacks based on weapons in the weapon section, as well as a generic attack roll button.

This PR *does not* contain:

* CSS Changes -- EDIT: It now contains one change to make the weapon fieldset accept the two extra columns
* Changelog changes (I figured I'd ask if you want me to do it or not)
* Automatic calculation of stat bonuses[3]

I don't know if any of these changes are wanted, but I find them pretty useful (and I'm kind of tired of turning it to custom-sheet on my campaigns).

Let me know if you need me to make any more changes. I've got a vague plan of how to move some of the parameterized skills into a repeating fieldset, but I don't know if I'm going to bother (I'ven't had a game where I needed more than what is in the sheet; it just bothers me on principle).

----- footnotes -----

[1] This gives you `@{intBonus}` and so on -- whenever dropdown's come, it should be possible to do something like:

    @{?{Attribute Bonus|STR,strBonus|DEX,dexBonus|CON,conBonus|INT,intBonus|WIS,wisBONUS|CHA,chaBonus|None,0}}

[2] I like to have every player have a token, even though I don't use maps, target macros + player and mook tokens make combat go pretty quick.

[3] I figured out a 10th order equation which, combined with `floor`, managed to make it work, but it is not a pretty thing.

### CODE REVIEW

**Comment by jfredett** [comment]
I managed to find a less awful equation for calculating bonuses on the fly, I'll include that bit in the morning.

**Comment by jfredett** [comment]
So -- the equation I found is: `floor(STAT/18)+floor(STAT/14)-floor((18-STAT)/15)-floor((18-STAT)/11)`. However, it appears that auto-calculated values don't generate attributes on the charsheet, so I think it's probably better to leave them manually entered, since the attributes are pretty handy to have around.

**Comment by jfredett** [comment]
I added a couple more buttons, and edited the main summary to include that information

**Comment by Rhallinan** [comment]
The changes look good to me. I'm going to merge them in and test them out.

**Comment by jfredett** [comment]
Awesome! Assuming that everything checks out -- what's the turnaround time on them going live? I'm starting my next Stars campaign in a couple of weeks, curious if I'm going to be able to use these for the start of it. Gonna be like -- 6 or 7 players; so char sheet macros would be *very* handy.

**Comment by kevinsearle** [comment]
@jfredett Awesome that you've done this. I haven't had time to give the sheet the love and attention it's needed.

**Comment by kevinsearle** [comment]
Make sure you update version number on the sheet HTML itself, if you haven't already. Also, add your name and Roll20 account to the sheet.json! It can handle multiple authors in that field.

**Comment by jfredett** [comment]
Willdo, @kevinsearle; though it'll probably come w/ the next round of improvements. I'm thinking of digging into the ship charsheet or some nice roll-templates next (embedding the `/me` feels hacky).

**Comment by kevinsearle** [comment]
Just got some feedback from someone on Roll20:

"you embedded roll buttons for attacking do not work. The rolls turn out to have waaay to many addition signs, just straight up breaking the roll."

**Comment by kevinsearle** [comment]
https://github.com/Roll20/roll20-character-sheets/issues/957

**Comment by jfredett** [comment]
Hmm. I'll take a look. I tested them w/ the custom sheet thing, was working fine. I wonder if the @{target|0} bit is broken.

**Comment by kevinsearle** [comment]
@jfredett I've added you to the credits and updated the changelog to reflect your changes.

**Comment by jfredett** [comment]
@kevinsearle Oh -- I did that too, in the ship-sheet PR, easy enough to pull out. There is also a PR which 'fixes' the attack roll issue (it was an issue of bad defaulting, not an actual bug).

**Pull request merged**
