### PR TITLE
New sheet for a homebrew [Gotham90]

### PR DESCRIPTION
**Pull request by StoneM0nkey**
New character sheet for Gotham90 - a homebrew rpg system

# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <Gotham90>  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <no publisher, homebrew system> _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <Gotham90> _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <https://docs.google.com/spreadsheets/d/1EB7hfgOxQBkW31RUjg66hPvgc_rV7Ok73s5smh6fwws/>
- [x] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by BronsonHall** [comment]
Hey @StoneM0nkey!

A few questions/notes before we could approve this:

- Is there a way to access this system's rules online?  We need sheets to have easily-discoverable rules to play, for free or for purchase, typically on places like DriveThruRPG, Reddit, a personal website, or something similar.  If the rules are already publicly available somewhere, that's cool, just add a link to them in the body of this PR in that second-to-last checkbox.  
- There are some copyright concerns with the background image of the sheet, as it's the cover art to an official DC comic volume.  You'll need to find an alternative background for the sheet that's legally ok to use.  
-  Your sheet.json has a small typo - the preview file you've included is "Preview.jpg", capitalized, but your sheet.json is looking for "preview.jpg", lowercase.  The code to parse sheet.json is case sensitive, so you'll need these file names to match exactly, or the preview won't be displayed when a user goes to create a game for your system.  

Let us know if you have any questions addressing the above issues!

**Comment by StoneM0nkey** [comment]
Okay, link to to rules added. I changed preview image and in the process fixed that typo in sheet.json. Background image was changed. Hopefully it's okay now. If it isn't, is there a way to tell if an image is legal to use? Pinterest doesn't really help in that regard.  Thanks!

**Comment by mperes** [comment]
Hey there @StoneM0nkey, there is an error within you PR that needs to be fixed before we merge it. your sheet.json files points the preview image to "preview.jpg", however the image bundled in the sheet is named "Preview.jpg" with an uppercase "P". Our system is case-sensitive, so you must either rename the file or update the json file.

Thanks for all the work you do!

**Comment by NorWhal** [comment]
Hey @StoneM0nkey, are you planning to distribute this game with that google docs link? If you are only planning to run this sheet as homebrew for your own games or if the game is currently in development, I'd encourage you to use the "custom" sheet template in your game settings. We cannot add this game without a link to drivethru, itch.io, or some other marketplace.

**Comment by BronsonHall** [comment]
Hey @StoneM0nkey 

You will be able to use a custom sheet even if your Pro membership runs out - you just won't be able to make new tables with that sheet or edit the code.  Any existing tables using the custom sheet will still function for you and your friends.

You'll likely have similar issues if you get it onto this repo, as you won't be able to test new code to make future changes without a membership.  

The purpose of this repo is to host sheets created by the community for public use.  That's why we need the rules to be publicly available (for free or purchase) and easily discoverable, so anyone can pick up and start playing the game when they see it in the sheet dropdown.  This unfortunately isn't really the place for custom sheets that aren't designed for widely accessible play.  

That in mind though, I think this sheet will be just fine for your purposes being left as a custom sheet - just make sure you've created and set up all your tables using the system before your pro runs out.  You can always restart your membership to make changes to the sheet in the future or make new tables using it.   

If you decide to instead take the route of putting this game out there publicly, either now or in the future, all you'd need to do is upload the rules on a dedicated website, or list them on a marketplace.  That may raise its own issues of adjusting the system to not infringe upon the DC IP, of course.  

I'm closing this PR for now, but don't hesitate to reach out with further questions.

**Comment by StoneM0nkey** [comment]
Understood. Thank you all for your patience.

**Pull request closed without merging**
