### PR TITLE
[Pendragon] Battle size modifier fix

### PR DESCRIPTION
**Pull request by RhOmicron**
Battle size modifier change to the correct ones.

### CODE REVIEW

**Comment by Solarswordsman** [comment]
You're reducing the number of options for this attribute as well as changing their value.  Existing games with the previous values are going to default to 1.  Is it worth the change for this sheet to lose that value?

**Comment by RhOmicron** [comment]
This change is in accordance with book of battles 2nd ed, page 81. Where only 1x, 2x and 3x modifier exist. I assume you have recorded the battles glory in the glory tab as well?

**Comment by Solarswordsman** [comment]
Sorry, I'm not familiar with the system.  I just want to make sure people with the old version of the sheet aren't losing functionality (e.g. might they be using the old modifiers, and still want to?) and that this attribute change won't be a destructive change to existing sheets.

**Comment by RhOmicron** [comment]
It shouldn't change much unless they get uncertain how much they earned last battle and didn't record it in the appropriate tab. 

It would be easy enough for them to know which modifier they are supposed to have looking at how big army they were against.

**Comment by Solarswordsman** [comment]
Ok, thanks for clarifying.  Looks good.

**Pull request merged**
