### PR TITLE
The Witcher (Sheet Completely Remade)

### PR DESCRIPTION
**Pull request by Leothedino**
Completely redesigned The Witcher sheet to have an abundance of functionality that it lacked previously. None of this was built upon the former sheet by Austin Mitchell or in collaboration with that author. This sheet is freshly written from scratch, hence the amended json file.

## Changes

witchersheet.html - NEW
witchersheet.html - NEW
witcherpreview.png - NEW
witchersheet.json - NEW
images folder - NEW

## Additional comments

Due to the nature of not being able to upload multiple sheets of the same game type to Roll20, and baring in mind this new sheet does far more than the last, I thought this was the appropriate course of action in making it available to people.

### CODE REVIEW

**Comment by Leothedino** [comment]
Additional comment. I have actually reached out to the author of the current Witcher sheet, just to include and inform them of this request and to invite them to [take a look at a test version of the sheet](https://app.roll20.net/join/3878876/cDEZow).

**Comment by Leothedino** [comment]
Anything I should know?

**Comment by Leothedino** [comment]
> Removing merge as it overwrites the old sheet.

That was explained, in the Pull Request comment. Not sure I understand. Why was it approved then?

**Comment by Leothedino** [comment]
@clevett

**Comment by clevett** [comment]
Greetings @Leothedino 

My apologies on this one. You did explain in the Pull Request and I even reviewed your changes. It some how slipped pass my front thinking brain. That was certainly a mistake on my part.

When a new sheet is made to replace an old one we deprecate the previous sheet. This will hide it from being selected by new games but it will still be used by games that already had the sheet selected. With this process we do not disrupt games already in progress.

I renamed your folder to "TheWitcher" without a space and changed all your image links in the css & html to reflect this. The previous sheet has been deprecated and your sheet now appears in the drop down for The Witcher so it is live now on the site. You'll want to make sure you update your local files to reflect these changes.

Sorry for the confusion. 

Thanks,
Cassie

**Comment by Leothedino** [comment]
@clevett thank you ever so much, and for making this image link changes. I appreciate your care, attention and time.

**Comment by clevett** [comment]
@Leothedino You are most welcome. I am happy to help.

**Pull request merged**
