### PR TITLE
Fading Suns 2nd Edition Revised - sheet release 1.2.0

### PR DESCRIPTION
**Pull request by admiralnlson**
### 1.2.0
- Renamed sheet to `Fading Suns 2nd Edition Revised` from `Fading Suns v2.75`
- Added ability to select the characteristic for the roll of a skill on the fly (as opposed to having to select a characteristic beforehand)
- Fixed error on Critical Success rerolls or Critical Failure confirms of custom Lore and Creative skills (bug introduced in 1.1.0)
- Fixed typo in Initiative stance roll query. Aggressive stances give -2 Defense, not +2  (bug introduced in 1.1.0)
- Cosmetic fixes

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by admiralnlson** [comment]
Hello @oliviakristiansen 

I realize now that the name `Fading Suns v2.75` is not ideal for this sheet. `Fading Suns 2nd Edition Revised` would probably be much better and aligned with the naming pattern used in other Roll20 sheets.

Are you able to change the sheet name visible to Roll20 users to `Fading Suns 2nd Edition Revised` thanks to `approved.yaml`?
And if yes, should I move the folder itself to match this new name?

Also: is this a transparent change for existing users of the sheet, or will this break their games and require they update their game settings to select the new name?

Thanks,

Best Regards
admiralnlson

**Comment by oliviakristiansen** [comment]
Yes! If you submit a PR with the updated folder name, I will be sure to change the name in the `approved.yaml` file. And it should not break user's games. If you submit the PR by Monday morning with the needed changes, it will be pushed on Tuesday. Thanks!

**Comment by oliviakristiansen** [comment]
You could probably just update this open PR

**Comment by admiralnlson** [comment]
Thank you for your response. 
I did just that and updated the PR.

**Comment by Reonin** [comment]
Hello @admiralnlson it seems like with the name change some folders were missed in the process (looking at the translations as an example). It also seems like you have committed some VSCode file snippet with the branch (might not want that in the branch). Please update and we can merge this in next week.

**Comment by admiralnlson** [comment]
hello @Reonin 

The vscode snippets file is meant to be part of the pull request. It is a enabler for whoever might end up maintaining the sheet, should I somehow go missing. Including such source files is a best practice agreed among us sheet authors.

Regarding missed translation files, I'm not sure what you mean. The guideline is not to touch such files as I did not generate them initially.
I can only provide translations for "en" and "fr". Others were auto-generated, and nobody from the CrowdIn service have contributed translations for those so far. So I would assume they will be re-generated from the `translations.json` again on your end.

Pretty sure everything is in order here, really. It would be a shame to have this PR pushed by one week.

BR
admiralnlson

**Comment by admiralnlson** [comment]
Hello @Reonin ,

I removed the controversial vscode snippets code file as per your request.

Also, despite some fellow sheet authors advising me not to, I affected other (auto-generated) `translations/xx.json` files as per you request also.
The only one I am definitely unable to change is the `zu` one which is extremely cryptic.

BR
Yohan

**Comment by Reonin** [comment]
Thanks for the quick turnaround @admiralnlson. I should have your changes in for next week's push.

**Comment by admiralnlson** [comment]
Great! Thanks @Reonin

**Pull request merged**
