### PR TITLE
Initial Commit of Trone de Fer

### PR DESCRIPTION
**Pull request by noritaka97**
A Song of Ice and Fire Character Sheet.
Adding Army Sheet

## Changes / Comments
Sheet name for the french version of RPG Song of Ice and Fire.
Adding new features : Army sheet for Armies battle in a new layout.
Adding multiple new attributs for Armies Unit.
New Character sheet based on the the existing character sheet "A Song of Ice and Fire"

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by noritaka97** [comment]
it's possible tu push fix and update of this character sheet before the merge of this monday ?

**Comment by Anduh** [comment]
> it's possible tu push fix and update of this character sheet before the merge of this monday ?

Basically zero chance. Roll20 almost never does mid-week sheet changes even for their own, official sheets. It's a considerable process to restart the servers/whatnot when these weekly updates are made. And you're not submitting a fix, you have a new character sheet.

And even though Roll20 often merge the PRs on Mondays, they push the actual sheet updates to Roll20 on Tuesday evening or Wednesday morning.

Any particular reason you want it out quickly?

**Comment by noritaka97** [comment]
Hi Andush,
Sorry for my poor English...
it's not for a quick push of the new sheet, but i make cosmetic change in the code i push for the initial sheet.
Can i push this change before to the fork to have a fixed version of the sheet instead au the initial version ?
thank you for your answer.

**Comment by Anduh** [comment]
If you're asking if you can push changes to the sheet code between now and Monday, yes you can. You removing the License file was an example of this.

**Comment by noritaka97** [comment]
Thank you for your answer Andush.

**Comment by Reonin** [comment]
Hello @noritaka97 there are already 2 'A Song of Fire and Ice' sheets based on the Chronicle System. Could your changes be a [translation](https://wiki.roll20.net/Building_Character_Sheets#Translating_Character_Sheets) using Crowdin. If there are not significant rules changes between this and the others I will probably not be able to merge this :(

**Comment by Reonin** [comment]
Also check out this for more info https://roll20.zendesk.com/hc/en-us/articles/360037773493-Character-Sheet-Translation

**Comment by noritaka97** [comment]
Hello @Reonin,
this sheet was quickly develop to answer my table needs by adding Army layer for our next game next week-end for a big army battle in the SOIAF. My next update is a full french version of the sheet and translation intégration in this sheet for the community.
Add a complet part of the army battle rules are not significant change ?

**Pull request closed without merging**
