### PR TITLE
fix layout for Horror Movie World character sheet and add placeholders to See You In Hell character sheet

### PR DESCRIPTION
**Pull request by loversandcode**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
Note that roll20 will reject PRs that edit more than one sheet at a time. (one of the failed checks)

**Comment by loversandcode** [comment]
> Note that roll20 will reject PRs that edit more than one sheet at a time. (one of the failed checks)

can i somehow revert one of past commits or its better to make new PR instead?

**Comment by Anduh** [comment]
reverting commits is possible at least with git, but probably easier to just make two separate branches/PRs for this if  you dont know how to revert commits

**Comment by loversandcode** [comment]
> reverting commits is possible at least with git, but probably easier to just make two separate branches/PRs for this if you dont know how to revert commits

ok, ty, ill close this one

**Pull request closed without merging**
