### PR TITLE
Quest

### PR DESCRIPTION
**Pull request by MichaelCalleia**
## Changes / Comments

Initial upload for character sheets for board game Quest designed by William Hoyt. Quest is a board game based on MAR Barker's Empire of the Petal Throne. Bill was one of MAR Barker's original players in 1974 and helped get Empire of the Petal Throne published by TSR. Bill is planning to run Quest at Gary Con this year and this is part of the preparation for running the game virtually. It is a very basic sheet, I'm hoping to do some CSS clean up this week, but we wanted to get this up on Roll20 to play test the basics.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [X ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ X] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
Hey there @MichaelCalleia, could you remove the DS_Store file from the root folder and update your pull request? Thanks!

**Review by MichaelCalleia — COMMENTED** [review]
Removed DS-STORE

**Comment by MichaelCalleia** [comment]
Doh! I believe this is resolved.


Warm regards,
Michael Calleia

917-753-7259
michael@calleia.com <mailto:michael@calleia.com>

calleia.com

**Comment by MichaelCalleia** [comment]
Going to use custom instead for this.

**Comment by MichaelCalleia** [comment]
This was corrected a while back, any chance the pull request will be merged the week?

Warm regards,
Michael Calleia

917-753-7259
michael@calleia.com <mailto:michael@calleia.com>

calleia.com

**Pull request closed without merging**
