### PR TITLE
[Magic_World] Cosmetic

### PR DESCRIPTION
**Pull request by imaginosmusic**
Corrected a spelling error and made some cosmetic changes to provide a more consistent look throught the whole of the character sheet.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Lockbox313** [comment]
You are probably going to need the following files  sheet.json, a  preview image of the character sheet and  a readme.md to get this released.  If you look in any of the sheet folders you will see examples.  In  you pull request you could asked for it to be listed under Basic Roleplaying.

**Comment by imaginosmusic** [comment]
Thanks! I thought I had all the files. Looks like I missed the readme.md. Basic Roleplaying would be the most appropriate place for the sheet. I will get the missing readme.md file submitted.

**Comment by Lockbox313** [comment]
You are missing 3 files

**Comment by imaginosmusic** [comment]
I'm confused. When I look in the Magic_World folder in the master repository, I see, sheet.json and magicworld.png. Both of these files were merged on the original pull request. Do I need to update or upload them again?

**Comment by Lockbox313** [comment]
You are correct I am obviously losing it.

**Comment by imaginosmusic** [comment]
You are perfectly sane. I needed you to point out my oversight!

**Pull request merged**
