### PR TITLE
[Project Moon TRPG] Re-release v0.7 

### PR DESCRIPTION
**Pull request by BeautiDemise**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <https://drive.google.com/drive/folders/15nMYLz0sB5xWUiSOG4oN6IsteRJjpdZk>
- [x] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description
Release v0.7 of this sheet was initially released three weeks ago ([Pull request 1](https://github.com/Roll20/roll20-character-sheets/pull/13297)), before being reverted after multiple bugs were discovered ([Pull request 2](https://github.com/Roll20/roll20-character-sheets/pull/13313))
With all new features now being fully tested and all known bugs having been resolved the update is ready for re-release
The re-release also includes four new features:
- Any property of the sheet that can be Imported/Exported can now be set through Default Sheet Settings. This notably includes settings in the top-right cogwheel menu
- The Auto Update setting now displays an indicator inside the Update button showing if the functionality is active (green), searching for the initiative item (yellow) or failed to find the item and is in standby mode (red)
- The token instance display is now resizable
-  Damage Resistance and Protection now apply to after resistance damage

A full illustrated changelog for the release can be found here: [Roll20 - v0.7 Changelog](https://docs.google.com/document/d/1ZNR8x0R-Nkn0bDn361mFUzzYxlQRnK5XCuAF16SFAsk/edit?usp=sharing)

## Important Info!
I've tested merging this update into the master branch locally and found that the merge does not function properly unless the [[Project Moon RPG] Revert from v0.7 back to v0.6.3](https://github.com/Roll20/roll20-character-sheets/pull/13313) merge is ***first*** reverted
- I've added a second pull request [Revert "[Project Moon RPG] Revert from v0.7 back to v0.6.3"](https://github.com/Roll20/roll20-character-sheets/pull/13369) which does this
- All the merge conflicts on this request should resolve after the other pull request is merged
- I'll be available tomorrow for the review period in case any issues or questions arise over this. Apologies for the mess!

### CODE REVIEW

**Comment by NorWhal** [comment]
@BeautiDemise looks like there are a few more merge conflicts to sort through

**Comment by BeautiDemise** [comment]
Understood! Give me a few minutes to give them a look over

**Comment by BeautiDemise** [comment]
@NorWhal The changes from Release v0.7 are correct for both of the conflicts

**Comment by NorWhal** [comment]
@BeautiDemise please verify this is the correct code - just being extra cautious.

**Comment by BeautiDemise** [comment]
Believe I figured it out. Getting a couple of differences at there two locations (the leftmost code is correct)
image
image

**Comment by BeautiDemise** [comment]
@NorWhal Learning a lot on the go here! Added a commit that corrects the last few conflicts. It should be all good to go!

**Pull request merged**
