### PR TITLE
HeXXen1733 Advanced - Version 1.2.2

### PR DESCRIPTION
**Pull request by Gorthian**
Unterstützung der erweiterten Regeln aus Hexenjagd und Hexenzorn.
Volle Unterstützung für Rage, Ambitionen und Segnungen

## Changes / Comments
I knew there is already a character sheet available for HeXXen1733. 
I tried to commit my own version some weeks ago wich was rejected then. 
I did have a look at the existing sheet, but I'm missing some features:

- The current sheet only supports the core rules. Some advanced rules from newer rulebooks are missing.
- I'm missing the possibility to run dice rolls directly from the existing sheet.
 
So i decided to risk a second request of my own sheet, which includes all currently available rules plus dice rolls.
Perhaps you could list it as advanced version.

Currently I'm using a rollable table to implement the special dices of HeXXen1733.
An instruction how to setup this tables is found on my wiki (https://github.com/Gorthian/HeXXen1733_Custom_Character_Sheet/wiki/W%C3%BCrfeltabellen-erstellen).

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [Yes ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ No] Is this a bug fix?
- [ Yes] Does this add functional enhancements (new features or extending existing features) ?
- [ Yes] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ None / First Version] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ Hope so] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
Hello @Gorthian , why not just make you improvements on top of the existing sheet. I bet other player using the existing sheet would love some advanced functionalities ;)

**Comment by Gorthian** [comment]
> Hello @Gorthian , why not just make you improvements on top of the existing sheet. I bet other player using the existing sheet would love some advanced functionalities ;)

Hi.

I thought about this, too.
But the author of current sheet isn't using pure HTML and CSS files for development. He is using pugjs for his sheet (https://github.com/m-gora/Roll20-Charactersheet-HeXXen1733) which i'm not firm with.
So, if if I would start to add changes to the existing sheet it would somehow block the original author to merge my changes back to his development branch, wouldn't it? 

I treid to contact him some days ago, to ask him about his further plans for the sheet, but didn't get any answer so far.

**Comment by mperes** [comment]
Hey @Gorthian, please keep trying to get in touch with the original author. Another thing you can try is using an online HTML to PUG converter. How big are you changes compared to the original sheet? If not too much, I may be able to help you on my spare time.

**Comment by Gorthian** [comment]
Thx for your reply.

I developed my sheet from scratch. So there will be a lot of changes in comparison to the original sheet.
I used a different layout, new attributes and added some "intelligence".

But I can understand your decission not to add a second sheet to an existing system.
So, I will try to send my main features as issues to the original sheet's author.

**Comment by mperes** [comment]
Thanks for the comprehension, @Gorthian!

**Pull request closed without merging**
