### PR TITLE
created CyberpunkRED_raycw

### PR DESCRIPTION
**Pull request by ray-cw**
## Changes / Comments

This is a new sheet submission for Cyberpunk RED. I did my best to adhere to the character sheets standards, if you find they aren't sufficient please let me know so I can fix my mistakes and improve. 

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name. (Done.)
- [x] Is this a bug fix? (No)
- [x] Does this add functional enhancements (new features or extending existing features) ? (Yes)
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? (Yes)
- [x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ? (N/A)
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ? (Yes)

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
Nice, I see this sheet follows the sheet design of the full game release, while the older sheets available on Roll20 are just for the Cyberpunk Red Jumpstart Kit from last year. 

Roll20 ought to rename the old ones to avoid confusion.

**Comment by Anduh** [comment]
There is another Cyberpunk Red sheet submitted this week: #7810

**Comment by ray-cw** [comment]
@Anduh So I've been working a LOT on this character sheet in a [separate repository](https://github.com/ray-cw/roll20-CPR-charactersheet), should I commit my changes here? Or wait until this pull request gets merged/closed then update afterwards, or just submit a new pull request?

**Comment by oliviakristiansen** [comment]
I am merging this and will update the current "Cyberpunk Red" to be "Cyberpunk Red Jumpstart Kit" to avoid confusion. Thanks to you both!

**Pull request merged**
