### PR TITLE
added ultimaBomba sheet only ita

### PR DESCRIPTION
**Pull request by FrancescoCalise**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by FrancescoCalise** [comment]
added ultimaBombaSheet

**Comment by Reonin** [comment]
Hello @FrancescoCalise same game correct? https://www.serpentarium.net/l-ultima-bomba

**Comment by FrancescoCalise** [comment]
> Hello @FrancescoCalise same game correct? https://www.serpentarium.net/l-ultima-bomba

yes, I asked the author before publishing it

**Comment by FrancescoCalise** [comment]
hi @Reonin, how can add this game in list of the game?

**Comment by Reonin** [comment]
No worries I already added it but in the future write it somewhere in the title of the pull request

**Pull request merged**
