### PR TITLE
SWN Revised v2.5.1 HOTFIX

### PR DESCRIPTION
**Pull request by Karlinator**
## Changes / Comments

Simple hotfix, some checkboxes had default values they shouldn't. This was causing all new sheets to initialise as AI and Transhuman (which among other things hides some fields).

@clevett could we get this out before next batch? It is possible to work around (by toggling and untoggling the options for AI and Transhuman), but without that knowledge it kind of breaks all new sheets (though without data loss).

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Karlinator** [comment]
This is also affecting a good number of returning sheets, not just brand new ones.

Extra ping for @oliviakristiansen, so at least one of you maybe sees this.

**Comment by Karlinator** [comment]
Correction: this affects all existing sheets.

**Comment by Karlinator** [comment]
Since this never got addressed in the previous week, I've accumulated a few other minor fixes and improvements.

As a side note: this bug has affected quite a few people. Is there a reliable way to alert you all at Roll20 about a hotfix like this? Clearly neither pinging here nor emailing like the repo says has any real effect. Twitter, maybe? Messages in bottles?

It's frustrating to have the fix for a bug like this ready to be deployed, but be unable to get in contact to deploy it. Yes, I introduced this bug in the first place, but once it was discovered I had a fix submitted here within 2 hours. I feel like I did my part here, the week-long wait and several bug reports after that is not on me.

**Comment by oliviakristiansen** [comment]
Hello,

I apologize for the delayed response. Unfortunately, we do not do hotfixes for character sheets because it relies on a restart of our entire app, which is why we only merge once a week. This will be merged on Monday and out on Tuesday. I can certainly understand your frustration for not having a hotfix go out for a bug that potentially affects a number of people, but this is not the first time a bug was introduced and a week passed before the fix was out. I just want to reinforce that this is definitely not on you. I hope this alleviates any frustration you may be feeling. We certainly appreciate all of your hard work! Have a great weekend!

Olivia

**Comment by Karlinator** [comment]
Well, you should probably remove the sentence about critical hotfixes in the repo description then. Kind of gives the impression that it is possible to reach out.

I understand the policy, though. A full app restart is not something I'd want to be doing at random times. I'll keep it in mind for the future.

**Pull request merged**
