### PR TITLE
[GURPS 1.7.0]

### PR DESCRIPTION
**Pull request by MadCoder253**
## Merge Issues

When attempting to merge using **git merge upstream/master** is giving the following error.

```
fatal: cannot create directory at 'Fallout: Vaults & Deathclaws PNP': Invalid argument
````

Windows does not support **:** in a folder or file name.

There might be some conflicts with merging these files, all of them will be **Use Incoming Changes**. I would really like this to get deployed on Tuesday. Please advise.

## Changes

**Files Updated**
gurps.html
gurps.css
sheet.json

Repeating skills/spells. Removed checkbox to show success/fail notes. Converted text boxes to multi-line text boxes.
Repeating melee/ranged attacks. Ability to link weapon to skill or spell. The weapon will show the skill or spell level and should update when the skill or spell level is updated.
Reformat minimum damage notes and include page reference.
Repeating Spells. Moved checkboxes for ON and MT to avoid collision with delete button. Resized some text 
boxes to allow more space for delete button. Change Maintained Penalty titles to Concentration Penalty. Thanks to Valter.

### CODE REVIEW

**Comment by Anduh** [comment]
You have conflicts in this submission.
And the Fallout thing is known and was reported almost a week ago #5672, will be fixed with this week's updates.

**Comment by MadCoder253** [comment]
Hi @Anduh, 

Here's my problem. I can't resolve the merge conflicts because I get massive conflicts and errors when attempting to merge upstream/master to my codebase. Is there a way to resolve conflicts directly in this pull request or will I have to wait until next week? Also, will there be pulls happening next week or delayed because it's a holiday week?

Thank you, 
Ken

**Comment by MadCoder253** [comment]
Hi @clevett, 

Would you be able to answer my questions on my pull request?

Thank you,
Ken

> Hi @Anduh,
> Here's my problem. I can't resolve the merge conflicts because I get massive conflicts and errors when attempting to merge upstream/master to my codebase. Is there a way to resolve conflicts directly in this pull request or will I have to wait until next week? Also, will there be pulls happening next week or delayed because it's a holiday week?
> Thank you,
> Ken

**Comment by KlingonMike** [comment]
Hi @Anduh, Hi @clevett,. Hi @technicalpickles @
We need help for our merge. We have a critical big fix to our sheet and need to PULL this as soon as possible.
Mike

**Comment by Anduh** [comment]
As said in #5672, @clevett said this will get fixed, so I have nothing new to bring to the conversation.

**Comment by MadCoder253** [comment]
@Anduh Got the latest upstream master and everything merged. It does show that I changed the Fallout files but hopefully that doesn't affect anything.

**Comment by Anduh** [comment]
> @Anduh Got the latest upstream master and everything merged. It does show that I changed the Fallout files but hopefully that doesn't affect anything.

You _deleted_ the fallout files in this PR, so I wouldn't expect this to get approved.

Let Cassie fix the file thing, and then resubmit the GURPS v.1.7 changes. Preferably from a clean, new fork, properly using branches in git. The way you develop using your master branch and continuously do those "merge remote branch" pollutes your git history, and likely was the reason you had conflicts(the Fallout problem doesn't affect me for example).

Please take a look at at [Roll20's GitHub guide](https://wiki.roll20.net/Beginner%27s_Guide_to_GitHub). The guide is how to use the graphical GitHub interface, but many who works with Git/GitHub a lot like me and Cassie, uses the command line tool.

**Comment by MadCoder253** [comment]
Thanks again @Anduh Do I just close this pull request?

**Comment by Anduh** [comment]
Yeah you can close this one, after you're certain my version is fine.

**Comment by MadCoder253** [comment]
Yes, your version is good. thanks again.

**Pull request closed without merging**
