### PR TITLE
Add files for D6 Fantasy character sheet

### PR DESCRIPTION
**Pull request by megaBadger**

### CODE REVIEW

**Comment by megaBadger** [comment]
I wish to add the D6 Fantasy system character sheet, let me know if I need to change anything. Thanks!

**Comment by megaBadger** [comment]
Thanks!

**Comment by megaBadger** [comment]
Will this get added to the list on the Roll20 site? Just curious.

**Comment by SteveKoontz** [comment]
Yes. Next time we deploy code the sheet will be pushed live. I bucketed the other D6 sheets into an optgroup together in the Character Sheet list.

**Pull request merged**
