### PR TITLE
English Translation For Nechronica (Nechronica: The Long Long Sequel - English)

### PR DESCRIPTION
**Pull request by Brewstone**
## Changes / Comments
Created a new sheet for Nechronica using English text instead of Korean. The previous sheet was redone and changed to Korean in August. There are no other changes to the previous sheet

- nechronica.html updated to use English text (placeholder texts, section headers, etc.)
- nechronica.css name changed
- necrhonica.png updated to show English version of the sheet
- sheet.json updated for new file names

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
Hey there @Brewstone, there is a already a sheet for nechronica, so why not translate that instead of creating a new sheet? I am asking because while there have been duplicate public sheets allowed in the past, going forward Roll20 wants to limit this practice. Thanks for all the work you do!

**Comment by Brewstone** [comment]
This basically is a translation. I'm not sure what the way to go about doing a translation for a sheet would be, other than simply having a new sheet for the new language. If you can point in the right direction I'd be willing to give implementation a shot.

**Comment by Brewstone** [comment]
Hey @mperes , just checking to see what the process is for getting a sheet added to Crowding or who the person to ask is.

Thanks!

**Comment by mperes** [comment]
Hey @Brewstone, the sheet is not there because it was not setup for translation. I believe that would be a great contribution from you if are willing to put the work. Please check [this link](https://roll20.zendesk.com/hc/en-us/articles/360037773493-Character-Sheet-Translation#CharacterSheetTranslation-ListOrdering)

**Pull request closed without merging**
