### PR TITLE
Convert to UTF-8

### PR DESCRIPTION
**Pull request by Orta15a**

### CODE REVIEW

**Comment by Orta15a** [comment]
@pjbehr87  Hi,

I don't know why it's not able to automatically merge, but this file is now in UTF-8.

**Comment by Orta15a** [comment]
There, should be able to merge now. @pjbehr87

**Comment by pjbehr87** [comment]
That did it. You're changes are live, and appear to be working correctly. Thanks again for all your work in making this sheet available to translators on top of also adding the French translation!

**Comment by Orta15a** [comment]
Thanks ! It is indeed working.
While I got you, I could not find a good way to translate the RollTemplate, without breaking everything.
If you have a couple of minute, I'll really appreiciate if you could take a look at this post : https://app.roll20.net/forum/post/3762625/policy-change-for-alternate-translation-character-sheets/?pageforid=4457866#post-4457866

You guys are doing an amazing job with Roll20, thank you so much for all you work. I am living in Colombia right now and Roll20 allows me to continue to play with my French friends, even from the other side of the world. It's amazing.

**Pull request merged**
