### PR TITLE
[GURPS v1.7.0] clean PR

### PR DESCRIPTION
**Pull request by Anduh**
## Changes / Comments
This PR is a cleaned up version of #5689. I copied the changes made by @MadCoder253 to the GURPS sheet, and added a Changelog to the Readme for quicker overview of recent changes.
I'll leave this as a draft until Madcoder approves this PR. @KlingonMike might want to comment as well.

### v1.7 (2019-11) MadCoder253
* Repeating skills/spells. Removed checkbox to show success/fail notes. Converted text boxes to multi-line text boxes.
* Repeating melee/ranged attacks. Ability to link weapon to skill or spell. The weapon will show the skill or spell level and should update when the skill or spell level is updated.
* Reformat minimum damage notes and include page reference.

**Cosmetic Only:**

* Repeating Spells. Moved checkboxes for ON and MT to avoid collision with delete button.
* Resized some text boxes to allow more space for delete button.
* Change Maintained Penalty titles to Concentration Penalty. Thanks to Valter.

**Other:**
* add Changelog section in Readme

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by MadCoder253** [comment]
Oh wow. thank you very much @Anduh !  I don't know why the upstream/merge messed up those folders. This pull request looks good. Thanks again.

**Comment by KlingonMike** [comment]
Thank you Andreas, thank you so much!Please, if possible, do the PULL today once MadCoder approves.
Mike
    On Wednesday, November 20, 2019, 06:28:51 AM PST, Andreas J. <notifications@github.com> wrote:  
 
 
Changes / Comments

This PR is a cleaned up version of #5689. I copied the changes made by @MadCoder253 to the GURPS sheet, and added a Changelog to the Readme for quicker overview of recent changes.
I'll leave this as a draft until Madcoder approves this PR. @KlingonMike might want to comment as well.

v1.7 (2019-11) MadCoder253
   
   - Repeating skills/spells. Removed checkbox to show success/fail notes. Converted text boxes to multi-line text boxes.
   - Repeating melee/ranged attacks. Ability to link weapon to skill or spell. The weapon will show the skill or spell level and should update when the skill or spell level is updated.
   - Reformat minimum damage notes and include page reference.

Cosmetic Only:
   
   - Repeating Spells. Moved checkboxes for ON and MT to avoid collision with delete button.
   - Resized some text boxes to allow more space for delete button.
   - Change Maintained Penalty titles to Concentration Penalty. Thanks to Valter.

Other:
   
   - add Changelog section in Readme

Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.
   
   -  Does the pull request title have the sheet name(s)? Include each sheet name.
   -  Is this a bug fix?
   -  Does this add functional enhancements (new features or extending existing features) ?
   -  Does this add or change functional aesthetics (such as layout or color scheme) ?
   -  If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
   -  If this is a new sheet, did you follow Building Character Sheets standards ?

If you do not know English. Please leave a comment in your native language.

You can view, comment on, or merge this pull request online at:

  https://github.com/Roll20/roll20-character-sheets/pull/5692

Commit Summary
   
   - GURPS: v.1.7 readme & sheet.json changes
   - GURPS: v.1.7 Sheet changes, see readme for summary

File Changes
   
   -  M GURPS/README.md (33) 
   -  M GURPS/gurps.css (34) 
   -  M GURPS/gurps.html (546) 
   -  M GURPS/sheet.json (2) 

Patch Links:
   
   - https://github.com/Roll20/roll20-character-sheets/pull/5692.patch
   - https://github.com/Roll20/roll20-character-sheets/pull/5692.diff

**Comment by KlingonMike** [comment]
AndreasPlease make sure to do the PULL for [GURPS v1.7.0] clean PR #5692 and cancel [GURPS v1.7.0] #5689
ThanksMike
    On Wednesday, November 20, 2019, 06:28:51 AM PST, Andreas J. <notifications@github.com> wrote:  
 
 
Changes / Comments

This PR is a cleaned up version of #5689. I copied the changes made by @MadCoder253 to the GURPS sheet, and added a Changelog to the Readme for quicker overview of recent changes.
I'll leave this as a draft until Madcoder approves this PR. @KlingonMike might want to comment as well.

v1.7 (2019-11) MadCoder253
   
   - Repeating skills/spells. Removed checkbox to show success/fail notes. Converted text boxes to multi-line text boxes.
   - Repeating melee/ranged attacks. Ability to link weapon to skill or spell. The weapon will show the skill or spell level and should update when the skill or spell level is updated.
   - Reformat minimum damage notes and include page reference.

Cosmetic Only:
   
   - Repeating Spells. Moved checkboxes for ON and MT to avoid collision with delete button.
   - Resized some text boxes to allow more space for delete button.
   - Change Maintained Penalty titles to Concentration Penalty. Thanks to Valter.

Other:
   
   - add Changelog section in Readme

Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.
   
   -  Does the pull request title have the sheet name(s)? Include each sheet name.
   -  Is this a bug fix?
   -  Does this add functional enhancements (new features or extending existing features) ?
   -  Does this add or change functional aesthetics (such as layout or color scheme) ?
   -  If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
   -  If this is a new sheet, did you follow Building Character Sheets standards ?

If you do not know English. Please leave a comment in your native language.

You can view, comment on, or merge this pull request online at:

  https://github.com/Roll20/roll20-character-sheets/pull/5692

Commit Summary
   
   - GURPS: v.1.7 readme & sheet.json changes
   - GURPS: v.1.7 Sheet changes, see readme for summary

File Changes
   
   -  M GURPS/README.md (33) 
   -  M GURPS/gurps.css (34) 
   -  M GURPS/gurps.html (546) 
   -  M GURPS/sheet.json (2) 

Patch Links:
   
   - https://github.com/Roll20/roll20-character-sheets/pull/5692.patch
   - https://github.com/Roll20/roll20-character-sheets/pull/5692.diff

**Comment by Anduh** [comment]
> Andreas Please make sure to do the PULL for [GURPS v1.7.0] clean PR #5692 and cancel [GURPS v1.7.0] #5689 Thanks Mike 

I'm not going to forget this, @MadCoder253 just haven't closed the other PR, which was my condition to turn this into a regular PR. But considering you're in such a hurry even if we have time until Sunday, I'll just turn this on instead of getting bombarded daily until MadCoder does that.

@KlingonMike If it's possible, could you stop including all that bloat in your messages when you reply? It makes these comment chains unnecessary large.

**Comment by KlingonMike** [comment]
Sorry about that Andreas, the bloat was included by mistake. I did not notice until I had posted a reply. Then when I try to edit the message and remove it, it keeps reappearing. I also did not mean to bombard you as we greatly appreciate all you have done for us.
Mike

**Comment by KlingonMike** [comment]
Andreas
I had not noticed this before but why does this now say it is missing the sheet.json file? Indicated by the RED X next to the name of the PULL request.

**Comment by Anduh** [comment]
That is nothing I've seen up until now, must be some of those GitHub actions someone is trying out. I'll take a look and try figure out what's going on tomorrow.

**Comment by KlingonMike** [comment]
Andreas
Any luck figuring this out?

**Comment by Anduh** [comment]
My current understand is that these new checks aren't completely functional yet, and to me it seem as a mistake. At latest, I'll get response on Monday and know if there is some small thing I need to change.

**Comment by clevett** [comment]
We're still working on the automation. When we ran it the first time we had a few things incorrectly set for the sheet.json to validate correctly. I think we've fixed it but it doesn't update for the pull requests already submitted.

**Pull request merged**
