### PR TITLE
[Mongoose Traveller 2e Advanced] Initial commit

### PR DESCRIPTION
**Pull request by hartzenberg**
## Changes / Comments
Created a new, extended version of the Mongoose Traveller 2e character sheet.
 - Added Luck and Morale to Characteristics
 - Added ship shares to Wealth
 - Added Augments to Inventory
 - Added Journal Tab for players to track events

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Reonin** [comment]
Hi @hartzenberg it seems like most of your layout uses tables. Can you please update the HTML to fit closer to the [coding standards](https://wiki.roll20.net/Building_Character_Sheets#2._Good_Code)

**Comment by hartzenberg** [comment]
> Hi @hartzenberg it seems like most of your layout uses tables. 
This is a clone and extension of the existing  (legacy?) Mongoose Traveller 2e character sheet. Reworking it to not use tables is on the cards. I'm just not there yet.

@Reonin Will the PR be accepted in the current state?

**Comment by Anduh** [comment]
> This is a clone and extension of the existing (legacy?) Mongoose Traveller 2e character sheet. Reworking it to not use tables is on the cards. I'm just not there yet.
> 
>  Will the PR be accepted in the current state?

New sheets need to fit the minimum coding practices, while old sheets are grandfathered. I doubt pointing this out won't make a difference, haven't seen it work previously either.

**Comment by Reonin** [comment]
Hi @hartzenberg unfortunately I have to adhere to the new standards put in place to ensure clean code going forward. Let me know if you have any additional questions.

**Comment by clevett** [comment]
Greetings,

I'm going to close this pull request as the updates have not been completed in over a month. I appreciate your interest in contributing to the community repository.

**Pull request closed without merging**
