### PR TITLE
Adventures in Middle Earth Roll20 sheet update.

### PR DESCRIPTION
**Pull request by Echoblade9**
## Changes / Comments
I have updated the areas for the features and traits box and other proficiencies and languages box to allow for the newer OGL model of input.
Added a corruption saving throw option in saving throws
Changed "Attacks and Spellcasting" to "Attacks and Abilities"
Overall, functional changes to improve gameplay. 
The only section data may be lost is for distinctive quality, specialty, hopes and despairs. I don't know how to work around that.
I am not a coder, and I understand there may be redundant code, but the sheet works. Feel free to clean up my shoddy work.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ Yes] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ Yes] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [Yes ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Echoblade9** [comment]
Hi Cassie,

I have not made a post yet, thanks for the heads up. This is all very new to me. These changes I originally made for my personal games and am trying to work out how to contribute to the community.

As far as I have tested these changes all work fine. 

Cheers,
Riley

**Comment by clevett** [comment]
Greetings @EnricoDandolo1 

I'll go ahead and approve these for merge. The forum post is a curiosity. People sometimes get upset when their game changes significantly unexpectedly. The forum can help solicit feedback and just let them be aware.

Thanks,
Cassie

**Comment by EnricoDandolo1** [comment]
Think you may have tagged the wrong person here ... @Echoblade9

**Comment by clevett** [comment]
Sorry about that.

**Comment by Farhunter** [comment]
Is this a finished project? Would be great if the globals were made available as well as the spell tab, but as I look over everything I realize it's way over my head

**Pull request merged**
