### PR TITLE
HackMaster_5E Bug Fix

### PR DESCRIPTION
**Pull request by generalripphook**
## Changes / Comments
This is request to fix shield use and defense calculation error. Also Aiming Error. These were caused by missing {

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by generalripphook** [comment]
It's weird, everytime I fix the errors and hit "resolve" it gives me a check mark but won't let me merge anything. Only create a new file. 

Anyways, in each issue the second line of code is in error and should be removed.

**Comment by Reonin** [comment]
Hi @generalripphook the PR still seems have conflicts. Did you try making the changes locally on your machine? If you try to resolve it on Github there are inconsistent results.

**Comment by generalripphook** [comment]
I have made the changes locally, and I tried the resolve conflict button as well.

The changes all merged correctly on my local machine. I tried pushing the next update, maybe that will help?

**Comment by generalripphook** [comment]
I am at a loss of what to do here, I tried to even merge into a different name because it wouldn't let me resolve the conflicts and thats where "generalripphook:Hackmaster-5e-Changes-Resolved" came from but when I try to follow that link it just gives me a 404 message.

**Comment by generalripphook** [comment]
Okay @Reonin , so I tried a new pull request, there were merge conflicts and this time when I hit resolve and fixed the issues it worked. Would you be able to review that other pull request today?

**Comment by Reonin** [comment]
yep! @generalripphook I started the day a bit earlier so I could leave comments for folks with quick fixes that I can make a second pass and get them merged in before the day was up. Thanks for the quick turnaround

**Pull request closed without merging**
