### PR TITLE
Add Taura sheet

### PR DESCRIPTION
**Pull request by Ravencrow**
## Changes / Comments
Added the character sheet for the spanish roleplaying game Taura, from Juan F. Donoso, published by Nosolorol.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
Yes, it's the sheet for Taura roleplaying game
- [ ] Is this a bug fix?
No
- [ ] Does this add functional enhancements (new features or extending existing features) ?
No
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
No
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?
Yes, I did

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by clevett** [comment]
This a very pretty character sheet.

**Comment by clevett** [comment]
@Ravencrow The sheet was added but it appears to have some issues. Can you check on it and see if you can fix them? We will need to resolve them for next week code update or I will have to remove the sheet from the select

- Cassie

**Comment by Ravencrow** [comment]
@clevett on it. Is there any previewer for the characters sheets before merging them?

**Comment by clevett** [comment]
You'll need to have a Pro account and load it into a game for testing.

**Comment by Ravencrow** [comment]
@clevett Ok, Cassie, I have subscribed a pro account, and I have found the online editor. I have copied the HTML and the CSS and I can preview it but... this sheet depends a lot on the background, which is the sheet itself. 

So, my question is... how can I upload a picture so I can see the html elements over it?

Thanks in advance for the answer :)

**Pull request merged**
