### PR TITLE
[Ironsworn][Feature] Added assets summary in Moves

### PR DESCRIPTION
**Pull request by idispatch75**
- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description

~~PR not tested in the sandbox.~~

- [x] **DO NOT MERGE until a tester validates the changes on the sandbox**

Added the ticked assets in the Moves page: #10850
As a bonus, you can also track the health of your pets or asset resources there.
The display can be toggled via a new Setting.

Other small changes:
- Better handling of the changelog, which does not show entries that were previously acknowledged. Not a fan of the current implementation though, see #10997.
- Use move name as roll header for move oracle rolls. In my previous impl I had created specific i18n for these rolls, such as "Oracle: Endure Harm", but it's not worth the translation effort: now the header will just be "Endure Harm" which is already translated.
- Made the roll templates headers/footers a bit more clear by changing the font to Montserrat which is cleaner for bold text.
Before 
image
After 
image

- Fixed a waiting-to-be-triggered bug in the vow progress tracking where setAttrs was called on the incorrect section.

# How to test

## Assets summary
When adding assets in the Assets page and ticking items, these items should be visible in the Moves page. If the the asset contains a track (companion health for instance) it should be visible in the Moves pages and selecting a value in either page should synchronize the other page.
If you setup the assets like so:

image

they should be displayed in the Moves page like so:

image

A custom asset created like so (do not create 2 assets, the first one in the picture is just there to illustrate how to build the asset):

image

should be displayed like so:

image

Check the toggle button in Settings properly shows/hides the assets in the Moves page.

## Changelog
Just a non-regression test: the full changelog (2.4.0 to 2.7.0) should appear on a new sheet, disappear when you click Close, and stay hidden if you reopen the sheet.

## Move oracle header
Select the Endure Harm move and click Roll Oracle: the header of the roll should be Endure Harm.

## Cleaner roll template header/footer
Roll on a move, and validate the styling matches the one on the description

## Vows track fix
Non regression test: in the Summary page, on a vow, select Formidable and click Mark: 1 case should fill.

image

### CODE REVIEW

**Comment by idispatch75** [comment]
Hi @aureyia
If you think this PR is worth it, could you validate the sheet works as expected please?

**Review by aureyia — APPROVED** [review]

**Comment by aureyia** [comment]
@idispatch75 everything seems to work 👍

**Comment by aureyia** [comment]
@nmbradley all good on my end 👍

**Comment by idispatch75** [comment]
@aureyia Indeed the Discord seems to be the proper place to discuss char sheets. I should have started with that, but never thought there was such a thing.

**Pull request merged**
