### PR TITLE
Update spanish translations

### PR DESCRIPTION
**Pull request by helio-huete**
## Changes / Comments

Spanish translations for D&D_3-5 sheet.
IMPORTANT: I tried to keep english string lengths for the spanish translations. Please, check if translations fit in place before merging.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by clevett** [comment]
@helio-huete You'll need to speak with the original sheet author if you'd like to have the spacing checked on the sheet. Do you want me to hold off on merging this until you contact them?

**Comment by helio-huete** [comment]
@clevett Thanks for the info. We can wait some time for @suldae to comment on this PR (I don't know how to contact her in other way).

**Comment by suldae** [comment]
I've never been asked to verify translations before; so I just dropped it into the translation tab on the game and looked at what it looked like.  Hopefully that replicates things well enough. 

The only translation I see that doesn't appear to fit is:
"power-points": "Puntos de Poder",
it gets cut off after the "o" in Poder.
I went ahead and created a pull request to increase the size of that field slightly so it would fit nicely.

**Comment by helio-huete** [comment]
@suldae thank you very much for the test you have done. I think this is enough, so feel free to merge the PR.

**Comment by helio-huete** [comment]
@clevett feel free to merge the PR.
Thanks.

**Comment by clevett** [comment]
@helio-huete 

This will be merged in the coming week's pull. 

If you are interested in doing further translations please send me an email at cassie@roll20.net  . We use Crowdin to process translations it is safer and easier to do than editing a JSON. :)

Thanks,
Cassie

**Comment by suldae** [comment]
Hey Cassie, did something happen with my pull request?  It seems to have just disappeared; I don't see that the sheets were updated and even my branch no longer shows the change.  

Should I try again?  Is editing the file in my branch through the browser a bad way to do it? (Didn't want to use the desktop app because I have a bunch of pending changes for a different sheet in there which I haven't pushed up to the server yet).

**Pull request merged**
