### PR TITLE
[Marvel Heroic RPG by Pktome] new sheet

### PR DESCRIPTION
**Pull request by pktome**
New Sheet
Marvel Heroic RPG by Pktome

- [X] The pull request title clearly contains the name of the sheet I am editing.
- [X] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X] The pull request makes changes to files in only one sub-folder.
- [X] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

- The name of this game is: < Marvel Heroic RPG >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < Marvel Heroic RPG > _(i.e. Dungeons & Dragons, FATE)_

- [X] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [X] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

### CODE REVIEW

**Comment by nmbradley** [comment]
Hi @pktome 

Thank you for the submission. Unfortunately, we no longer accept duplicate sheets for existing games, and there is [already a sheet](https://github.com/Roll20/roll20-character-sheets/tree/master/Marvel%20Heroic%20Roleplaying)  for this game in the repository. On this basis, I'm sorry to have to inform you that your PR will be denied.

While there have been duplicate public sheets allowed in the past, going forward Roll20 wants to limit this practice. In the spirit of community collaboration we would advise you to consider how the upgrades you have provided would be implemented into the existing sheet for this game. You should feel empowered to push all sorts of features that would make running and playing the game a better experience, provided steps have been taken to protect the users of the existing sheet from unnecessary data loss.

**Comment by pktome** [comment]
@nmbradley Is it no longer possible to load custom sheets from existing systems? Where are these new rules on the site?

I understand that it is a practice that you are adopting, however, where could I open a discussion point for this? Would tokens created and updated many years ago prevent new tokens from being placed on the site?

**Comment by nmbradley** [comment]
This is a choice on our part and not a technical limitation. The repository has nearly a thousand sheets in it, and many of those are duplicate sheets for the same systems. 

Folks come along, start a sheet and then abandon it, and then someone else comes along and creates a new one only to also abandon it. It's better if people contribute to the existing work, rather than start from scratch every time.

**Comment by pktome** [comment]
I get it. But assuming there is a file there, unmodified for 1 year or so, would I have to find a way to find the original author to "update" it? Or I could simply ask the Roll20 team to give priority to the new sheet (as long as it is ok)... this is my point, I would like to raise this point of discussion because one of my hobbies would be to visually improve different sheets that are already inside from roll20. If that's not possible, then some of the things I intended to do I can't do anymore - due to unnecessary extra steps (for me).

**Comment by nmbradley** [comment]
You would just need to update the existing files with your new files. Provided the `attr` names are identical, users will just see the new sheet. With the exception of "official" sheets, work submitted here is done so with the understanding that they will be modified by other contributors.

**Comment by pktome** [comment]
> Você só precisa atualizar os arquivos existentes com seus novos arquivos. Desde que os `attr`nomes sejam idênticos, os usuários verão apenas a nova planilha. Com exceção das folhas "oficiais", os trabalhos aqui submetidos são feitos com o entendimento de que serão modificados por outros colaboradores.

in this case, can I replace any other sheet not originally created by me?

Could fields that I think are unnecessary - or complicated - be omitted/deleted? Following the example of this Marvel Heroic RPG, a person asked me to make it easier to play/view... so I did, but I did it in my original language (Portuguese-Brazil), for me to update it, I should do it it in english? etc...

**Comment by nmbradley** [comment]
We ask that you take care not to potentially disrupt the games of others, so in this case I would suggest:

- Providing [sheet translation keys](https://wiki.roll20.net/Character_Sheet_Translation) wherever possible
- Trying to match the attrs wherever possible
- If you intend to remove attrs, use sheetworkers to convert existing values to new ones

**Pull request closed without merging**
