### PR TITLE
[Electric Bastionland] Add electric bastionland character sheet

### PR DESCRIPTION
**Pull request by smcabrera**
Adding [Electric Bastionland](https://www.bastionland.com/) character sheet using black hack character sheet as a starting point (thanks Plexsoup!)

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by oliviakristiansen** [comment]
This Pull Request is still in the "Draft" status, so I cannot merge. If you would like it merged next week and your code is ready, please remove "Draft" from the PR. 

Thanks,
Olivia

**Comment by Reonin** [comment]
To add to that don't forget to put a preview image of the sheet before moving it out of draft!

**Comment by Reonin** [comment]
@smcabrera in case you missed the notes on the Pull Request

**Comment by clevett** [comment]
Greetings,

I'm going to close this PR as it has been over 20 days and is still in draft mode. It is also missing a preview image.

Thanks,
Cassie

**Pull request closed without merging**
