### PR TITLE
[1800 El Ocaso de la Humanidad] bugfix by @Hornwar

### PR DESCRIPTION
**Pull request by Anduh**
## Changes / Comments
- bugfixes by @Hornwar, originally rejected in #5751 due to GitHub difficulties

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
@Hornwar you need to comment here that you approve of this PR before I change it to a proper PR. Otherwise it stays as a draft.

**Comment by Hornwar** [comment]
Ok, my question here is why my previous pr was rejected. This is only some margins rectifications, the bugs that needs to be fixed are actually malfunctions on the sheet. What I have to do to update the code with the corrections? Last time I did a pr with all code corrected.

**Comment by Anduh** [comment]
This is the code you had and I fixed, I just want you to explicitly say that the end result is okay and you have tested it, before I fully submit it to Roll20. Don't want to send something that isn't checked, even if it seems to be an alright version of your code.

**Comment by Anduh** [comment]
@Hornwar can you please say you approve of this submission?

I'm waiting for you to approve this so I know it works, as I haven't tested this nor do I know the sheet, so I will change this into a full PR when you have tested this version of the code and know things are right.

**Comment by Anduh** [comment]
@Hornwar Is this still needed? Tell me this PR is okay and I will turn it on, otherwise I'll just remove it and stop trying to help you.

**Comment by Hornwar** [comment]
Hi,

Yes, both the first and the second corrections are needed. The second one
should have all mistakes corrected anyway.
Sorry for the delay to answer, I did not have time to check github this
last months.

Best regards

**Comment by Anduh** [comment]
@pwilson-roll20 @oliviakristiansen want to review/merge this now that I turned it from a draft to a full PR?

**Pull request merged**
