### PR TITLE
Fix for buff handling

### PR DESCRIPTION
**Pull request by Kurohyou**
Fixes handling of buffs and adds missing mods for backpacks.

### CODE REVIEW

**Comment by Kurohyou** [comment]
Thanks Wing-it. Hopefully no more emergencies and I can stop pestering you :)

**Comment by Kurohyou** [comment]
Also, what is the general time required for a merge to go live on the site?

**Comment by wing-it** [comment]
It varies. After I handle the merge on my end I have to pass it up the chain to a senior dev to push it live, so it's whenever he gets the free time.

**Comment by Kurohyou** [comment]
sounds good, thanks

**Comment by wing-it** [comment]
should be up now

**Pull request merged**
