### PR TITLE
[NEW SHEET] Hexen Academy

### PR DESCRIPTION
**Pull request by colearkenach**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: Hexen Academy  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: Stormforge Productions _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: Hexen Academy _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by NBrooks-Roll20** [comment]
Hi @colearkenach! We're going to get in touch with the publisher to ensure that this is an official sheet, please stand by.

**Comment by colearkenach** [comment]
> Hi @colearkenach! We're going to get in touch with the publisher to ensure that this is an official sheet, please stand by.

Understood, I don't know if they have a public means of contact but I can send their publisher's email if you have a way I can privately send it to you?

**Comment by colearkenach** [comment]
> > Hi @colearkenach! We're going to get in touch with the publisher to ensure that this is an official sheet, please stand by.
> 
> Understood, I don't know if they have a public means of contact but I can send their publisher's email if you have a way I can privately send it to you?

info@stormforgeproductions.com

Here's the publisher's email, if you want to check with them. I asked and was given the okay to send over the business email so you can reach out.

Let me know if you have any questions or concerns.

**Comment by NorWhal** [comment]
Thanks for the wait @colearkenach! You're good to go here

**Pull request merged**
