### PR TITLE
SWN Revised v2.4.0

### PR DESCRIPTION
**Pull request by Karlinator**
A few bug/typo fixes bundled with a major update to support a new supplement, Codex of the Black Sun.

No changes to basic functional aesthetics.

All old attributes preserved, just adding new ones.

### CODE REVIEW

**Comment by Anduh** [comment]
This PR have conflicts now

**Comment by Karlinator** [comment]
Conflicts are in the rendered HTML, source code merges fine. I've incorporated the conflicting changes into the source code, rendered, and marked resolved.

**Comment by Anduh** [comment]
Damn that was quick, great job!

**Comment by Karlinator** [comment]
Noticed the other PR yesterday. Once you said "conflicts" I knew right away what it was and how to fix it.

**Pull request merged**
