### PR TITLE
ChroniquesOublieesContemporain Version 3.2 hotfix

### PR DESCRIPTION
**Pull request by stephaned68**
Added a missing CSS class required for Version 3.2

## Changes / Comments
@Ulty forgot to include a change I made in the CSS
From now on, I will do the PRs for this character sheet (I am now more experienced with the Git versionning system and do not need Ulty's help anymore)
If this PR can be integrated sooner than later as a hotfix, that would be great. 
TIA

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Ulty** [comment]
In case a confirmation is needed, @stephaned68 will indeed take care of the sheets ChroniquesOublieesContemporain and ChroniquesGalactiques. Thanks Stéphane, and sory for the partial PR.

**Comment by Reonin** [comment]
Thank you both @stephaned68  and @Ulty for the communication on this. It makes my job easier :D

**Comment by stephaned68** [comment]
Hey @Reonin Thanks for the merge
I asked for this PR to be merged as an hotfix, even sent an email to team@roll20.net
Is 7 days the regular delay I must expect for an hotfix, or did I miss something in the procedure to have the correction sent out to the field as quick as possible ?
TIA for any input

**Comment by Reonin** [comment]
Hey @stephaned68 as of now 7 days is the usual delay. In the guide somewhere it mentions we typically only push out new sheets with the rest of our releases on Tuesday which means it needs to be ready by Monday morning.

**Comment by stephaned68** [comment]
Even for "hotfixes" ?
By the way, can you point me to the guide are you referring to ? So far, @Ulty was doing PRs for those sheets, but since I'm going to do them going forward, I'd like to have all pertinent information to avoid messing anything ;)

**Pull request merged**
