### PR TITLE
[D&D 3.5] Add new fields "classes" for multiplayer character

### PR DESCRIPTION
**Pull request by hoyer555**
## Changes / Comments
Add for new fields "classes" in PC and NPC sections, now it's possible to indicate all classes of a character.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by nmbradley** [comment]
Hi @hoyer555 I notice that this PR has changes to the individual translation json files. We no longer accept PRs that contain changes for these files, even for new translation keys. Would you be able to adjust the PR so you are not attempting changes, please? Until then, I cannot accept these changes.

**Comment by hoyer555** [comment]
Hi, for sure.
If I have understood correctly: I must remove new attributes from all json files inside the folder "translations", I must add all new key only in the "translation.json" file in the main folder, right?

**Comment by hoyer555** [comment]
I have removed all translations.

**Comment by nmbradley** [comment]
Thanks!

**Pull request merged**
