### PR TITLE
Fixed comma in html file name in JSON

### PR DESCRIPTION
**Pull request by Lockbox313**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Lockbox313** [comment]
Still throwing an error when you try to load a game set with the sheet

Uncaught TypeError: Cannot read property 'siteURL' of undefined
    at app.js?1568130243:536
    at app.js?1568130243:572

**Comment by clevett** [comment]
It loaded fine for me in English. What language are you using it in?

**Comment by Lockbox313** [comment]
I checked it 14 hours after I got the merged message and it wan't working
but is working now.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by clevett** [comment]
Oh! It likely wasn't on the server yet 14 hours after merge. Merge is just the first step. The new updates have to be pulled to the Live servers then the servers restarted. This change probably fixed it.

**Comment by Lockbox313** [comment]
OK thanks

**Pull request merged**
