### PR TITLE
[Ryuutama] Style fixes

### PR DESCRIPTION
**Pull request by jlvgit**
## Changes / Comments
Some small styling tweaks. And changing the image url to use the github one.

## Roll20 Requests

*Include the name of the sheet(s) you made changes to in the title.*

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- Is this a bug fix?
- Does this add functional enhancements (new features or extending existing features) ?
- Does this add or change functional aesthetics (such as layout or color scheme) ? 
- Are you intentionally changing more that one sheet? If so, which ones ?
- If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by jlvgit** [comment]
Note that it's just the last commit, the other stuff should be merged already. Don't know why it shows them all.

**Comment by Anduh** [comment]
If they don't show up in the **Files Changes** tab, it doesn't matter

**Comment by clevett** [comment]
@jlvgit It does that because your fork has different commit history than the master. This is happens when you commit directly to the fork instead of using branches for development. It's perfectly fine and wont hurt anything. The recent change you did will be the only ones that show up in File Changes tab.

**Comment by jlvgit** [comment]
Gotcha. Thanks for the info!

**Pull request merged**
