### PR TITLE
Stargate SG-1 character sheet 

### PR DESCRIPTION
**Pull request by MattBx8**

### CODE REVIEW

**Comment by clevett** [comment]
Hey @MattBx8 

You've included a change to the Wrath & Glory css. Ultimately deleting the file. Was this an intentional change? You can revert the Wrath & Glory changes for this pull request. 

As a best practice I recommend working in a separate folder from the Roll20 repo. When you're finished move the changes into the Roll20 repo.

Thanks,
Cassie

**Comment by MattBx8** [comment]
Sorry about that. I meant to append the Wrath & Glory CSS to the Wrath & Glory sheet I did but the Mac desktop GitHub version I’m using stuck it in with the Stargate SG-1 sheet.

I will wait for the Stargate SG-1 sheet to be approved before I re-do the Wrath & Glory CSS file.

/Matt

**Comment by clevett** [comment]
Greetings @MattBx8 

This pull request still has the Wrath & Glory changes in it. Can you edit the pull request to remove the changes to Wrath & Glory and make a separate pull request for it?

We generally ask each different sheet get its own pull request so its easier for us to monitor them.

Thanks,
Cassie :)

**Comment by MattBx8** [comment]
I have attempted to remove the Warhammer40kWrathNGlory pull request. It doesn’t work. I don’t know what I am doing wrong.

**Comment by clevett** [comment]
@MattBx8 

Where the Wrath & Glory changes ready to go? If so we can merge this pull request this time for simplicity. If the code is not ready you'll want to remove the pull request then revert the changes to Wrath & Glory before making a new pull request just for Stargate.

Thanks,

Cassie

**Comment by MattBx8** [comment]
Hello Cassie,
Sorry that I haven't gotten back to you earlier. Yes, the Wrath and Glory changes were ready to go. If you can merge this request this time, I will endeavor to improve my committing in the future.
/Matt

**Pull request merged**
