### PR TITLE
Initial commit for a better Fate Core character sheet

### PR DESCRIPTION
**Pull request by MagooChris**
After playing with a fully decked out DnD character sheet, I found the lack of smarts in the Fate Core sheet very depressing, so I decided to recreate it.

I have deliberately chosen to go with a new sheet over editing the existing one as it would just break any existing games as the sheet was built from the ground up.

This is a first draft of the new Character Sheet and I wanted to get some feedback. I haven't moved the image into the repository yet and no i18n have been set up. I don't expect this to be merged into the main branch just yet as I'm sure it won't meet all the standards, but wanted to get the ball rolling on getting it reviewed.

Thanks in advance for taking a look and giving me any feedback!

Regards,
MagooChris

### CODE REVIEW

**Comment by Anduh** [comment]
If you don't expect for it to be approved, don't make PR yet, and instead post your current progress on the forums.
Read the [sheet submission guidelines](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository)

**Comment by MagooChris** [comment]
Thanks Anduh and Cassie,

I guess I'm too used to other development groups. I'm not looking for User feedback but technical, and I'm not going to go pasting my code on the forums for people to steal. Most places I have contributed to will have code standards and will review and reject a first PR.

If you don't see anything wrong with the current version, then it can be merged, I just expected that there would be complications and it would be "rejected".

Sorry for the confusion!

Regards,
MagooChris

**Comment by clevett** [comment]
Greetings @MagooChris 

I did not check it that close for standards. I will do that Monday but you can find the standards at https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository

Our character sheet forum on Roll20 actually has a technical crowd and you're more likely to get feedback from other sheet authors rather than causal users. Its worth noting this repository operates under the MIT license so no need to steal work. Its accessible to any who wish to use it per the policy.

- Cassie

**Comment by clevett** [comment]
Greetings @MagooChris 

I merged your sheet it and gave it a look over. The improvement I see that would need to be added for this to become a listed sheet is roll buttons. The current sheet has roll buttons for skills which I was unable to find on this one. 

The sheet is off to a good start.

Thanks,
Cassie

**Comment by MagooChris** [comment]
Hi Cassie,

I've got inline roll buttons for skills or are you referring to something different?
`                        <fieldset class="repeating_skills">
                            <input type="hidden" name="attr_shiftLevel" class="sheet-skills-filter" />
                            <input type="hidden" name="attr_shiftLevelText" />
                            <div class="sheet-skills-pyramid-skill">
                                <div class="sheet-options">
                                    <input type="text" name="attr_skill" />
                                </div>
                                <div class="sheet-display">
                                    <button type="roll" class="sheet-action-button" name="roll_skillRoll" value="&{template:skill} {{charname=@{character_name}}} {{fatePoints=@{fatepoints}}} {{showInfo=1}} {{shiftLevel=@{shiftLevel}}} {{shiftLevelText=@{shiftLevelText}}} {{skill=@{skill}}} {{skillRoll=[[4df + @{shiftLevel}]]}}">
                                        <span name="attr_skill"></span>
                                    </button>
                                </div>
                            </div>
                        </fieldset>`

Skills Roll

Regards,
MagooChris

**Comment by clevett** [comment]
Greetings @MagooChris 

I see how you have them in there now. I would suggest adding the same style on hover button that the current Fate sheet has when you are in 'edit' mode in order for users to have some continuity between sheets.  It will help people  moving to this new one.

If you put in that pull request for the button next week then I'll deprecate the current Fate sheet to make yours the Core option in the drop down.

Thanks,
Cassie

**Pull request merged**
