### PR TITLE
GURPS Sheet Updates

### PR DESCRIPTION
**Pull request by MadCoder253**
## Changes / Comments

Updated files
GURPS\gurps.css
GURPS\gurps.html

## Roll20 Requests

- Added attributes for enhanced ground movement, flying, swimming, and jumping
- Added encumbrance columsn for enhanced ground movement, flying, and swimming
- Added roll table templates. Shows success/error on rolls. Shows critical success or fail.
- Modified option for private/public rolls. NOTE: Roll templates do not support showing just skill.
- Added option for private/public speed button. NOTE: If token is not selected,  it show an error to select token in order to add character to the order tracker
- Added option to use Skill+10 for critical success or just use 3 or 4 for critical success
- Added option to mark updates as read. If marked, last tab visited will be opened instead of the updates tab.

### CODE REVIEW

**Comment by clevett** [comment]
@MadCoder253 

Check your pull request. You're changing a number of sheets not listed in the comment/title. I assume your out of synch with master. You may need to update your fork.

You can do this by going to your fork and do a new pull request. The compare across forks to merge Roll20 character sheets repo into your fork. **MadCoder253/roll20-character...** <- **Roll20/roll20-character....**

**Comment by MadCoder253** [comment]
Hi clevett, 

I did a git merge upstream/master, but I'm not sure if that fixed the problem. The files listed below are shown to be different, but I think the only difference is maybe the carriage return/line feed. I haven't touched those files before and they all show the exact same number of line deletes and line adds. I use the default GIT process for windows carriage return and line feed and none of the other files seem to have the same problem. Any ideas on how to fix that? Maybe just copy those files directly from roll20 and paste over mine?

example: Sword & Scoundrel/Sword & Scoundrel.html  
@@ -1,2767 +1,2767 @@

Problem files (carriage return/line feed?)
El Resurgir del Dragón/elresurgirdeldragon.css
El Resurgir del Dragón/elresurgirdeldragon.html
El Resurgir del Dragón/sheet.json
Kids-on-Bikes/kob.css
Kids-on-Bikes/kob.html
Kult Divinity Lost/KULT Divinity Lost.css
Kult Divinity Lost/KULT Divinity Lost.html
Kult Divinity Lost/sheet.json
Sword & Scoundrel/README.md
Sword & Scoundrel/Sword & Scoundrel.html
Sword & Scoundrel/sheet.json

**Comment by MadCoder253** [comment]
Hi @clevett 

I verified on the Files Changed tab that all those non-GURPS files are white space changes (I clicked the option to hide white space changes), which I think is line endings. I tried experimenting by copying the raw code for Kids-on-Bikes\kob.css into my codebase but that didn't seem to work, so I reverted my commit. 

I looked at the history of my fork commits and on the history of roll20 and I couldn't find anything related to line endings. My fork history shows no changes were committed for those files. Please advise on what to do next. 

Thank you,
Ken

**Comment by MadCoder253** [comment]
Hi again @clevett 

I did some more digging by downloading source code directly from roll20 and it appears that all those files that are shown to be different were saved with CRLF for line endings. I checked several other files and those were saved with LF (normalized GIT line endings). I also verified my GIT settings normalize line endings to LF when committing changes. 

Thanks,
Ken

**Comment by clevett** [comment]
@MadCoder253 

That is very odd. Everything in the repo is required to have LF endings else they will fail to load. They should have entered your fork as LF. ^_^

**Comment by MadCoder253** [comment]
@clevett That is very weird. You know, I did do searches on json files looking on how others did useroptions and I also looked at other code at ways people did macros. I wonder because I opened them Visual Code the line endings for those files were changed to LF but didn't show up as a changed file in version history. 

Please let me know if there's anything I can do.

**Comment by clevett** [comment]
I changed all the line endings on those sheets and manually committed your [GURPs changes](https://github.com/Roll20/roll20-character-sheets/commit/136c8c81383574d8744573d5aa28231570ad0f1f) just to be on the safe side. I'll close this PR since the changes have been committed.

**Comment by MadCoder253** [comment]
@clevett  You rock, thanks for all your hard work. I see you got swamped with a bunch of pull requests.

**Pull request closed without merging**
