### PR TITLE
[Nuestro ultimo verano] Some bugs fixed

### PR DESCRIPTION
**Pull request by elfonochasis**
## Changes / Comments
Some bugs fixed

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
This seems like you're trying to submit a new sheet, not making edits to an existing one.

**Comment by elfonochasis** [comment]
Pull request name changed

**Comment by PrimalZed** [comment]
@Anduh It's a merge conflict: he got the sheet added yesterday, but continued working on his same remote branch for this new PR, so it looks like it's still "adding" stuff because the commit comparison is off.

**Comment by Anduh** [comment]
Oh, that makes things more complicated. I guess thing will be more clear later this week.

**Comment by elfonochasis** [comment]
I haven't write permissions

**Comment by PrimalZed** [comment]
You have to merge from roll20 master to your fork/branch in order to resolve merge conflicts.

**Pull request closed without merging**
