### PR TITLE
[Dragon Age RPG] Update Sheet & Internationalization

### PR DESCRIPTION
**Pull request by Zakarik**
## Changes

Provide a few comments about what you have changed. 

- Bugfix for Tab in the sheet : Before that, tab doesn't work (only radio button)
- Internationalization of the sheet & translate to french

## Additional comments
It's not my sheet, but this sheet isn't updated since 2016.

### CODE REVIEW

**Comment by muhammadrizal77** [comment]
Update

**Comment by joesinghaus** [comment]
Isn't it a bit pointless to add updates for a deprecated sheet?

**Comment by clevett** [comment]
@joesinghaus 

Deprecated sheets are still accessible to those who already have them selected or using the Custom Sheet.

**Comment by joesinghaus** [comment]
Fair enough :)

**Pull request merged**
