### PR TITLE
Correct the alignment of the Skills tab-Warhammer Fantasy: 2nd Edition (Havoc)

### PR DESCRIPTION
**Pull request by timothystone**
## Changes / Comments

It seems that the use of DIVs over TABLEs on this sheet defeated the
usability in game. This uses TABLEs to present the TABULAR list of
Skills with Mastery, custom mods, the calculated Sum, and Roll
button

Some inline style sheet work was cleaned up and put in the CSS.

## Roll20 Requests

*Include the name of the sheet you made changes to in the title.*

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by clevett** [comment]
Greetings @timothystone 

Can you expand on or list what the challenges are from using divs here? I see the skills list is one and we could fix the skills being out of align with a simple extra div to wrap the row or margin-bottom solution. The div change was a good one and I'd like to help you tweak the small issues that came from it. :)

Thanks,
Cassie

**Comment by timothystone** [comment]
Is this a `table` vs. `div` discussion? Understanding that Warhammer makes Zealot a playable career... :P I've worshipped at the altar of Zeldman and praised the high saints of Cederholm, Meyer and Holzschlag. And all agree: Tables have merit presenting tabular structures and lists. `div`s for `div`-sake leads to `div`itis.

I'd be willing to consider rapid iteration here. Since I'm supporting the sheet and this was raised in the forums, I think there are games waiting on this PR (my own WFRP game being re-tooled). I can follow on with a rewrite of the `div` structure, but wanted to resolve this quickly for the games looking for it.

**Comment by clevett** [comment]
`tables` are heresy so say the tech-priest of Mars. Such elements offend the machine spirits and it is the will of the Omnissiah that such code be squashed. Fear not the `div`itis, imperial citizen. For ye need only embrace the power of [selectors](https://www.w3schools.com/cssref/css_selectors.asp). 

I can quickly fix the skill list with divs or selectors on the headers. Both options are less code than a table will be. :) What other challenges are there? Tables do have merit but on a whole they add more tech debt than benefits to a sheet.

**Comment by timothystone** [comment]
Reading the CSS, assuming all Roll20 documentation is up-to-date, are you looking for the following:

```
<div class='2colrow'>
  <div class='col'>
    <div class='row'>
      <!-- header -->
    </div>
    <div class='row'>
      <!-- single skill row with sibling containers for skills, calculated values, button -->
      <!-- though the documentation is a little fuzzy on elements being spans or inputs or divs -->
      <!--  -->
    </div> 
    <!-- more skill rows and siblings -->
  </div>
  <div class='col'>
    <!-- repeat above, neighboring column -->
  </div>
</div>
```

I am not objecting to the review—an advocate of selectors myself; I have a signed copy of _CSS:TDG 2e_ by Eric Meyer, was a former committer to the YUI CSS Module, and have committed documentation on Page Objects and selectors to Protractor.

Admittedly, the sheet has a lot of other bad practices, e.g., remote images, inline styling. All PRs I'm willing to work on based on your review.

Thanks!

**Comment by clevett** [comment]
This would be a good option if you want to do a large rework:

``  <div class='col'>
     <div class='row'>
      
    </div>
    <div class='row'>
      
    </div> 
    
  </div>``

For a quick fix you could do this: https://github.com/Roll20/roll20-character-sheets/pull/4582/files
(Ignore the changes around likes 800. I did a alignment out of force habit but these aren't important.)

I added a class called skills to the column with the headers.

``<div class="sheet-col skills">
</div>``

I then removed the inline styles from this div & all the headers inside it. These can be moved to the CSS sheet.

``div.sheet-skills {
    width: 45%;
}

div.sheet-skills h4 {
    height: 25px;
    margin-top: 0.32em;
} ``

**Comment by timothystone** [comment]
@clevett thanks for the look. Do you want to continue this conversation in your PR? 

Before we do, what I don't see is handling **full** skill row alignment.

Each row **must** align in column, Basic and Advanced Skills aligning is a strong visualization aspect that needs to be considered too. 

This really leads to a responsive (and a possibly an A11Y) discussion. Currently, as set out in a table, for a VTT solution on the  desktop, the table use meets minimum functionality of responsive (I used relative widths versus fixed to allow it to stretch and squish, but overflow for scrolling in narrow views) and Roll20 allows it, q.v., [Roll20 documentation, Good Code, Proper HTML Syntax](https://wiki.roll20.net/Building_Character_Sheets#HTML_Layout)

I think your argument for a more responsive `div` based layout is sound, but I would want to rewrite it so collapsing by column and then column row was possible.

That's the issue with the sheet currently. So in ASCII...

Collapse by Column, then Row
```
+--2rowcol------------------+---------------------------+
| +---row-----------------+ | +---row-----------------+ |
| |Basic                  | | |Advanced               | |
| +-----+-----+---+---+---+ | +-----+-----+---+---+---+ |
| |  t  | ---v| t | t | o | | |  t  | ---v| t | t | o | |
| +-----+-----+---+---+---+ | +-----+-----+---+---+---+ |
| |  t  | ---v| t | t | o | | |  t  | ---v| t | t | o | |
| +-----+-----+---+---+---+ | +-----+-----+---+---+---+ |
| |  t  | ---v| t | t | o | | |  t  | ---v| t | t | o | |
| +-----+-----+---+---+---+ | +-----+-----+---+---+---+ |
| | ...                   | | | ...                   | |
| +-----+-----+---+---+---+ | +-----+-----+---+---+---+ |
+---------------------------+---------------------------+
```

Narrow screen

```
+--2rowcol------------------+ <--- each Column collapses
| +---row-----------------+ |
| |Basic                  | |
| +-----+-----+---+---+---+ |
| |  t  | ---v| t | t | o | |
| +-----+-----+---+---+---+ |
| |  t  | ---v| t | t | o | |
| +-----+-----+---+---+---+ |
| |  t  | ---v| t | t | o | |
| +-----+-----+---+---+---+ |
| | ...                   | |
| +-----+-----+---+---+---+ |
+---------------------------+

+---------------------------+
| +---row-----------------+ |
| |Advanced               | |
| +-----+-----+---+---+---+ |
| |  t  | ---v| t | t | o | |
| +-----+-----+---+---+---+ |
| |  t  | ---v| t | t | o | |
| +-----+-----+---+---+---+ |
| |  t  | ---v| t | t | o | |
| +-----+-----+---+---+---+ |
| | ...                   | |
| +-----+-----+---+---+---+ |
+---------------------------+
```

Narrower screen

```
+--2rowcol------------------+
| +---row-----------------+ |
| |Basic                  | |
| +-----------------------+ |
| +-----+-----+---+---+---+ |
| |  t                    | | <--- each skill row collapses
| +-----+-----+---+---+---+ |
| |  ---------------V     | |
| +-----+-----+---+---+---+ |
| |  [ t               ]  | |
| +-----+-----+---+---+---+ |
| |  [ t               ]  | |
| +-----+-----+---+---+---+ |
| |  [ button          ]  | |
| +-----+-----+---+---+---+ |
| +-----+-----+---+---+---+ |
| | ...                   | |
| +-----+-----+---+---+---+ |
+---------------------------+
```
Hence, the `2colrow` use. I'm not adverse to the rewrite. I did rewrite it using `table`. 

**The rest of the page would be fixed and scroll, but the skill list would be sound.** :P

**Comment by clevett** [comment]
How about we merge in the fix in my PR to help the skills list for this week and we can take this overall discussion to the character sheet forums on Roll20?  Other veteran sheet authors will have helpful input & tips.

I use a set width on the overall character sheet in order to create an overflow scrollbar for narrow screens.  I do this with: 

```
	.charsheet {
		width: 850px;}
```

Usings 2rowcol, col, and row are generally advised against by veteran sheet authors these days. Typically its suggested to create your own classes to give you more control. Using these built in classes was very common in older sheets.

**Comment by timothystone** [comment]
> Usings 2rowcol, col, and row are generally advised against by veteran sheet authors these days. 

You may not be aware, but _none_ of the Roll20 documentation is updated to reflect the experience of veteran authors.

> Typically [it's] suggested to create your own classes to give you more control. Using these built in classes was very common in older sheets.

Agree and concur. Roll20 should make documenting sheet best practices either directly or by soliciting for a broader community review of the documentation to bring it to current best practices.

My PR addresses the specific ask of users in the forums. I would rather close my PR and revisit, than apply a PR that "bubbles" past the focused intent of the `table` based solution to patch a gap in the wider character sheet.

I'm concerned in adding `width`, if only because I have not had a moment to test your PR in context on the dev environment. Let me try that tonight (8-ish EST) and comment here.

**Comment by timothystone** [comment]
Let me amend my test commitment. I have a Face-to-Face D&D game tonight. D'oh! (I thought it was Thursday; first game of the new year and all that I just incorrectly noted the date).

I may get to it before 8PM, but I may do it tomorrow (1/9). Sorry.

**Comment by clevett** [comment]
No rush with the testing. I'll keep an eye on Github for additional feedback. 

[Building Character Sheets](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) wiki is indeed a document that needs continued updates. The new section for [Roll20 Character Sheets Repository](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) was added 2 months ago composed from a long list of standards provided by several veteran & feedback of new sheet authors. Additional feedback for the wiki can be left here, [Updates to Building Character Sheets...](https://app.roll20.net/forum/post/6917043/updates-to-building-character-sheets-wiki-and-github-readme).  When getting into design philosophies its best to move the discussion back to the Character Sheet forums to give other sheet authors a chance to weigh in. :)

**Comment by timothystone** [comment]
Closing. Completed testing.

**Pull request closed without merging**
