### PR TITLE
[Tesero y Gloria] New sheet

### PR DESCRIPTION
**Pull request by Anduh**
## Changes / Comments
* New Character Sheet for "Tesero y Gloria", by the publisher @Tenfes  
* This is a cleaned up version of #5684 where I placed the the new sheet in a separate folder from the old TyG sheet, fixed the filenames, uploaded sheet logo. By not replacing the old sheet folder, this PR could be approved whether the old sheet is kept or not.
* The sheet uses a couple of `<table>` to style it, but is otherwise cleaned up, and is made by the publisher, there could be a reason to approve it nevertheless.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
@Tenfes, if you mention your roll20 id here, I can add it to the PR, and then things should be fine.

The "roll20 id" can be found by going to your profile, and looking at the url. My Roll20 account for example is https://app.roll20.net/users/1223200/andreas-j , where that number is my roll20id.

**Comment by Tenfes** [comment]
Hi, sorry for the delay,

I already rewrote the code without the table styling, but I'm having some
trouble putting the folder into the pull again. Sorry, I'm quite new to
programming, this is my first work. Could I send the folder to you here so
you could put it back into GitHub? I would be very thankful.

Greetings,

Telmo

**Comment by Anduh** [comment]
You can share the new version of the sheet with a [Gist](https://gist.github.com/), and I'll copy and update the changes, no problem.

**Comment by Tenfes** [comment]
Thank you! Here is the gist for the html and css, the other items are the
same.

<script src="
https://gist.github.com/Tenfes/809829cee5299a617b6906f5c044582c.js
"></script>

**Comment by Anduh** [comment]
That sheet version looks same as the first one, I see all the same tables still exist.

**Comment by Tenfes** [comment]
That can't be, the name (nombre), gloria, fama, etc are all in columns now,
not in tables. I only left there the tables for the equipment (weapons and
protections), and the ones at tab of Monstruos for the attacks.

**Comment by Anduh** [comment]
Oh you changed one table, I missed that. Still, you have all those other tables. We will see on Monady when Roll20 reviews these, if that is enough changes.

Did you found out your `roll20id` ? It can be found if you go to your roll20 profile, and look at the numbers in the URL, like I pointed out.

**Comment by Tenfes** [comment]
There are 4 tables in total: Características, Armas, Protecciones y Ataques
(in Monstrruos), ¿is that still a lot? I don't have a clear idea of how
much would be too much :(

Oh, and right, i got my id: 101803

**Comment by Anduh** [comment]
According to the [Minimum Requrements](https://wiki.roll20.net/Building_Character_Sheets#Minimum_Requirements):

> Proper HTML Syntax. Proper HTML syntax is encouraged to increase accessibility and make the code maintainable for community contributions. **As a general standard a** `<⁠table>` **element should only be used for tabular data. The** `<⁠table>` **shall not be used for layouts.** All new sheets are expected to use proper containers elements such as `<⁠div>` and `<⁠span>` elements. Your HTML file must not use `<⁠head>` or `<⁠body>` tag, or your character sheet may not load in the virtual tabletop. 

This is a [PR that was turned down](https://github.com/Roll20/roll20-character-sheets/pull/5548) by Roll20, due to using `<table>` for layout.

If it's important for you to get the sheet approved next week, changing all tables now would be a good idea, to avoid the risk of getting delayed.
If you're in no hurry, then just wait until you get Official Roll20 response on Monday, and see if you can avoid doing more work on the sheet. Considering you're the author of the game system itself, it's possible Roll20 might soften the minimum demands, but we will see what they say tomorrow.

You can look at the things I pointed out, and decide what you do.
I do not know 100% what Roll20 will say, I'm just pointing out the guidelines they have made for us and how they have decided previously so that you can do things now, instead of hearing more or less the same from Roll20.

**Comment by Tenfes** [comment]
OK, thanks for all your help ^^

**Comment by Anduh** [comment]
I'll cleanup the code some more, so that future changes to the sheet should be easier to make.

**Comment by Anduh** [comment]
@Tenfes There you heard it.
I'd suggest you continue from my version of the sheet to do the rest of the conversion, instead of yours. Unfortunately I won't have time to help further in the near future, but this submission just needs the `<table>` converted and then it's fine.

**Comment by Tenfes** [comment]
Yep, is a pein, but I understand... thanks so mucho for your help!

**Comment by Anduh** [comment]
@Tenfes I added your changes into this PR, your where misplaced withing the old forder and didn't have the updated images. But with this I'm sure the sheet is ready to be approved next Monday.

**Pull request merged**
