### PR TITLE
DC Heroes: Initial version

### PR DESCRIPTION
**Pull request by BrianSaga**
## Changes / Comments

*Provide a few comments about what you have changed.*

## Roll20 Requests

*Include the name of the sheet you made changes to in the title.*

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by Anduh** [comment]
Does this system use dice at all? Didn't find any on this sheet.

Seems good otherwise, on a quick look.

**Comment by BrianSaga** [comment]
It does use dice, but it uses charts to look up the success number by comparing an acting value versus an opposing value. Same for damage, which is not variable and is derived from a second table.  It doesn't do 1dN + attr + skill, hence no roll buttons.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BrianSaga** [comment]
Hi, Cassie:

It was originally published as DC Heroes, which is OOP. The mechanics are
called MEGS (Mayfair Exponential Game System).

DC Heroes Role-Playing Game, 3rd Ed.
https://www.amazon.com/dp/1569050007/ref=cm_sw_r_cp_apa_i_VUfwCb531ARJZ

It was also published in the Batman RPG
Batman Role-Playing Game
https://www.amazon.com/dp/0923763082/ref=cm_sw_r_cp_apa_i_LVfwCb2S5MS46

But if the name I submitted doesn't work (i.e., DC Heroes), it's latest
incarnation is Blood of Heroes Role-Playing Game
https://www.amazon.com/dp/0966528034/ref=cm_sw_r_cp_apa_i_HRfwCbFKFCJKB.

**Comment by clevett** [comment]
DC Heroes is fine. I just needed a little more context for adding it to the approved list.

Thanks,
Cassie

**Comment by BrianSaga** [comment]
Ok, great. Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
