### PR TITLE
Vulcania - Notes and PNG/NPC tab

### PR DESCRIPTION
**Pull request by Zipippo**
I added some important spaces to insert part of the character's background. I also implemented the tab with a section dedicated to PNGs

# Submission Checklist
## Required

- [X] The pull request title clearly contains the name of the sheet I am editing.
- [ ] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [ ] The pull request makes changes to files in only one sub-folder.
- [ ] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [X] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [X] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by BronsonHall** [comment]
Hey @Zipippo

Couple small things here.  First, your PR title is a little vague - while we can tell what you're changing about the sheet by way of your comment and the file context, we do ask that each PR clearly indicates what sheet it changes, and how (in very general terms), in the title itself.  

This makes it much easier for all who use the repo to both understand the changes and trace them after they've been implemented.  You can still provide the specifics of your changes in the description as you have - something like "Vulcania - New Features" would be enough in the title if those details are present in the PR.  

Other thing is that your readme and the folder containing it both seem to refer to the Exalted, Second Edition sheet, rather than Vulcania.  Seems like you may want to change that, can you clarify here?

Thanks!

**Comment by Zipippo** [comment]
Hi!!! What I have inserted are some implementations to the player card:
1. In the main tab I inserted a tab that contains the character's background notes and various Notes
2. I have included the possibility for the master to create a specific card to create PNGs

regarding the readme file I made a mistake. Exalted is a typo! what I wanted to write is Vulcania Second edition.

I apologize for all these incompressions but it's the first time for me

**Comment by BronsonHall** [comment]
Sounds great @Zipippo !

I've gone ahead and changed the title of this Pull Request to reflect the changes as I understand them, but you can adjust this if you need to.  

If you could, please fix that typo in the readme file, and commit that change to this branch.  

I've also got to ask that you remove the changes made to everything in the `translations` folder.  These files are generated by our crowdin translation service, and there will be merge conflicts if any changes are made manually.  You only need to worry about adding new translations to `translation.json` in the base sheet folder - we'll copy those translations over to the other files on our end.

There are also a few other issues I noticed, that you may want to take a look at:
- It seems you may be missing a few translations on the PNG/NPC tab (`capacity-i`,`addestramento-i`,`opportunity-i`)
- Some `</div>` closing tags may need to be adjusted around your notes section in `vulcania.html`.  Currently, the notes section is entirely enclosed within your PNG/NPC tab, and thus doesn't show up where it should.
- I notice you've also removed the buttons wrapping the images in the PNG/NPC weapon section.  You may want to add some CSS rules to limit how big these images are, so they don't push content off the page.  The button elements on the other tabs have these rules, as examples.
- You can add your roll20 user id to the `roll20userid` property in sheet.json if you'd like the "Sheet Author" badge on Roll20.  

If you fix the readme and translations folder, though, that's enough for me to merge this PR!  
Thanks for your hard work!

**Comment by BronsonHall** [comment]
Hey @Zipippo !

Sorry, to clarify -> You don't need to remove those translation files entirely, just the changes you had made to them in this branch!  If you reset that specific folder to how it is on master (so that in the `Files Changed` tab on this PR, the translations folder does not show any changes), that'll be enough. 

Secondly, a sheet can have multiple authors!  You'll want to keep the original author's user id in the `sheet.json`, and change that line to `"roll20userid": "2122249, 9093769",` to get both of you credit for your work on the sheet.

**Comment by Zipippo** [comment]
I made the requested changes. I apologize but I'm not familiar with Github. In fact, now I'm still convinced that I didn't do all the right procedures. I apologize but I couldn't find anyone who could help me do what I did. I apologize again for the incompressions

**Comment by BronsonHall** [comment]
@Zipippo 
No worries!  I've gone ahead and done the last two things:
1. I restored the translations folder from master.   
    - Specifically, I made sure that this Pull Request had no differences to any file in that folder compared to master.  
       For the future, try and avoid changing anything within translations/ - but `git checkout master Vulcania/translations/` is the command to reset that folder to master if needed.  
2. I moved the Readme from the exalted2e/ folder to the main sheet folder

That should get this PR good to go - if you can double check and confirm for me that all your changes are in there, I can merge this into master!

**Pull request closed without merging**
