### PR TITLE
Elder Scrolls: UESTRPG (D&D 5e conversion) sheet

### PR DESCRIPTION
**Pull request by EnricoDandolo1**
## Changes / Comments

A simple conversion of the 5e OGL character sheet for use with the Unofficial Elder Scrolls Tabletop Roleplaying Game conversion of D&D 5e (https://uestrpg.wixsite.com/home/). Tested in my campaign and those of others, seem to have spotted and fixed most of the major bugs and added requested features unique to the conversion.

## Roll20 Requests

*Include the name of the sheet you made changes to in the title.*

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by EnricoDandolo1** [comment]
Thanks for the pointers. Done all that.

**Comment by EnricoDandolo1** [comment]
My bad, done that.

**Comment by clevett** [comment]
Fyi,

I renamed the folder for this sheet so it will be easier to know the system its for. Acronyms can be hard for people out of the loop to know. :) The sheet.json also was missing a comma but I added it. Just make sure to update your fork before trying to submit another pull request or you may run into merge conflicts.

Thanks,
Cassie

**Comment by EnricoDandolo1** [comment]
Thanks! I can't find the sheet on the site right now, I assume approved sheets are made available on the site with a slight delay? (First submission in case it wasn't obvious :'D)

**Comment by Anduh** [comment]
Yes, updates and new sheets usually go live on Tuesday even if some things are merged on Mondays.

**Comment by clevett** [comment]
Anduh had the answer but its up now.

**Pull request merged**
