### PR TITLE
VtM v5 Copying bug fix. Added warning about updating. 

### PR DESCRIPTION
**Pull request by Kirintale**
Updated translation to "Experience To Spend"

I've copied @joesinghaus bug fix. (Feel free to accept either).
The other difference I made is warning people about Powers section being updated.

I'm honestly uncertain why there is a conflict where it says there is. If you could accept the new code.

### CODE REVIEW

**Comment by joesinghaus** [comment]
You need to resolve the merge conflict first before this can be accepted.

**Comment by Kirintale** [comment]
Good point.

BTW I would like to add you to the Thank you section of the sheet, if you would like to be added could you tell me what name you want to be thanked under and optionally your Roll20 ID.

**Comment by joesinghaus** [comment]
Ah, it's really not necessary. I didn't do anything special here :).

**Comment by Kirintale** [comment]
Are you sure? You caught the ball that I dropped ^_^

**Comment by joesinghaus** [comment]
Yeah I'm good ;)

**Pull request closed without merging**
