### PR TITLE
M.A.G.U.S.-character-sheet-v0.1

### PR DESCRIPTION
**Pull request by larrodan**

### CODE REVIEW

**Comment by Rhallinan** [comment]
You need to include the CSS, Image and JSON file. If you need help with understanding that let me know. Right now all I see is an HTML file.

**Comment by larrodan** [comment]
Hi!

Do i have to make a separated css file? html is already contains that.
There is no json, no roll templates.


2015-09-21 17:41 GMT+02:00 Ryan Hallinan <notifications@github.com>:

**Comment by Rhallinan** [comment]
Sorry about the delay on getting back to you, but you will need the JSON and we prefer it to include a preview image. The CSS file will also need to be seperate due to how our system is set up.

Here is an example of what the JSON file look like. It should be titled sheet.json when you upload it:


{
	"html": "D&D_5e.html",
	"css": "D&D_5e.css",
	"authors": "Mark Lenser (Mark on Roll20.net, @mlenser on Twitter). Tooltips & German translations done by Rouby. Wiki done by Heather Lazar (HLazar on Roll20.net). Original 5e sheet Author: John Myles",
	"roll20userid": "277007",
	"preview": "D&D5e.jpg",
	"instructions": "This sheet is designed for use with D&D 5th edition. It has been designed to match the layout of the D&D 5e Character Sheet. Sheet help is available on the roll20 wiki - https://wiki.roll20.net/DnD5e_Shaped_Character_Sheet"
}

**Comment by SteveKoontz** [comment]
I'm closing this request. Please issue a new request with the format changes Ryan suggested. Feel free to email me steve@roll20.net with any questions.

**Pull request closed without merging**
