### PR TITLE
[Twilight 2000 2.2] Changes to accommodate Dark Mode

### PR DESCRIPTION
**Pull request by Lockbox313**
## Changes / Comments
Changes to accommodate Dark Mode

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by nmbradley** [comment]
Hi @Lockbox313 

Just wanted to check, it looks like you've added two files called 'Kult' to this unrelated sheet. Was this intentional?

**Comment by Lockbox313** [comment]
No it wasn't that willl teach me for trying to do 4 at once. Can the Kult
files be removed.?

**Comment by Lockbox313** [comment]
> Hi @Lockbox313
> 
> Just wanted to check, it looks like you've added two files called 'Kult' to this unrelated sheet. Was this intentional?
No it wasn't that will teach me for doing 4 sheets at once. Can the the Kult files be removed ?

**Comment by nmbradley** [comment]
Hi @Lockbox313 I've reverted the whole change, you'll need to move your changes to a new branch and create a new PR for this sheet.

**Pull request merged**
