### PR TITLE
[The One Ring] Version 2.0: update to match formatting of printed sheet

### PR DESCRIPTION
**Pull request by stuartj**
## Changes

This commit squashes down multiple changes to more closely reflect the official printed character sheet, specifically:

* use a styled background
* display diamond checkboxes for common skills and skill groups
* format and style experience, valour and wisdom in top right of sheet
* use a serif font

Additionally, internationalisation support is improved:
* switch the logo to display correctly for different language versions (English, French, German, Spanish).
* support migrating from 'Der Eine Ring' and 'Anneau Unique' sheets, by use of worker scripts to copy data to new fields.

Other minor additional features:
* fixed slots for weapons for ease of macro scripting.
* user-definable skills for Loremaster Characters
* adding 'Mounts' for horses etc.

## Additional comments

This is a major update of layout and styling but seeks to be completely backwards compatible with the original version of the sheet, as well as other language versions of the sheet ("Anneau Unique" and "Der Eine Ring") that have developed over time.

The development and testing has been a team effort, announced and coordinated on the RPGGeek forum at rpggeek.com/thread/2024136/fellowship-roll20-character-sheet. We have recently completed testing and a 'public beta' period for feedback.

### CODE REVIEW

**Comment by clevett** [comment]
Also thanks for the detailed comment! It was very helpful.

**Comment by stuartj** [comment]
@clevett - thanks for merging this, but it seems your subsequent commit f34b45a4 overwrote the translations and broke the changes for 'The One Ring'!

I've raised a new Pull Request to fix this, at https://github.com/Roll20/roll20-character-sheets/pull/4457. Could you please give this new Pull Request urgent attention to merge as soon as possible, to resolve this problem?

**Comment by clevett** [comment]
Greetings @stuartj , 

It looks like nine keys are experiencing an issue on production due to this overwrite and those keys are well labelled so users will know their intended purpose. I'm going to hold off on merging the new PR for now and merge it as part of a test to see why the translation process replaced those keys. That translation merge happens every week as part of the sheet updates and I want to ensure this was just a one time fluke that wont happen every week thereafter. 

Thanks,
Cassie

**Comment by stuartj** [comment]
Thanks Cassie. Hopefully anybody who goes to take a look at the new sheet in the meantime will overlook the glitches while you are doing your test!

Re: your comment about ensuring no subsequent overwrites, is there somewhere else that I need to update the translations, on CrowdIn or wherever? After reading https://wiki.roll20.net/Character_Sheet_i18n#Changing_your_Translation, I also edited the translation.json - which I gather is the 'source' for CrowdIn -  in commit 
34d3e36 for this Pull Request. I also updated the other as yet untranslated translation .json files, though I boggled at what to do about translations/zu.json.

best regards

Stuart

**Pull request merged**
