### PR TITLE
Insane Character Sheet - Korean

### PR DESCRIPTION
**Pull request by avocadoedition**
Insane Character Sheet - (lang)Korean

### CODE REVIEW

**Comment by Solarswordsman** [comment]
Hi @avocadoedition, now that we have a translation system in place, we no longer use directly-named languaged-versions of character sheets.  I would ask that you please rename the sheet to simply the name of the game, and then submit it as is.  It is fine to be in the Korean language for the upload, it just should not be labeled as such; if for example someone wanted to make an "English version" of the sheet they could then add translation keys and strings.

Thanks,
Jeff

**Comment by avocadoedition** [comment]
I am convinced.
I accepted your request.
These files have been modified.

**Comment by avocadoedition** [comment]
Thank you.
That code is better than this code.
I am very happy to be able to use the character sheet of this system on Roll20.
If I add a Korean translation to the character sheet, when will the roll20 system be updated?

**Comment by Solarswordsman** [comment]
If you're willing to drop this code and add a Korean translation to that sheet, then we can put out the sheet right away and then add your translation right on our next sheet update next Tuesday.  I think that would be the ideal solution.

**Comment by avocadoedition** [comment]
Thank you for your kind advice.
I will update the Korean translation on the Shinobi_gami character sheet.
Although this code was not used, it was a pleasant experience.
I wish you a happy day today!

**Comment by zeteticl** [comment]
@avocadoedition  
I also like your design style.
I already download your code, and try to make it together. 
.....in a month?

**Pull request closed without merging**
