### PR TITLE
D6Starwars.css lightmode/darkmode fix

### PR DESCRIPTION
**Pull request by DarthBanjo**
fixes character sheet fields for lightmode and darkmode css

# Submission Checklist
## Required

- [ x] The pull request title clearly contains the name of the sheet I am editing.
- [ x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [ x] The pull request makes changes to files in only one sub-folder.
- [ x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [ x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   d6holocron.com >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

I added these:
.sheet-lightmode .characterviewer input{ color:black; } 
and 
.sheet-darkmode mode .characterviewer input{ color:white; background:black; }

### CODE REVIEW

**Comment by DarthBanjo** [comment]
This pull request should fix lightmode and darkmode issues on the character sheet: and should look something like this. If in review, this is not how character sheets look, please reject or modify to fix.

unknown

**Comment by mperes** [comment]
@Anduh @Moondancer83 @tgtrammel are you folks good with the proposed changes?

**Comment by Moondancer83** [comment]
Thanks for the effort 👍

However, please check the current version (2.44).
The above issue seems to be fixed already.

Light
image
Dark
image

**Comment by DarthBanjo** [comment]
Ok great. I will close this request. Yesterday there was a complaint on the Star Wars D6 discord so I looked at the issue. I guess he should have just waited a day. :)

**Pull request closed without merging**
