### PR TITLE
[Pendragon]Fixed NPC and Horse values. New Background.

### PR DESCRIPTION
**Pull request by RhOmicron**
NPC and Horse values same, breaking stats.

New Background.

### CODE REVIEW

**Comment by Lockbox313** [comment]
There appears to be some problem with the newimage link.

**Comment by RhOmicron** [comment]
There seems to be code missing from my testing and I can't seem to get it into a pull request because phone copying doesn't work in roll20 html layout(great...) I won't have access to a computer until Friday.

**Comment by RhOmicron** [comment]
It is the dividers for the background missing amongst other things which I have no idea.

**Comment by Lockbox313** [comment]
There is an image tag with its source looking for p-titre.jpg which is not
in the image folder

**Comment by RhOmicron** [comment]
I see, the p-titre image part of the code has been removed in the code I have in testing. I somehow forgot to paste in this in my last pull request.

This will be fixed as soon as possible.

**Pull request merged**
