### PR TITLE
Imperium Maledictum character sheet for roll20

### PR DESCRIPTION
**Pull request by clgarret**
# Submission Checklist
## Required

- [ X] The pull request title clearly contains the name of the sheet I am editing.
- [ X] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [ X] The pull request makes changes to files in only one sub-folder.
- [ X] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: < Imperium Maledictum 1st Edition  >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <  Cubicle7 > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < Imperium Maledictum  > _(i.e. Dungeons & Dragons, FATE)_

- [X ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by clgarret** [comment]
Do I have to do anything further to submit this?  This is the first sheet that I created.

**Comment by BronsonHall** [comment]
Hey @clgarret,

Great stuff for your first sheet!  A couple small things jump out to me that you'll want to change before we can consider merging this.  

First, I noticed you're using `<table>` for your roll templates - while some older games do use table for layout, we don't allow this on new sheets for the repo.  You should try and use the div grid or flex layouts you use elsewhere on the sheet here as well. You can find more info about this [here](https://wiki.roll20.net/Designing_Character_Sheet_Layout#HTML_Table).

Secondly, your game logo is hosted externally, linked from the Cubicle7 site.  This is generally not a good idea, as the image link could change or stop working.  We recommend all images you use be included in this repo - further info can be found [here](https://wiki.roll20.net/Image_use_in_character_sheets).  There's also a possible issue with copyright on this image.  Unless you're making this sheet on the behalf or with the blessing of Cubicle7, you'll want to avoid using their artwork, including the game logo.  You may want to create your own logo instead, or find another way to aesthetically display the game title.  

Bronson

**Comment by clgarret** [comment]
Hi BronsonHall,

Please take a look again.  There are no tables in the sheet.  Everything is using CSS Grid and Flex box already.

I will fix the image issue.

Thanks for the feedback.

**Comment by BronsonHall** [comment]
Hey @clgarret 

You're correct regarding the sheet itself - your grid and flexboxes are perfect there.  I was referring to the `<rolltemplate>` at line 1892 of imsheet.html, which does use `<table>`.   This is something that's not perfectly clear by my earlier definition of the rule, but `<table>` usage anywhere on new sheet code, including roll templates, is something we don't merge in anymore as a practice.  

I've taken a look back through our custom sheet dev resources, though, and I think I know how this might have occurred - some of our examples on the helpdesk and wiki pages do use `<table>` in roll templates, referencing older sheets from before we put this policy in place!  This is outdated advice on our part, and I'm reaching out now to get this corrected.  

What I suspect may also be to blame is that many existing sheets in this repo still use `<table>` for layout in roll templates, and are exempt from the rule if they were originally created before we started enforcing it - though we encourage devs maintaining these sheets to consider changing this practice.  Unfortunately, we do require all new sheets to abide by the strict "no tables" policy. 

Sorry, I know it's a bit confusing, but it's important as we try and step away from `<table>` usage in this repo entirely.  There are just too many styling and layout bugs that arise from tables when implemented on the live site.  Your css grid and flexbox solutions in the sheet proper would work perfectly if you can convert these roll templates to use them as well. 

Let me know if you have any further questions,

Bronson

**Comment by clgarret** [comment]
Ah lol, got it.  Yeah thanks for the clarification and quick responses.  I have someone working on providing a stylized logo for me and I will fix the roll templates.

**Comment by clgarret** [comment]
I switched the rolltemplate to css grid and uploaded a new stylized logo that my friend created so copyright issue should be resolved as well.  Please let me know if there's anything else that needs fixing :)

**Comment by clgarret** [comment]
I wasn't positive on generating the link for the sheet so I used imgur - hopefully that's ok.  Otherwise I can make a relative path to the local version tomorrow.  I tried to get that working in the sandbox but without luck, so that's why I switched to the imgur version.

**Comment by mperes** [comment]
Hey @clgarret, I am gonna merge this. Please, once that is live, change the image log path to match the image that is gonna be hosted within github. If you also feel inclined, it would be nice to add translation support to the sheet. Thanks for the hard work!

-
Miguel

**Pull request merged**
