### PR TITLE
Call of Cthulhu - Powered by the Apocalypse

### PR DESCRIPTION
**Pull request by Berserkas**
## Changes / Comments
New character sheet for a Call of Cthulhu Powered By the Apocalypse hack that is being made.
https://sanitylossguaranteed.blogspot.com/2018/10/powered-by-apocalypse-call-of-cthulhu.html

## Roll20 Requests
New sheet for above PBtA hack.

### CODE REVIEW

**Comment by Berserkas** [comment]
Created a custom sheet for a Call of Cthulhu Powered by the Apocalypse hack that is being made.
https://sanitylossguaranteed.blogspot.com/2018/10/powered-by-apocalypse-call-of-cthulhu.html

**Comment by Berserkas** [comment]
Thanks for the info Cassie, I will make proposed changes and get rid of my nasty tables. Last time I dabbled with html was 20+ years ago and then CSS was something very new. "Google Academy" here I come. :)

**Comment by clevett** [comment]
Greetings @Berserkas 

I'm with you. :) I had to Code Academy to get myself up to speed on all these new found CSS ways when I started making sheets. [Reach of Titan](https://github.com/Roll20/roll20-character-sheets/tree/master/ReachofTitan) may help a helpful example of how to do a simple display sheet.

**Comment by Berserkas** [comment]
Hi @clevett 
I've removed all the tables and used inline-block. I'm also a new user of GitHub, but I think that I've managed to update said files in this request...hopefully. :)

**Pull request merged**
