### PR TITLE
New version of the Delta Green sheet

### PR DESCRIPTION
**Pull request by uriele**
## Changes / Comments

Several changes has been made. 
The name of the attributes has been made standard to simplify future updated
Added monster sheet and animation
Implemented new roll template and fixed the bugs present in previous sheet (BP, POW and autocomputations)

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by clevett** [comment]
Greetings @uriele 

You have merge conflicts that need to be resolved before the submission can be accepted. Your comment notes changing attribute names. Did you write versioning to migrate user data?

- Cassie

**Comment by uriele** [comment]
Hi Cassie,
sadly no and I wouldn't know where to start all  the repeated field has been removed to make the sheet looks better and closer to the printed version still keeping the utility. It is more of an entire new character sheet than an upgrade. It has been rewritten and tested from the ground up.

**Comment by uriele** [comment]
Also most of the attributes of the previous sheet that were present but unused has been removed. For example
'exhaustion','stim','lowwill','dazzled','pepperspray','teargas','flashbang','electroshock','status1','status2','status3','mod1','mod2','mod3'

There were given to the players but weren't changing anything on the sheet (and weren't used in the rolls). I have removed them and only introduced simple modifiers like 'aimchk', 'calledshot1','calledshot2','rangeshotchk'.

**Comment by clevett** [comment]
I'd recommend you submit this as a new character sheet rather than a replacement for the currently deprecate done. The sheet this pull request is currently being submitted as an update for is no longer active on the site. This update would result in an interruption to users.

I'd recommend backing up your code, updating your current fork's master with this repository, and then submitting this a new sheet from a branch.

- Cassie

**Comment by uriele** [comment]
Hi Cassie,
I've submitted it as a new sheet DeltaGreenRPG. Please let me know if it's ok. I will close this request. Marco

**Pull request closed without merging**
