### PR TITLE
RyuutamaSpanish: Add all the sheets in spanish version

### PR DESCRIPTION
**Pull request by Ravencrow**
## Changes / Comments
This PR adds all the characters Sheets from the spanish version of Ryuutama to Roll20.

**Why so big files?**
This game has an incredible amount of character sheets, and the spanish publisher wanted the users to have the same experience online that on the tabletop. So, there are actually 15 different character sheets for the game. I tried to separate with comments every character sheet both in the html and the css file.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [X] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [X] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
Hello @Ravencrow, before merging your commit I would like to get a clear understanding of your PR. There is already a character sheet for Ryuutama in the repository (https://github.com/Roll20/roll20-character-sheets/tree/master/Ryuutama). Is your PR just a Spanish translation for the same system, if so, I would ask you to help translate the existing sheet instead of creating a new one. If you sheet has new capabilities that the old one does not, I would advise you to contribute to that project instead of creating a new one for the same game. If those are completely different system, who happens to share the same name, please let me know and I will go ahead and merge your PR. Thanks!

**Comment by Anduh** [comment]
This page helps with how to add translation to an existing sheet: https://wiki.roll20.net/Character_Sheet_Translation

**Comment by Ravencrow** [comment]
Thanks @mperes and @Anduh for the comments. Very appreciated for the review.

I think the same: it's best to translate a sheet whenever possible. Sadly, there are two big reasons why I cannot translate in this case, even when we are talking about the same system:

a) the actual version of ryutama has only the character sheet, the one for the PJ. The one I'm trying to merge is a version with all the sheets in the game: travel diary, adventure sheet, scene sheet, world sheet, and so on and so on for a total of 15 different sheets that's included in this game manual. 

b) one of the main points of the spanish publisher is "the player should have the same game experience in tabletop than in roll20", meaning the character sheet should look the same. The character sheets in ryuutama are very nice, with small drawings and such. While the one in roll20 is clean and nice, it's not the same as the ones the players have on the manual. That's why I have used scans for all the 15 different character sheets in this PR from the spanish ryutama manual.

I hope these are valid reasons to merge this big PR. I had a similar situation with Tenra Bansho, from the same spanish publisher, and it went through. 

I'm really sorry for the inconvenience that these requirements could be causing you. And again, thanks truly for the review.

**Comment by mperes** [comment]
Hey there @Ravencrow , I'm sorry to have to inform you that your PR will be denied. While there have been duplicate public sheets allowed in the past, going forward Roll20 wants to limit this practice. Your collaboration with existing sheets should not be restricted to translations, in fact in the spirit of community engagement, you should be able to push all sorts of features that would make running the game a better experience. Things such as the implementation of a setting that makes the sheet look completely different, like a dark theme or a completely revamped visual are completely valid additions you might consider.

Another option you could pursue is to check with the authors of the current sheet to see if a complete rewrite would be allowed.

**Pull request closed without merging**
