### PR TITLE
Dark Horizons Mechanized Corps -New Sheet

### PR DESCRIPTION
**Pull request by edgardnerNESP**
# Submission Checklist
## Required

- [x ] The pull request title clearly contains the name of the sheet I am editing.
- [x ] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x ] The pull request makes changes to files in only one sub-folder.
- [ x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is:  Dark Horizons Mechanized Corps   
- The publisher of this game is: X10 Game Studios
- The name of this game system/family is: X10 Combat System

- [x ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [X ] This sheet has been made on behalf of, or by, the game's publisher.
- [X] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: < https://preview.drivethrurpg.com/en/product/467690/Dark-Horizons-Mechanized-Corps-QuickStart  >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

First Revision

### CODE REVIEW

**Comment by nmbradley** [comment]
Hi @edgardnerNESP 

Could you answer the following questions, please?

**The name of this game is:

The publisher of this game is:

The name of this game system/family is:**

**Comment by edgardnerNESP** [comment]
Sorry I thought I added thatDark Horizons Mechanized Corps published by x10 game studiosThe game system is the x10 combat system but that only exists right now as this game. ——Edward GardnerPrincipalNew England Safety Partners, LLCBook a meeting!Your partner in security and compliance (857) 342-1035 ext 101 | (617) ***@***.***://www.newenglandsp.com77 Oak St, Suite 202, Newton, MA 02464On Feb 20, 2024, at 16:45, Nic Bradley ***@***.***> wrote:﻿
Hi @edgardnerNESP
Could you answer the following questions, please?
**The name of this game is:
The publisher of this game is:
The name of this game system/family is:**

**Comment by edgardnerNESP** [comment]
Just looked no idea how that didn't get captured. 

I see my email got munged 

Game: Dark Horizons Mechanized Corps

Publisher: X10 Game studios

system: x10 combat system.

**Comment by edgardnerNESP** [comment]
I see, I put those into the  brackets and it hid them, updated main desc.

**Comment by edgardnerNESP** [comment]
@nmbradley, it turns out I neglected to name the attribute fields in this PR. Should I cancel it and resubmit?

**Comment by nmbradley** [comment]
If they now have the correct names that should be fine. It'll get merged later today 🙂

**Comment by edgardnerNESP** [comment]
I just committed the revision. Thanks!

**Pull request merged**
