### PR TITLE
Version 2.0 Character Sheet

### PR DESCRIPTION
**Pull request by waders01**

### CODE REVIEW

**Comment by pjbehr87** [comment]
Sorry for the delay, I was gone on vacation all last week. I just have a few questions for you before I finish this PR: (I only ask because of the large number of changes)
1.  Is this new version completely backwards compatible with the previous version?
2. Does this new version coincide with a new version of Star Frontiers, or is it just an update to the sheet?

**Comment by waders01** [comment]
It is a completely new version of the sheet and IS NOT backwards compatible.  I added significant changes to the entire sheet, including new repeatable sections and sheetworkers.  The game system has not changed though.  I have additional changes coming shortly for some additional enhancements but those enhancements will be backwards compatible with this new sheet.

**Comment by waders01** [comment]
I don't believe at this time there is a lot of users.

**Comment by waders01** [comment]
please let me know if you need anything to get this pulled.

**Pull request closed without merging**
