### PR TITLE
Savage Worlds Tabbed v3.0 Update

### PR DESCRIPTION
**Pull request by finderski**
Complete Re-write of the sheet. Incorporated feedback from the community.

This sheet includes Sheet Worker scripts to aid in the migration of data, though in most instances all the field names remain the same as the original. The sheet has been up and shared with the community to ensure feedback was received and to help test the sheet workers for the upgrade process. All known issues have been resolved.

For clarity, the file names of the HTML, CSS, and Sheet image have been changed.

This update was done to streamline the code with lessons learned and to bring the sheet into compatibility with the latest rules edition. It also still includes support of the Savage Worlds Deluxe edition of the rules.

### CODE REVIEW

**Comment by Anduh** [comment]
Did you make the Archive folder for quick access to the old versions of the sheets?
The old version doesn't get lost anywhere with you update, it can be retrieved from the git history if necessary.

And the fact that you both renamed the html & css  as well as moved the old versions to the archive folder makes hard or impossible to have a real overview of the code changes. I think this should be done in a better way as to preserve the change history of the files, but I'm unsure exactly how.

Well, you'll know tomorrow if this minor things _actually_ would delay merging the changes.

**Comment by finderski** [comment]
The Archive folder is for quick access. And everything is basically new. The only things that would be the same are most of the field names. Other than that...completely rewritten from scratch, if you were to compare, everything would be red...

Finderski

"Nice tuxedo! Nice tuxedo to die in!"

**Comment by Anduh** [comment]
Oh good, so it's a complete rewrite.
Sorry I didn't take it literally when you wrote this being a complete rewrite.

Salutes to the impressive work!

**Comment by finderski** [comment]
Thanks! Don’t know if I’ll ever do that again, though. LOL 

Rich Finder

"Nice tuxedo! Nice tuxedo to die in!"

**Comment by clevett** [comment]
Thanks for the comment. This has been very helpful for such as big update. After it goes live tomorrow keep me posted if you a hotfix.

**Comment by finderski** [comment]
Awesome, thanks. :)

Rich Finder

"Nice tuxedo! Nice tuxedo to die in!"

**Comment by clevett** [comment]
@finderski 

You sheet.json is not valid. You're missing a number of ','. Use https://jsonlint.com/ and if you can get it updated tonight for me I'll merge it in. Otherwise I will need to revert this commit.

Thanks,
Cassie

**Comment by finderski** [comment]
Can you define “tonight?” I’ll get it updated, but I’m in Chicago on business so not sure what time I’ll get back to my hotel room. 

Rich Finder

"Nice tuxedo! Nice tuxedo to die in!"

**Comment by finderski** [comment]
Updated and submitted pull request. 

Rich Finder

"Nice tuxedo! Nice tuxedo to die in!"

**Pull request merged**
