### PR TITLE
SWN Revised v1.6.0

### PR DESCRIPTION
**Pull request by Karlinator**
Lots of changes!

I've added Sheet Default settings (in valid JSON), and am now hoping I did it all correctly...

This is the "Homebrew/Customisation Update", so a lot of new toggleable things. with a settings page and everything.

### CODE REVIEW

**Comment by Karlinator** [comment]
Oh I do remove a whole section, but it was a duplicate of somewhere else, so nothing is lost (apart from maybe having to scroll a little bit).

**Comment by Anduh** [comment]
Wow, this json-toggleable setting stuff is all new to me, are there any documentation available to learn how to utilize this in other sheets?

Found no similar mentions on the roll20 wiki, and wouldn't know what to search for on the internet.

**Comment by Karlinator** [comment]
There is [this](https://app.roll20.net/forum/post/4364848/dev-update-12-slash-13-default-settings/?pageforid=4364848#post-4364848). No, really, that's it. You'll just have to use that and the code from the 5EOGL sheet to discern it for yourself.

**Comment by Anduh** [comment]
The link just shows "My Games"-page for me, maybe I can't see it because I'm not in the game? Whaterever they say there sure is better than having _only_ the OGL and your sheet to look at. Are there any other sheets who successfully used this?

**Comment by wing-it** [comment]
Yeah, sorry about the lack of documentation for this, we're aware of it and hope to be adding better documentation to the wiki in the near future.

To name a few other examples for you to look at, checkout the GUMSHOE Official sheet and Pathfinder.

**Comment by Karlinator** [comment]
@Anduh that was my bad on the forum link. The link is to the Pro forums, so you'll need a Pro subscription to read it.

**Comment by Anduh** [comment]
Giving this concept a name and describing how it works in three sentences could be a start? And maybe copypaste whatever stuff there happened to be on the Pro forum thread?

**Pull request merged**
