### PR TITLE
[Hammerhead cortex prime] Finalise the Dice Roller Template

### PR DESCRIPTION
**Pull request by tapiochre**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by tapiochre** [comment]
I think I have one more update to the character sheet allowing stress to go higher than 12. This might need an extra image. Will try to get that done today.

**Comment by mperes** [comment]
Hey there @tapiochre, your json valid is invalid there are some characters in there that need to be escaped. Please run it through a JSON validator, fix the problems and update you pull request. Thanks for all the work you do!

**Comment by tapiochre** [comment]
removed the offending characters. Thanks

**Comment by tapiochre** [comment]
ok looks like I've missed something - on it

**Comment by tapiochre** [comment]
I think its all good now

**Pull request merged**
