### PR TITLE
7th Sea 2e update

### PR DESCRIPTION
**Pull request by BluSponge**
## Changes / Comments
Large update to the existing sheet design.  These changes were made over two years of regular play.

Modifications include: 

- Updated color scheme and logo (trade dressing)
- Removed Roll Template for better representation of the system’s die roll (easier for sorting raises) 
- Internal die roll formula changes 
- Ship record includes support for Expanded Ship Rules PDF 
- Minor formatting and content changes to all pages 
- Hero Points counter fixed and goes to 9

## Roll20 Requests

*Include the name of the sheet you made changes to in the title.*

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by Anduh** [comment]
If your other update is the correct one, you could close this pull request. (Don't delete the branch, only close this pull request as it's redundant and contains errors anyway.)

**Comment by Anduh** [comment]
You're aware that deleting files in a branch is not the same as closing a pull request?

**Comment by BluSponge** [comment]
Um…nope.  How do I close an old pull request?

**Comment by Anduh** [comment]
The "close pull request" button you be next to the button for making comments.

Visual guide:
https://help.github.com/en/articles/closing-a-pull-request

**Comment by clevett** [comment]
Greetings, 

We've got two Pull Request updating similar code. What's going on with this PR and #4806 ? This update appears to be touching a number of more files than #4806.

Thanks,
Cassie

**Comment by BluSponge** [comment]
Hi Cassie,

Sorry, I’m out of town so I can’t check GitHub at the moment. I believe the latest update (patch-6) should include everything. All the files (html, css, png, Json, et al) are updated.

I apologize for the confusion. There was some github learning curve that needed to be overcome.

Tom H.

**Comment by Anduh** [comment]
The other PR is the correct one, this was just the earlier one that we didn't manage to close, as per the above mentioned learning curve.

**Pull request closed without merging**
