### PR TITLE
New Character sheet [Locus]

### PR DESCRIPTION
**Pull request by cobblepathgames**
## Changes / Comments

New character sheet submission for the recently kickstarted Locus horror roleplay system.  
We have included the sheet name in the pull request title.  
It is not a bug fix - it is a first submission.  
It does not add enhancements for the same reason.  
We have followed building character sheets standards to the best of our ability and also followed examples from other successful sheets in the repository.  

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
Hey @cobblepathgames, there is a problem with your PR which is forbidding it to pass through the automatic validation. The file named "Locus Official.json" should be named "sheet.json" instead. Could you make this change and push? Thanks!

**Comment by cobblepathgames** [comment]
Hi!

Woops sorry that's a holdover I forgot to change.  Now pushed. Let me know
if any other issues!
Steph @ Cobblepath

**Comment by cobblepathgames** [comment]
Thanks a bunch! Does this mean it will be available in the custom sheets
list on the website?  Do you think it would be there for halloween? (new to
this)

**Comment by pwilson-roll20** [comment]
Yes it will be!!!

**Pull request merged**
