### PR TITLE
Fragged Empire HACKED

### PR DESCRIPTION
**Pull request by ve4grm**
## Changes / Comments
New Sheet:
Fragged_Empire-HACKED

New sheet, based on the existing Fragged Empire sheet, but with improved usability, improved readability, roll buttons, tabs, removing hard-to-read gradients, other usability improvements.

Introduced auto-calculating skill modifiers.

Also updated sheet to work for the HACKED variant of Fragged Empire.

As many attributes from the old sheet as possible are still there, to allow for maximum compatibility if people switch.

## Roll20 Requests

*Include the name of the sheet(s) you made changes to in the title.*

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- Is this a bug fix?
- Does this add functional enhancements (new features or extending existing features) ?
- Does this add or change functional aesthetics (such as layout or color scheme) ? 
- Are you intentionally changing more that one sheet? If so, which ones ?
- If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by ve4grm** [comment]
Hi Cassie,

Unfortunately, as this has some massive functionality improvements, it would not work as a skin for the existing sheet.

I could submit it as a rewrite of that sheet, but it also is mimicking an alternative ruleset (the "HACKED" rules) which has some changes, and the old ruleset is still used.

Would it be possible to bring the sheet in so I can troubleshoot it (as I'm not a Pro member, so I can't 100% confirm my functions work as intended as I don't have a Custom sheet to play around with) and I rework the layout into DIVs as I do that?

**Comment by ve4grm** [comment]
FYI - I have already started work on a DIV-based version of the sheet. Unfortunately, it will require a significant amount of work to adapt the pre-existing layout from the copied sheet.

I would appreciate the ability to start testing and confirming the formulas in the meantime (which I can't do myself, not being a pro member), as well as to let people start using it. I understand that it's not holding to current best practices, but it is very functional and I am working on the update.

**Comment by clevett** [comment]
Greetings @ve4grm 

I apologize but submissions to this repository currently requires access to Pro membership in order for sheets to be tested and troubleshoot reported bugs.

- Cassie

**Comment by ve4grm** [comment]
@clevett Wait, really? Based on all discussion I'd seen, this wasn't true. (The following two threads, for example:
https://app.roll20.net/forum/post/3591226/creating-a-character-sheet-as-a-non-pro-member
https://app.roll20.net/forum/post/3808930/creating-slash-editing-character-sheets-without-pro

Can you please point me to where this is stated? I can't find it in the wiki or the Git repo.

If this is the case, but not listed, then I've wasted literal days.

**Comment by Anduh** [comment]
It's mentioned in the [readme](https://github.com/Roll20/roll20-character-sheets/blob/master/README.md#improving-existing-character-sheets):
>**Improving Existing Character Sheets**

If you want to help improve an existing sheet, just clone this repository. Make your changes, test them in app using the Custom accessible with a Roll20 Pro account, and submit a pull request.

**Comment by clevett** [comment]
Grreetings,

In web programming testing is critical in order to ensure the integrity of the user experience. We work on an honor system in trusting our community sheet authors to do their own testing and at this time to test on our platform Custom sheet access is required. References to these expectations for testing with Custom sheets is listed in three places, two on the wiki & one in GitHub.

[Building Character Sheets](https://wiki.roll20.net/Building_Character_Sheets#Building_a_Character_Sheet).

> To build a sheet, you must have access to a Pro account.

> Make your changes, test them in app using the Custom accessible with a Roll20 Pro account, and submit a pull request.

The [GitHub Readme](https://github.com/Roll20/roll20-character-sheets#improving-existing-character-sheets).

> If you want to help improve an existing sheet, just clone this repository. Make your changes, test them in app using the Custom accessible with a Roll20 Pro account, and submit a pull request.

**Pull request closed without merging**
