### PR TITLE
Created Demon: The Fallen (cWOD)

### PR DESCRIPTION
**Pull request by bhcunit6**
New Demon: The Fallen sheet. Includes HTML, CSS, JSON, README, preview image and sheet images. Uses classic WOD storytelling system.

### CODE REVIEW

**Comment by pjbehr87** [comment]
Now that the PR has been accepted, you'll have to update the image links to the raw version of each image in our repo. (you can find this by going to the image and clicking the "Download" button at the top right) So, for the AF_Faith_Health_divide.png image you would use the link https://raw.githubusercontent.com/Roll20/roll20-character-sheets/master/CWOD-Demon/img/AF_Faith_Health_divide.png

**Comment by bhcunit6** [comment]
Got it. Thanks!

**Comment by pjbehr87** [comment]
Hey, just wanted to say you made a really fantastic looking sheet. Keep up the good work!

**Comment by bhcunit6** [comment]
Thank you for the great feedback! I'm already thinking about improvements so there will definitely be more PRs in the future.

**Pull request merged**
