### PR TITLE
Improvements to the [The Fantasy Trip] character sheet

### PR DESCRIPTION
**Pull request by jaemzfleming**
This is a pretty big set of improvements to the sheet.  These include:

- Nicer looking Roll Templates for attacking and spells, including optional flavor text.
- An Initiative button to add you to the Turn Order.
- Tracking of unspent and spent experience points and IQ points to add in talent and attribute selection.
- An array of attack buttons at various to-hit amounts, to allow single-click attacks at various to-hit amounts.  You select your spell or weapon, then click the button you want.  There are tooltips for common situations such as rear and flank attacks.
- Tooltips on most captions and values.
- A repeating section just for equipment, including current count, weight per item.
- Description buttons to describe items/talents in the chat text.
- Gear buttons to pop open repeating sections to edit detailed descriptions.
- Weight tracking.  every item has a weight, and a checkbox for whether it is currently carried or not.  This is used to compute total weight and the Movement penalties, which are automatically applied.

Player data is preserved.  I kept all the old names of attributes.
Layout is also nicer looking, using a grid layout and some formatting.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by jaemzfleming** [comment]
Hello @nmbradley, thanks for the merge.  Hey I just checked in-game and I'm not seeing any of my changes when I select "The Fantasy Trip" as my character sheet.  How do I see the changes (I mean, without cutting and pasting into custom)  Also, I wasn't expecting the pull to happen so quickly, and I actually added some more features today.   Should I just make a new pull request?

**Comment by nmbradley** [comment]
Hi @jaemzfleming 

I'll investigate why these updates are not showing up on the service and get back to you.

Yes, please create a new pull request for any further changes.

**Comment by nmbradley** [comment]
One further point: if you're not ready for a PR to be merged yet, you should be able to [indicate that it's a draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft).

Let me know if you have any problems doing this!

**Comment by jaemzfleming** [comment]
Thanks for looking into that.  And I'll do the draft thing, that sounds smart.

**Comment by jaemzfleming** [comment]
Oh, @nmbradley it looks like the sheet.json had a trailing comma after the "instructions" field.  This was failing validation.  Maybe that's why it's not showing up?  I've fixed it in my new pull request, which I've marked as draft.  Maybe I'll un-mark it as draft then since it has that fix and do a new pull request next week for any other straggling features.

**Comment by jaemzfleming** [comment]
Hi @cjstoddard and @clevett, not sure if this is the right way to alert you, but I've made some improvements to The Fantasy Trip character sheet, they've been merged and you can grab them to see if you'd like.   I'm new to GitHub, not sure exactly where/how discussions should take place.

**Comment by cjstoddard** [comment]
I am glad to see others working on improvements to this character sheet. Honestly, what I did was pretty crude and my intention was just to get something onto Roll20 hoping others people with actual skills would improve on it.

**Comment by jaemzfleming** [comment]
Mission accomplished then!  It provided a great launching point.

**Pull request merged**
