### PR TITLE
Weaverdice

### PR DESCRIPTION
**Pull request by Anduh**
Character sheet for Weaver Dice, based on the superhero webserial by John C. "Wildbow" McCrae,
converted from the original sheet to Roll20 by Andreas J.

Subreddit for the game: https://www.reddit.com/r/Weaverdice/

This is the horrible first draft, only for the truly desperate. Made on request

### CODE REVIEW

**Comment by wing-it** [comment]
Just wanted to let you know, I changed your sheet to make it work correctly. You can look it up on the master branch here to see what I did, but here's a quick run down of the changes I made:

- I added a preview image, taken from [your reddit post](https://www.reddit.com/r/Weaverdice/comments/7ei5qs/roll20_char_sheet_v01_for_weaver_dice_will_go/).
- I changed your image links. Note that relative links, i.e. `images/image2.png` won't work here, I linked to the raw images from github (`https://raw.githubusercontent.com/Roll20/roll20-character-sheets/master/Weaverdice/images/image2.png`)
- I added `.sheet-` in front of your class names in the css, so `.charsheet .c12` becomes `.charsheet .sheet-c12`. This is required so that the styles get properly applied.

The final result ended up looking slightly different from the preview image from reddit, so you may want to go look at it and make sure everything is working as intended. None of my changes should have anything to do with how the sheet works, they just made sure that the styles you already defined got used.

**Comment by Anduh** [comment]
Thanks! I don't care if it looks different, I just want the first version out so people can use it, I can fix layout problems later. Do publish it if you still can.

**Comment by Anduh** [comment]
I'm sorry I didn't notice your message here, I hope that's not what delayed pushing the updates live.Don't have a pro accoint so can't see how the changes look there, sorry.

I noticed some changes to another sheet isn't on roll20 even if you merged all request. I saw that I missed adding ”sheet-” to the html and made a new push request but that can wait to next week, I and a few others would apprichiate it the sheet goes live in any for this week, looks can be fixed later.

**Comment by wing-it** [comment]
No worries, we had to delay our normal code push by a day, it should be up in a few hours.

**Pull request merged**
