### PR TITLE
[Star War Saga Edition] Minor appearance tweaks, Defense Notes

### PR DESCRIPTION
**Pull request by LilLiteralist**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description

Minor appearance tweaks. Added new image files that better mimic the proper logo, including ones to be used with dark mode.
Next update, will change the links to match the location of the files in GitHub.

### CODE REVIEW

**Comment by NorWhal** [comment]
Hello @LilLiteralist,

I see that the sheet has been making use of the logo for some time, but this sheet is not listed as having the proper authorizations to be using trademarked content like the Star Wars Logo. I'm marking this PR as "In Review" until we're sure that it's allowed to be on the sheet. 

Thanks

**Comment by NorWhal** [comment]
Hi again, 

If you have approval from Lucasfilm/Disney the logo can remain in place, but otherwise I'm sorry to say that I cannot approve this PR until the logos are removed from the sheet.  While this was allowed when the sheet was originally added to the library, [our policy ](https://help.roll20.net/hc/en-us/articles/360037773453-Minimum-Requirements-Best-Practices)has changed since.

**Comment by LilLiteralist** [comment]
That's a bummer, though understandable. I do want to ask some questions, though.

Is it possible to say Star Wars on the sheet at all? It's my understanding that the name itself is trademarked, though it's kinda in the name of the system... 

Does this mean that no future pull requests can be done for the sheet until the logo is removed, or just that no pull requests can be done to update the logo?

**Comment by nmbradley** [comment]
Hi @LilLiteralist 

We've contacted our licensing team for a comment on the first question, but I would assume in this context it would fall under Fair Use in a way that a logo/trade dress would not. It's the name of the thing.

Unfortunately, the logo must be removed before any other changes can be made. Ultimately, if it isn't removed in a timely fashion, we'll be compelled to remove it ourselves. For obvious reasons, we'd prefer not to do this.

I'm sorry for the situation, licensing is not a fun endeavor :(

**Comment by LilLiteralist** [comment]
All right, thanks for your patience. One last question: Since fonts can't be copyrighted, would it be permissible to say "Star Wars Saga Edition" in a (publicly available) font that resembles (but doesn't exactly depict) the font used in the Star Wars logo, such as Star Jedi?

**Comment by BronsonHall** [comment]
Hey @LilLiteralist 

Using a publicly available font like Star Jedi in images, to make your own logos, should be fine - though we'd advise attributing the font in the readme/wiki, given how close it is to the original.

**Pull request closed without merging**
