### PR TITLE
Everyone Is John

### PR DESCRIPTION
**Pull request by sydearly**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [y ] Does the pull request title have the sheet name(s)? Include each sheet name. 
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [y ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Stexinator** [comment]
You should split your commit according to the sheets you worked on

**Comment by sydearly** [comment]
> You should split your commit according to the sheets you worked on

I agree, I only uploaded the Who stuff because of merge conflicts. My fork was somehow behind. The only actual changes to the master are the new EIJ sheet.

**Comment by mperes** [comment]
Hello there @sydearly, could you split your PR into multiple ones? There are modifications for 3 different character sheets into this pull request. Thanks!

**Comment by sydearly** [comment]
Think it is all fixed in https://github.com/Roll20/roll20-character-sheets/pull/8068 
@mperes

**Pull request closed without merging**
