### PR TITLE
"Cyberpunk Red Jumpstart Kit B7DX": A character sheet for use with Cyberpunk RED Jumpstart Kit

### PR DESCRIPTION
**Pull request by drewctaylor**
This is a character sheet for use with Cyberpunk RED Jumpstart Kit; it supports the following

* Rolls for statistics and skills.
* Rolls for initiative.
* Tracking luck points.
* Rolls for reputation; tracking reputation.
* Rolls for grappling attacks.
* Rolls for melee attacks, targeting head or body.
* Rolls for ranged weapons, targeting head or body, tracking difficulty at range; for those capable of a three-round
  burst, rolls for three-round burst and suppressive fire.
* Tracking hit points.
* Tracking head and body armor stopping power.
* Tracking grappled and prone conditions; modifying rolls for grappled condition.
* Rolls for death saves; tracking death saves; modifying rolls for wound states.
* Damage calculation.
* Tracking cyberware; modifying rolls for cyberware.

### CODE REVIEW

**Comment by drewctaylor** [comment]
### Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [X] Does the pull request title have the sheet name(s)? Include each sheet name.

- [ ] Is this a bug fix? 

- [ ] Does this add functional enhancements (new features or extending existing features) ?

- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ?

- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?

- [X] If this is a new sheet, did you follow Building Character Sheets standards ?

If you do not know English. Please leave a comment in your native language.

**Comment by mperes** [comment]
Hey there @drewctaylor, before I proceed with merging you PR, I need to ask you: Are there any major difference in the rules between Cyberpunk Red JK and the other version of cyberpunk red sheets that already exist in our repo? From my understanding, the jumpstart is just a resume to start playing faster a thus you would be able to play it using one the existing sheets, right? I am asking you that because while there have been duplicate public sheets allowed in the past, going forward Roll20 wants to limit this practice. Thanks for all the work you do?

**Comment by Anduh** [comment]
> From my understanding, the jumpstart is just a resume to start playing faster a thus you would be able to play it using one the existing sheets, right? 

The Jumpstart was published as a kinda-playtest game, 1 year before the full game.

There are already two Jumpstart **and** two Cyberpunk Red proper sheets in the repo, so it's really getting crowded for this single game edition.

**Comment by drewctaylor** [comment]
I've run games using Rúnar B.'s sheet, which is based on the Jumpstart Kit.

Compared to that sheet, this sheet adds the following features:

* It lists all skills; automatically populates the default value for skills based on their statistic; and allows players to modify skills based on their level.
* It tracks reputation.
* It adds rolls for grappling, choking, throwing, and brawling.
* It distinguishes between melee attacks, ranged attacks, and ranged attacks with weapons capable of 3-round bursts.
* For all attacks, it allows the player to choose between body attacks and head attacks (and automatically applies -6 penalty).
* For brawling and melee attacks, it produces two attack and two damage rolls, as the player may make two attacks per action.
* For ranged attacks, it allows the player to record the difficulty value at distance for each weapon.
* For ranged attacks with weapons capable of 3-round bursts, it allows the player to choose a three-round burst, which produces three damage rolls.
* It allows the player to mark themselves as grappled, and it applies the appropriate roll modifier (-3) if so.
* It tracks whether the player is seriously or mortally wounded, and it applies the appropriate roll modifier (-3, -5) if so.
* It includes a damage calculator, which automatically reduces hit points and armor stopping power based on the number of hits, the damage location, and the damage type.
* When adding cyberware, it allows the player to indicate the statistic, skill, or other attribute it modifies and by how much; for cyberware that modifies all rolls with that attribute, it applies the cyberware bonus to rolls with that attribute; for cyberware that modifies only some rolls with that attribute, it applies the attribute as a bonus to rolls with that cyberware.
* It includes simple buttons for resetting luck points, hit points, armor stopping power, and death saves.

I am not as familiar with Gerdofal's sheet; however, at a glance:

* It handles critical successes and critical failures as described in the Jumpstart Kit Rulebook.
* It adds rolls for grappling, choking, and throwing.
* For all attacks, it allows the player to choose between body attacks and head attacks (and automatically applies -6 penalty).
* For brawling and melee attacks, it produces two attack and two damage rolls, as the player may make two attacks per action.
* For ranged attacks, it allows the player to record the difficulty value at distance for each weapon.
* For ranged attacks with weapons capable of 3-round bursts, it allows the player to choose a three-round burst, which produces three damage rolls.
* It allows the player to mark themselves as grappled, and it applies the appropriate roll modifier (-3) if so.
* It tracks whether the player is seriously or mortally wounded, and it applies the appropriate roll modifier (-3, -5) if so.
* It includes a damage calculator, which automatically reduces hit points and armor stopping power based on the number of hits, the damage location, and the damage type.
* When adding cyberware, it allows the player to indicate the statistic, skill, or other attribute it modifies and by how much; for cyberware that modifies all rolls with that attribute, it applies the cyberware bonus to rolls with that attribute; for cyberware that modifies only some rolls with that attribute, it applies the attribute as a bonus to rolls with that cyberware.
* It includes simple buttons for resetting luck points, hit points, armor stopping power, and death saves.

I'd say the biggest value this sheet offers over the existing sheets are

* Automatic application of cyberware bonuses to appropriate rolls.
* Automatic application of grappling, seriously wounded, and mortally wounded penalties to appropriate rolls.
* Distinction between attacks; appropriate application of penalties for attacks; convenience rolls for attacks; difficulty values for ranged attacks.
* Damage calculator.

**Comment by mperes** [comment]
I see. Instead of creating another sheet, could you collaborate to implement the new features you've mentioned above on top of an existing sheet, @drewctaylor

**Comment by drewctaylor** [comment]
No, I can't. As you can see, these are significant changes, and they would radically alter the existing sheets. I'm not comfortable making those changes. And, honestly, I'm now concerned that they'd simply be rejected.

**Comment by nmbradley** [comment]
Hi Drew,

Regrettably, given that this is a very well designed sheet, I'm going to have to reject this PR as there are so many Cyberpunk Red sheets already in the repository. We strive to have a single sheet per game, and as you can see, this rule has already been broken in the instance of this game. 

I'm sorry that this is the outcome, and would hope that there would be elements of this sheet that you could contribute towards the existing sheets. But, I will understand if not.

Apologies.

**Comment by aryairani** [comment]
Oh bummer, I was looking forward to using this.

**Pull request closed without merging**
