### PR TITLE
Low Fantasy Gaming changes for luck attribute

### PR DESCRIPTION
**Pull request by dedurrett**
## Changes / Comments

Luck is a special attribute that functions a little differently from the rest. I've taken away a few fields that are not associated with Luck, modified the roll template to account for these changes, and added a dropdown for luck (attribute) saves. New column width style associated with luck added to css as well.

### CODE REVIEW

**Comment by dedurrett** [comment]
Still not a github expert; not sure what is up with the first two commits. One is old, and the other has no diffs? I'm trying to commit the changes to Luck Attribute diffs.

**Comment by Anduh** [comment]
Is the end result what you want? Of so, doesn't matter much. The commits looks differently bc you submit them directly from your master branch.

**Comment by dedurrett** [comment]
Yes, I think the end result will be the same. Thanks for taking a look; appreciate what you do!

**Comment by dedurrett** [comment]
Added solution as requested per:
[Low Fantasy Gaming] Initiative: suggested changes. #4986
Initiative now has a checkbox toggle for Classic vs Deluxe roll method. Deluxe is checked by default.

In regards to:
[Low Fantasy Gaming] Crit damage: Has to be filled manually. #4985
Without a way to evaluate the maximum result of a roll expression I don't know how to parse and evaluate it myself. Suggest closing this request as I will not be able to fulfill it.

**Comment by dedurrett** [comment]
added default value for hidden init toggle attribute

**Comment by clevett** [comment]
@dedurrett Thanks for the detailed comments and following up on those Issues.

**Pull request merged**
