### PR TITLE
Add Pugmire character sheet

### PR DESCRIPTION
**Pull request by IuryAlves**
## Changes / Comments

Add new character sheet for [Pugmire RPG](https://www.realmsofpugmire.com/)

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Review by Anduh — CHANGES_REQUESTED** [review]
Submitting new sheets using `<table>` elements in sheet design, doesn't comply with minimum code requirement, and is likely to be rejected/postponed by Roll20.

**Comment by IuryAlves** [comment]
Thanks for the feedback @Anduh. 

I am not using `table` for layout. The usage of `tables` elements in the` html `is for creating tabular data, which is allowed by Roll20 docs. See attachments:

image

image

**Comment by mperes** [comment]
Hey @IuryAlves could you do some refactoring in your code to use flexbox instead of tables to layout those section? We are trying to avoid using table for anything but simple tabular data and you have a couple of interactive elements in there like buttons and checkboxes.

**Comment by IuryAlves** [comment]
Hey @mperes I refactored the code to use flexbox instead of tables.

**Pull request merged**
