### PR TITLE
New sheet (french) "Cahiers du Vastemonde" + New sheet (french) for "Dungeon World" + Savage Worlds French v1.4 + Cypher System english and french v1.6 + Portes Monstres Tresors v4.1

### PR DESCRIPTION
**Pull request by NathaTerrien**
* New french sheet for "Cahiers du Vastemonde"
* New french sheet for "Dungeon World"
* Savage Worlds french 1.4: new Deadland Reloaded optional style, NPC / Extra display, new raw roll
option and lots of other stuff.
* Cypher System english and french v1.6 : Cosmetic changes, to ease access to the delete button on repeatable sections, and diminish repeatable sections line height.
* Portes Monstres Tresors v4.1 : spell description can be enlarged/reduced

### CODE REVIEW

**Comment by pjbehr87** [comment]
Hey, thanks for all of your work creating and maintaining all of these sheets. If it's not too much work, could you possibly break up your pull requests by sheet, it would make it a whole lot easier for me to read and approve changes. Also, if one of these has an issue I would have to revert all 5 sheet additions/changes, rather than just reverting changes to a single sheet. Thanks!

**Comment by NathaTerrien** [comment]
Hi @pjbehr87 
You're welcome (though I do mostly french stuff ;) ).
I agree with you, especially if there's a problem on one pull resquet. You're totally right.
But the problem is : I don't know how I can make separated pull requests between two of your "commit fests" ;). Create as many forks as sheets I created/maintain ?

**Comment by pjbehr87** [comment]
I’ve never really dealt with Pull Requests from the other side, but yeah that sounds like it would be your best option. I didn’t realize you couldn’t just open different PRs for different commits. If that’s too much of a hassle, then don’t worry about it, it’s just a little messy on my end trying to scroll through 20 pages of changes at once.

**Comment by NathaTerrien** [comment]
@pjbehr87 : after doing a bit of googling, it seems possible to open different PRs for different commits if using different branches of my own fork. I'll try that next time.

**Pull request merged**
