### PR TITLE
Major Update SR6thEdition

### PR DESCRIPTION
**Pull request by yagrima**
## Changes / Comments
**RENAMED from SR6D to SR6 in general**
Changed native language to English
Fixed a lot of existing bugs
Started to implement Matrix functionality
Cared for DE, EN, ES (thanks for providing Andres Martinez!) translation files

### CODE REVIEW

**Comment by mperes** [comment]
@yagrima you PR has some conflics, also it includes changes to translation files. We would not deny your Pull Request, but we would prefer sheet contributors use Crowdin for translations. Please email Cassie at cassie@roll20.net and she will get you an invite to our Crowdin. Be sure to include the languages you would like to translate, and please use Crowdin for future translation updates! Thanks for all you do!

**Comment by yagrima** [comment]
What do you suppose me to do now? I already have an CrowdIn invite and want to see the sheet updated.

 

Best wishes




Gesendet: Montag, 02. November 2020 um 21:19 Uhr
Von: "Miguel Peres" <notifications@github.com>
An: "Roll20/roll20-character-sheets" <roll20-character-sheets@noreply.github.com>
Cc: "yagrima" <avalia@gmx.net>, "Mention" <mention@noreply.github.com>
Betreff: Re: [Roll20/roll20-character-sheets] Major Update SR6thEdition (#7588)


 

@yagrima you PR has some conflics, also it includes changes to translation files. We would not deny your Pull Request, but we would prefer sheet contributors use Crowdin for translations. Please email Cassie at cassie@roll20.net and she will get you an invite to our Crowdin. Be sure to include the languages you would like to translate, and please use Crowdin for future translation updates! Thanks for all you do!

**Comment by mperes** [comment]
Dear @yagrima your PR has a conflict within "Shadowrun6th-German/translations/es.json" which needs to be resolved before I can merge it. Please rebase you PR against last Master and fix this issue. If you are unsure how to do this, take a look at the Git documentation.

**Comment by yagrima** [comment]
As I am not that used to all the Git stuff. Can I just make another PR without the es.json?

 

Regards.

 
 

Gesendet: Montag, 09. November 2020 um 12:45 Uhr
Von: "Miguel Peres" <notifications@github.com>
An: "Roll20/roll20-character-sheets" <roll20-character-sheets@noreply.github.com>
Cc: "yagrima" <avalia@gmx.net>, "Mention" <mention@noreply.github.com>
Betreff: Re: [Roll20/roll20-character-sheets] Major Update SR6thEdition (#7588)


 

Dear @yagrima your PR has a conflict within "Shadowrun6th-German/translations/es.json" which needs to be resolved before I can merge it. Please rebase you PR against last Master and fix this issue. If you are unsure how to do this, take a look at the Git documentation.

**Comment by mperes** [comment]
Dear @yagrima, yes. That should be ok, once that is done I can merge the new PR and delete this one.

**Pull request closed without merging**
