### PR TITLE
[Mothership Official] Add modifier prompt and correct dice type

### PR DESCRIPTION
**Pull request by itsPizzaTom**
## Changes / Comments
Three changes have been made to rolls in this sheet. First, modifier prompts are now on all rolls, allowing users to input modifiers for the roll's Target. Second, the dice type has been corrected. Initially it was a d100 (range of 1 to 100), however Mothership uses a d% (range of 0 to 99). This correction manifested as replacing instances of 1d100 with 1d100-1 to get the proper range of values. Finally, the critical successes and critical failures have been updated to reflect the new dice range. CS is now 0 instead of 1, and CF is now 99 instead of 100.

I would also like to apologize for the additional differences due to whitespace changes.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
Hey @nmbradley, are you game with this PR?

**Comment by itsPizzaTom** [comment]
@nmbradley I just found your issue tracker specific to the sheet, and it seems this would address (if not outright solve) issue #6, #7, #9, #13, and #24 by letting users enter in all those modifiers themselves.

**Comment by nmbradley** [comment]
Hi Tom, 

Many thanks for the pull request, unfortunately I'm going to have to close this without merging. There's absolutely nothing wrong with the intent of your changes, but unfortunately the sheet html is compiled from pug, meaning that the next time it's updated, your changes would be overwritten. 

I'm going to open a ticket to translate your changes into the pug files and I will try to get to it this weekend.

Very best,

Nic

**Comment by itsPizzaTom** [comment]
Sounds good @nmbradley. I'll make sure to change pug and scss files. 

In the future,  would you prefer I make changes to your MoSh character sheet repo (this one: https://github.com/nmbradley/mothership-roll20sheet), or will changes to the pug/scss files here be fine?

**Pull request closed without merging**
