### PR TITLE
Arianrhod2 (new sheet)

### PR DESCRIPTION
**Pull request by tifereth**
## Changes / Comments
Create Arianrhod RPG 2nd Edition (F.E.A.R) Sheet

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by tifereth** [comment]
There are some typos in file names.

**Comment by Anduh** [comment]
The sheet will likely to be turned down for using html tables extensively, which is specifically mentioned in the minimum requirements.

**Comment by tifereth** [comment]
> The sheet will likely to be turned down for using html tables extensively, which is specifically mentioned in the minimum requirements.
> 
> * https://wiki.roll20.net/Building_Character_Sheets#2._Good_Code

Understand. My reference was the old one using table. 
I`ll change tables to grid.

**Comment by Anduh** [comment]
Yes, old sheets are grandfathered but the rules apply to all new sheets.

**Comment by oliviakristiansen** [comment]
Hello! Yes, Anduh is correct regarding the use of tables, but your idea to move to a grid is a great idea! Please update and it will be merged next week.
Additionally, your Pull Request includes changes to translation files. We will not deny your Pull Request because of that, but we would prefer sheet contributors use Crowdin for translations. Please email Cassie at cassie@roll20.net and she will get you an invite to our Crowdin within 48 hours. Please use that for future translation updates! Thanks for all you do!

**Comment by tifereth** [comment]
> Hello! Yes, Anduh is correct regarding the use of tables, but your idea to move to a grid is a great idea! Please update and it will be merged next week.
> Additionally, your Pull Request includes changes to translation files. We will not deny your Pull Request because of that, but we would prefer sheet contributors use Crowdin for translations. Please email Cassie at [cassie@roll20.net](mailto:cassie@roll20.net) and she will get you an invite to our Crowdin within 48 hours. Please use that for future translation updates! Thanks for all you do!

Ok. I`ll use Crowdin. Sent an email to Cassie according to your advice. Thanks.

**Comment by tifereth** [comment]
All tables are replaced by grid. Please review again.

**Pull request merged**
