### PR TITLE
CoC_7th_Ed. Fix 

### PR DESCRIPTION
**Pull request by orphs**
## Changes / Comments
The out-of game options seemed to not be working, so they are all now visible in-game, on the top-section of the sheet.  As  in-game options, they all appear to be working as intended.

Sorry for the mess-up, can't find what went wrong.

### CODE REVIEW

**Comment by clevett** [comment]
Greetings @orphs 

Are the out of game options breaking anything? Are they just not working? If they are just not working then I will just update the CSS & HTML as that can be done easier on our end. 

Thanks,
Cassie

**Comment by orphs** [comment]
Hey @clevett 
The out of game options are working only on newly created games, the first time you select them. Any change after that reverts the sheets to their default selection, wich is something that will cause confusion and is not really user friendly. 
Updating the CSS and HTML will fix the problem to my knowlege.

Ill remove the other fixes and re-push them during the week.

Again, sorry for the mess.

**Comment by orphs** [comment]
@clevett 

If you havent done it already, it would be prefferable if I deleted this push and pushed another update that just makes the checkboxes visible in the in-game sheet, because at this current push, if the translations arent merged, some conflicts might exist.

**Comment by clevett** [comment]
Go ahead. I haven't merged this.

**Comment by orphs** [comment]
Sure, thank you very much.

**Pull request closed without merging**
