### PR TITLE
Attempt t20, 7th Sea

### PR DESCRIPTION
**Pull request by CoalPoweredPuppet**

### CODE REVIEW

**Comment by CoalPoweredPuppet** [comment]
I have no idea what the refs/remotes/Roll29/Master are, nor how to remove them.

**Comment by pjbehr87** [comment]
We already have a 7th Sea sheet. Is it safe to assume that since this is 2e that the other sheet is for 1e? I want to make sure everything is labeled correctly.

**Comment by CoalPoweredPuppet** [comment]
Yes, this is 2e.  Something in my system is saying the commit for 2e is already there, but that pull request was closed to to issues on my end.

**Comment by CoalPoweredPuppet** [comment]
Thank you!

**Pull request merged**
