### PR TITLE
CoC7 Sanity calculation

### PR DESCRIPTION
**Pull request by JaegersNet**
Added automatic calculation of 20% Sanity (current / total)

### CODE REVIEW

**Comment by orphs** [comment]
Hey there @JaegersNet ,
 it seems like you have been using a far previous version of the CoC 7th Ed. Sheet as a base for your updates. If you take a look at the current state of the sheet you will find that many of the things you want to implement are already in place (apart from the 20% Sanity calculation). 
Sad to say, that merging your commits as they are atm, would revert the sheet back about a year or so.

Where did you get a copy of the sheet's old code? (just out of curiosity)

**Comment by JaegersNet** [comment]
Uh, that‘s strange. I was sure to work on a fresh copy. Strange, but I‘ll have a look at it later.

**Comment by Anduh** [comment]
The problem comes from JaegersNet not updating his fork of the sheet repo, and working on a old version
image

**Comment by JaegersNet** [comment]
Indeed, something went wrong and I was working on an old version :-( I'm very sorry. 

I'll add the 20% calculation these days to the current version.

BTW: As the international version of the CoC7 sheet includes also the German language, the German only sheet could be archived. (IMHO)

**Comment by Anduh** [comment]
> Indeed, something went wrong and I was working on an old version :-( I'm very sorry.

I guess that means this PR could be closed considering it can't be used, and you'll later make a new one when you worked on a up-to-date version?

**Comment by JaegersNet** [comment]
Closed due to obsolence. Will be renewed after changes are implemented in the new sheet.

**Pull request closed without merging**
