### PR TITLE
Cyberpunk 2k20 spellcheck/translation

### PR DESCRIPTION
**Pull request by velvetsanity**
Completed (as far as I can tell) spellchecking and translating fiddly bits from french to english

### CODE REVIEW

**Comment by Solarswordsman** [comment]
Hi @velvetsanity, you're changing the names of a few attributes here, which will cause the loss of some data for users if the data isn't transitioned properly into the new attributes as a versioning update.  Is this something you've already done?  If not, please either rename the attribute names back to what they were or provide a sheet worker that transitions the previous values to the new ones.

Otherwise, the update looks good, though I would encourage the addition of `data-i18n` attributes so that translation of the sheet can be flexible and not stuck to a single language.

Thanks!

**Comment by velvetsanity** [comment]
My intent was to correct what appeared to be the use of French terms and/or spelling for a few items that are visible on the sheet (skill names and such) in-game when everything else on the sheet was in English. I’ll go back and revert those items I shouldn’t have changed.

**Comment by velvetsanity** [comment]
@Solarswordsman Ok, reverted those items in my copy, do I need to make a new pull request or will it pull the latest version automatically?

**Comment by Solarswordsman** [comment]
It looks like those changes were committed directly to this branch, so there's nothing else you need to do; I will merge this pull request at the next opportunity.  Thank you!

**Comment by velvetsanity** [comment]
Sorry, missed one of the attributes at first. Fixed now.

**Comment by velvetsanity** [comment]
@Solarswordsman Am I doing this right?

<link rel="stylesheet" type="text/css" href="Cyberpunk%202k20.css"/>
<div class="sheet-body">
    <input class="sheet-pc" type="radio" value="pc" name="attr_pcToNpc" checked />
    <strong class="sheet-strong-pc" data-i18n="player" >Player</strong>
    <input class="sheet-npc" type="radio" value="npc" name="attr_pcToNpc" />
    <strong class="sheet-strong-npc" data-i18n="non-player_character" >NPC</strong>
    <input class="sheet-meta" type="radio" value="meta" name="attr_pcToNpc" />
    <strong class="sheet-strong-meta" data-i18n="meta_characters" >Meta Characters</strong>


    <input type="radio" style="float:right; display:block;margin-right:5px;" name="attr_FFNtoFSN" class="sheet-show-FSN" value="1"/>
    <i class="sheet-strong-option" data-i18n="saturday_night_scuffle" >SNS:</i>
    <div class="sheet-strong-option-label sheet-strong-option-FSN" data-i18n="use_SNS" >Use Saturday Night Scuffle combat system (Cybergeneration combat system).</div>
    <input type="radio" style="float:right; display:block;margin-right:5px;" name="attr_FFNtoFSN" class="sheet-show-FFN" value="0" checked/>
    <i class="sheet-strong-option" data-i18n="friday_night_firefight" >FNFF:</i>
    <div class="sheet-strong-option-label sheet-strong-option-FFN" data-i18n="use_FNFF" >Use Friday Night Fire Fight combat system (Cyberpunk 2020 combat system).</div>
    <input type="checkbox" style="float:right; display:block;margin-right:5px;" name="attr_show-repcontrol" class="sheet-show-repcontrol"/>
    <i class="sheet-strong-option" data-i18n="edit_mode">Edit Mode:</i>
    <div class="sheet-strong-option-label sheet-strong-option-repcontrol" data-i18n="use_edit_mode" >Edit mode: You can see add and delete option on fieldset.</div>

    <div class="sheet-sectionM">
        <h1 style="position:absolute;top:50px;left:150px;" data-i18n="meta_characters" >Meta Characters</h1>

**Comment by velvetsanity** [comment]
@Solarswordsman Want to make sure I'm adding the translation bits correctly...
`<link rel="stylesheet" type="text/css" href="Cyberpunk%202k20.css"/>
<div class="sheet-body">
    <input class="sheet-pc" type="radio" value="pc" name="attr_pcToNpc" checked />
    <strong class="sheet-strong-pc" data-i18n="player" >Player</strong>
    <input class="sheet-npc" type="radio" value="npc" name="attr_pcToNpc" />
    <strong class="sheet-strong-npc" data-i18n="non-player_character" >NPC</strong>
    <input class="sheet-meta" type="radio" value="meta" name="attr_pcToNpc" />
    <strong class="sheet-strong-meta" data-i18n="meta_characters" >Meta Characters</strong>


    <input type="radio" style="float:right; display:block;margin-right:5px;" name="attr_FFNtoFSN" class="sheet-show-FSN" value="1"/>
    <i class="sheet-strong-option" data-i18n="saturday_night_scuffle" >SNS:</i>
    <div class="sheet-strong-option-label sheet-strong-option-FSN" data-i18n="use_SNS" >Use Saturday Night Scuffle combat system (Cybergeneration combat system).</div>
    <input type="radio" style="float:right; display:block;margin-right:5px;" name="attr_FFNtoFSN" class="sheet-show-FFN" value="0" checked/>
    <i class="sheet-strong-option" data-i18n="friday_night_firefight" >FNFF:</i>
    <div class="sheet-strong-option-label sheet-strong-option-FFN" data-i18n="use_FNFF" >Use Friday Night Fire Fight combat system (Cyberpunk 2020 combat system).</div>
    <input type="checkbox" style="float:right; display:block;margin-right:5px;" name="attr_show-repcontrol" class="sheet-show-repcontrol"/>
    <i class="sheet-strong-option" data-i18n="edit_mode">Edit Mode:</i>
    <div class="sheet-strong-option-label sheet-strong-option-repcontrol" data-i18n="use_edit_mode" >Edit mode: You can see add and delete option on fieldset.</div>

    <div class="sheet-sectionM">
        <h1 style="position:absolute;top:50px;left:150px;" data-i18n="meta_characters" >Meta Characters</h1>`

**Comment by velvetsanity** [comment]
<input class="sheet-pc" type="radio" value="pc" name="attr_pcToNpc" checked />
    <strong class="sheet-strong-pc" data-i18n="player" >Player</strong>
    <input class="sheet-npc" type="radio" value="npc" name="attr_pcToNpc" />
    <strong class="sheet-strong-npc" data-i18n="non-player_character" >NPC</strong>
    <input class="sheet-meta" type="radio" value="meta" name="attr_pcToNpc" />
    <strong class="sheet-strong-meta" data-i18n="meta_characters" >Meta Characters</strong>


    <input type="radio" style="float:right; display:block;margin-right:5px;" name="attr_FFNtoFSN" class="sheet-show-FSN" value="1"/>
    <i class="sheet-strong-option" data-i18n="saturday_night_scuffle" >SNS:</i>
    <div class="sheet-strong-option-label sheet-strong-option-FSN" data-i18n="use_SNS" >Use Saturday Night Scuffle combat system (Cybergeneration combat system).</div>
    <input type="radio" style="float:right; display:block;margin-right:5px;" name="attr_FFNtoFSN" class="sheet-show-FFN" value="0" checked/>
    <i class="sheet-strong-option" data-i18n="friday_night_firefight" >FNFF:</i>
    <div class="sheet-strong-option-label sheet-strong-option-FFN" data-i18n="use_FNFF" >Use Friday Night Fire Fight combat system (Cyberpunk 2020 combat system).</div>
    <input type="checkbox" style="float:right; display:block;margin-right:5px;" name="attr_show-repcontrol" class="sheet-show-repcontrol"/>
    <i class="sheet-strong-option" data-i18n="edit_mode">Edit Mode:</i>
    <div class="sheet-strong-option-label sheet-strong-option-repcontrol" data-i18n="use_edit_mode" >Edit mode: You can see add and delete option on fieldset.</div>

    <div class="sheet-sectionM">
        <h1 style="position:absolute;top:50px;left:150px;" data-i18n="meta_characters" >Meta Characters</h1>

**Comment by Solarswordsman** [comment]
Indeed, the scope of an element with the `data-i18n` tag is such that everything within that element is replaced by the contents of the translation. It looks like you've got that down, so carry on with your translation support efforts.  Let me know if you have any other problems.

**Pull request merged**
