### PR TITLE
Vampire v5 Sheet

### PR DESCRIPTION
**Pull request by chrisleaptrott**
Vampire V5 sheet ready for 'first build' release.

### CODE REVIEW

**Comment by jgoppert** [comment]
@chrisleaptrott We apparently both did this at the same time. I have a custom sheet I've been using and is easier to maintain than the old V20 stuff on here, never got merged because making it backwards compatible sounded like too much work. Now that we have a chance to start fresh on the 5th edition, I'd like to bring in my changes.

It allows auto calculation of XP, so it really makes it easy for players and storytellers. The formatting is also cleaned up.

https://github.com/Roll20/roll20-character-sheets/pull/4031

**Comment by chrisleaptrott** [comment]
Oh yeah, by all means dude....let's do it up. I just wanna get the best sheet we can have for V5 haha.

**Comment by Anduh** [comment]
I have a suspicion many prefer the boxes that have existed since earlier editions. Either way, it's good you started a dialogue for how you proceed with the sheets, as only one sheet will be approved.

Some layout things could be implemented as optional, with checkboxes to toggle things on/off for example.

**Comment by jgoppert** [comment]
@chrisleaptrott The XP solves the problem of your the storyteller and you want to create a 1000 XP elder on the fly. You don't really want to sit and count up the XP by hand, adding 5*level, it becomes very slow. Also for new characters, just being able to click on the sheet and them see the effect on XP makes it easier for them.

With respect to the box vs chart. I already have a dual checkbox controlled layout for all the other attributes that you can switch back and forth, maybe start up a game and check it out. The checkbox on the top right controls the layout.

Perhaps we can merge our sheets together and find something that will be best for the community, I think you will find it pretty easy to change mine. If you want to change the format of the attributes/skills for instance, you just have to change it in one spot in the V5e.jinja file, and the run V5e.py that outputs the V5e.html instead of copying and pasting it 24 times.

With regard to the health and willpower, we could also add a dual layout that allows the boxes for / X, this would be pretty easy to implement since it is similar to what I did for the attributes.

**Comment by jgoppert** [comment]
### Editing
For editing my sheet you don't need to know how to use python. You just edit the template file: V5e.jinja, it allows writing for loops to deal with the tedious parts. http://jinja.pocoo.org/docs/2.10/

If you want, just tell me what you want me to pull in from your sheet and I will merge them so you don't have to worry about it.

### Pushing

If we push before we merge this, then we won't have backwards compatibility for character sheets. Embedding all the data about whether points were spent via XP upgrade or base character points is something I think we need to get in before pushing to the community. I think my players really benefit from it. Also, the layout improvements and being able to make the character sheet tiny is really nice.

**Comment by chrisleaptrott** [comment]
Well man, I don't know what to tell you other than: If you take my sheet, show me what we need to change in some clear manner and we can then do whatever needs to be done to, IDK, add over the XP tracker here or something, that's fine. I just need a path and direction to move forward.

**Comment by jgoppert** [comment]
What I'm hearing from you is this:

1. Make it so you don't have to see any numbers.
2. Make the character sheet look like the original.

Let me know what else you want me to fix, then I can merge it and everyone will be happy.

**Comment by chrisleaptrott** [comment]
Okay, but wouldn't that very much mean that my several hours of editing this all together would basically come down to a glorified template for you?
Sorry if I'm getting the wrong idea here, but I don't really know what to do with this.

@Anduh what's the usual protocol with two sheets, say if we didn't merge?

**Comment by chrisleaptrott** [comment]
Honestly, also: This guy's sheet looks great too.....and I'm surprised he didn't submit a Push for it since he's listed as a sheet author. PRetty nice simple style

https://app.roll20.net/forum/post/6649241/vampire-v5-very-simple-sheety

**Comment by jgoppert** [comment]
@chrisleaptrott  I've been there and spent hours on the raw html, but I don't think that is a good reason to keep that approach. That is why I got fed up with it and used templates. How are we supposed to keep maintaining and updating a sheet that takes that long to edit. I'm trying to stick to the "don't repeat yourself" principle as much as possible. So whoever comes after us and needs to update the sheet can do it in minutes instead of hours.

That sheet looks pretty nice as well. Do you like the white color vs. yellow? Would be easy for me to switch out my text at the top for the logo. Then switch the humanity, willpower, hunger to boxes like that sheet.

**Comment by chrisleaptrott** [comment]
I think I'm done discussing this until I hear from @Anduh on what the SOP is moving forward honestly.

Thank you for your input.

**Comment by jgoppert** [comment]
OK, @Anduh I think our main question is whether we go with the template approach which requires more programming knowledge and has support for more advanced features like calculating xp, or do we stick with a sheet based on the existing vampire sheets with raw html.

I think either way the look of the sheet is fairly easy to modify and making it so there are no numbers is easy to do, so we are in agreement there.

**Comment by chrisleaptrott** [comment]
No, that is not my main question. My main question is what they normally do in the case of two sheets being submitted like this.

Please, let's hear a response before posting more.

Thank you.

**Comment by Anduh** [comment]
Roll20 will approve only one sheet, and as you two(and also Havoc) are concurrently working on separate ones, they will tell you to work it out among yourselves to a single sheet, so yes, @chrisleaptrott you two decide to push one sheet that you use as a base and improve upon it.

If one of you would have been quicker and got one sheet approved before the other appeared as a pull request, Roll20 would have told the author of the "new" sheet to instead improve/help with the established sheet. I'd say this is the first time there have been **three** sheets made within the same week, but I think we can discount Havoc's sheet he said: 
> `I've made a veeeeeeeery simple sheet. There are no rolls.`
That doesn't mean his sheet have nothing to contribute to whichever sheet you choose as the base for the sheet that will be approved.

**Comment by Machiavel77** [comment]
There is nothing wrong with this sheet, it is in the style of older vampire sheets, sure there are some formatting issues that need fixing and im sure they will be.
With that said i think a sheet that requires less programming knowledge to edit is probably a good thing.

**Comment by chrisleaptrott** [comment]
Thanks for the reply @Anduh . Honestly, At this point I'm quite okay with whatever @jgoppert would like to add to my sheet, or even adjust.
Chief reason is that my sheet being based on the ones that came before, thus is familiar (as 'lacking in advanced' options as it may be at the moment.)

I'd also refute the claim that updates would somehow take longer for some reason. Maybe, if something major were to happen, but Even at this point beyond a few minor layout things, I can't see any adjustments being needed.....again, too, someone coming in to fix that sheet behind me would have the whole of the Roll20 character sheet wiki to use vs having to deal with whatever new, secondary systems are in place here.

I'm not trying to be hard about all this, I'm not...but there is a lot to be said about the how things have been approached that personally bothers me. Not in the Roll20 system, mind you, but in how you've approached me here @jgoppert . You basically just assumed that we'd use your sheet, you keep doing the 'salesman' style of trying to get me to agree to something for you to change when I've had other questions and concerns, and in your last post you put 'words in my mouth' about what my question was to Anduh while also belittling my sheet (seemingly).

Had it been me to put in a push request, what 8 hours, after you....I'd have removed the request, checked your code, and then maybe (if I felt like it needed) approached you with humility about possibly using my code. I wouldn't have left the request up and then gone on and on about the superior nature of my sheet vs yours and this and that.

At the very least its bad form and I don't appreciate it.

If this wasn't your intention, okay...but that's my perspective of it.

Thank you.

**Comment by jgoppert** [comment]
I was trying to suggest we work together. I realize it is easy to get passionate about this stuff after you sink a lot of time in. My sheet has 5x less code to maintain and I'm a professional software developer, but if there isn't support for that, will close my PR and we can go with this.

**Comment by chrisleaptrott** [comment]
Okay.
I'm still more keen on going with the sheet I've posted, regardless of time sank, just simply because its based on existing sheets, styled like them already, already has the boxes and other bits, and it already looks like the sheet out of the book.

I think the XP automation thing you have is cool, and I think it would be a nice addition to a sheet, but I'm standing by my sheet, or if Havoc were to push one for his (with the edits for adding rolls that I've messaged him about since having rolls is pretty important I feel). That's my stance.

**Comment by Anduh** [comment]
_Opinion:_ I'd agree that a sheet requiring less programming knowledge might be preferable for in the long run, to lower the bar for future edits/fixes. Beyond any initial work on a sheet, further changes wouldn't involve "hours of works" unless you're talking about any the large monster-sheets like D&D5E/D&D3.5E/PF. But now that I've taken a look at both and considering things, I might be inclined to lean toward the generated sheet. I'm no real programmer yet so can't tell if it would be a wiser choice, I see the logic of both sides. Either way, people probably would prefer a sheet that have similar layout to the paper-version/old ones.

_Suggestion:_ Go with @jgoppert sheet. 

_Change:_
- correctly fill the sheet.json
- add logo & visual changes from the other sheet to have it look closer to the original sheets
- implement roll buttons
_Less Important, but people will request it at some point:_
- add note/ background text fields if they are missing
- add translation tags(like in the original), WoD games seem to have multilingual following on Roll20

If you go the other way around, it sounds like implementing the automated xp calculation and the switch for the doted/numeral view of the stats.

The sheet/game isn't too important for me, so won't spend much more time on this beyond my initial two cents, I hope you can work this out between yourselves, with or without external mediation. If you want others to join the discussion, start a thread in the forums.

**Comment by jgoppert** [comment]
OK. Will close mine then. The xp would be too big of a pain to bring over to that sheet

**Comment by chrisleaptrott** [comment]
Thank you for the help and input on things.

**Comment by jgoppert** [comment]
Feel free. Most of the math is in worker.js

**Comment by chrisleaptrott** [comment]
@Anduh since Jg has closed his request, I think this one is good to go. Got the alignment done as well as some 'quality of life' fixes. Will be looking at adding JG's XP tool as well as a better solution to the Hunger Dice mechanic (probably via script) as soon as we have some time on it.

**Comment by Anduh** [comment]
Yeah, seems so.

You should change the translation filetype to .json

I'd change the filenames to vampirev5.css and vampirev5.html for clarity's sake, kinda oxymoron to have filetype as the filename.

**Comment by chrisleaptrott** [comment]
@Anduh Yeah sorry, the redundant naming came from the personal repo and I didn't think to change it back.

Done and done, should be ready for you now.

**Comment by Anduh** [comment]
No problem, it's just slightly easier when one uses descriptive names on files. Oh and remember to update the file reference in the sheet.json, still pointing to the old names.

**Comment by chrisleaptrott** [comment]
@Anduh Done and done! :D

**Pull request merged**
