### PR TITLE
StarWars5e - NPC Layout Improvement

### PR DESCRIPTION
**Pull request by BE-Arbiter**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description

- Split design in two column
- Allow to link npc traits to chat
- Leading spaces corrections (Sorry about that)

Testing URL : https://app.roll20.net/join/17737343/0TAFzQ

### CODE REVIEW

**Comment by BE-Arbiter** [comment]
@Anduh Second try :')
I have provided a test-game for the changes.

**Comment by Anduh** [comment]
I'll see if I have time checking this over the weekend. If not, likely be the weekend after that.

If I haven't commented on this by Sunday at same o'clock, feel free to ping me again.

**Comment by NorWhal** [comment]
Hey @Anduh 

Tagging you here for a follow-up! The usual wait period we have is three weeks of no response. Please let us know if you need more time.

Nora

**Comment by Anduh** [comment]
Yeah I need time, hadn't found the time to review this properly, so was kicking it down the lane.
Should find the time to test it propely within the next 9 days.

**Comment by BE-Arbiter** [comment]
@Anduh Thank you :)

**Comment by kfroll20** [comment]
Hello @Anduh, 

Tagging you for another follow-up. Have you had a chance to take a look at this PR? Please let us know if we can move forward with merging these changes.

Thank you!

**Comment by BE-Arbiter** [comment]
Unfortunately not yet. 
I'm trying to have the rest of the community to have a look in the test game but, as fast as they were complaining when I broke something, there is not much activity to prevent the brokenness to happens =D

**Comment by NorWhal** [comment]
We've made this PR a draft while y'all are still in the testing phase of this project. Once @BE-Arbiter has finished with those tests and marked this as ready for review again, we’ll be looking to move forward with merging this PR. @Anduh if you have time to weigh in, we’d appreciate your insight, but we’ll merge as soon as Arbiter is happy with the testing.

**Comment by BE-Arbiter** [comment]
I am personally happy with the tests I made. I'm just not sure it's good practice x').

**Comment by Anduh** [comment]
will take a look this weekend

**Comment by NorWhal** [comment]
If there's no objections from @BE-Arbiter, we'll be merging this next Monday to give @Anduh one last weekend for review

**Comment by BE-Arbiter** [comment]
No objections

**Comment by Anduh** [comment]
@BE-Arbiter High possibility something went wrong with the sheet update, based on timing: https://www.reddit.com/r/sw5e/comments/1gpwii6/roll20_sheet_issue/

Sorry I never found the time to review the changes

**Comment by BE-Arbiter** [comment]
@Anduh No problem, they already have been analysed and should be corrected in https://github.com/Roll20/roll20-character-sheets/pull/13515

**Pull request merged**
