### PR TITLE
ChroniquesGalactiques Version 2020.0525

### PR DESCRIPTION
**Pull request by stephaned68**
## Changes / Comments
Retrofitted all changes to ChroniquesOublieesContemporain into ChroniquesGalactiques sheet
Changed character sheet file to .html extension (instead of .htm) for consistency with all other Chroniques Oubliées character sheets
Changed version label scheme to YYYY.MMDD

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
Better buffs/debuffs system, attack and damage modifiers, gear and encumbrance system
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
Some sections moved to a different tab
- [x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
A migration sheet worker script is run the first time a sheet is opened with the new version
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by stephaned68** [comment]
Hello. I have not the littlest idea why the 'coc.css' file change appears in this PR, as the commit was done for PR  6378 which has been merged a week ago. Very strange !

**Comment by Anduh** [comment]
> Hello. I have not the littlest idea why the 'coc.css' file change appears in this PR, as the commit for this file was done for PR 6378 which has been merged a week ago. Very strange !

This is likely due to you working from you master branch from where you submitted your previous update, and you may or may not have reset you master branch to be identical to Roll20's master branch.
I recommend you look at the wiki's [Github Guide](https://wiki.roll20.net/Github) and how to use branches when working with github, instead of working directly in your master branch. It enables you to work and submit several sheet/updates per week, and safeguard your main branch form mistakes, which would mean you'd be a ble to create new clean branches from your master branch if anything goes wrong with something you work on.

**Comment by stephaned68** [comment]
Thanks Andreas. Hope you can commit the updates to the ChroniquesGalactiques sheet anyway ?

**Comment by Anduh** [comment]
Usually it doesn't create problems if the old commits are seen in a PR, it should be good as long as the "changes" show only the changes you're after. There are plenty of sheet authors who work the same as you, but the most common troubles are usually caused by this, so preemptively switching to a better workflow will reduce the change that any updates would end up being held back by troubles.

As you see, Roll20 didn't take issue with this PR and merged it anyway.

**Pull request merged**
