### PR TITLE
Bugfix brigandyne_2e_edition.html 

### PR DESCRIPTION
**Pull request by CuracaoGold**
# Submission Checklist
## Required

- [x ] The pull request title clearly contains the name of the sheet I am editing.
- [x ] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x ] The pull request makes changes to files in only one sub-folder.
- [x ] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [ ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

Correcting a typo to enhance the display of the spells repeating list

### CODE REVIEW

**Comment by kfroll20** [comment]
Hello @CuracaoGold,

I wanted to let you know that we are taking a look at why the check is failing. Once we get that resolved, we will merge this as soon as possible to ensure the build succeeds and the sheet is updated.

**Comment by CuracaoGold** [comment]
> Hello @CuracaoGold,
> 
> I wanted to let you know that we are taking a look at why the check is failing. Once we get that resolved, we will merge this as soon as possible to ensure the build succeeds and the sheet is updated. 

Hello kf, any update since last week message ?
Kind regards

**Comment by kfroll20** [comment]
> > Hello @CuracaoGold,
> > I wanted to let you know that we are taking a look at why the check is failing. Once we get that resolved, we will merge this as soon as possible to ensure the build succeeds and the sheet is updated.
> 
> Hello kf, any update since last week message ? Kind regards

Hello @CuracaoGold! I am sorry for the delay in getting this merged. The team finished work on a more descriptive and reliable replacement validator to allow for us to better understand why the checks fail. Once this gets implemented and we can pinpoint the cause of the failing check, we will get this merged as soon as possible. We appreciate your patience with this. 

Thank you for your understanding, 
Kayla

**Comment by kfroll20** [comment]
@CuracaoGold, we are going to attempt to merge this now since the change you made is so small. If it still doesn't build, we will continue to dig deeper into why the build breaks and keep working on the new validator as it will be a lot more reliable and informative. Thank you again for your patience and understanding as we make improvements to the workflow!

**Pull request merged**
