### PR TITLE
[SWAdE Grid] version 1.0 submission

### PR DESCRIPTION
**Pull request by popebabylon**
## Changes / Comments
- Yes, the pull request title does have the sheet name
- No, this is not a bug fix
- This is a brand new sheet, so it does add functional enhancements
- This is a new sheet so it does add functional aesthetics
- No steps have been taken to preserve player data
- Yes, I believe I followed Building Character Sheets standards

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
Doesn't the Savage Worlds Tabbed sheet already to this? It seems like a comprehensive sheet, so I'm surprised if it doesn't cover the "Adventure Edition" thing.

**Comment by popebabylon** [comment]
Hi Andreas,

The Savage Worlds Tabbed sheet does handle SWAdE and is more comprehensive
than my submission.  I've gone to the trouble of making my own mostly to
learn the ins-and-outs of the whole process (including the github
fork/commit/pr approach), and for some stylistic changes I wanted to try.

If there's any concern about competing sheets being available I'm not
worried about this submission being declined.  I'll likely still potter
about with it for my own games and hopefully will learn enough to
contribute to other projects.

Thanks!

**Comment by DanieleSuppo** [comment]
Hello @popebabylon,
feel free to join us here:
https://app.roll20.net/campaigns/details/5632027/swt-test-game-v4-and-later
and partecipate to development of the  Savage Worlds Tabbed if you like.

Best

**Comment by popebabylon** [comment]
Thank you @DanieleSuppo -- happy to join in if I can.  The link gives me an error though, do I need to be invited? https://app.roll20.net/users/94776/peter-j

**Comment by DanieleSuppo** [comment]
Invited ;)

**Comment by Reonin** [comment]
Hi @popebabylon I see that you have started the conversation with @DanieleSuppo on the new sheet. I look forward to your next PR! Is it safe to say we can close this particular PR?

**Comment by popebabylon** [comment]
Yes, let’s close this for now.  I’ll see how I can contribute to the SW
Tabbed sheet.  Thank you.

**Comment by Anduh** [comment]
@popebabylon you have a "comment and close" option at the button of this page, besides the "comment" button. Only you and Roll20 can close PRs, so it's best you do it yourself so it doesn't stay hanging.

**Pull request closed without merging**
