### PR TITLE
[Basic Roleplaying System]

### PR DESCRIPTION
**Pull request by KPhan1212**
## Changes / Comments
Found that the Perform Skill still had a pop-up that it was not supposed to have so I fixed it.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Stexinator** [comment]
I think you made a mistake, please look at the code again

**Comment by KPhan1212** [comment]
> I think you made a mistake, please look at the code again

I just checked the Perform Skill and it makes a pop-up query and when I go into the server with a custom sheet with my fixes it just makes the rolls normally without a pop-up query. Originally the sheet used pop-up queries asking for a modifier to give a bonus or penalty to the skill check but I opted to have a modifier input box built into the sheet that applies to all skill checks in order to reduce the number of unnecessary clicking. So the mistake was missing the question mark that turned the modifier and multiplier into a pop-up query window.

**Comment by Stexinator** [comment]
I cannot comment to code directly so I have to copy and paste.

(@{Perform}*{Multipler}+{Mods|0})/2 <-- I guess you missed some @

**Comment by KPhan1212** [comment]
> I cannot comment to code directly so I have to copy and paste.
> 
> (@{Perform}*{Multipler}+{Mods|0})/2 <-- I guess you missed some @

Ah, thx for pointing it out. I'll make the changes as soon as I can.

**Comment by KPhan1212** [comment]
> Gonna wait until this is fixed to merge it, ok @KPhan1212 ?

Just go ahead with the merge, Stexinator found a mistake that had nothing to do with this fix.

**Pull request merged**
