### PR TITLE
[Castles&Crusades] sheet rewrite

### PR DESCRIPTION
**Pull request by seregrauko**
# Submission Checklist
## Required

- [X] The pull request title clearly contains the name of the sheet I am editing.
- [X] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X] The pull request makes changes to files in only one sub-folder.
- [X] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [X] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [X] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

**2023-01-31 ** v.2.0 Paul V
	New Sheet Version
	Rewritten to use DIV instead of Table
	Added new tabb for Settings - Allowing Critical Damage optional rule

### CODE REVIEW

**Comment by mperes** [comment]
Hey there @seregrauko, you are trying to modify an official sheet. In order to do that, we need to get a pass from the publishers. @BoomerET, are you good with the proposed changes?

**Comment by BoomerET** [comment]
Fine by me. Do as you wish. Is there anything I need to do to accept the changes?

**Comment by TrollLordGames** [comment]
Appreciate all the help! @seregrauko has been contracted by us to update and create content for us on Roll20. If you need anything else please reach out! @BoomerET good to see you friend! hope you are doing well!

**Comment by BoomerET** [comment]
Things are beyond well. Moved my family from California San Francisco bay area to North Dallas 6 months ago. Should have left a very long time ago.

**Pull request merged**
