### PR TITLE
Urban Jungle - New Character Sheet

### PR DESCRIPTION
**Pull request by vicberg**
# Changes / Comments
Use Permission Granted for this.  
This is a new character sheet

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by vicberg** [comment]
Yes, I'm a discord server with the creator the game.  He gave explicit use to create this char sheet.  If you would like some verbiage from him to this effect, just let me know.

**Comment by vicberg** [comment]
Is a preview a requirement?

**Comment by vicberg** [comment]
The actual jpg file is the background of the char sheet.  Is there a better place to put this?  Is a preview pic mandatory?

**Comment by Anduh** [comment]
The background image is fine where it is. However, in the sheet code the link will not work, you need to point it to the full url of th image where it will be on github.

Example of [functional link](https://github.com/Roll20/roll20-character-sheets/blob/122c0eb48b610760e0dbcfb19d8f6ab91c91f139/Feast_of_Legends/feast_of_legends.css#L126) to background image of sheet.

After you changed the url for the background image, and then go into your test campaign and take a screenshot of the sheet, you place the preview image in the same folder.

Follow the [example](https://github.com/Roll20/roll20-character-sheets/tree/master/Feast_of_Legends) of any existing sheet

**Comment by vicberg** [comment]
URL is fixed.  Anything else needed?

**Comment by Anduh** [comment]
Now make a preview image of the sheet in Roll20, and place it in the same folder, and make the `sheet.json` point to it, instead of the background image.

**Comment by vicberg** [comment]
preview.jpg added and css changed to point at it.

**Pull request merged**
