### PR TITLE
[Medievo Oscuro] Change on the images URL and bugfix for weapons repeating section

### PR DESCRIPTION
**Pull request by VJRolmasters**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

# Changes / Description
- Changes on the files medievooscuro.css and medievooscuro.html
- Changed all images URL to point the ROLL20 Git Hub repository
- BUG FIXED on the weapons repeating section.
- Added a missing image (mo.png) in the Git hub images folder to change the url image link in the html file.

### CODE REVIEW

**Comment by BronsonHall** [comment]
Hey @VJRolmasters ,

Looks like you've got an additional sheet in this PR - you'll need to separate that one into its own PR before we can merge either.

**Comment by VJRolmasters** [comment]
Hi BronsonHall
I am new in the git hub world and I really don't know how I did this mess up.
How can I separate both in two different PR?
Thanks in advance

**Comment by BronsonHall** [comment]
Hey @VJRolmasters 

You'll want to move the Dragonball sheet's folder into its own branch, without these changes to Medievo Oscuro in its commit history.  You've currently got both on your master branch - if you make two branches from there, one for each sheet, you can submit a separate PR for each of them.

**Comment by VJRolmasters** [comment]
Thanks again I will try my best!

**Pull request closed without merging**
