### PR TITLE
[Shinobigami-ko] Add a new Shinobigami sheet

### PR DESCRIPTION
**Pull request by sakitdev**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: < Shinobigami (Korean) >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: < Adventure Planning Service > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < Shinobigami > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [x] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

This sheet is based on an existing sheet from Shinobi Gami, but with a new design and functionality. Everything is so different from the existing sheet that I don't think I can overwrite it, so I'm requesting a pull request for the new sheet. I would be grateful if you could review it.

### CODE REVIEW

**Comment by mperes** [comment]
Dear @sakitdev, you have checked that this sheet was made in behalf of the publisher so I need to confirm if you work for Adventure Planning Service or was hired by them to develop this character sheet. If is that the case, are there any developers that should be authorised to push changes to this sheet once it is published? Thanks for all the work you do.

**Comment by sakang07** [comment]
Hello, @mperes. I'm really sorry, but I think I misunderstood this question and checked the wrong box. I don't work for Adventure Planning Services and have no relationship with the publisher. This is an unofficial fan sheet. I apologize for the misunderstanding and please let me know if there are any other issues. Thank you.

**Comment by sakitdev** [comment]
Hello, @mperes. I'm really sorry, but I think I misunderstood this question and checked the wrong box. I don't work for Adventure Planning Services and have no relationship with the publisher. This is an unofficial fan sheet. I apologize for the misunderstanding and please let me know if there are any other issues. Thank you.

**Comment by BronsonHall** [comment]
Hey @sakitdev 

Thanks for the clarification there!  Unfortunately, our policies no longer allow multiple unofficial sheets to exist for the same game.  It's clear you've done great work on this sheet, and we'd encourage incorporating this redesign and restructure into an update for the existing sheet - though we recognize that this is not a simple task, particularly given the nature of differences between the sheets.  We'd be happy to answer any questions you have about this process, and what needs to be done to preserve the data of existing games, and transfer them properly to the new sheet.  

Apologies for the inconvenience.

**Pull request closed without merging**
