### PR TITLE
Taura - The background should be visible now

### PR DESCRIPTION
**Pull request by Ravencrow**
## Changes / Comments
The background of the character sheet was not showing on the application. The css change should fix that.
Plus, the html elements <html>, <head> and <body> where removed from the html file.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
When you say "should be visible now", does that imply you have or haven't tried out the proposed changes inside Roll20, using a the code applied in a custom character mode?

**Comment by Ravencrow** [comment]
Hi, @Anduh 
I have tested everything but the image. I don't know how to upload image in the pro account editor in Roll20

**Comment by Anduh** [comment]
> Hi, @Anduh
> I have tested everything but the image. I don't know how to upload image in the pro account editor in Roll20

You don't upload images into the editor, you directly reference the image location on github.
See [one of my latest PR](https://github.com/Roll20/roll20-character-sheets/pull/5662/files) for a functioning way of showing images.
I'll also point out that currently you're using the background image as a "sheet preview image", where the sheet preview should be a real representation of how the sheet looks like. After you've changed the `background-image` url, you should be able to get the sheet look as it should, after which you can take a screenshot of how it looks and use the new image for the "preview" image in the `sheet.json`.

**Comment by Ravencrow** [comment]
Ok, I'll close the pull request and do se. Thanks!

**Pull request closed without merging**
