### PR TITLE
SLVNZ 2.2.0 Custom Character Sheet - New Sheet

### PR DESCRIPTION
**Pull request by SLVNZ**
Created a new custom character sheet and looking forward to upload it to community sheets.

# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <  SLVNZ RPG  >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <  Cagri K. - Silevenza  > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <  SLVNZ  > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <https://slvnz.github.io/playguide-en.html>
- [x] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

This is a custom character sheet designed specially for my custom TTRPG system named SLVNZ, which is currently on version 2.2.0. I have plans to translate it to English in the future.

### CODE REVIEW

**Comment by SLVNZ** [comment]
Hello, this is my first time making a request here. It says to correct errors below, but I couldn't understand what are the errors that I have to correct.

**Comment by NorWhal** [comment]
Hello, @SLVNZ

Thanks for submitting this sheet, it looks lovely! The error is just to tell us moderators that we haven't approved this sheet yet! Nothing in the code looks wrong to me. There is one thing that needs to be addressed before I can approve this though:

We do not accept new character sheets to the repository when the game rules are not publicly accessible. This means having the rules to play the game available for free or for purchase, typically on places like DriveThruRPG, a personal website, or something similar. Even a google drive link posted to Reddit is acceptable!

If the rules are publicly accessible, please update the Pull Request with a link to the rules in the body of the PR. 

Best,
Nora

**Comment by SLVNZ** [comment]
> Hello, @SLVNZ
> 
> Thanks for submitting this sheet, it looks lovely! The error is just to tell us moderators that we haven't approved this sheet yet. Nothing in the code looks wrong to me. There is one thing that needs to be addressed before I can approve this though:
> 
> We do not accept new character sheets to the repository when the game rules are not publicly accessible. This means having the rules to play the game available for free or for purchase, typically on places like DriveThruRPG, a personal website, or something similar. Even a google drive link posted to Reddit is acceptable!
> 
> If the rules are publicly accessible, please update the Pull Request with a link to the rules in the body of the PR.
> 
> Best, Nora

Hello Nora, 

Thanks for the information! Do the rules have to be in English? I only have them in Turkish for now. If this isn't a problem, I can gladly mention the link to the rules.

Regards,
Cagri

**Comment by SLVNZ** [comment]
Hello, @NorWhal 

Thank you for the information! I've prepared and updated my checklist with the accessible game rules. I hope it is enough for the requirements. 

Regards,
Cagri

**Pull request merged**
