### PR TITLE
[Das Schwarze Auge 5] Updated English translation

### PR DESCRIPTION
**Pull request by HauRukh**
Here the english translation again that keeps being overwritten by weekly translations for whatever reason.
It also contains the additional lines from @mckee14 in patch #6070

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Reonin** [comment]
Hi @HauRukh  and @mckee14 , there seems to be a conflict in your en.json file. Please take a look at it and we can get this merged in for next week.

**Comment by mckee14** [comment]
I dont get it. My PR is merged and closed, so nothing more I can do from my side. I don't see why your en.json doesn't get trough...

Maybe write something in the description? Your version should just replace the one in the main repo...

**Comment by HauRukh** [comment]
@Reonin We are aware, just overwrite with my version, I already added the changes by @mckee14 .

**Comment by Reonin** [comment]
Thanks for fixing the issue! The conflict has been resolved but unfortunately it was too late to make it into today's build. I'll be sure to get it in for next week.

**Pull request merged**
