### PR TITLE
Dragonbane initiative fix

### PR DESCRIPTION
**Pull request by RandomUsername**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [ ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

Correction for the initiative sheet/process.  The sheet is using the K-scaffold.  It holds an internal object with a list of row ids for the repeating sections.  Something is causing that list to hold id's for rows that do not exist for the repeating_initiative section.  Ignoring those rows when resorting and drawing the section.

### CODE REVIEW

**Comment by NBrooks-Roll20** [comment]
Hi @RandomUsername!

Unfortunately, you have submitted a PR to modify an official sheet that is owned by the publisher of that game, and they have final decision making authority over whether changes to this sheet can be merged.

@Kurohyou could you please confirm that these changes are solicited and/or welcome? If you instead wish them to be rejected, please indicate as such. 

Many thanks!

**Comment by Kurohyou** [comment]
Unfortunately, because this is generated code, I can't approve this PR as the changes would be overwritten by future updates we make. However, thank you @RandomUsername for finding a possible cause for the issue. I'll take a look at this code and see if we can incorporate it into the source code.

**Comment by RandomUsername** [comment]
@Kurohyou I wasn't sure if you were still maintaining this or not.  It would be great if you could review this and look at getting a fix implemented.  The Initiative sheet is a major pain point as a player.  Although the fix will not prevent the accumulation of the ghost row ids it will prevent them from being an issue for the players.

**Comment by Kurohyou** [comment]
Yep, we're still maintaining the sheet. I was just on vacation for a bit. I'll be looking at this over the weekend to try and get a permanent fix done.

**Comment by NorWhal** [comment]
Since @Kurohyou is gonna be implementing this in a different PR, we'll be closing this one. Thanks for the catch, @RandomUsername!

**Pull request closed without merging**
