### PR TITLE
Initial commit of the Heroclix character sheet

### PR DESCRIPTION
**Pull request by Coogrr**
## Changes / Comments

This is a new character sheet for the Heroclix miniatures game which is being played online on your site as a replacement for tabletop during Covid. The issue we face is not being able to see dials etc while playing which this character sheet should help with so that it is closer to a tabletop experience. The rules are freely available here: https://wizkids.com/heroclix/gameplay/rules-format/. As far as I know I have followed all the character sheet standards, except that I have not added rolls as the only rolls are 1d6 or 2d6 and I do not expect players to play with the character sheets open at all times.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Coogrr** [comment]
Good call, missed the html tag, I assume for the Star wars one you're referring to the wiki link, is that an autogenerated page of some kind or do I have to create that once it's accepted? If it's autogenerated what's the naming convention?

**Comment by Anduh** [comment]
No, I meant it as an example on how to use markdown to link to the sheet's readme file. The wiki thing is just some extra I've created for the sheet manually, and some may consider it overkill for some sheets. 

That does remind me that if a sheet have lots of instructions or want to show multiple image of the sheet, creating and maintaining a Roll20Wiki page would be easier to maintain, than a Readme file or having the sheet instructions squeezed into the `sheet.json`'s "instructions section. You can update the wiki at any time, and fit much more stuff, and others can easily contribute there, where as anything on GitHub can only be updated once a week. It's quite a bit more than most sheets need, but it's a nice thing. There is no drawback to have a small wiki-page with some instructions, tips on using the sheet, link to a relevant forum thread or external page, or just playing the game. And others can also add their tips if wanted.

**Comment by mam882002** [comment]
I noticed that the a couple of Defense powers were mismatched for the powers they represent in the game. Impervious should be Pink and Invulnerability should be Gray. Also, Impervious has an abbreviation mismatch (Im or Ip?).

Thank you for putting this together and I am excited to play HeroClix on Roll20 with this.

**Comment by Coogrr** [comment]
Thanks @mam882002, I've fixed the defense powers in the latest PR, hope you enjoy and feel free to hit me up if you have any questions

**Comment by mam882002** [comment]
Wonderful! Thanks bunches

**Pull request merged**
