### PR TITLE
[A Fistful of Darkness] V1.1 Improved Location Cards and Achievements, typos fixed, added credits

### PR DESCRIPTION
**Pull request by monkeyEcho**
## Changes / Comments

V1.1
- Improved colors for Location Cards (black / red)
- Improved colors for Achievements (better contrast)
- Bugfix to Outlaw Achievements (wrong category)
- Typos fixed
- Add credits for Jacob and Tim

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [X] Does the pull request title have the sheet name(s)? Include each sheet name.
- [X] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
Is this a new sheet? There seems to be conflicts either way.

**Comment by monkeyEcho** [comment]
Hi,
no, this is not a new sheet. I'm not sure why there are conflicts. I made
some minor changes and the new version of the files should be ok.
I'm new to this. Can you add the new files as lates version and resolve the
conflicts that way?
Or must I make the changes?
Thanks for the helping hand.
-Stefan

Am Sa., 25. Apr. 2020 um 20:16 Uhr schrieb Andreas J. <
notifications@github.com>:

**Comment by Anduh** [comment]
I think the problems comes from you working in your master branch and not updating your fork based on the changes done on Roll20 repo. It's hard to tell.
If you end up trying to do some more extensive fixing like updating your fork, take a backup of your v1.1.

**Comment by monkeyEcho** [comment]
Hi, yes I did work directly from the master branch. I though that was ok
because they were only minor fixes. Will create a fork in the future,
thanks for the tip.

Am Sa., 25. Apr. 2020 um 21:39 Uhr schrieb Andreas J. <
notifications@github.com>:

**Comment by Anduh** [comment]
I encourage you to check out the [GitHub guide](https://wiki.roll20.net/Github) on Roll20 wiki

**Comment by monkeyEcho** [comment]
Hi Andreas,
I reverted to the original content, created the fork, made my changes and
committed. Then I create the new pull request.
Looking good that far, getting the message "Able to merge. These branches
can be automatically merged."
So, I learned why the guidelines recommend to create the fork. Coming from
a subversion background I still don't understand 100% but hey, if it's
working now I don't mind creating a fork for every change from now on.
I hope everything is ok now, looking forword to seeing the changes in the
master.

Thanks for the help, info and patience!
Cheers
Stefan

Am So., 26. Apr. 2020 um 13:15 Uhr schrieb Andreas J. <
notifications@github.com>:

**Pull request merged**
