### PR TITLE
Fixes to Buffy and first commit for Deliria character sheet.

### PR DESCRIPTION
**Pull request by Kirintale**
## Roll20 Requests

*Include the name of the sheet you made changes to in the title.*

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by Anduh** [comment]
What's the point of adding a new license, when everything in this repository is already under MIT license?

**Comment by Kirintale** [comment]
Didn't realise that. The license I've selected is a copyleft license, effectively meaning people are welcome to use it, provided its attributed, but all uses must be in the public domain.

**Comment by clevett** [comment]
Greetings @Kirintale 

Everything accepted into this repository must operate under the MIT license. I can appreciate the desire to use the GNU license but we currently do not have the support or process in place to allow for a variety of individual licenses. To accept the sheet into the repository the license will need to be removed.

Thank you,
Cassie

**Comment by Kirintale** [comment]
Understandable. I'll fix it tomorrow. No rush for getting this commit in.

**Comment by Kirintale** [comment]
Hi If you can cancel this. I can do the update later and try to commit again during the week.
Ah so I can use table for tabular data but not for layout. Strange, but I'll do an update later.

Have a wonderful day.

**Comment by Anduh** [comment]
Tables for formatting is harder to change and maintain and change, I've witnessed it first hand with one sheet I took over as maintainer.

[A few more](http://phrogz.net/CSS/WhyTablesAreBadForLayout.html) [examples and reasons.](https://www.lifewire.com/dont-use-tables-for-layout-3468941)

**Comment by Kirintale** [comment]
@Anduh 
Thank you for your input and the links. I'll do the updates later.

**Pull request closed without merging**
