### PR TITLE
Whitehack sheet Community requested changes and features.

### PR DESCRIPTION
**Pull request by sydearly**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name. Yes
- [ ] Is this a bug fix? Yes
- [ ] Does this add functional enhancements (new features or extending existing features) ? Yes
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? A little
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ? na
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by oliviakristiansen** [comment]
Hello! Looks like you have 3 files with merge conflicts. Please resolve these and this PR will be merged the following Monday after you make these changes. 

Thanks!
Olivia

**Comment by sydearly** [comment]
@oliviakristiansen Hi, I am unable to click the resolve conflicts button, due to access rights.

**Comment by oliviakristiansen** [comment]
I'm unable to click the button as well, but it is saying "These conflicts are too complex to resolve in the web editor" and that may be why you can't click it as well. Is that the message you get when hovering over the `?` on the button? If so, you will need to resolve these conflicts through the command line.

**Comment by sydearly** [comment]
K going to do a fresh clone and push to see if that resolves it. Thanks!

**Pull request closed without merging**
