### PR TITLE
Godlike Initial Commit

### PR DESCRIPTION
**Pull request by CoalPoweredPuppet**
Made Possible by Rachel K. Ivey of Arc Dream Publishing

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by CoalPoweredPuppet** [comment]
Can this be done without closing the pull request or not?

**Comment by Anduh** [comment]
Yes. You change the name of the file on your computer in the same branch, and then push the changes up to github, and it will update the PR automatically.

**Comment by CoalPoweredPuppet** [comment]
Okay, I think I did it.  Maybe.  Looks that way.

**Comment by CoalPoweredPuppet** [comment]
Thank you for your help.

**Pull request merged**
