### PR TITLE
MechWarrior Destiny Character Sheet 2.0

### PR DESCRIPTION
**Pull request by AgentofChange**
Format changes, input changes, colorized character sheet, some scripting for edge and armor.

Changes / Comments

Fix list
• Fix Tonnage to go to 20 tons minimum
• Skill rating 5-8 are numbered wrong

Format list
• Mechgun 1 hard coded to be Punch / Kick with damage #/#
• Mech melee damage drop down
• Fix mechgun1 fields to melee stat line
• Range Boxes – drop down with range options.
• Add Mech heat dissipation text/numbers only
• Add label to current heat number box
• Make mech weight class a drop down list
• Mechgun Type drop down selector
• Mech loc drop down
• Mech range drop down
• Personal weapons ranges drop downs
• Movement is a number box min 1 max 5
• Bold all text
• Italicize all tags
• Add drop down to skill section that sets attribute value to relevant attribute
• total skill point and attribute counter
• Add Plot Point Counter
• Max Armor input for mechs, with max and value set as armor stat
• EDGE counter added, with max and value set as edge stat

Formulas
• Skill bonus addition

Roll20 Requests
Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.
• [Y ] Does the pull request title have the sheet name(s)? Include each sheet name.
• [Y ] Is this a bug fix?
• [Y ] Does this add functional enhancements (new features or extending existing features) ?
• [Y ] Does this add or change functional aesthetics (such as layout or color scheme) ?
• [Y ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
Unfortunately this change required a renaming of a class of attributes however the data in question is default info out of the core book and easily replaced.
• [ N/A] If this is a new sheet, did you follow Building Character Sheets standards ?
If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by AgentofChange** [comment]
Had an issue with teh inital .json submit for no good reason that i could tell.  I changed the file names saved and re-pushed and it validated.  fingers crossed.

**Comment by wing-it** [comment]
I understand you had some problems with the validation, but when you change the file names like that it makes it so that I cannot see the file diff. Can you please try again with the original file names?

**Comment by AgentofChange** [comment]
I actually got it sorted i think.  i deleted teh branch and fork and
restarted from a new fork and it seems to have worked.

**Comment by AgentofChange** [comment]
missed the part about the original file names
stand by I will do so

**Comment by AgentofChange** [comment]
Renamed everythign back to the original names let me know if that is what you needed

**Comment by sanpats** [comment]
Hi,
Can you make the skill list to allow more than 9 skills? Some pregen characters have 11-12 skills.

**Comment by AgentofChange** [comment]
> Hi,
> Can you make the skill list to allow more than 9 skills? Some pregen characters have 11-12 skills.

Well holy hell I didn't think anyone else would be using this yet :)

Yes, I do intend to get really creative with the sheet and right now have a large backlog of features i wanted to apply.  But life, work and the state of the world have created a bit of a slow down on my progress.

As it stands my next feature list/goals was to create a functional chractersheet for new characters  to use build fully off the existing provided sheet from the Beta PDF and include roll formulas built into the combat, skill, and attribute sections.   At this point the rolls are what I am workign on slowly and hope to have an update in a week or two.

once that is up and working I'm goign to start work on a drastic over haul that seperates the sheet elements into more logical groupings that will provide more tabs, larger fonts, more skills, and ultimately an "npc" sheet.

I hope that helps.

**Comment by sanpats** [comment]
Thank you

**Pull request merged**
