### PR TITLE
Forbidden Lands: Bug fix switched attributes for Insight and Healing

### PR DESCRIPTION
**Pull request by wesbaker**
## Changes / Comments

- Use Wits attribute for Insight
- Use Empathy attribute for Healing

### CODE REVIEW

**Comment by wesbaker** [comment]
For reference, [here's the official character sheet](https://frialigan.se/wp-content/uploads/2018/10/Forbidden_Lands_Sheets_BW.pdf).

**Comment by vince-roll20** [comment]
Thanks for fixing this wesbaker. ;-)

**Comment by wesbaker** [comment]
When will these changes appear in Roll20?

**Comment by vince-roll20** [comment]
> When will these changes appear in Roll20?

The changes were committed 16 days ago... but as you've already corrected, the labels still needed to be updated.  No worries.  Thanks for the update.

**Pull request merged**
