### PR TITLE
Earthdawn (FASA Official) Resubmit with minor changes, Problems with list of games. Also change address of wiki help.

### PR DESCRIPTION
**Pull request by ChrisDDickey**
## Changes / Comments
There was a problem when the sheet was added to the system last month (I think maybe with the way it was stored in the approved.yaml file), I am hoping that during this submission (which also has some other minor changes), the person who merges it will look again and see where it went wrong. 
There was already an Earthdawn sheet on the system named "Earthdawn 4th Edition". I know some people use it. I expected, like all game systems with more than one sheet that there would be a category called Earthdawn with two indented options. "Earthdawn 4th Edition" and "Earthdawn (FASA Official). 
On the Dev system, Earthdawn 4th Edition is the only one listed. On the production system, my sheet is the only one listed, but it is named only "Earthdawn", not "Earthdawn (FASA Official)" so some people were not recognizing it as mine. 

In addition there are a small number of minor edits. 
The big edits is that the wiki help file used to be https://wiki.roll20.net/Earthdawn_(FASA_Official)
however the link in the sheet.json file gets majorly messed up having an ending paren in the link name, so the link was not working when somebody selected the sheet from the settings drop-down list, it took the user to a page that did not exist (one without the ending parenthesis that was supposed to be there).  Rather than wrestle with this, I just decided to rename the wiki help file to https://wiki.roll20.net/Earthdawn_-_FASA_Official
I have modified the html and the sheet.json file to point to this wiki instead. 

**I am hoping that the person who merges this can please delete the following two wiki pages which are previous names that did not work out.** Sorry I created them, but I can't delete them, and hope that you can and will. They are ...
https://wiki.roll20.net/Earthdawn_(FASA_Official)
https://wiki.roll20.net/Earthdawn_4e_(Integrated)

Thank you.

## Roll20 Requests

*Include the name of the sheet(s) you made changes to in the title.*

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- Is this a bug fix?
- Does this add functional enhancements (new features or extending existing features) ?
- Does this add or change functional aesthetics (such as layout or color scheme) ? 
- Are you intentionally changing more that one sheet? If so, which ones ?
- If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by clevett** [comment]
Greetings @ChrisDDickey 

My apologizes for the naming issue in the approve yaml. I am working to put in an official designation for sheets that are developed/approved by the publisher. Would you be interested in being part of this program? I will be adding a header at the very top of the sheet select which will be "Sheets by publisher" and the sheet name would be displayed as "Earthdawn by FASA" in the drop down.

We want to make it easier for users to identify sheets that are supported by the publishers and this one would be a great candidate for that. There is no extra work on your part since this sheet's folder is already using Official in the name. I am taking care of all the handling behind the scenes.

Also I will look into deleting the extra wiki pages.

Thanks,
Cassie

**Comment by ChrisDDickey** [comment]
Yes, Earthdawn by FASA would be wonderful! 
Thanks!
Since you did not mention it, I want to mention again how weird it is that only the other sheet is available on the Dev system, and only my sheet is available on Production.

**Comment by clevett** [comment]
@ChrisDDickey 

The Dev server is not updated on a schedule and is likely just out of sync with Production. I can get it updated as well after Tuesday's code push.

I'll rename the sheet in the approved.yaml to "Earthdawn by" FASA in preparation for our official program. The extra header mentioned here about "Sheets by publisher" is still a work in progress but should be deployed by the end of the month.

Thanks,
Cassie

**Comment by clevett** [comment]
@ChrisDDickey 

I just wanted to update you. The sheet is now Earthdawn by FASA in the drop down. I deleted the extra wiki pages. The Dev server update will be delayed for a bit as we are fixing some things on the backend for it.

**Comment by ChrisDDickey** [comment]
Thank you very much!!!

**Comment by clevett** [comment]
You're welcome

**Pull request merged**
