### PR TITLE
Wrath and Glory v2.1

### PR DESCRIPTION
**Pull request by bts1967**
Fixed all attack rolls as they were rolling 1 additional die.
Updated Corruption to include label and DN for tests (more accurate reflection of RAW)
Added a Resist Corruption roll that uses Conviction vs Corruption.
Added onload section to manage updates to existing character sheets for corruption.
Updated Readme to reflect changes and acknowledge user who found the attack roll bug.
Fixed a bug with xp gained from missions not being totaled.

### CODE REVIEW

**Comment by bts1967** [comment]
Note there is one change to an existing field; added on open to manage the updates.

**Comment by clevett** [comment]
Greetings @bts1967 

Could you check your line endings for me pretty please? You'll want to ensure that you are using **Unix**. How to do this will vary by your text editor. For example in Sublime I go to View -> Line Endings. 

Thanks,
Cassie

**Comment by bts1967** [comment]
I am not sure what you want me to look for.  I use NP++ on a windows machine.  Nothing has changed from any of my previous releases... this sheet or Rotted Capes.  I turn on View > Show Symbol > and check Show End of Line.  I see CRLF after each line but the very last item </script>

**Comment by clevett** [comment]
Greetings @bts1967 

For Notepad++ on Windows you'll want to go to **Edit** -> **EOL Conversion** -> **Unix (LF)**. CR LF will make our server unhappy with the sheet. We need to use Unix (LF).

I only learned about how important this was recently. :) 

Thanks,
Cassie

**Comment by bts1967** [comment]
Both files were updated.  That brings up a question.  Do you need me to submit the json and css with Unix LF as well?

**Comment by clevett** [comment]
Greeting @bts1967 ,

You didn't change them here so they should be fine. If they were an issue in the past we likely fixed them for you in an earlier pull request. You'll want to make sure all your local files are using Unix (LF). I'll put in my notes for the review this coming week to double check everything.

Thanks,
Cassie

**Comment by bts1967** [comment]
FYI I went ahead and updated all of the files to make sure I didnt miss it in a future release.

**Comment by clevett** [comment]
Fyi, I merged the sheet and manually fixed your lines endings on the .html file. They will be in Unix on the repo in about an hour. You'll want to update your local copy so that future updates have appropriate line endings.

Thanks,
Cassie

**Pull request merged**
