### PR TITLE
[Demon Gate Scripted] sheet deprecation

### PR DESCRIPTION
**Pull request by phaldenby72**
## Changes / Comments

For several months we've shown a prominent message to users of this sheet that it's no longer supported and that they should switch to the newer, full compatible sheet (Demon Gate).

This change changes the sheet to only show that message, along with a bit more guidance for changing sheets and reassurance that character data will not have been lost.

This change is made to bring Demon Gate in line with the guidance that there should ideally only be one character sheet for a game system.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by nmbradley** [comment]
@phaldenby72 I'm blocking this temporarily, while we work out what the best way to gracefully handle this change is.

Would you mind answering: how compatible with the new sheet is this old one? If we automatically migrated all players to the new sheet and deprecated this one, do the `attr_` names line up close enough that they would have a seamless transition?

**Comment by phaldenby72** [comment]
Hi Nic,

Thanks for checking. If you're able to automatically migrate players to the new sheet and deprecate this one that would be brilliant.

The sheet "Demon Gate" is a copy of "Demon Gate Scripted" with a bunch of improvements (and an extra "Old Sheet" tab for backwards compatibility with an even old version of the sheet) so it's 100% compatible. The attributes for three key fields have been changed since the Demon gate sheet was created, but a sheet worker will migrate the values when the sheet is first opened.

I've been planning this step for some time, so players have had several months' warning that Demon Gate Scripted is going away.

Thanks,

Peter


________________________________

**Comment by phaldenby72** [comment]
@nmbradley any news on this? I think the sheet is a good candidate to be deprecated.

**Comment by nmbradley** [comment]
Apologies for the delay Phalden: summer vacations have taken their toll on action being taken here. 

There's a ticket sitting awaiting the specific lead dev with the ability to resolve this. I still think that this is a good candidate to formally deprecate, and so we'll be holding off until they're back.

**Comment by phaldenby72** [comment]
Sounds good -  thanks for the update.

**Comment by nmbradley** [comment]
This has now been migrated out. You shouldn't be able to see or select the demon gate scripted sheet any more. 

Do you still want to take this code out, or are you happy to leave it for posterity?

**Comment by phaldenby72** [comment]
Thanks @nmbradley, that's great! Happy to leave the code for posterity, I'll abandon this PR.

**Pull request closed without merging**
