### PR TITLE
Genefunk2090initialrelease

### PR DESCRIPTION
**Pull request by Kurohyou**
## Pull request notes
- Should be added as a publisher sheet, for CRISPR Monkey Studios
- Documentation will be added to the wiki this week

### CODE REVIEW

**Review by Anduh — CHANGES_REQUESTED** [review]
- `GeneFunk2090.json` must be named `translation.json` for things to go right.
- There is a `debug.log`-file in the PR, probably unintentional?

**Comment by Kurohyou** [comment]
Thanks Andreas. Not sure how those made it in

**Comment by Anduh** [comment]
>     * Documentation will be added to the wiki this week

Might as well add a link to the sheet's eventual wiki page, to the sheet.json's "instructions" section. with markdown, like: ` Link to [GeneFunk2090 Sheet Documentation](https://wiki.roll20.net/GeneFunk2090).`

To create a placeholder page mentioning the future documentation, here is a [direct link to create the wiki page](https://wiki.roll20.net/index.php?title=GeneFunk2090&action=edit).

**Comment by Kurohyou** [comment]
Repaired issues in new PR #7382

**Pull request closed without merging**
