### PR TITLE
StarWars5e: Added a Ship sheet type with all necessary fields

### PR DESCRIPTION
**Pull request by speedreeder**
## Changes / Comments

* Added a sheet with type "Ship"
* Specific new fields added for ships:
    * Modifications (similar to Features)
    * Pilot proficiency
    * Pilot skill: INT(Piloting) with it's own specific field
    * Ship tier
    * Shield points
    * Abbreviated saving throws (STR, DEX, CON)
    * Abbreviated attributes (STR, DEX, CON)
    * Separate inventory for hidden cargo, with it's own total weight counter
    * Turning speed
    * Flying speed
* All new fields and any calculation changes do not affect NPC or PC type sheets.
## Roll20 Requests

*Include the name of the sheet you made changes to in the title.*

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by speedreeder** [comment]
Yeah, I was gonna ask about that. If there are multiple authors, what's the separator for roll20id? Or can there be only a single author and therefor a single roll20id?

**Comment by Anduh** [comment]
There can be several authors.

[example of a sheet with multiple authors](https://github.com/Roll20/roll20-character-sheets/blob/369dc320a21edfd1ed1eb3283e037a04c16b03b5/D6StarWars/sheet.json#L5)

**Comment by Pajellen** [comment]
Sorry saw the update, looks excellent to me!

Pajellen

**Comment by clevett** [comment]
Look at all this community effort. Eeeexxxcelllent.

**Pull request merged**
