### PR TITLE
Update-Zweihander-Grim-&-Perilous

### PR DESCRIPTION
**Pull request by nogileyelsew**
## Changes / Comments
This update is a major Overhaul to the Zweihander Grim & Perilous character sheet.
• Changed the HTML table format to HTML/CSS Grid
• Added Translation Support
• Rewrote a large portion of the Sheetworkers to make them more Efficient
• 95% of the attributes were changed to a lowercase naming scheme.
• 75% of the roll buttons were renamed to meet a lowercase naming scheme.
• HTML Titles were used to label each attributes and roll button name on mouse hover.
• Sheet workers were used to migrate the attribute values in both regular and repeating sections. None 
   of the old values have been erased.
• Added a version check for upgrading.
• Condensed multiple roll templates to one and added functionality for D100 dice mechanics.
• Roll 20 wiki page is being constructed to track all of the changes to the attributes and roll buttons.
• A banner was created for the top of the character sheet informing users of the changes and how to 
  proceed with using the updated sheet.
## Roll20 Requests

*Include the name of the sheet(s) you made changes to in the title.*

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- Is this a bug fix?
- Does this add functional enhancements (new features or extending existing features) ?
- Does this add or change functional aesthetics (such as layout or color scheme) ? 
- Are you intentionally changing more that one sheet? If so, which ones ?
- If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by CoalPoweredPuppet** [comment]
Adding the comment" **nogileyelsew** should be congratulated for all of the hard work they put in without my input.  Thank you

**Comment by nogileyelsew** [comment]
I just did the update to the Zweihander sheet and I notice that I need a file for translations. I'm not sure if I was supposed to do this or not. I thought that the en translation would automatically be populated.

Any Insight would be appreciated,

Wes

**Comment by clevett** [comment]
@nogileyelsew 

The files will automatically be generated if a **translation.json** is included. I think the issue here is the file you included is translations.json with an "s". You can submit a PR to rename this file and come Tuesday when I run the translation process again it should update. 

Thanks,
Cassie

**Comment by nogileyelsew** [comment]
Thank you. I will do this!

**Pull request merged**
