### PR TITLE
[Please Rule the North with me, Grand Duke!] New Sheet (Edited)

### PR DESCRIPTION
**Pull request by headdrop**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: < Please Rule the North with me, Grand Duke! >
- The publisher of this game is: < Choi mika >
- The name of this game system/family is: < Cooperation & Jealousy System >

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: https://smartstore.naver.com/kukibox/products/10388579971
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

This game, < Please Rule the North with me, Grand Duke! > is a game rule created by Choi mika, who requested me to make a sheet.
And all the information included in this sheet has obtained permission from game publisher.

### CODE REVIEW

**Comment by BronsonHall** [comment]
Hey @headdrop !

Really great work here.  Just one small issue with sheet translations:  There has to be a `translation.json` file to support translations via crowdin - which will automatically populate the two-letter translation files in `translations/`.  If this file isn't present, it'll cause every field w/ `data-i18n` to appear in red font and brackets, signifying a missing translation, when the sheet goes live.  

The tricky piece here is that our crowdin policy expects translation.json files to hold english translations initially.  As we **don't** expect **or** require you to translate the game into english to put it on the site, I'd suggest one of two options:  

Either remove translation support initially, taking the `data-i18n` and `data-i18n-placeholder` out of every element for now.

Or just move your `ko.json` out of the `translations/` folder and rename it `translation.json`.  This will fix the sheet for now, but may require some manual changes on our end when someone wants to submit crowdin translations in the future. 

Terribly sorry for the inconvenience here, and please let me know if you have any questions.

**Comment by headdrop** [comment]
Thanks for your kind explanation, @BronsonHall ! I'll fix it and PR again! 😃

**Comment by headdrop** [comment]
Hello, @BronsonHall .
As your kind explanation I can fix the problem.
Could you please check again?

Thank you very much.

**Comment by BronsonHall** [comment]
Hey @headdrop 

Thanks for the fix, translation looks all set - however, I noticed one more issue just as I was about to merge this.  It looks like some of your files (namely I'm seeing `northgrandduke.html` and your `sheet.json`) have CRLF line endings.  We require all files in this repo to have unix-friendly LF line endings, for sake of our backend, and to prevent other sheet authors becoming blocked by automated changes to this sheet. 

This should be a quick fix, depending on your editor, but again if you have any questions, let me know!

**Comment by headdrop** [comment]
I fixed it again. Thanks for your ckeck :) !

**Comment by BronsonHall** [comment]
Hey @headdrop 

Those two files still seem to have CRLF endings to me.  The method to change CRLF to LF will vary depending on your dev environment, but when you commit, it should appear as a change to the entire contents of the file.  Check to make sure that the `.gitattributes` file in the base `roll20-character-sheets` folder is present in your fork of this repo - that file contains code that should automatically enforce the correct line ending conversion.  Using the `--renormalize` flag when you `git add` should complete this conversion.  

I apologize for the extra time added to this process - but getting line endings correct is important, and will prevent this from becoming an issue in future updates to the sheet.  If time is an issue, I can make these changes for you to get the sheet merged in, but your environment will need to be set up to use LF endings the next time you make a change to this repo.  

Thank you for your patience

**Comment by headdrop** [comment]
Sorry for my fault.
Previously, I performed commits on github web.
This time, I committed it through github desktop.
Then, as you said, the entire contents of the file appear as changes! Thanks you so much.

Is there anything else I should do?

**Comment by BronsonHall** [comment]
Nope, looks great!  All set, I'm merging this now.

**Pull request merged**
