### PR TITLE
Added Spell Scorched Character Sheet Files

### PR DESCRIPTION
**Pull request by PeteNutButter**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: < Spell Scorched >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: < Dynamic Games > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < Dynamic Defense Systems > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] This sheet has been made on behalf of, or by, the game's publisher.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: < https://www.drivethrurpg.com/product/384179/Spell-Scorched-Core-Rulebook   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by PeteNutButter** [comment]
I'm looking right at the sheet.json file. Am I missing something else?

**Comment by PeteNutButter** [comment]
[Sheet.json](https://github.com/Roll20/roll20-character-sheets/files/12923171/Sheet.json)

**Comment by nmbradley** [comment]
Hi @PeteNutButter your file extension is `.JSON`, can you correct it to `.json`, please?

Thanks!

**Comment by PeteNutButter** [comment]
Arg capslock strikes again. It should all be fixed now!

**Comment by BronsonHall** [comment]
Hey @PeteNutButter ,

This is looking good, but one more small issue - it seems like your files use CR-LF line endings. Sheets in this repo are required to use LF line endings for the sake of avoiding automatic conflicts.  You should be able to set this up once in your editor of choice, to where it will use LF by default for future sheet updates.  

Once you've got that set, this should be good to go.
Thanks!

**Comment by PeteNutButter** [comment]
Thanks, I think I've corrected the issue now.

**Comment by BronsonHall** [comment]
Hey @PeteNutButter ,

Looks like capitalization's got you again here - css is correct, with proper line endings, but you've added a new `SpellScorchedsheet.html` (leaving the old `SpellScorchedSheet.html`), and a new `Sheet.json` (as opposed to the existing `sheet.json`)

**Comment by PeteNutButter** [comment]
oh facepalm

OK, fixed that!

**Pull request merged**
