### PR TITLE
[Ironsworn] Fixed roll template selectors not prefixed with template class, and forbidden escape sequence in CSS

### PR DESCRIPTION
**Pull request by idispatch75**
- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description

This is a possible fix for the CSS not loading into the chat frame, which completely screws the roll templates.

image

See also https://app.roll20.net/forum/post/11059481/roll-template-styles-no-more-applied-on-ironsworn-sheet

### CODE REVIEW

**Comment by idispatch75** [comment]
@aureyia I'm sorry to bother you but there is something wrong with my last PR regarding roll templates : it seems the CSS is rejected by the sanitizer.
I do not have a Pro account and can't test on the sandbox. Could you please check if this PR fixes it? If not then I will have to revert the whole PR I guess, because I have no idea of what's is wrong with the CSS.

**Comment by aureyia** [comment]
@idispatch75 the problem is this: 
```
.charsheet .move-roll-shortcut-title::before,
.charsheet .move-roll-shortcut-title::after {
  content: "\a0";
}
```

Sanitizer isn't allowing the escaping

**Comment by idispatch75** [comment]
@aureyia Committed a fix. Is it working now?

**Comment by aureyia** [comment]
@idispatch75 yep it is working 👍

**Comment by idispatch75** [comment]
@aureyia  Thank you so much. I'll be able to sleep tonight.

**Pull request merged**
