### PR TITLE
[PokemonTabletopAdventures_v3] Bugfix: Removes scrollbars from sections

### PR DESCRIPTION
**Pull request by mrianmerry**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description

- Adds `scrollbar-width: none;` to the visible component of the collapsible sections
- Also set webkit scrollbar height and width properties to zero
- Updates readme

### CODE REVIEW

**Comment by mrianmerry** [comment]
First time in multiple years of submitting sheet updates that I've seen the checks fail.
What's the issue? I'd like to get this merged in this update window.

**Comment by mrianmerry** [comment]
@NorWhal any guidance?

**Comment by NorWhal** [comment]
This is a new sheet validator we're phasing in that's (intended to be) more descriptive of problems when it finds them so it's easier for us to moderate PRs and spot code policy breaks (Like end of lines not properly being set to LF, for example). There's a few kinks that we still need to work out, though, so we're running it in parallel with the old validator, which is still giving you a pass here.

You all can safely ignore that sheet-checks action for now ^-^

**Comment by mrianmerry** [comment]
Nice one! Good to know I didn't mysteriously break something 😅

**Pull request merged**
