### PR TITLE
Splittermond - Bugfixes and New Features

### PR DESCRIPTION
**Pull request by 0dr**
# Submission Checklist
## Required

- [X] The pull request title clearly contains the name of the sheet I am editing.
- [X] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X] The pull request makes changes to files in only one sub-folder.
- [X] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description

- Optimized performance with better crafted attribute requests 
- Optimized control flow with await async usage
- Magic schools updated to the parsed rolls e.g. computing success ratings
- Combat masteries now add roll bonus automatically to weapon attacks by name matching
- Added _max values to "lebenspunkte_t" and "focus_t" for use with token bars for health and mana
- Fixed german Umlate to display corectly
- Fixed the action "umklammerung lösen" to correctly use ticks (Steps)
- Attacks by weapons now correctly display ticks necessary, adding negative effects like "benommenheit" and advances the turn order

### CODE REVIEW

**Comment by NBrooks-Roll20** [comment]
Hi @0dr! Since this sheet has been touched somewhat recently by other authors (@ap3h3ad), we're going to give them a chance to respond to this PR before merging it. Also, you seem to have conflicts with our master branch, which you'll have to resolve as well.

**Comment by ap3h3ad** [comment]
Hey @NBrooks-Roll20!

Since I'm not longer supporting this character sheet I'm fine with other users improving it. I must however make one condition: 

@0dr Please make clear inside the sheet that you made those changes. I don't want fingers pointing in my direction if things break. You could for example expand the "Entworfen und umgesetzt" text on line 10 in the Sheet.html and something like ("version 2.2.0 by [username]") or something like that.

Happy rolling!

**Comment by 0dr** [comment]
I fully understand and hope this satisfies your request: 

Screenshot 2024-06-28 074337

**Comment by ap3h3ad** [comment]
@0dr Looks good. :)

Cheers.

**Comment by ap3h3ad** [comment]
Hey @0dr,

there seems to be a problem with the sheet. Since I didn't commit any changes, could it be because of your changes?

grafik

I tested it and it seems that new weapons don't have an automatically calculated value anymore. Also the weapon value doesn't change upon changing the attributes. I noticed that in your commits you are also changing the weapon values, if I'm not mistaken.

Cheers!

**Comment by 0dr** [comment]
Thanks for the heads up, I'll look into it.

**Pull request merged**
