### PR TITLE
[Das schwarze Auge 5] - Bugfix

### PR DESCRIPTION
**Pull request by mckee14**
## Changes / Comments
Bonus Damage calculation for off-hand changed from autocalc to sheetworker.
Bonus Damag is now correctly added to damage rolls.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by oliviakristiansen** [comment]
Please resolve the merge conflicts in your `en.json` file.

**Comment by mckee14** [comment]
I resolved the conflict. Hope I did it correctly, as I'm new to GitHub :).

**Comment by HauRukh** [comment]
The merge looks good to me (basically you added some new fields as far as I can tell it).
Unfortunately the "weekly translations" keep overwriting my English translations with German it seems -.-
I tried to get on the Crowdin to make translations there, but the roll20 team is taking over 7 days now to react to me sending in my "credentials" they requested .. so might be a while still.

I changed combat techniques for bows, blowguns etc. twice now and it keeps getting overriden.

**Comment by dyvim** [comment]
@HauRukh you should log an issue for your merge problem with the en.json it is not normal.
Usually the merge were made by @clevett but the last ones have been made by  Olivia Lemmelin

**Comment by HauRukh** [comment]
Okay, so it seems as of right now, my patch of the en.json is in the repository again, with translation for bows etc. [no idea why though]
However in the current version of this patch, my translations are still missing.
@mckee14 can you take the en.json that is currently in the repository (with the patch "more english translations" and replace your file with it, then add your 3 lines at the end again?

Just to make sure your patch will not override the translation again.

**Comment by mckee14** [comment]
@HauRukh Your translation has already been merged, and my PR has only the 3 added lines at the end of en.json. So it should be ok?

Let me know, I can also just delete the en.json if it overwrites something from you. Still not really figuered out how github stuff works :)

**Comment by HauRukh** [comment]
Since my file is in the main branch now, your version will be seen as an update you intended to overwrite something.
Normally, if you addeda line in the end it could be merged easily.
But because your file is based on the old version, it means that your file translates
"Bögen" : "Bögen" (German to German)
and mine translates
"Bögen" : "Bows" (German to English)
For git it is unclear though that mine is an improvement and yours is old, so I assume you will just overwrite it back to old German again.

**Comment by mckee14** [comment]
That's the thing I don't get - when I check the original file in the Roll 20 main repository, it alread IS "Bögen" : "Bögen", and not "Bögen" : "Bows"
Hence, the only difference when I check my Pullrequest are the 3 Lines at the end.

When you check the history, it looks like the weekly translations killed your translations and my PR only added the 3 lines at the end. 

Suggestion: just add my 3 lines to your updated en.json file and make a new PR for it. I can take the en.json file out of my PR then.

**Pull request closed without merging**
