### PR TITLE
[Aventures] Introducing Light Theme Tab - 11.20-1

### PR DESCRIPTION
**Pull request by Kasenai3**
Hello,
In this update:

-I added a tab(action buttons) system to switch from a Darker theme to a Lighter theme
-I changed font color on the darker theme to make it more readable
-I integrated the former rows outside repeating fields into said repeating fields, as they were the same, using script and versioning
-I added a "Weapons" repeating field in the Equipement section
-added a version number in the footer and an update log message

The new Light Theme tab, when clicked on, displays a redesigned sheet, whilst keeping all the information from the Dark tab: all Attributes remain the same between tabs, only the lay-out changes.
I removed the "Competences", "Dons" and "Equipements" fixed rows and added their values inside the repeating sections they served as headers for, using generaterowID function not to lose any player data. This makes these sections entirely re-organisable, and also transferable between themes.
I changed the name field on the character sheet, from attribute name attr_character_name to a new attribute name (as character_name is actually the hand-out name, ni data is lost). Creating a new attribute name for this field allows players to type in their characters real or secret names, without sharing it to other players.

The tab (action button) system lets players who want to stay with the original lay-out stay with it while allowing those who want a fresher look to their sheets have so. And in just one click one can revert back to the other theme without any additional change or action needed.

Thank you,
Kasenai3.

### CODE REVIEW

**Comment by Kasenai3** [comment]
I'm dead.
I struggled for 3 hours to try and request this pull, as you can see in the desastrous commit history, full of rookie/here-once-a-year mistakes...
As I failed and tried again, when I compared masters to get my fork up-to-date, I resolved some merge problems with the RWBY-UnofficialTabletopRPG.html. I thought it would be faster to copy and paste the correct code rather than pick the right solutions individually for each of the 44 conflicts in this file.
Now because of that, the pull request considered that I commited a change to the RWBY sheet too, returning me a 'signle sheet' error.
I went to the 'files changed' tab and deleted the RWBY.html one, and commited the change. Now this pull request is able to merge, but my repository:master has the RWBY.html missing, since I deleted it.

Can someone tell me if this pull request is now actually trying to push for the RWBY-UnofficialTabletopRPG.html to be deleted in the roll20 master as well? Am I doomed? I can close this pull request, or do whatever you suggest.

Thank you.

**Comment by samus** [comment]
@Kasenai3 Yes, look at the "Files Changed" tab above.  It reports that you're trying to delete the `RWBY-UnofficialTabletopRPG.html`.  The easiest way to fix this is to close this PR and reapply your changes to a fresh fork of the sheets repo.  If you feel confident with git, you can revert the delete commit 71fd932.  You will need to then restore the `RWBY-UnofficialTabletopRPG.html` file to the version prior to your merge.  For steps to restore an individual file see: https://stackoverflow.com/a/215731/2351

**Comment by joesinghaus** [comment]
https://xkcd.com/1597/

**Comment by Anduh** [comment]
>  The easiest way to fix this is to close this PR and reapply your changes to a fresh fork of the sheets repo.

Yeah that's the easiest to do, but in the future it's recommended to work with **branches** so you don't have to create a new fork of the repositiory just for a small mistake.

On the community wiki we have a guide on how to handle GitHub & Roll20 better: https://wiki.roll20.net/Beginner's_Guide_to_GitHub

**Comment by Kasenai3** [comment]
Actually, I did create a branch for my commit, by I forgot to compare the master before doing so... And then I merged the branch, and all went wrong haha.
I'll refork the roll20 master.

**Comment by Anduh** [comment]
It's smartest to make a PR from the branch to Roll20, instead of merging with your own master-branch, that defeats half the point of using branches...

**Pull request closed without merging**
