### PR TITLE
[Kuro] Features and Graphical update to version 2.0

### PR DESCRIPTION
**Pull request by Kasenai3**
- [X ] The pull request title clearly contains the name of the sheet I am editing.
- [X ] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X ] The pull request makes changes to files in only one sub-folder.
- [X ] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)
- [X ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

# Changes / Description

Hi, I made a complete overhaul of the Kuro Character Sheet. I thus named this update: version 2.0.

2.0 Changelog:
-Graphical udpate with new logo and section colors
-Added Roll template so that 4's are now signaled in rolls and rolls have titles and descriptions
-Fixed Skills repeating section
-Added Gimikku rolls
-Added detailed Equipement and Contacts repeating sections
-Automated Secondary Characteristic calculations
-Added automation for serious wounds and weapon reactionspeed modifiers
-Added options to roll in secret, ask for a general modifier for rolls, and switch to French vs English rules for Characteristic rolls.
-Added Tooltips explaining the character sheet's new functionalities

Thank you.
Yui V.

### CODE REVIEW

**Comment by mperes** [comment]
Hey there @Kasenai3, have you changed attributes names on you refactoring? If so, is there backward compatibility between the new and previous version of the sheet? Thanks for all the work you do.

**Comment by Kasenai3** [comment]
> Hey there @Kasenai3, have you changed attributes names on you refactoring? If so, is there backward compatibility between the new and previous version of the sheet? Thanks for all the work you do.

Hi, I have not changed attribute names, the character sheet is retrocompatible.
There was a broken repeating field set (with a second "_" in the name) that didn't work, I replaced it.
The secondary characteristics have the same attribute names as before, but they are auto-calculated now, in disabled fields. So there is, in the version note details, a section that displays the old secondary characteristic values of the player if they previously used different calculations than Rules as Written.
Some textareas are now labelled differently, but have the same attribute name, so their content will be preserved too.

Thank you.

**Comment by nmbradley** [comment]
Hi @Kasenai3 

There's an error in your `sheet.json` file making it not a valid json file. Specifically this line:

```
"roll20userid": "2592188", "340910"
```

**Comment by Kasenai3** [comment]
> Hi @Kasenai3
> 
> There's an error in your `sheet.json` file making it not a valid json file. Specifically this line:
> 
> ```
> "roll20userid": "2592188", "340910"
> ```

Thanks, This should have fixed it: missing commas, right?

**Comment by nmbradley** [comment]
You're missing the opening and closing brackets of the array notation:

```
"roll20userid": ["2592188", "340910"]
```

**Comment by mperes** [comment]
Hey there @Kasenai3, your JSON file is still invalid, please add a comma after the following lines:
"authors": ["Sylvain LÃ©zier", "Yui V."],
"roll20userid": ["2592188", "340910"],

**Comment by Kasenai3** [comment]
> Hey there @Kasenai3, your JSON file is still invalid, please add a comma after the following lines: "authors": ["Sylvain LÃ©zier", "Yui V."], "roll20userid": ["2592188", "340910"],

Thank you ! The check passed, finally haha.
I'm so incompetant when it comes to JSON .... Really need to find some time to learn it

**Pull request merged**
