### PR TITLE
FATE Accelerated ES

### PR DESCRIPTION
**Pull request by aecetra08**
Translation of FAE character sheet to Spanish

### CODE REVIEW

**Comment by zstlaw** [comment]
Looks good Alberto!  I am glad to see you customizing/localizing the FAE templates I added.  I hope you have fun using the Spanish version once it gets through the review process!

**Comment by aecetra08** [comment]
Thank you very much! Im working in some templates for spanish games that currently aren't in roll20, and your sheet is a great reference on how to code a simple but well designed template!

**Comment by SteveKoontz** [comment]
Looks good. I'm going to merge it in. However, can you add the original author whose sheet you used as a template to translate as an author of the sheet?

**Comment by aecetra08** [comment]
¡Sure! Ill do later, when i get home, and add the last improvements he added this week

**Pull request merged**
