### PR TITLE
Besm4e v1 1 3

### PR DESCRIPTION
**Pull request by Darth-John**
## Changes / Comments

Fixed attribute Power Variation group and pool cost accounting.
Fixed skill group max point allocation when activating or deactivating skill attribute.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ y] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ y] Is this a bug fix?
- [ n] Does this add functional enhancements (new features or extending existing features) ?
- [ n] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ n] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ na] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by nmbradley** [comment]
Hi @Darth-John 

Unfortunately, it appears as though there are conflicts between this and another pull request that was merged. You'll need to resolve these issues before we can merge this content in.

In order to avoid issues like this in the future, we would recommend appending additional changes to an existing PR rather than creating multiple branches and pull requests.

**Comment by Darth-John** [comment]
Thank you sir!  Please forgive me as I'm new to Git/GitHub and learn as I go.  I think I understand what happened now, I either should have been patient and waited for the initial pull to have a baseline of code to compare against, or, as you said, appended additional changes to the existing PR.  I will get better at this!  ;)

Question: I read that it is best practice to create a new branch for new changes, but should I create one branch for one PR?  Such as, when making changes to a sheet, create a new branch and put all my commits into it, and when finished create one PR for that new branch.  Then say after that PR is merged, create a new branch for additional changes, rinse and repeat?  Or should I just keep working out of the same branch (not master)?

Thanks in advance!

**Comment by Anduh** [comment]
> I read that it is best practice to create a new branch for new changes, but should I create one branch for one PR? Such as, when making changes to a sheet, create a new branch and put all my commits into it, and when finished create one PR for that new branch. Then say after that PR is merged, create a new branch for additional changes, rinse and repeat?

Yes, make new branch from your master for each. remember to update your master by fetching updates from Roll20's master branch.

Se there two guides for more:
* https://wiki.roll20.net/Beginner%27s_Guide_to_GitHub
* https://wiki.roll20.net/Git

**Comment by nmbradley** [comment]
@Darth-John There are many different ways you could do this, as you've identified. In my own projects, I try to create branches on my fork of the repo for each piece of work, merge those into the fork's master (so that I can squash any merge conflicts) and then create a single pull request from that master branch. This way if I make additional changes between creating the pull request and it being merged, it will automatically update the Pull Request.

Hope this helps!

**Comment by Darth-John** [comment]
Thank you for your insight, Nic!  I think that makes sense but I need to
digest it more...and apologies up front if I make more mistakes getting
proficient at this.  ;)

I appreciate your help!

John

**Pull request merged**
