### PR TITLE
exalted2e.html  -  Added Abyssals/Infernals castes

### PR DESCRIPTION
**Pull request by Briteblade**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [ ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

Added option to select Infernal Castes in the attr_Caste dropdown menu. Added Caste names to attribute columns

### CODE REVIEW

**Comment by Anduh** [comment]
It's possible some of these changes introduced bugs to the sheet, I had a person reach out to me yesterday, but don't have more details yet.

I'll direct them here.

**Comment by Briteblade** [comment]
Yeah, they unfortunately did, my bad. Found out almost immediately and set to work to correct it. They just merged the new fix, everything should be working as intended now. Let me know if anything else seems screwy.

If anyone else asks you can send them my way. Thank you!

**Comment by Anduh** [comment]
Great you figured it out!

It's an older sheet, so uses some of the oldest tricks to to show the dots, and I think I ran into the same problem when few years ago added the Dragonblooded.

If you think about updating the sheet some more in the future:

* You could add your [roll20id](https://wiki.roll20.net/Roll20id) to the `sheet.json`-file, and you'd get the Sheet Author profile flair for having contributed to the sheet.  
* could be a good idea to convert it to [CSE](https://wiki.roll20.net/CSE). Would make coding sheet easier and enables more options
  * would make it possible to use [datalist](https://wiki.roll20.net/CSE#Datalist) for inputs, meaning one could include  Name suggestions for things like Specialty, Merits & Flaws, Combos, Sorcery etc. 
* saw a few oddly aligned things on the sheet *(might be limited to firefox)*
* the TODO have list of my older suggestions, but as I don't use the sheet, don't know how relevant they are, just something I noticed

**Comment by Briteblade** [comment]
Thanks! Still kinda surprised I'm not the only one who prefers 2E

Yeah I think you did, I had to use a similar trick to what you did to get the other Exalts to work.

I'll do that and add myself, thanks!

I would love to do that, but it's going to be a while for me to figure some things out before I attempt it. Especially after the previous fiasco.

Weird, I don't remember seeing anything that was off alignment. I'll try to check it out in Firefox later to see if I can find them.

I saw your TODO, started trying to update it with my changes, and add one or two things I would like to add. I'll go through them and see what I can actually do. Once I get Lunars set up, I think it's mostly QoL after that.

**Pull request merged**
