### PR TITLE
Coriolis (Update)

### PR DESCRIPTION
**Pull request by agjwilson**

### CODE REVIEW

**Comment by pjbehr87** [comment]
So, is this the complete, final version of all of your changes?

**Comment by pjbehr87** [comment]
I've noticed a lot of your changes are in a new folder Coriolis English. I thought these were all changes to the existing Coriolis. If they are can we please remove this other folder and only change the files in the existing folder?

**Comment by agjwilson** [comment]
Okay I have removed Coriolis English and replaced them all into Coriolis. I will now remove the fold Coriolis English.

**Comment by agjwilson** [comment]
https://github.com/agjwilson/roll20-character-sheets/tree/master/Coriolis

**Comment by pjbehr87** [comment]
Please let me know when you're done making changes and I'll accept the PR.

**Comment by agjwilson** [comment]
Yes it is the final. If what I see [here](https://github.com/Roll20/roll20-character-sheets/pull/2415/files) is correct

**Comment by agjwilson** [comment]
That's really very useful in this situation

**Comment by agjwilson** [comment]
If you can give me a date you will next be doing this merge I can keep this as a mental note from when the next update will roll.

**Comment by pjbehr87** [comment]
I manage the sheets on a pretty loose once-a-week schedule. I will do PRs on either Monday or Tuesday, _usually_. Then, the changes will go out Wednesday morning, again _usually_. These days can change, or not happen at all, from week to week. It all depends on when I have time. We currently only have 2 devs working on Roll20, so I have a lot of other stuff going on as well.

**Comment by agjwilson** [comment]
Fine. That's useful information that I was not aware of. Thank you.

**Comment by pjbehr87** [comment]
2 things you can do in your next commit.
You can add your Roll20 account ID to the roll20userid (in a comma delimited list) so that your account will get flagged as a sheet author.
You can upload all of the images to git, then, after I've accepted the PR you can then link directly to the images on GitHub.(you can't link to them until I've added them to the main repo, you have to do that in a 2nd commit) That way the images aren't hosted on a 3rd party site that can just remove them whenever they want.

**Pull request merged**
