### PR TITLE
Pathfinder - manually merged with #1234

### PR DESCRIPTION
**Pull request by vince-roll20**
- noticed that @{PC-whisper} was added twice to skill macros
- button titles were incorrect, changed to include "%{selected|" , some un-closed " } " as well.
- changed the attention text about button macro names.  All rolls on the sheet except attacks use " _roll ".  Only attacks use " -roll " on the end.  I thought it was better to leave the button names as is vs renaming to make them include " -roll " which could break anyone's existing macros that include the button macro names.

### CODE REVIEW

**Comment by plutosdad** [comment]
Actually it looks like some javascript updates were missed, can you recopy the entire javascript section? I made some last minute changes.

**Comment by vince-roll20** [comment]
Will do

**Comment by plutosdad** [comment]
then if you go to the git desktop tool, maybe you can click "update from roll20/master' and it might merge back to yours, if not, you have to open the shell and do some funny stuff.

**Comment by rileydutton** [comment]
Yeah I was just getting ready to attempt to merge this haha. You guys just let me know what I need to do.

**Comment by vince-roll20** [comment]
I just merged your latest, including the your last sheet worker js.  I'll make a new PR and stand back.  :-)

**Comment by vince-roll20** [comment]
https://github.com/Roll20/roll20-character-sheets/pull/1238

**Comment by plutosdad** [comment]
huh i still see the javascript section is old.

**Comment by vince-roll20** [comment]
I just copied the entire script area from your raw code on the last PR... ?

**Comment by vince-roll20** [comment]
I can make a new clone of the roll20 fork and do my changes again.

**Pull request closed without merging**
