### PR TITLE
Legacy: Life Among the Ruins Family Sheet Rebuild

### PR DESCRIPTION
**Pull request by kierduros**
## Changes / Comments
This is a near complete rebuild of the Family section of the character sheet and fixes for character stat setup in the Character section of the sheet.

Massive structural changes, with associated styles. (Should all work, thoroughly tested in the sandbox.)

Numerous fixes for bad roll buttons and HTML structure. Adds more useful roll button setups, notes fields, and other data fields that either weren't in place before or weren't usefully/properly functioning.

All old data structures preserved and accessible to sheet users. No old attribute fields removed.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by OnyxCourage** [comment]
You appear to have deleted all the Family moves and tracking data for Treaty, Resources, Data, etc. Now there is just basic stats and un-editable blank spaces for everything else. You have left the sheet in much worse state. 

I was running a fortnightly game of Legacy and now most of the Family data for my players is gone. We can re-choose the moves and details, but I can't remember what everyone's Treaties were up to and Resources were, exactly.

I understand that you are trying to improve the sheets, but you've basically destroyed the Family sheets for my players and now we have to re-create them, and the new version is pretty useless.

**Comment by kierduros** [comment]
That shouldn't at all be the case. (Checks my own game... oh, yikes... yeah, that looks terrifying.)

I didn't change any variable names... all the data is still there.

What it looks like is that the family playbooks need to be re-select from the drop down... to populate the overall display trigger, which is a new variable. That was, indeed, an oversight on my part. But all the data is still there.

I'll add that check in for the next round. So sorry for that...

**Comment by kierduros** [comment]
Also, to avoid any other possible confusion, the old fields for the treaty and resources are in collapsible fields under the "Classic Treat" or whatever heading. Clicking on the title should expand the old fields to allow the data to be moved into the new format (if desired).

Really, seriously sorry for the disruption. I would've freaked out when I checked in to my own game to do setup for tomorrow if I hadn't seen your message first, @OnyxCourage, so I totally know where you're coming from.

**Comment by OnyxCourage** [comment]
Hey, thanks for responding so quickly, and now that I've chosen the playbooks again, I can see all the data is still there. What a relief! Sorry for being so angry, I was pretty horrified when I first opened up and it looked like most of it was gone!

I like the new versions, now that I can see them. Good work :)

**Comment by kierduros** [comment]
@OnyxCourage, thanks. Next chore is the character playbooks... and that's going to be a haul. But I'll *definite* remember to include the "on sheet open" variable update.

You were well within your right to be angry right off the top. I would have been, for sure.

So, if you're cool, I'm cool. Cool? :)

Also, very open to any suggestions for further improvements. This was just the first round to get the major structural changes out of the way. There are a number of other visual and usability enhancements I'm going to try to work out.

**Comment by OnyxCourage** [comment]
@kierduros  thanks, I'm all good, now. So relieved I don't have to somehow rebuild those Family sheets!

I appreciate that you are updating all the sheets and so far I like the changes. The previous version was a bit buggy but this version looks a lot clearer.

My group loves Legacy so far (we are playing the Core version) and I'll let you know if we have any suggestions for improvements as we progress. Here are some suggestions right now:
- Inheritance is misspelled as "Inheretance"
- Consider updating the Quick Characters so they can select their Inheritance moves from their Character sheet - no need to have the rest of the Family sheet info there, as that will stay with the player of that Family on their Family sheet.

One thing I can think of is updating the Quick Characters so you can select the Inheritance on the Character sheet itself

**Comment by kierduros** [comment]
The plan for the Quick Character sheet is already in the works. Because that's definitely an issue I ran into that slows things down, having to bounce around to other sheets to figure out what you should get.

Will definitely fix that spelling error, too... I'm sure there's a few of them (that one's mine, but there were a lot that I caught in my first pass of the sheet a few weeks back... so I'm sure there are more).

I'm in my first run-through of a game, myself. So the real reason I'm fixing these sheets is so that I don't get super frustrated running the game. ;)

My group is coming off of about a year of Blades in the Dark, so we're all still getting used to the zooming in and zooming out... and we're heading for our first age change in another week or so. That'll be interesting (my players tend to get attached to characters... so I've been reminding them, everyone is temporary).

**Comment by OnyxCourage** [comment]
We haven't used Quick Characters yet, but we will soon. We'd be happy to trial any Quick Character sheets you develop. No worries on spelling errors, happens all the time, just thought I'd mention it.

Yes, Legacy is an interesting beast. It's difficult to tell sometimes what level you should be on to do things, such as when you have a fight, as you can do that on both levels, and the core book isn't entirely clear at times on that, as you can also "temporarily" be at one level.

Good luck with the turning of the age! We aren't up to that, yet, as I am keen to keep going on the interesting situations that are playing in the current age.

**Comment by tonydowler** [comment]
So if I go into the character sheets, unselect the family and then select it again all the data will come back? Just want to verify before I mess around with anything.

**Comment by kierduros** [comment]
@tonydowler That's correct. All the data is still in place. It's just the display that's not activated properly until the sheet is re-selected.

I meant to get a fix in for that this past week, but the day job sucked the life out of me.

Sorry for the confusion... and likely moment of terror.

**Comment by tonydowler** [comment]
Thanks! Appreciate your work on this. Having character sheets makes Legacy
a lot easier to play online.

**Pull request merged**
