### PR TITLE
Donjon de Naheulbeuk 2.8.2

### PR DESCRIPTION
**Pull request by Kaias26**
- add patches notes in config tab 
- add new attribute "protection max"
- add new temporary buff "protection"
- few ui & css fix

### CODE REVIEW

**Comment by Kaias26** [comment]
holy crepes, all my comits again, even with a new branch 🤕 
the "files changed" are goods.

I think i'll delete my fork, my local repo and create a new one after tuesday to start a clean project...

**Comment by clevett** [comment]
Its unsightly but not really an issue on my end. If you go to the Files tab you can see the actual changes. 

You can delete your fork if they are bother you. Using branches to do updates rather than your fork's master will prevent this. [I wrote a step by step of my process here.](https://app.roll20.net/forum/post/7282579/questions-about-github-advice-request-request-that-somebody-edit-beginners-guide-to-github-to-explain-a-bit-more/?pageforid=7332367#post-7332367)

**Comment by Kaias26** [comment]
Yeah i saw the topic, and my pull request is precisely from a new branch... 
but since this branch came from my master's fork, i still have the commit history, even after a pull request from roll20 to my fork 😨 

I'll just delete my fork tomorrow and make a fresh start 👍

**Comment by Kaias26** [comment]
Yeah, my fork is now uptodate, no need to delete anything, thanks to this comands :
```
git fetch upstream
git checkout master
git reset --hard upstream/master  
git push origin master --force 
```

**Pull request merged**
