### PR TITLE
New Classic World of Darkness Vampire the Masquerade 5 edition charac…

### PR DESCRIPTION
**Pull request by Kirintale**
…ter sheet

To help you play VTM 5 edition this character sheet comes with a host of easy to use roll button to ensure you don't have to keep flicking through the rules book.
The health and will power system takes all styles of damage.
We have included custom visuals to aid players realise the result of rolls.
Plenty of room to store extended character information
Enables custom rolls via the MISC section.
Coterie section to store all details of your coterie, domain and haven.

It is recommended the ST makes one extra sheet for the entire party. They can then press the COTERIE button and share all their coterie stats.

### CODE REVIEW

**Comment by Anduh** [comment]
There exists a sheet for it already, and it got approved earlier today. So 
if this sheet have improvements over the existing sheet you could discuss with the creator to add some features to it, but your sheet won't be approved with Roll20’s current "One System - One sheet" rule(I'm parafrasing here).  https://github.com/Roll20/roll20-character-sheets/pull/4030

**Comment by Anduh** [comment]
Curiously enough, this is the fourth character sheet independently developed for V5 in the last two weeks.

**Comment by chrisleaptrott** [comment]
@Anduh the game JUST came out and its quite popular haha.

@Kirintale If there is anything I can do to help you take your mechanics and improve the sheet published, I will. Of course, you will be credited on the author and all that. I'm working with another on it and we were just about to start work on the Hunger dice mechanics ourselves (as a script).

**Comment by Anduh** [comment]
Yeah figured as much when the two first ones commented on it on the forums. I just mean it's funny that almost nobody checked if someone else where working on a sheet before making one.

**Comment by Kirintale** [comment]
Hey Chrislea

I've already got all the mechanics in there along with custom picutres.

I've spent about a month working on this. Could you please give it ago and see what you think.

**Comment by Kirintale** [comment]
Literally all the mechanics are in the sheet, 

There is hunger, frenzy, disciplines, tabs, coterie section, humanity.
Custom displays .

**Comment by Kirintale** [comment]
screenshot_1
screenshot_4

**Comment by Kirintale** [comment]
screenshot_2

**Comment by Kirintale** [comment]
screenshot_3

**Comment by TheGrandCoterie** [comment]
Let me check out the current sheet and do a comparison of features.

**Comment by chrisleaptrott** [comment]
Yeah, I've looked at it. I like it a lot and it looks pretty good.
My biggest question would be if it is integrated, will people need to have the script or will r20 add that.
Asking for the folks who have the accounts that can't add API.

Not a huge deal, of course.

**Comment by chrisleaptrott** [comment]
@TheGrandCoterie I'm sorry, but who are you?

**Comment by TheGrandCoterie** [comment]
I am the sheet designer. :)

**Comment by Kirintale** [comment]
Hi Chris.

TGC is my co-developer who did all the graphics.

The script is required, but I believe there is a way to get it into Roll20. I'm not sure if Roll20 automatically adds the script the API. If not I'm sure there is a way to get acccess to the fucntions via HTML as that's what happens in D&D 5e

**Comment by chrisleaptrott** [comment]
Cool. I can say that the current sheet doesn't have the Coterie page or the script integration.
I was playing around with it last night, and script integration is easy as pie to add to the existing sheet...as well as, I'm sure, the Coterie page.

Also, I saw some custom roll areas and such, which could be added as well.

If I had known this excellent sheet was in the works, I'd have not made mine for sure....but let's see what we can do to ease that over.

**Comment by Kirintale** [comment]
Thanks man I appreciate it. It was my first Roll20 sheet and we wanted it to be near perfect before release.

**Comment by TheGrandCoterie** [comment]
Awesome! Thank you chrisleaptrott.

**Comment by chrisleaptrott** [comment]
Yeah, this was my first sheet too, haha.

I think honestly, the only issue I have with your sheet is that the radio buttons for hunger and such could be switched over to the VTR ones (the ones that I use) and if the tabs could be placed somewhere else. It honestly looks like all the attributes are the same beyond something like the advantages.

Let me take another look, see what I'd be happy with merging from my sheet to yours, and then we'll see about getting them over. Cool?

**Comment by Kirintale** [comment]
That sounds amazing!

After the merge I would recommend adding yourself to the About Us page and lets work on imrpoving it together ^_^.

**Comment by chrisleaptrott** [comment]
Thank you! That would be really really nice, haha. I really just want the best sheet for the community....and you guys have done an amazing job. Like just stellar work with a focus on the actual mechanics problems (them darn hunger dice).

**Comment by Kirintale** [comment]
Wait till you see what had to be done for the willpower and humanity roll

**Comment by chrisleaptrott** [comment]
Okay, if y'all don't mind I'm going to just toss some adjustments real fast and get them over to you so you can see what you think.

Not too much honestly needs it, but what I'm looking at is room for Discipline Powers and giving hunger a stylized button. I'll send that over to ya'll somewaysomehow and see if that's good with you.

**Comment by Kirintale** [comment]
Ha I know that one. I only get a proper chance to code after the little one is asleep.

**Comment by chrisleaptrott** [comment]
Yeah, that would be good I think as well.

I might not be able to get to much of this today, actually. Just remembered a few meetings in today.

Not sure on how to move the js over to the HTML, but I'm going to start looking at some other sheets that do it for methods and speak to the guy who helped me out so we can maybe figure that one out too.

Goodness, though, I gotta say great work again on this sheet. Its like the smallest of the small adjustments and its like perfect haha.

**Comment by Kirintale** [comment]
Thanks man. Means alot.

If I grab you on Facebook I can add you to the group I have. I had a couple people beta test it and they came up with some great fixes and great ideas on where to take it next.

**Comment by chrisleaptrott** [comment]
Okay dudes, here's what I've done so you can look at it before we do some mergin':

I've added the repeating powers field below the Disciplines
As I've been requested this over and over, I've added a repeating Specialties field on the first page.
I've added a few equipment fields to the details section at the bottom.

Listed myself in the about us as a design contributor (if that's okay haha, I didn't know what else to put haha).

I've tossed it over to a repo here:

https://github.com/chrisleaptrott/VampireV5API

**Comment by chrisleaptrott** [comment]
Okay, super!

**Comment by Kirintale** [comment]
Sweet.  Ill have a look when I get a moment.  I'd recommend adding the js for now. As all the rolls operate off it

**Comment by chrisleaptrott** [comment]
Having a weird problem where it won't seem to store the powers. Maybe you guys will have better luck with it. Worst case we can just add over 5 blank boxes since its meant to be one power per dot.

Yeah, looking into that too.

**Comment by Kirintale** [comment]
You need a name like 

attr_power

**Comment by chrisleaptrott** [comment]
Yeah, I've got it in there, I think the problem is repeating under repeating.

**Comment by chrisleaptrott** [comment]
updated with just some power boxes up under and they seem to 'stick' just fine. Looking into script integration now.

**Comment by chrisleaptrott** [comment]
Okay, so after reading in the documentation, looks like we'll just have to leave the script up as it is (as some other sheets do) since Roll20 disables the <script> tag for 'security reasons' and won't allow it in-line on the sheet. Not a big deal, other sheets do this stuff fine and get away with the DM having to have pro level for the API access.

I say we move ahead as it goes with the changes I've made (if you guys are cool with that). Once y'all approve or alter, I'll do a pull request to basically replace the sheet stuff in and update with the proper sheet.json that gives you guys credit and has your instructions and all that.

If that's how y'all want to move forward :D

**Comment by Kirintale** [comment]
Cool

**Comment by chrisleaptrott** [comment]
Okay, pushed the changes over to consolidate things in prep to make the pull-request on the official sheet when you guys give the word. Just whenever you all have time to look over and then let me know. I should be around in the afternoon.

**Comment by Sdinapoli** [comment]
Hi guys, I am the person that was helping @chrisleaptrott with his original sheet. I just had a quick look at this, and it looks very nice, especially with the script for rolls.
A couple of comments I had from a quick first look would be:
The hidden checkbox that is used to swtich between Character/Coeterie on the top right, is fixed to the right margin, so if someone changes the width of the sheet, the checkbox will no longer be in the same place as the text. It needs to be set to a fixed position.

For the attributes/flaws i would say you can easily fit 2 per line and reduce the amount of scrolling needed for that page.
And lastly I would make the text boxes in the "Details" tab, especially the Notes, expandable to make it easier to read if you have a lot of text in there.

**Comment by Kirintale** [comment]
Good idea

**Comment by chrisleaptrott** [comment]
Sorry, didn't mean to 'laugh' at that.

Been playing around with this sheet for the last half-hour....goodness, you guys deserve a round for that work. Great job again.

**Comment by Kirintale** [comment]
Memo to self do the same for Names on Coterie

**Comment by Kirintale** [comment]
Haha thanks.  I aint going to lie my heart dropped when I heard the sheet was rejected,  thankfully you are nice :-D 

We ended up chatting with some of the game devs to make sure we understood the rules correctly and didn't get into copyright issues (Note the black dog logo) :-D

**Comment by chrisleaptrott** [comment]
Rock on. Yeah, you guys were super nice in appealing and your work shows out well so I'd like to see that adopted for sure.

Check the code in the repo I linked, if you guys like it and are okay with the bit of credit I added for myself on there (totally changeable haha) we can pull that to the main repo.

**Comment by Kirintale** [comment]
You've already been helpful so no worries on that front. 

I'll do a check in a couple hours

**Comment by Kirintale** [comment]
Whats your roll 20 ID

**Comment by chrisleaptrott** [comment]
app.roll20.net/users/95940/obi

**Comment by Kirintale** [comment]
Just looking now

**Comment by chrisleaptrott** [comment]
Awesome, let me know what ya think and if you have any changes and I can put it as a commit in the current pullrequest to update it before it goes in and such.

**Comment by Kirintale** [comment]
Man I swear I nearly kicked myself that I forgot to add Spec.

**Comment by Kirintale** [comment]
Ok I've sent a pull request to your repo.
Once done you can ship it to Roll20
^_^

**Comment by chrisleaptrott** [comment]
Pull request updated with all changes in tow.

**Comment by Kirintale** [comment]
You are amazing!

**Pull request closed without merging**
