### PR TITLE
Savage Worlds Tabbed v3.8

### PR DESCRIPTION
**Pull request by gronyon**
## Changes / Comments

- Ability to change linked attribute of any skill.
- Can enable/disable Soak button from the game settings.
- Made it easier to enable/disable a skill in a setting (can click the skill name, not just the checkbox, in config panel)
- Fix translations for Renaming Piloting and Climbing skills.
- Attempt to fix skills in Game Settings being all disabled by default (instead of enabled).
- Fix Show Modifiers option not working (until you unset and set it again) despite being on by default.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by gronyon** [comment]
Hello @clevett,

I experimented in the sheet.json trying to create a "title" about user options. That must be the reason why sheet.json doesn't work.

Here is the section : 
`
 {
            "attribute":"fakeattributeusedfortitle",
            "displayname":"Custom skill selection for your setting",
            "type":"checkbox",
            "checked":"checked",
            "readonly":"readonly",
            "description":"Here you can enable/disable skills for your setting, as well as renaming them, or linking them to different attributes. Skills linked to Agility or Strength will suffer encumbrance penalties. Fighting can't be disabled. It can however be renamed or relinked. If you need skills that can activate power, enable and rename any of : Faith, Focus, Psionics, Ritual, Spellcasting, Weird science, Performance or Athletics. If you need skills that can fire weapons, enable or rename any of : Fighting, Athletics, Shooting or throwing."
        },
`
First, I used "readonly" expecting it to be added to the input, despite readonly option is not in the Wiki regarding sheet.json. (like checked=checked wasn't, but I read in the forum it would work, and Fate Core v2 use it and it works).

Second, for attribute name I gave an attribute the sheet HTML is not using at all. It's not even declared there. I assumed the attribute would be added to all characters created (in the attribute & abilities section), but never be displayed in the sheet itself.

I'm going to rename this "fakeattribute" and add it to the SWTRedesign.html, and see whether it works ?

**Comment by gronyon** [comment]
Fix pushed. (affect both the HTML and the sheet.json)

Could you test if that solves the issue or if that's something else ?

**Comment by gronyon** [comment]
Hello @clevett,

Would you have time to check and help me on this pullrequest before this week push to servers ?
Finderski (the sheet author) would need this update to safely work on new features of his own.

Tell me how best I can help.

**Comment by clevett** [comment]
@gronyon 

I'm actually on vacation through tomorrow and just stopping in to do merges. I'll test your sheet.json changes tomorrow before the push. 

You could work from each other's branches as remote repositories then you'd be able to collaborate together easier without awaiting changes be merged into master. Here are some simple directions on how to do this https://gist.github.com/elfrank/c08256de9c15e41e1781

**Pull request merged**
