### PR TITLE
[Nahual] New game - Character sheet

### PR DESCRIPTION
**Pull request by ChubertoM**
## Changes / Comments
[Nahual] New game - Character sheet

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by ChubertoM** [comment]
I can't see the errors to correct.

**Comment by ChubertoM** [comment]
Hola, es la primera vez que voy a subir una character sheet nueva a roll20. En espera de sus comentarios, gracias.

**Comment by Anduh** [comment]
The check always fails for new sheet submissions, so you PR is probably fine.

**Comment by ChubertoM** [comment]
> The check always fails for new sheet submissions, so you PR is probably fine.

Oh, Thank so much for your answer. First time here.

**Pull request merged**
