### PR TITLE
[Burning Wheel] Version 2.2 - big update

### PR DESCRIPTION
**Pull request by Seraaron**
## Changes / Comments
* Fixed quite a major incompatibility issue with Chrome. Specifically, the difficulty tracker buttons for stats and wounds couldn't be selected properly. In the process of fixing this bug, it was required to fit most stats and attributes into `<div>`s (rather than `<tables>`) and generally a lot of effort was spent on beautifing the HTML code and CSS to be more human-legible (many long sections of code were written on one line which looked horrible) **This is also the main reason that the number of lines of code in this PR basically just doubled.**
* Fixed a styling issue where columns would wrap onto themselves and look very bad at certain browser zoom levels.
* Put test trackers in separate boxes, and a few other things for a prettier general aesthetic.
* Added some non-proprietary fonts to the stack for better Mac and Linux support. The new default font is an open-license font called 'Crimson Pro' by Jacques Le Bailly, which fits in with the style and theme of BW quite nicely. But there are plenty of fallback fonts now too.
* Changed page tab style to newer sheet-worker format, as recommended in the Roll20 CSS Wizardry wiki
* Fixed background image stretching on long page tabs by splitting it into a top, middle, and bottom segment, where the middle repeats until it reaches the bottom.
* Corrected an implementation of the 'Being Learned' autocalc that would use the average Aptitude as your skill total, rather than the first chosen Root (see BWG pg 49). And also made tax affect these rolls.
* User request fulfilled: Added option to make every stat and attribute taxable to support more homebrew mechanics
* Added dropdown menu in the wound tolerance scale that can actually go grey or white
* Improved injury tracking with automated segments
* Added a dropdown menu in the Combat tab to remind players how 'Shrugging it Off' works
* Separated trait names from description and added tags and a 'used' checkbox
* Added Hesitation and Reflexes modifiers
* Added base Mortal Wound modifier in the Char Burner, and a Stature dropdown on main sheet (nb. these are deliberately not linked, because the answer to how much base MW each stature grants changes with editions)
* Made Beliefs and Instinct slots renamable
* Slightly better organised the layout of the Character Index
* Expanded 'Additional Notes' section and moved 'Gear Notes' to Combat tab
* Added a taxable emotional attribute slot for things like Corruption, and made them open-ended by default
* Added a repeating segment to Cash, so that players can better organise their monies
* Slightly altered appearance of the weapons tables, and made editing them easier
* Moved Artha trackers to the top of the sheet for ease of access on every tab
* Added new repeating segments for Fatigue and Tools
* Added extra Stride options
* Added a 'luck' macro button for exploding 6s after a roll next to the Fate tracker
* Updated the wording of and moved the 'Earning Artha' dropdown to the Information tab
* Added a semi-hidden command symbol "⌘" checkbox on the far right of each skill list that turns the skill into a renamable skill 'group / type' separator, which will be useful for organised players with many skills
* Reformatted skill layout to be clearer and look better with the above-mentioned skill groups. Basically every skill is on one line now, but every (n*2)th row is lightly shaded gray
* Changed the 'open-ended' checkbox to a more magical looking "✦" star symbol
* Made the roll-dice macro button invert on hover to more clearly indicate to the user that it's actually a button
* Altered the 'Test Difficulty' dropdown segment to fit the width better, and added useful table for quickly calculating arbitrary test difficulties
* Moved the 'Old text practice log' into the 'Practice Times' dropdown menu
* Changed the default selected stat for learning new skills and the Char Burner to Perception (the most common stat Root)
* Added passive steel tests dropdown
* Added an extra armor and missile weapon slot, and made the 'Bare-fist' weapon renamable
* Created a new 'Magic' tab and moved spells lists and notes into it. In addition, spell fields are now renamable to better accommodate elven spell songs and alternate magic systems from the Codex (and there is still plenty space here for perhaps more additions and improvements in the future)
* Added numbers to the weapon Lengths for ease of making numerical references
* Added dropdown check-boxes for Training skill effect descriptions
* Adjusted Character Burner section to make transferral of skills and traits easier
* User request fulfilled: Added Age-Table support for Great Spiders (from the old Monster Burner) and the Kerrn and Kukhadish (from Burning Empires)

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?

Some pre-existing attributes and values have been moved to new locations, but not destroyed. There are only a few minor breaking changes in this update for existing users; all of which are single values that can be easily looked up again from the rulebook:
* Changed the checkboxes on Beliefs and Instincts into number inputs for better long-term tracking
* The 'All Other Tests' for armour clumsy weight has been automated to a dropdown menu and gets treated like an additional wound penalty in macro calculations.
* Changed dropdown menus on Add and WS in the weapons section into text imputs for ease of customisability
* Number of 'sustained spells' value has been changed for more consistent / easier macro referencing reasons, but the original value can still be found in the main sheet Attributes & Abilities tab.
* I have also taken the liberty of opening a [public testing game](https://app.roll20.net/join/8910408/CK3Kdg) on Roll 20 to collect user feedback and request from the unofficial Burning Wheel Discord, and haven't had any complains about the proposed changes.

- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Seraaron** [comment]
I have no idea how or why that Cyberpunk2020.png file got into this PR, but I also have no idea how to get rid of it! It just showed up in my Fork last week when I made an upstream merge. I tried reverting the merge, and adding it to a .gitignore, and yet it's still there... Please ignore it when resolving this conflict.

**Comment by mperes** [comment]
Dear @Seraaron  your PR has a conflict within "Cyberpunk 2020/Cyberpunk2020.PNG" which needs to be resolved before I can merge it. Please rebase you PR against last Master and fix this issue. If you are unsure how to do this, take a look at the Git documentation.

**Comment by Seraaron** [comment]
@mperes Hi, the conflict should now be resolved. Thanks, I didn't know that rebasing was different from just a normal upstream merge.

**Comment by coreyhickson** [comment]
Hey, loved the update! Do you know if it's possible to make the sheets so that one person can view one tab while another play views another? As a GM, bouncing around between tabs is disruptive to my players so I thought I'd ask :)!

**Pull request merged**
