### PR TITLE
Renamed Tabs

### PR DESCRIPTION
**Pull request by dougansf**
Reformatted Readme, Carrying capacity, minor cosmetic fixes

### CODE REVIEW

**Comment by wing-it** [comment]
In your last commit, your code was using the default Windows new-line characters (\r\n) when we need it to use the default Unix character (\n). Our website runs on a Unix system, and requires the Unix line-endings rather than windows. To avoid this in the future, you can change the settings in your text editor to use Unix line-endings rather than Windows.

**Comment by dougansf** [comment]
Sorry, I did try to fix it because I've gotten this feedback before.

**Comment by wing-it** [comment]
Which text editor are you using? I may be able to help you get the settings correct.

**Comment by dougansf** [comment]
I've been writing in the Roll20 custom character sheet editor.

I tried to use Sublime to correct it, but apparently it's not working.

**Pull request merged**
