### PR TITLE
German translation for Runequest Glorantha sheet

### PR DESCRIPTION
**Pull request by phoenix1561**
Created German translation for the Runequest: Roleplaying in Glorantha sheet, trying to follow closely German core rulebook

## Changes / Comments

1st edit from initial English file
- new translation, no bug

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Lockbox313** [comment]
Was this down through Crowdin? 
[](https://help.roll20.net/hc/en-us/articles/360057432414-How-to-Translate-Content-on-Crowdin)
[](https://app.roll20.net/forum/post/9382237/translation-and-crowdin-changes#post-9599126)

**Comment by phoenix1561** [comment]
> Was this done through Crowdin?
> 
> https://help.roll20.net/hc/en-us/articles/360057432414-How-to-Translate-Content-on-Crowdin
> https://app.roll20.net/forum/post/9382237/translation-and-crowdin-changes#post-9599126

Wasn't aware of that tool. Did it in Crowdin just now. You can close the PR.

**Comment by mperes** [comment]
Hello @phoenix1561 ! Your Pull Request includes changes to translation files. Unfortunately, we no longer accept translations submitted outside of Crowdin. To learn more about Crowdin and how to submit translations through Crowdin, please see our article on [How to Become a Translation Volunteer.](https://help.roll20.net/hc/en-us/articles/360058423993-How-to-Become-a-Translation-Volunteer) Thanks for all you do!

**Comment by phoenix1561** [comment]
Hey @mperes,
As I mentioned in above comment I wasn't aware of Crowding. I redid the translation in the tool a few hours ago and as well applied for the core translator team.
Thanks

**Pull request closed without merging**
