### PR TITLE
[NoReturn 2E] New Features

### PR DESCRIPTION
**Pull request by Gorthian**
# Submission Checklist
## Required

- [X] The pull request title clearly contains the name of the sheet I am editing.
- [X] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X] The pull request makes changes to files in only one sub-folder.
- [X] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [ ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [X] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by NorWhal** [comment]
Hey, @Gorthian, the file in your `tmp` folder uses a `<head>` tag, which breaks sheets [per our documentation](https://wiki.roll20.net/Building_Character_Sheets#CSE). Just want to mark that out of an abundance of caution before we approve this.

**Comment by Gorthian** [comment]
The TMP-Folder contains only sample files for testing some HTML concepts and ideas.

They are not used in the sheet itself.

Should I better remove the TMP-Folder from my commits to your branch?

**Comment by nmbradley** [comment]
Hi @Gorthian 

Generally, it's our policy to avoid having extraneous files included in PRs. This just helps prevents repo bloat (it's already really big).

**Comment by Gorthian** [comment]
OK. I will remove the TMP-Folder.

**Pull request merged**
