### PR TITLE
[Warhammer 4e Character Sheet] Banner rework & fixes

### PR DESCRIPTION
**Pull request by Djjus**
## Changes / Comments

- Feb 2 2020

- Banner rework, added light/dark mode to settings
- Roll public/whisper chooser moved to settings
- Fields for Career level and Career Path added.
- Perception/Stealth rolls influence from armour fixed
- Critical Hit roll fixed
- Bug fixes

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by SebastianGrohnert** [comment]
Hey there,

this merge deleted the background "parchment" from another charactersheet, again!

**Comment by clevett** [comment]
I see that. I totally missed the image being edited was in another folder. I'll revert this change.

**Comment by clevett** [comment]
@Djjus You changes here broken another sheet, WFRP4CharSheet/assets/parchment.jpg was removed.

You need to update your fork to be in sync with master before submitting additional pull requests. 

- Cassie

**Comment by Crossems** [comment]
I've been enjoying the work you guys have done.  For my play group through I've found the SL computing to be heavy and tedious for new players.  So I've added the following to help them.  Basically They roll their attack, then plug their SL and the defenders SL, along with any bonus damage (impale, damaging, etc.) and select the location that was rolled with their previous attack.

I'm sure ya'll can offer better guidance on how to clean this up a bit. 

I'm also very new to roll20, so I'm not sure what the best method for offering suggestions is:

here's my edits (all on the HTML page)
Added two buttons (in the repeated Melee and Ranged weapon table)
- melee -
`
							<div class="sheet-col-4-100 sheet-center  sheet-vert-middle">
                                <span><button type="roll" class="sheet-roll" name="roll_MeleeDamage" value="@{Whisper} &{template:whfrp2e} {{title=@{MeleeWeapon} Damage}} {{character_name=@{character_name}}} {{target_name=@{target|character_name}}} {{attackersl=[[?{Attacker SL|0}]]}} {{defenderssl=[[?{Defender SL|0}]]}} {{successlevel=[[?{Attacker SL|0}+(?{Defender SL|0}*-1)]]}} {{bonusdamage=[[?{Bonus Damage|0}]]}} {{targettoughness=@{target|ToughnessBonus}}} {{strBns=@{MeleeStrengthBonus}}} {{melBns=@{MeleeDamageBonus}}} {{damagedone=[[((?{Attacker SL|0}+(?{Defender SL|0}*-1))+@{MeleeStrengthBonus}+@{MeleeDamageBonus}+?{Bonus Damage|0})]]}} {{hitprotection=[[?{Hit Location|Head,@{target|armorAPtotalH}|Right Arm,@{target|armorAPtotalAR}|Left Arm,@{target|armorAPtotalAL}|Body,@{target|armorAPtotalT}|Right Leg,@{target|armorAPtotalLR}|Left Leg,@{target|armorAPtotalLL}}]]}} {{armorqualities=@{target|armorQuality}}} {{qualities=@{MeleeQualities}}} {{totalwounds=[[((?{Attacker SL|0}+(?{Defender SL|0}*-1))+@{MeleeStrengthBonus}+@{MeleeDamageBonus}+?{Bonus Damage|0})-(?{Hit Location|Head,@{target|armorAPtotalH}|Right Arm,@{target|armorAPtotalAR}|Left Arm,@{target|armorAPtotalAL}|Body,@{target|armorAPtotalT}|Right Leg,@{target|armorAPtotalLR}|Left Leg,@{target|armorAPtotalLL}})-@{target|ToughnessBonus}]]}}"></button></span>
                            </div>`

- ranged -
`
							<div class="sheet-col-4-100 sheet-center sheet-pad-r-sm">
								<button type="roll" class="sheet-roll" name="roll_RangedDamage" value="@{Whisper} &{template:whfrp2e} {{title=@{RangedWeaponName}}} {{character_name=@{character_name}}} {{attacktype=^{RANGED}}} {{character_name=@{character_name}}} {{target_name=@{target|character_name}}} {{attackersl=[[?{Attacker SL|0}]]}} {{defenderssl=[[?{Defender SL|0}]]}} {{successlevel=[[?{Attacker SL|0}+(?{Defender SL|0}*-1)]]}} {{bonusdamage=[[?{Bonus Damage|0}]]}} {{targettoughness=@{target|ToughnessBonus}}} {{strBns=@{RangedStrengthBonus}}} {{melBns=@{RangedDamage}}} {{damagedone=[[((?{Attacker SL|0}+(?{Defender SL|0}*-1))+@{RangedStrengthBonus}+@{RangedDamage}+?{Bonus Damage|0})]]}} {{hitprotection=[[?{Hit Location|Head,@{target|armorAPtotalH}|Right Arm,@{target|armorAPtotalAR}|Left Arm,@{target|armorAPtotalAL}|Body,@{target|armorAPtotalT}|Right Leg,@{target|armorAPtotalLR}|Left Leg,@{target|armorAPtotalLL}}]]}} {{armorqualities=@{target|armorQuality}}} {{qualities=@{RangedQualities}}} {{totalwounds=[[((?{Attacker SL|0}+(?{Defender SL|0}*-1))+@{RangedStrengthBonus}+@{RangedDamage}+?{Bonus Damage|0})-(?{Hit Location|Head,@{target|armorAPtotalH}|Right Arm,@{target|armorAPtotalAR}|Left Arm,@{target|armorAPtotalAL}|Body,@{target|armorAPtotalT}|Right Leg,@{target|armorAPtotalLR}|Left Leg,@{target|armorAPtotalLL}})-@{target|ToughnessBonus}]]}}"></button>
							</div>`

I also modified the column class width to 4-100, the melee qualities to 18-100, and the ranged weapon to 14-100

and modified the roll template as after the {{#test}}{{/test}} element:
`
				
	            {{#damagedone}}
                <div class="sheet-row">
                    <div class="sheet-col-11-24 sheet-pad-l-md sheet-pad-r-md sheet-rt-key">Success Level</div>
                    <div class="sheet-col-13-24 sheet-pad-r-sm sheet-rt-value">{{successlevel}} ({{attackersl}} - {{defenderssl}})</div>
                </div> 
                {{#rollGreater() bonusdamage 0}}
                <div class="sheet-row">
                    <div class="sheet-col-11-24 sheet-pad-l-md sheet-pad-r-md sheet-rt-key sheet-right">Weapon Damage</div>
                    <div class="sheet-col-13-24 sheet-pad-r-sm sheet-rt-value">STR {{strBns}} + Weapon {{melBns}} + Bns {{bonusdamage}}</div>
                </div>
                {{/rollGreater() bonusdamage 0}}
                {{#^rollGreater() bonusdamage 0}}
                <div class="sheet-row">
                    <div class="sheet-col-11-24 sheet-pad-l-md sheet-pad-r-md sheet-rt-key sheet-right">Weapon Damage</div>
                    <div class="sheet-col-13-24 sheet-pad-r-sm sheet-rt-value">STR {{strBns}} + Weapon {{melBns}} + Bns {{bonusdamage}}</div>
                </div>
                {{/^rollGreater() bonusdamage 0}}
                <div class="sheet-row">
                    <div class="sheet-col-11-24 sheet-pad-l-md sheet-pad-r-md sheet-rt-key">Total Damage</div>
                    <div class="sheet-col-13-24 sheet-pad-r-sm sheet-rt-value">{{damagedone}}</div>
                </div>
                {{/damagedone}}
                {{#hitprotection}}
                <div class="sheet-row">
                    <div class="sheet-col-11-24 sheet-pad-l-md sheet-pad-r-md sheet-rt-key">Protection</div>
                    <div class="sheet-col-13-24 sheet-pad-r-sm sheet-rt-value">Toughness {{targettoughness}} + Armor {{hitprotection}}</div>
                </div>
                {{/hitprotection}}
                {{#rollGreater() totalwounds 1}}
                <div class="sheet-row">
                    <div class="sheet-col-11-24 sheet-pad-l-md sheet-pad-r-md sheet-rt-key">Total Wounds</div>
                    <div class="sheet-col-13-24 sheet-pad-r-sm sheet-rt-value">{{totalwounds}}</div>
                </div> 
                {{/rollGreater() totalwounds 1}}
                {{#^rollGreater() totalwounds 1}}
                <div class="sheet-row">
                    <div class="sheet-col-11-24 sheet-pad-l-md sheet-pad-r-md sheet-rt-key">Total Wounds</div>
                    <div class="sheet-col-13-24 sheet-pad-r-sm sheet-rt-value">1 (damage Minimum)</div>
                </div> 
                {{/^rollGreater() totalwounds 1}}
				
`

Hope this is the right place for this.

Crossems

**Comment by Djjus** [comment]
Hey Crossems, thanks, sorry I'm only just reading this. Interesting suggestion about a different SL mechanic. I will play around with it a bit this week. I may need to separate it out for the original code, we'll see, but a selectable SL mech mode should be possible. Thanks for providing the code, stay tuned.

**Pull request merged**
