### PR TITLE
(NoReturn) some improvements

### PR DESCRIPTION
**Pull request by Tealk**
insert weight calculation

### CODE REVIEW

**Comment by clevett** [comment]
Greetings @Tealk 

This PR has changes to Runequest assets and Thorg. Are these changes intentional?

- Cassie

**Comment by Tealk** [comment]
Hi @clevett 

No, not really, and I don't know how that got in there.
But I don't think I can delete it?
Sorry I have very little experience with github

**Comment by Tealk** [comment]
Hi @clevett

I think I've corrected everything again.
Sorry to bring such a mess in here.

**Comment by clevett** [comment]
@Tealk 

You can click on the Files change tab at the top to see Thorg is still part of this change request.

**Comment by Tealk** [comment]
> Edit: I would recommend backing up your No Return changes and then updating your fork with the current master repo.

Unfortunately I don't get any changes from the master repo

**Pull request closed without merging**
