### PR TITLE
[Duty & Honor] Fix couple of attribute not saving stats, code cleanup

### PR DESCRIPTION
**Pull request by Anduh**
## Changes / Comments
- there was a good +100 appributes taht din't save anything, as they where missing "attr_" from their name
- figure @MattBx8 the author want a chance to look at it before approval, I'll leave it as a draft a couple of weeks before turning it in if you haven't checked this out.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by MattBx8** [comment]
Thanks! My HTML coding skills are still in their infancy, I fear, and any assistance is appreciated. I will check out the changes and learn from them. Thanks again!

**Comment by clevett** [comment]
@Anduh Are you ready for this to be merged?

**Comment by Anduh** [comment]
No, Matt haven't given an approval yet. @MattBx8 can you give this a quick check if this PR have any problems? I did check it, but don't use the sheet so it's possible I missed something.

**Comment by Anduh** [comment]
@MattBx8 have you had time to check this out?

**Comment by MattBx8** [comment]
I will check it out tonight.

**Comment by MattBx8** [comment]
Looks like it works.

Thanks!

**Pull request merged**
