### PR TITLE
major overhaul of combat section

### PR DESCRIPTION
**Pull request by sohaho**

### CODE REVIEW

**Comment by Rhallinan** [comment]
You should check with Meteox before I merge these changes in. He reverted the last changes you made and since he created the sheet originally he does control ownership over it.

**Comment by sohaho** [comment]
Hi Ryan, I think he did so, because the .css-changes did not make any sense without the .html-changes, but of course it makes sense to coordinate with him. I have just sent him an e-mail and hope that he will have no other reason for disagreeing with my changes.

**Comment by Meteox** [comment]
Hi Ryan.
sohaho contacted me and checked his changes and they´re ok.

Please merge them :)

**Comment by Rhallinan** [comment]
Sounds good!

**Comment by sohaho** [comment]
Thanks for merging! Unfortunately I am new to Git and split my changes into two different branches, one for the .css and one for the .html. So this one was for the .css, the one for the .html is this one:
https://github.com/Roll20/roll20-character-sheets/pull/1062
Could you please merge that one as well? I will take care to not split changes into two different branches next time, promise. :)

**Comment by Meteox** [comment]
i created a pull request for the missing file :)

**Pull request merged**
