### PR TITLE
Exalted2e - Mortals added, fixed errors

### PR DESCRIPTION
**Pull request by Briteblade**
Correcting a bug introduced with the addition of mortal races. Minor spelling fixes.

# Submission Checklist
## Required

- [ x] The pull request title clearly contains the name of the sheet I am editing.
- [x ] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x ] The pull request makes changes to files in only one sub-folder.
- [x ] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [ ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

I. Exalted2e.html
   1. Several spelling corrections
   2. Corrected an error introduced with the addition of mortal 'castes' that caused them to be permanently visible
   3. Corrected an alignment error in mortal 'caste' abilities

II. exalted2e.css
  1. Added requisite fields for the recent additions of the mortal 'castes'

III. Readme.md
  1. Updated changelog

Error fix for the addition of mortal 'castes'

### CODE REVIEW

**Review by Adrail86 — APPROVED** [review]
Thanks for the assist in fixing the alignment issues

**Comment by Briteblade** [comment]
No problem, same kind of glitches happened me. Let me know if you have any
other issues with it. I might start working on it again as well.

**Comment by Adrail86** [comment]
I am currently working with a downloaded copy of code that I will convert to fork soon that adds a Heartsblood tab to Lunars and has a repeating section for Stats that mimics the Familiar section.

**Comment by nmbradley** [comment]
@Briteblade there's a conflict on the files here preventing this from being merged. If this is still a work in progress, please mark the PR as a draft, to avoid getting it accidentally merged.

Thanks!

**Comment by Briteblade** [comment]
Welp.
@nmbradley It is not wip, I'll see if I can resolve the conflicts. It has been tested and does work correctly in Roll20's sandbox.

**Comment by Briteblade** [comment]
@nmbradley Conflicts should be resolved, let's give that a whirl before I start tinkering again.

**Pull request merged**
