### PR TITLE
[Das_schwarze_Auge_Ilaris] [Translation] Added Json Translation Files

### PR DESCRIPTION
**Pull request by HauRukh**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [O] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description

- Added translation files for de/en
- I know using Crowdin is preferred, but I am waiting 5 days now and the project was not added to Crowdin.
- Since there is no possible conflict with non-existing files, and I am very likely the only translator anyway, I am hoping this way I can get the game translated in time for my intended games over the holidays.

### CODE REVIEW

**Comment by mperes** [comment]
Hello @HauRukh 

Your Pull Request includes changes to translation files. Unfortunately, we no longer accept translations submitted outside of Crowdin. To learn more about Crowdin and how to submit translations through Crowdin, please see our article on [How to Become a Translation.

**Comment by HauRukh** [comment]
@mperes Well, I did the translation myself specifically, as I wrote, because you guys would not add the sheet to Crowdin.
I was told it will be added automatically after commiting the initial change where I added the translation.json and i18n, but it over a week now and I see no change.
Why is it not on crowdin? 
Why do you make it so hard to contribute to your site?

**Comment by mperes** [comment]
Hey @HauRukh please accept my apologies in behalf of the team. I will try to escalate your issue later today to see if I can get it solved. However, due to the holidays, this may not happen this week. If that is the case I will merge your pull request and take the responsibility from any merging conflicts that may arise in the future with crowdin.

**Comment by mperes** [comment]
Hey there @HauRukh, following up on your issue: The reason why your translation did not appear on Crowdin was due to some problems in the translation.json you've submitted 4 days ago:
- There is a leading comma after  "Notizen":"Notizen" when there should be none;
- You have a few duplicated keys on your json:   "Entwaffnen", "Rüstungsbrecher", "Reichweite erhöhen" and "Notizen".

Our JSON validation is very pick so before submitting any changes, I would recommend validating them through something like [jsonlint.](https://jsonlint.com/) Once you make those changes you sheet will be made available for translation shortly on Crowdin.

Please do not hesitate to drop us a line if you have further questions.

**Comment by HauRukh** [comment]
I noticed and fixed those issues in the current version.
If you insist that I repeat the translation on crowdin, you can just merge the translation.json and roll20.html to get the updates and fixes at least, if not the translation.

**Pull request merged**
