### PR TITLE
Update Fallout PnP 4.html

### PR DESCRIPTION
**Pull request by SilverRahl**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Tealk** [comment]
i thought table elements were no longer allowed, why was this allowed here?

> Do Not Use old sheets using <table> as your template. They are just generally hard to handle, adn roll20 doesn't approve new sheet that contains <table>-elements.

**Comment by SilverRahl** [comment]
> i thought table elements were no longer allowed, why was this allowed here?
> 
> > Do Not Use old sheets using  as your template. They are just generally hard to handle, adn roll20 doesn't approve new sheet that contains -elements.

This is not a new sheet.

**Comment by Tealk** [comment]
Create Date Aug 3, 2020 i think it is new

**Comment by mperes** [comment]
Dear @SilverRahl and @Tealk, I was not the one who merged the initial version of the sheet, however, I believe at the time such rules were not strict as today and the person doing the merge had a final say on the topic.

**Pull request merged**
