### PR TITLE
[Band of Blades] Add Band of Blades Official v1.0

### PR DESCRIPTION
**Pull request by joesinghaus**
This includes complete sheets conforming to the release version of the game, including legion roles and Broken/Chosen. This sheet was created in collaboration with Evil Hat Games, so I have the necessary permission of all the copyright holders.

The new sheet is *not* compatible with the existing sheet for Band of Blades. I would suggest that the old sheet be deprecated in favor of this one.

### CODE REVIEW

**Comment by clevett** [comment]
@joesinghaus 

You submitted this PR as a Draft do you want it merged and to go live?

- Cassie

**Comment by joesinghaus** [comment]
Hey, thanks! I decided to make some more changes before I actually want this submitted (adding proper roll templates). I will mark this as ready for review once that's done.

**Comment by joesinghaus** [comment]
Hey @clevett, are you planning to update the approved.yaml for the new sheet?

Thanks

**Comment by clevett** [comment]
This should be updated. Sorry for such a late reply. I have a 130+ notifications in GitHub and trying to clear them out now.

**Pull request merged**
