### PR TITLE
[Old-School Essentials by Necrotic Gnome] - 1.5.0

### PR DESCRIPTION
**Pull request by wesbaker**
### Added

- Add critical hit and miss results to attack rolls. Closes wesbaker#22
- Add Dolmenwood classes. Closes wesbaker#18

### Changed

- Change "AC Benefit" to just AC. Closes wesbaker#19
- Change "Threshold Modifier" to "Situational Bonus". Closes wesbaker#20
- Change damage roll to show roll formula, but also no longer enforce minimum of 1 damage. Closes wesbaker#21
- Change weapons table to only have attack type and not attribute. Closes wesbaker#23

### Fixed

- Fix a bug where colors were not appearing for max and min rolls on dice

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [X] Does the pull request title have the sheet name(s)? Include each sheet name.
- [X] Is this a bug fix?
- [X] Does this add functional enhancements (new features or extending existing features) ?
- [X] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [X] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by samus** [comment]
Hello @wesbaker this PR has conflicts and cannot be merged to master until they are resolved.  Additionally, it is making changes to a translation file.  We will not deny your Pull Request, but we would prefer sheet contributors use Crowdin for translations. Please email Cassie at cassie@roll20.net and she will get you an invite to our Crowdin within 48 hours. Be sure to include the languages you would like to translate, Please use that for future translation updates! Thanks for all you do!

**Comment by wesbaker** [comment]
@samus alright. I’ll work out the conflict. As for the translations they’re coming direct from @elbj (and much appreciated), but I can point him toward Crowdin.

**Comment by elbj** [comment]
I'd be pleased using crowdin in the future for translations.

**Comment by wesbaker** [comment]
@samus got the conflict worked out and preferred @elbj's translations.

**Pull request merged**
