### PR TITLE
AD&D 2E ver 2.8.51 and Coriolis fix

### PR DESCRIPTION
**Pull request by Project462**

### CODE REVIEW

**Comment by wing-it** [comment]
Would you mind separating this into two pull requests, one for the sheet update and one for the new sheet?

**Comment by Project462** [comment]
I tried to, but I wasn't sure how. Should I just push them some-now,
some-later?

**Comment by Project462** [comment]
Ok, I removed the new sheet. I guess I'll wait for the other stuff to go through and then try to upload the new sheet. If it has to wait for next week, well, that kind of blows, but I get it :)

**Comment by wing-it** [comment]
The way to do this is to have the different sheets on different branches. So, create a new branch for the new sheet and the pull requests for it will be separate.

**Pull request merged**
