### PR TITLE
HITOS-cultos innombrables Spanish

### PR DESCRIPTION
**Pull request by Daniel1977**
HItos in Spanish ( Hitos en Español)

### CODE REVIEW

**Comment by SteveKoontz** [comment]
Hi,

I'm not sure why you have both a regular folder and a sub CSS folder with the same files in them.

Also, your .json file isn't valid. Please run it through http://jsonlint.com

**Comment by Daniel1977** [comment]
sorry iam new in this.

**Comment by SteveKoontz** [comment]
No problem, let me know if you have any questions.

**Comment by Daniel1977** [comment]
the character sheet is ok? sorry to folder and sufolders.

**Comment by SteveKoontz** [comment]
The sheet looks fine as far as I can tell from just looking at the code.

The problem is still the sheet.json file. The references in it aren't correct. They have to match the files in the folder with it. For example your html file is called just html. But in the .json file you reference it as HITOS.html. The names have to match.

Also, if you could remove the sub folders from the pull request.

**Comment by Daniel1977** [comment]
how can remove?

**Comment by SteveKoontz** [comment]
If you uploaded the files from the software suite that Github released, you'll need to change your locally cloned version of the files and resubmit the pull request.

**Comment by Daniel1977** [comment]
ok now? is all ok?

**Comment by SteveKoontz** [comment]
Haha, not really no. But I'm going to merge it in and fix it.

**Comment by Daniel1977** [comment]
thanks a lot...^^

**Pull request merged**
