### PR TITLE
Rename WFRP4Charsheet.CSS to WFRP4Charsheet.css

### PR DESCRIPTION
**Pull request by Arioch1973**

### CODE REVIEW

**Comment by Arioch1973** [comment]
renamed to try to fix roll20 problem with loading the sheet

**Comment by Arioch1973** [comment]
I don’t know if it has been updated on your side yet or not, but the character sheet prevents me from loading a campaign. So something is still wrong.

/Arioch

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by suntzu777** [comment]
Arioch , i copied your raw text from your uploaded files which were uploaded today and those worked and loaded a character sheet, however the current version on the roll20 doesnt load

Rob

**Comment by suntzu777** [comment]
however there are some formatting issues with the Armour section , if an item is added those formatting issues go away and the armour points gets shifted to its correct position

**Comment by Arioch1973** [comment]
Thank you for merging it into the master. However, as I just tried it, there is still something that prevents the campaign to be loaded with the character sheet. Are you able to see what is causing this?

/Sincerely, Arioch

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Pull request merged**
