### PR TITLE
Rolemaster 2nd / Classic sheet (new sheet)

### PR DESCRIPTION
**Pull request by Onirim**
## Changes / Comments
Initial pull request for a standard Rolemaster 2nd & Rolemaster classic character sheet, able to work with most of the optional rules, even for Rolemaster Express.

First pull request for me, so I hope it will be good. I plan to update the sheet with more options in a future release (for being able to change the colors or some mechanics).

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
Yes, I hope it will be fine 👍 
- [ ] Is this a bug fix?
No
- [x] Does this add functional enhancements (new features or extending existing features) ?
Yes, but it's the initial release
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
Yes, but it's the initial release
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
Non applicable
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?
Yes, the wiki have helped me so much!

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Reonin** [comment]
Hi @Onirim the sheet looks good! Although there is a heavy usage of table elements we [recommend](https://roll20.zendesk.com/hc/en-us/articles/360037773453#1-code-of-conduct-0-0) using more divs where possible.  Also there is another sheet in our repo for not only Rolemaster 2E, but also standard. We try to cut back on duplicate sheets , have you tried reaching out to the other authors on the other [Rolemaster 2E sheet](https://github.com/Roll20/roll20-character-sheets/tree/master/Rolemaster_2E) ?

**Comment by Onirim** [comment]
Hi Corey,

I can try to remplace the tables by div, I use the tables for the repeating fieldset headings (because in my mind, the fieldsets are tables ^^)

Actually the other Rolemaster sheet are not compatible with Rolemaster 2nd Edition or Rolemaster Classic ; the Standard System is not Rolemaster Classic (it’s a different system with different calculations).

For example, the Rolemaster 2nd/Classic doesn’t have predefinite set of skills, and use 1, 2 or 3 attributes for calculations, so we need a sheet who doesn’t auto-calculate things. All the other RM sheets are « strict » and tied to the sheet autor choice of rules, but Rolemaster is a game of options, and actually we cannot play Rolemaster with the other sheets. They are build-in options and choices we cannot play with ☹

I try to create a somewhat basic sheet who can handle really the RM2/RMC possiblities, and don’t want to be tied to the choice of one GM ^^

And sadly, the différences between the sheets are too much (the actual Rolemaster 2 sheets donesn’t follow the base rules of Rolemaster 2/Classic, it’s an hybrid not a true Rolemaster sheet) ☹

So what can we do ?

De : Corey J<mailto:notifications@github.com>
Envoyé le :lundi 19 octobre 2020 15:59
À : Roll20/roll20-character-sheets<mailto:roll20-character-sheets@noreply.github.com>
Cc : Onirim<mailto:onirim@outlook.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [Roll20/roll20-character-sheets] Rolemaster 2nd / Classic sheet (new sheet) (#7539)


Hi @Onirim<https://github.com/Onirim> the sheet looks good! Although there is a heavy usage of table elements we recommend<https://roll20.zendesk.com/hc/en-us/articles/360037773453#1-code-of-conduct-0-0> using more divs where possible. Also there is another sheet in our repo for not only Rolemaster 2E, but also standard. We try to cut back on duplicate sheets , have you tried reaching out to the other authors on the other Rolemaster 2E sheet<https://github.com/Roll20/roll20-character-sheets/tree/master/Rolemaster_2E> ?

**Comment by Reonin** [comment]
Interesting that the calculations differ so much between the sheets. I think that makes sense especially if there's room for the Role master express version to be added here. Swap out those tables and if you can get it in this should be good to merge if not this week then next.

**Comment by Onirim** [comment]
Thank you Corey,

I’ve cleaned the code and now having only 1 table (for the stats because it’s really a table).
The character sheet will be 100% compatible with the first edition family and nearly all the optional rules (with little automatizations)

  *   Rolemaster 1st (RM1)
  *   Rolemaster Express (RMX)
  *   Rolemaster 2nd (RM2)
  *   Rolemaster Classic (RMC)

The other versions are not compatibles

  *   Rolemaster Standard System (RMSS)
  *   Rolemaster Fantasy RolePlaying (RMFRP)
  *   Rolemaster Unified (RMU)

I will make a pull request later in the week.

Thank you and best regards,

Thibaut

De : Corey J<mailto:notifications@github.com>
Envoyé le :lundi 19 octobre 2020 19:34
À : Roll20/roll20-character-sheets<mailto:roll20-character-sheets@noreply.github.com>
Cc : Onirim<mailto:onirim@outlook.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [Roll20/roll20-character-sheets] Rolemaster 2nd / Classic sheet (new sheet) (#7539)


Interesting that the calculations differ so much between the sheets. I think that makes sense especially if there's room for the Role master express version to be added here. Swap out those tables and if you can get it in this should be good to merge if not this week then next.

**Pull request merged**
