### PR TITLE
Implement roll-template for all roll buttons.

### LINKED ISSUE #979: Stars Without Number: Initiative not using correct die
From a user:

"Rolling for initiative off of the character sheet uses 1d10+dex, but the rulebook (at least the free version from DriveThruRPG) says it's 1d8+dex."

### PR DESCRIPTION
**Pull request by jfredett**
What it says on the tin, the templates aren't the prettiest, IMO, but I used some NASA starfield image in the background, and it looks a hell of a lot nicer than the bare `/me`

Also adds defaults for attribute bonuses.

Also fixes a bug in the initiative button. The wrong die was being used (1d10 instead of 1d8). Fixes #979 

Bumps the version to 0.0.8

### CODE REVIEW

**Comment by jfredett** [comment]
As an aside -- if I need to make some breaking changes to the sheet (stuff that will, for instance, potentially change the names of some attributes) is there a way to specify an attribute migration?

In particular, I'm looking at separating out the 'culture' and similar skills into a repeating sheet, but that's going to break any existing values. Obviously I don't want to break players sheets, is there a process for this already in place?

**Comment by SteveKoontz** [comment]
There is no way to migrate attributes. Are these breaking changes necessary? Couldn't you have the default ones, limited in number in the skill list, then add a section for adding a repeating section if you want more below? That way it wouldn't break existing sheets?

**Comment by jfredett** [comment]
Clarification - There are no breaking changes in this pull.

As for the breaking changes, I think I can avoid them, but wanted to know if I had to work around them. The skill section is pretty messy, in terms of UX and the underlying code (I suspect it was created prior to repeating sections). I can probably work around that, but it just makes things harder.

What's the procedure if, say, I wanted to offer a 'version 2' that people could use w/ the improvements (maybe with some note that the existing sheet is deprecated?)

Mostly I think the limited-in-number version is a bit nasty, for my campaign, I don't mind a customized sheet, but if everyone can benefit from my UX improvements, that'd be awesome.

**Comment by SteveKoontz** [comment]
We'd be open to a overhauled version two of the sheet if it was substantially improved.

**Comment by jfredett** [comment]
Okay, I'll keep working on my new version, the point may end up being moot if I can keep it all compatible. For now, this pull was the last real set of changes I wanted to get in, my players are going to love it. Thanks!

**Pull request merged**
