### PR TITLE
AGE System 1.16

### PR DESCRIPTION
**Pull request by GhostMatter**
- I'm hoping this fixes the Default Sheet Settings once and for all.
(it would be helpful to be able to test it with a custom sheet instead of waiting for the merge each week)

### CODE REVIEW

**Comment by Karlinator** [comment]
I'm just going to jump in here and agree that there should really be a way for people without Pro accounts to test the changes they are making to character sheets. Some kind of system where you can set up custom sheets in a game, but only in games where you are the only player. Still keeps the ability to have custom sheets for a campaign as a Pro feature but allows Free and Plus users to actually contribute.

**Comment by GhostMatter** [comment]
Oh, that's wasn't what I was telling about. I was talking about Sheet Default Settings. I can't test them at all, Pro or not. On top of that, they are barely documented.

But... I definitely agree with you. My campaigns are on hold right now, so I'm basically paying Roll20 to create content for their website. I enjoy it and appreciate the opportunity, but it's still bothersome.
As for making custom sheets as a single player, that still has potential for abuse. I'd suggest giving that option for Sheet Authors and contributors only.

**Comment by GhostMatter** [comment]
Any further discussion should go in the forums I think, as not to clog GitHub!

**Comment by GhostMatter** [comment]
[Here's a forum thread](https://app.roll20.net/forum/post/3457170/allow-sheet-authors-to-make-custom-sheets)!

**Pull request merged**
