### PR TITLE
Earthdawn FASA Official - V315 - Bug Fixes and New Features

### PR DESCRIPTION
**Pull request by Jiboux**
# Submission Checklist
## Required

- [X ] The pull request title clearly contains the name of the sheet I am editing.
- [X ] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X ] The pull request makes changes to files in only one sub-folder.
- [X ] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

# Changes / Description

### CODE REVIEW

**Comment by nmbradley** [comment]
@Jiboux There are merge conflicts in this PR

**Comment by Jiboux** [comment]
Hello Nic,
I am unsure how there can be a conflict, and I have no way to resolve it
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

GitHub defines it by competing line changes. I am the only one editing this code, and this is the latest release.
Should I cancel & resubmit the pull request ? Any documentation I can look at to avoid the next pull request to be also in conflict ?

**Comment by BronsonHall** [comment]
Hey @Jiboux 

Merge conflicts can arise even when you're the only person changing the code.  In this case, it looks like this branch does not have your commits from last month in its history, so Github is uncertain how to resolve instances where your code differs from that last update.  

You shouldn't have to make a new PR, just merge those changes on master into this branch - which should prompt you to fix the conflicts.  As this is the latest version, you'll just pick this branch's code wherever there's a "clash", then commit those changes.  You'll be left with the same final state of code, but your previous work will be accounted for in commit history, letting Github know that this work is aware of those previous commits.  

To prevent this happening in future PRs, you'll want to make sure you are starting each new update branch in Github from a state that matches and reflects the current version of the sheet, with all your previous changes in its history.  This isn't always possible (say, for instance, you're working on two separate features simultaneously), so you can also just make sure to merge in the most current version of the sheet before you submit the PR.

**Comment by Jiboux** [comment]
OK, I think I'm good now... So the problem was I didn't merge my Jiboux repository to roll20 master before creating the new branch?

**Comment by NorWhal** [comment]
Hey @Jiboux! It's technically the opposite: you'd want to merge Roll20 Master into your repo to get the changes that are present on our end before submitting the PR. It looks like you've got it fixed, so you're good to go.

**Comment by Jiboux** [comment]
Thanks a lot for the merge...
Disgracefully as soon as loaded I saw a small bug that needed to be patched, so released a quick patch and did a pull. I know merges are weekly but am I too late for a quick merge ?

**Pull request merged**
