### PR TITLE
The One Ring 2e 2.0.1 - translation fix

### PR DESCRIPTION
**Pull request by bhuesemann**
## Changes / Comments

- Small translation fix
- trigger redeployment to hopefully fix roll-template

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by bhuesemann** [comment]
@nmbradley Hi Nic, the merge deployment today has not fixed the roll-template issue. A newly created game works when pasting the sheet as a custom sheet, but when selecting the sheet directly. All we see in a template based on a parsed-roll is this
image

**Comment by bhuesemann** [comment]
When I enter the same game as custom sheet this roll shows up correctly:
image

**Comment by bhuesemann** [comment]
What needs to be done to fix this? How can we help?

**Comment by nmbradley** [comment]
If I was going to make a guess, I would say something in your CSS is being thrown out by the character sheet service, and that for whatever reason the sheet sandbox is more tolerant.

For clarity, [only google fonts](https://wiki.roll20.net/CSS_Wizardry#Google_Fonts) can be safely imported via CSS. I would also advise running your CSS through a validator, as it's tripping a bunch of issues (mis-used variables, double semi-colons, etc.). I'd also advise using the plainest possible CSS in roll templates, and prefix every class with `sheet-`, just to be on the safe side. 

If you can work to eliminate these problems, I will investigate the sheet service logs to see if there's some issue being generated there.

**Comment by bhuesemann** [comment]
Hi Nic,
good catch. I think the syntax errors and sheet-prefix should be ok now for the roll-template. I'll take a closer look how to use standard fonts import in one of the next releases.

Hopefully this already makes the sheet usable.

Thx,
Bodo

**Pull request merged**
