### PR TITLE
Moldvay template revert to last version

### PR DESCRIPTION
**Pull request by MichaelCalleia**
## Changes / Comments

Had thought a pull would go to the original author to review. Reverting to the previous version. 

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by wing-it** [comment]
Please resolve the merge conflicts and resubmit.

**Comment by vince-roll20** [comment]
I can't comment on the merge conflicts... but a quick look at the css file that's submitted;
 there's an error on line 802

>    width:33px;s

That "s" after the colon can cause some problems and it should be removed.

**Comment by Lowe505** [comment]
still have no image background 
nnnnnnn
in chat box

**Comment by MichaelCalleia** [comment]
There is another pull request to try to fix that.

**Pull request closed without merging**
