### PR TITLE
New sheet: M.A.G.U.S. - Új Törvénykönyv

### PR DESCRIPTION
**Pull request by SirTocy**
This change contains files for a new character sheet for the hungarian
RPG M.A.G.U.S. - Új Törvénykönyv.

### CODE REVIEW

**Comment by pjbehr87** [comment]
Nice! I think this might be the first Hungarian sheet for Roll20.

**Comment by pjbehr87** [comment]
This commit was made to the wrong branch, please add this sheet to the master branch.

**Comment by SirTocy** [comment]
@pjbehr87 Could you tell me, how to add this to the master branch, please? Shall I simply merge the add-new-sheets-fork branch into the master branch on my repo and send another pull request?

**Comment by pjbehr87** [comment]
From your personal repo click the New Pull Request button, at the top of the screen it should have 4 drop-down menus. Make sure that base: and compare: are both set to master. That should let you open the same pull request you did before, only it will be against the master branch instead of the other one.

**Pull request merged**
