### PR TITLE
Mainly Minor Changes to NPC Sheet and Re-adding Translation Material

### PR DESCRIPTION
**Pull request by KPhan1212**
•	Changed the NPC’s Defenses section to make it more like the PC’s
•	Added an Armor Section for the NPC sheet
•	Changed the NPC’s Attacks Section to make it more like the PC’s.
•	Changed the Repeating Skills Section on the NPC Sheet to be more like the PC skills.
•	Fixed NPC Sheet’s Damage Threshold 
•	Fix NPC Sheet’s Condition Tracker
•	Fix NPC Grapple and Skills
•	Fix PC and NPC Sheet’s Weapon Damage, it should not be counting Non-Heroic Levels for damage.
•	Changed the NPC Grapple to function more like the PC Grapple

### CODE REVIEW

**Comment by wing-it** [comment]
Looking at the diff here on GitHub, it seems like there's still a significant number of translation keys being removed (for example, checkout lines 368-370). Can we get those added back in?

**Comment by KPhan1212** [comment]
Okay, I did it. I also added some translation materials that was missing, mostly strength in some skills.

**Comment by KPhan1212** [comment]
Huh, I didn't realize that all of my pull requests went to this one. Is there a way to turn them into separate requests? Or just remove them?

**Comment by Anduh** [comment]
If you make a pull request, and continue to improve the branch, the new commits are added to your pull request. If you want many, separate changes to get approved separately, have different branches for them and send a pull request from each.
It is possible to remove commits but I think it was a bit cumbersome. But still very doable.

**Pull request closed without merging**
