### PR TITLE
New sheet for Onyx Path's The World Below

### PR DESCRIPTION
**Pull request by chiptotlechris**
New sheet for Onyx Path's The World Below

# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by chiptotlechris** [comment]
This is a new character sheet for "The World Below" by Onyx Path

**Comment by NorWhal** [comment]
Hi @chiptotlechris 

I see you've marked this sheet as being made on behalf of Onyx Path Publishing, but you're not the usual name I see for Onyx Path sheets. Is this just a fan-made sheet that has been mislabeled?

**Comment by chiptotlechris** [comment]
Hi @NorWhal 
I'm a freelancer for Onyx Path, so while this is a fan made sheet, it does have sanction from the team there.

**Comment by nmbradley** [comment]
Hi Chris, sorry for the delay on approving this, but is there someone at Onyx Path we should reach out to contact about the sheet? 

Normally, our publisher relation team is aware of new sheets before they arrive, but this has taken them a little flat-footed. 

Just doing our due diligence, hope you can understand!

**Comment by chiptotlechris** [comment]
Matthew Dawkins is the creator and developer of this line, but Travis Legge should also know about this

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by NorWhal** [comment]
@chiptotlechris, we've reached out and Onyx Path has stated it's fine as a community sheet. If you want it to be raised to an official sheet, please have them reach out to our Partner Relations rep.

**Comment by chiptotlechris** [comment]
Hi Nora,

That's absolutely fine with me!

Cheers
Chris

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
