### PR TITLE
[Shadowbane Inquisition] Update v 0.1.2

### PR DESCRIPTION
**Pull request by ChtiKenny**
## Changes / Comments
v 0.1.2
+ Degrees of Failure have learned the correct Math
+ Psykana Powers now have damages options in a list
+ Psykana Powers now have a choice to roll hit location
+ you can now put a '+' in the modifier without breaking the roll
+ all Rolls will take unnaturals into account for Degrees of Success
+ all Rolls buttons can now be dragged into the Macro Bar

PS: @johnmoney-code have a look at how I did the unnat bonuses
PPS: how do I get the "Sheet Author" badge on my Roll20 Profile?

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
Hey there @ChtiKenny , in regards to the badge I will forward your question to the right people. Thanks for all the work you do ;)

**Comment by mperes** [comment]
Hey @ChtiKenny, just got the answer you were looking for:

> ~24 hours after a sheet is accepted and merged, if they put their user ID into the sheet.json, your badge should appear. If your haven't received it after a couple of days, you should check your sheet.json, and if it's properly inputted, your should open a ticket.

Cheers,
Miguel

**Comment by ChtiKenny** [comment]
Thanks @mperes, guess I'll have to open a ticket then.
By the way, for approving the sheet, you have the thanks of around ~150 people who use it (possibly more but I couldn't count them all)

**Comment by johnmoney-code** [comment]
That's terrifying, thanks for sharing

**Pull request merged**
