### PR TITLE
4e Sheets Lite

### PR DESCRIPTION
**Pull request by Derahex**
added all files

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by nmbradley** [comment]
Hi @Derahex 

What game system is this for?

**Comment by Derahex** [comment]
As indicated in the readme, this is is an alternative macro system for dungeons and dragons 4th edition. It is intended for larger scale guild play where complex sheets such as the current 4e sheet would slow down the game significantly.

**Comment by Derahex** [comment]
@nmbradley Sit rep on accepting the sheets?

**Comment by nmbradley** [comment]
@Derahex Apologies for taking so long on processing this; your submission fell into a significant enough gray area that nobody was quite sure what to make of it. In general, we try to only accept a single sheet for any given game, and there are already sheets for 4th Edition. We have made exceptions in the past for sheets that addressed some extra need, but this seems as though it is just existing functionality but isolated from another sheet.

I think, ultimately, this is not a character sheet and so doesn't belong in the character sheet repository. I'm also inclined to think that the use case for this macro is small enough that it falls squarely in the 'use the custom sheets functionality' bucket. 

I'm happy to hear arguments if you think you have a stellar one to merit its inclusion, but for now I'm going to close this.

**Comment by Derahex** [comment]
@nmbradley the merit of this sheet was that several people have asked to use this custom lightweight macro set, and not everyone wants to pay for the Pro subscription required to use custom CSS- me included. I thought that the roll20 community would have enjoyed this addition rather than exclude people for not having money to burn.

**Pull request closed without merging**
