### PR TITLE
Cyberpunk2020 terminal mistershades 20201202a

### PR DESCRIPTION
**Pull request by m1stershades**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by m1stershades** [comment]
First upload to repo

**Comment by m1stershades** [comment]
Loading core HTML, CSS, required media files and JSON.

**Comment by mperes** [comment]
Hey there @m1stershades, while there have been duplicate public sheets allowed in the past, going forward Roll20 wants to limit this practice. How does your sheet differs from the existing one for Cyberpunk 2020?

**Comment by m1stershades** [comment]
It’s a simpler layout, and I find it more intuitive to use than the
alternatives, which I find cluttered and have skills buried behind multiple
dialogs.

**Comment by mperes** [comment]
Hey there @m1stershades , I'm sorry to have to inform you that your PR will be denied. While there have been duplicate public sheets allowed in the past, going forward Roll20 wants to limit this practice. Your collaboration with existing sheets should not be restricted to translations, in fact in the spirit of community engagement, you should be able to push all sorts of features that would make running the game a better experience. Things such as the implementation of a setting that makes the sheet look completely different, like a dark theme or a completely revamped visual are completely valid additions you might consider.

**Comment by m1stershades** [comment]
Hi,

It does have a completely different look from the others - a dark theme,
simplified text, simpler layout, smaller and less intrusive logo, and a top
bar holding the most essential gameplay information.

It also adds journaling sections to track events and relationships, which
isn’t on other sheets.

Andrew

**Pull request closed without merging**
