### PR TITLE
Final changes for Fugue and Savage worlds Sheet

### PR DESCRIPTION
**Pull request by herrozerro**
I think I have fixed the issues with the last pulls

### CODE REVIEW

**Comment by bitspersecond** [comment]
Oh no!  The merge of The Beast!  :-)

**Comment by randal2k** [comment]
Why did this get reverted?

**Comment by SteveKoontz** [comment]
https://app.roll20.net/forum/post/1710699/savage-worlds-cs-merge-conflicts-guys#post-1713370

**Comment by randal2k** [comment]
oh.. that makes sense. ty

**Comment by herrozerro** [comment]
Can anyone tell me what i need to do about this whole merging and syncing thing?  I really dont know whats going on I have three branches, but I dont know what one i need to work on let alone why they dont seem to want to sync.

image

Roll20/master seems to be behind but it wont sync.
image

Do I need to be doing anything here?
image

**Pull request merged**
