### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by Zakarik**
Bugfix for all autocalc who bug after the last update of Roll20.

### CODE REVIEW

**Comment by wing-it** [comment]
I'm a little confused about what's going on here. for example, this change: `name="attr_energieBarbarianMax" value="@{energieBarbarian_max}"`. Since you changed the attribute name from "energieBarbarian_max", I don't see where that attribute is being set now.

Do these fields work with brand new characters? I'm thinking this will work for existing characters because that attribute is already set, but I'm concerned that new characters will not get that attribute set and those fields will break. Does that make sense?

**Comment by Zakarik** [comment]
The truth is, they're already set earlier. If you look at line 1628, you will see for example <input type="number" class="center" min="0" style="width:100%" name="attr_energieBarbarian_max" value="60+@{energieBarbarianModif}" disabled />.

Sorry about my English, I use an automatic translator.

**Comment by wing-it** [comment]
Ok, that makes sense! Sorry, I just wanted to make sure since I didn't see it.

We have a fix going out today to address the autocalc bug. Would you like to hold off on this update and just see if that fixes it, or would you rather me go ahead and merge this in?

**Comment by Zakarik** [comment]
I'd rather you merge. Maybe today's update will fix it or not. I prefer to be sure, by my update, that the bug will be fixed for this week. The players are counting on me for that.

**Comment by wing-it** [comment]
Sounds good to me!

**Pull request merged**
