### PR TITLE
[Crossed / Fates] Acts + Encounter Report Sheet

### PR DESCRIPTION
**Pull request by morgdalaine**
## Changes / Comments

New Character Sheet for CROSSED / FATES. Includes Act setup pages and Encounter Report Sheet once meeting your Sworn Rival on the battlefield!

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

### CODE REVIEW

**Comment by nmbradley** [comment]
@morgdalaine This sheet looks _great_. Stunning work. The code is beautiful, too.

I did want to clarify before submitting: was this work on behalf of the game publisher, or an effort you took on your own? It'll help us to tag appropriately :)

**Comment by morgdalaine** [comment]
Thank you so much! 

This is my own effort. I tried to get in touch with the creators, but I never heard back.

**Comment by nmbradley** [comment]
And what an effort it is! Thanks for the info. 

And because I know that our marketing team will be all over this: are there any socials we can reach you on, or is Github the best place to reach you? It's also fine to decline if you're not comfortable with spotlight :)

I will approve this momentarily.

**Comment by morgdalaine** [comment]
I'm @morgdalaine#0197 on Discord and @morgdalaine on Twitter. Discord is easier for me, but I can be reached either place!

**Pull request merged**
