### PR TITLE
[Forged In Dungeon] sheet update : legacy change

### PR DESCRIPTION
**Pull request by rotorri**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description
1. added legacy value to true at json file.
2. html, css all files has converted to legacy true sheet.
  - add prefix 'sheet-'
  - edit web font style

### CODE REVIEW

**Comment by nmbradley** [comment]
@rotorri Is there a reason you're changing to a legacy sheet? I'd highly recommend against it, they're worse in almost every way.

**Comment by rotorri** [comment]
> @nmbradley 
This issue is related to #11715 . The legacy value is set to default, but the roll template is not displaying properly. I couldn't find the issue in the developer sandbox, so I had to rework based on changing the legacy value.

**Comment by nmbradley** [comment]
Hi @rotorri 

I will investigate this issue and get back to you. It might be that you are failing CSS sanitization rules on the VTT.

**Comment by rotorri** [comment]
@nmbradley 
Thank you! I'll be eagerly waiting for your response.

**Comment by nmbradley** [comment]
@rotorri It appears that the font you had imported in your CSS was causing the failure. Anything that is in the CSS file when it is loaded into the sheet is prefixed with `.charsheet` with the exception of google font imports of a very specific style. This means that the first line of your css file was being listed as:

```.charsheet @import url('https://webfontworld.github.io/heiroflight/HeirofLight.css');```

This obviously was failing CSS validation and in turn meant that the whole stylesheet was not being loaded. 

I have removed this first line from the CSS and the roll templates are now loading correctly.

Unfortunately, this CSS validation is an essential part of our security measures on the VTT. Switching to legacy mode will not overcome this limitation. I would advise you to find a google font that can replace the removed file, or see if you can work with system fonts.

If you decide to use a google font, [here](https://github.com/Roll20/roll20-character-sheets/blob/master/Warhammer%20Fantasy%20Roleplay%204e%20Official/wfrp4.css#L1) is an example of how to format your import. The sanitizer is very specific about the syntax.

Sorry for the additional complication.

**Comment by rotorri** [comment]
@nmbradley 
Thank you for reviewing.

I couldn't find the problem on my own since it was showing up correctly in the sandbox.

I will try to make a different modification on the branch without changing the legacy and make a new PR.

**Pull request closed without merging**
