### PR TITLE
[Mothership Official] Swap Speed for Loyalty to match Player's Survival Guide

### PR DESCRIPTION
**Pull request by rjaduthie**
## Changes / Comments

This fixes the inclusion of Speed and not Loyalty for NPCs on the Mothership Official character sheet.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ Y ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ Yes, I would say so. ] Is this a bug fix?
- [ N ] Does this add functional enhancements (new features or extending existing features) ?
- [ Style is unchanged ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ The NPCs shouldn't have Speed anyway, unless I'm completely mistaken. ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ N/A  ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
@rjaduthie Have you spoken with @nmbradley  about this? This is an official sheet by the publisher, so they need to approve all changes.

**Comment by rjaduthie** [comment]
Good to know who to speak to.  I'd only posted on the Mothership Discord server.  I'm keen to hear whether these are welcome changes.

**Comment by nmbradley** [comment]
Hi @rjaduthie 

I'm going to reject this request on a couple of different issues:

- Speed is an element used by a number of official Mothership modules. Removing it would be problematic for that reason. 
- Changes to this sheet need to be made via Pug, rather than by directly changing the HTML. Otherwise, the next time it is compiled from Pug your changes will be overwritten.

**Comment by rjaduthie** [comment]
But surely Loyalty needs to featured on the sheet. It's a stat of an NPC featured in the PSG book.  I've not seen Speed used anywhere yet, although that's not to say it's not, of course; however, I have seen Loyalty (but not Speed) in The Black Pyramid.  Would you consider a feature request (or PR) to add it?

**Pull request closed without merging**
