### PR TITLE
Create sheet.json

### PR DESCRIPTION
**Pull request by MattBx8**
Created sheet.json for Warhammer40KWrathNGlory Character Sheet.

### CODE REVIEW

**Comment by Anduh** [comment]
You forgot to put everything in brackets and to put commas at the end of each row. The Sheet creation [readme](https://github.com/Roll20/roll20-character-sheets#creating-your-own) says to use use a online json validator so these mistakes can be avoided.

Example of a [correct, accepted sheet.json file](https://github.com/MattBx8/roll20-character-sheets/blob/0d29afa7ee82630860c946a175315371203febda/D6StarWars/sheet.json)

I recommend to have all files related in a single pull request/branch, it's both easier for yourself and for others. If you have made a pull request from one of your branches, you can continue working on the branch and push new commits, and your pull request will automatically update if you update your branch.

**Comment by MattBx8** [comment]
Thanks. I couldn’t upload my file so I opened it in the browser to copy over and it must have dropped the brackets and commas.

I’ll make the corrections.

/Matt

**Comment by Anduh** [comment]
Are you using the command line or the Graphical interface?

**Comment by MattBx8** [comment]
Website via Chrome browser. I also tried to upload the preview but couldn’t. 

Many apologies since my skill with GitHub is very limited. I’m mainly stumbling around, knocking things over, trying to figure it out. I’ll see if I can find a tutorial so I’m less of a pain in the ass.

/Matt

**Comment by Anduh** [comment]
Using the GUI or command line program might be less of a hassle, if you are doing this stuff a lot. I personally use command line, and to do that you you really use only 5-7 commands  and it keeps things much more organized. I did test the GUI in the beginning and iirc it was an improvement over just trying do thing in the browser. Sorry don't have any specific tutorial to point towards, I've just learned this from here and there(vidoes too) over the last half a year or so. But I think there is a t least a few good ~30min intro tutorials that might be a good starting point.

**Comment by Solarswordsman** [comment]
@MattBx8, I'll close these requests for now; please put your changes in a single branch and submit a new Pull Request after fixing the `sheet.json` formatting (you can verify that it is valid json by using https://jsonlint.com/) and including a preview image.

If you have any further questions, feel free to ask.

Thanks,
Jeff

**Pull request closed without merging**
