### PR TITLE
Crescent: Adding new character sheet

### PR DESCRIPTION
**Pull request by LoganSmithDarkLight**
## Changes / Comments
This change is adding the Crescent Character Sheet. For the time, the character sheet only includes the html and css, along with the preview picture and sheet.json.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by LoganSmithDarkLight** [comment]
Hello, I'm not sure why this is saying that checks are failing when I don't see any checks running. Is this a known issue with new sheets?

**Comment by Lockbox313** [comment]
> Hello, I'm not sure why this is saying that checks are failing when I don't see any checks running. Is this a known issue with new sheets?

The checks always fail for new sheets,  apparently they are only for updates to existing sheets.   There is nothing you need to do.

**Comment by LoganSmithDarkLight** [comment]
Hello again. I notice that this still doesn't have any reviews. Is there something I need to do on my end to have this looked at?

**Comment by LoganSmithDarkLight** [comment]
Hi @mperes @Lockbox313 , do you know when this will get looked at?

**Pull request merged**
