### PR TITLE
[Open Legend] Actions Section Major Update

### PR DESCRIPTION
**Pull request by BuildAndDie**
### 1.9.0 on 2018 May 7th
* Massive update to Favored & Other Actions sections
	- Select if action is an Attack (Damaging or Bane), Boon, or Effect
	- Effect isn't quite fully functional yet in that there is a pop-up that doesn't do anything, but will still roll the dice you choose
* Backgrounds for the borders updated
	- Also white background for things sent to chat
* Prep work for NPC/Alt Form/Companion tabs
	- Nothing functioning on the user side yet

### CODE REVIEW

**Comment by BuildAndDie** [comment]
Dang it, that last one "Roll Public or GM" I think is the same readme file in "GM roll option" just need to delete that I guess? Everything else should be fine. Was adding it to mark the issue fixed.

**Comment by joesinghaus** [comment]
You can probably just use the "resolve conflicts" option of Github to make this work.

**Comment by Solarswordsman** [comment]
I was so very close to fixing this for you. :P.  The problem is that you put the readme file in the root of the repository rather than in the character sheet's directory (or I guess, in both places).  `git rm ReadMe.md` in the root of the repo and commit that and submit a new PR and it should work fine.

**Comment by BuildAndDie** [comment]
just resubmitted it about 10 minutes ago :(  dang, wish I had known you were working on it. Darn my impatience.

**Pull request closed without merging**
