### PR TITLE
New SLA 2Ed Character sheet

### PR DESCRIPTION
**Pull request by seregrauko**
## Changes / Comments

I changfed the Table tags into DIV

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [X ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ X] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by seregrauko** [comment]
I have permission from Nightfall games to include game data in the character sheet, though I'm not sure how to go about verifying that statement

**Comment by mperes** [comment]
Hey there @seregrauko, could you ask a spokesperson from nightfall to drop a line here and confirm we are good to have game data in the sheet?

**Comment by seregrauko** [comment]
how would i get that? is this ok?

image

**Comment by jaredearle** [comment]
> Hey there @seregrauko, could you ask a spokesperson from nightfall to drop a line here and confirm we are good to have game data in the sheet?

Hi, I’m Jared Earle one of the founders and directors of Nightfall Games and we support this project. We are more than happy to have our game data on Roll20.

**Comment by seregrauko** [comment]
> Hey there @seregrauko, could you ask a spokesperson from nightfall to drop a line here and confirm we are good to have game data in the sheet?

Hi Is Jared's reply good enough?

**Comment by mperes** [comment]
Sure it is, thanks @seregrauko !

**Comment by seregrauko** [comment]
currently rejigging it again.. big changes to the way it works

**Pull request merged**
