### PR TITLE
Update Pendragon.html

### PR DESCRIPTION
**Pull request by Taliesin1**
Some minor label changes — capitalized skills, etc. Changed "Pious" to "Spiritual" per Book of the Estate and later. Changed Passions to follow the KAP convention so that "Love of Family" becomes Love (Family), etc.

### CODE REVIEW

**Comment by tontione** [comment]
Ok for me.

**Comment by Taliesin1** [comment]
Thanks, Steve —

How long will it take for the changes to show up. The character sheets still look the same in my game.

Not trying to rush, just curious.


Thanks,


M.

**Comment by SteveKoontz** [comment]
Updates to the code don't get deployed until we restart the servers, which will most likely happen sometime in the next 24 hours, unless there is some kind of delay.

**Comment by Taliesin1** [comment]
Okay, that’s good to know.


Thanks,


M.


> On Jan 15, 2015, at 11:45 AM, SteveKoontz <notifications@github.com> wrote:
> 
> Updates to the code don't get deployed until we restart the servers, which will most likely happen sometime in the next 24 hours, unless there is some kind of delay.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Roll20/roll20-character-sheets/pull/562#issuecomment-70128128>.
> 

Thanks,


M.

**Pull request merged**
