### PR TITLE
Converted to English

### PR DESCRIPTION
**Pull request by Jedra7609**
Converted to English from Swedish version

### CODE REVIEW

**Comment by pjbehr87** [comment]
I'm sorry, but we [no longer accept new sheets that are just an alternate translation to an existing sheet](https://app.roll20.net/forum/post/3762625/policy-change-for-alternate-translation-character-sheets). If you would like to add a new translation for this sheet, please update the original sheet to use [Roll20's sheet translation tools](https://wiki.roll20.net/Character_Sheet_i18n).

**Comment by aunderwo** [comment]
Hi @Jedra7609 are you still hoping to make this sheet English compatible? I can make a start if you'd like.

**Comment by Jedra7609** [comment]
Hi,

I converted the sheet into English and submitted it but it seems they can't accept it this way.  The original will need to be re-written to allow the inbuilt Roll20 translation tools to work.

**Comment by aunderwo** [comment]
@Jedra7609 i can have a go if you are ok with that

**Comment by Jedra7609** [comment]
Go for it!

**Pull request closed without merging**
