### PR TITLE
[Pathfinder] v1.58 damage by size update

### PR DESCRIPTION
**Pull request by plutosdad**
Fix to damage dice when changing size between small and medium
Fix to frequency fields showing on new abilities even when N/A

### CODE REVIEW

**Comment by wing-it** [comment]
We can't view the diff, just wanted to make sure you meant to delete 14k lines from your html file?

**Comment by plutosdad** [comment]
that doens't sound right,

**Comment by plutosdad** [comment]
OMG hold on, ill fix it in a minute

**Comment by wing-it** [comment]
Good, that did seem a little strange ;)

**Comment by plutosdad** [comment]
OK i added the missing lines back. thanks. The problem was one of the source files is named "index.html" and the build file is named "index.html" And I pasted in the source file apparently. probably i should give it a different name. Maybe automate the upload too.

**Comment by plutosdad** [comment]
thanks for letting me know. the users would be after me with pitchforks!

**Comment by wing-it** [comment]
No problem!

**Pull request merged**
