### PR TITLE
New character sheet for Cyberpunk 2020

### PR DESCRIPTION
**Pull request by micka9fr**
Hi

I have create a new character sheet for Cyberpunk 2020. I have used it in custom mod for my campagne of cyberpunk and I think that the sheet is ready to be shared with the others.

My sheet is more compact and have specific section for contacts, background, life event, ... and the sheet include two combat system for cyberpunk. The Friday Fire Night and the Saturday Night Shuttles given by cybergeneration 2027 and "listen up primitive..." book.

It's my first sheet and I hope that I have correctly follow the protocol.

### CODE REVIEW

**Comment by wing-it** [comment]
There are a number of xml files included in this commit, could you remove those?
Also, is there a reason why this is being submitted as a separate sheet, rather than as an upgrade to the existing sheet? If all of the changes are positive upgrades that would benefit all users, it may be best to commit these changes directly to the current sheet. If you are unsure what current users may think, feel free to make a post in the Roll20 character sheet forums.

**Comment by micka9fr** [comment]
Hi thanks for your reply and sorry for this late answer. 
My character sheet 2k20 is different from the cyberpunk 2020, so it's a new sheet. I'm not the author of the first character sheet and I don't have use the code, but I read it to inspire me, because it's my first character sheet. I have create the cyberpunk 2k20 from scratch. It's for this raison that I have call it 2k20 and not 2020 to mark the difference.
I don't understand what you mean about xml, I thought that it was a needing for post a new character sheet. Could you help me because I m a little lost ? What must I do to post my sheet to roll20 ?

**Comment by wing-it** [comment]
Your files in your character sheet folder (your html, css, json and the logo) all seem fine and to go. The only thing you're missing in that folder is the image for the preview (you have it listed correctly in your sheet.json, however it doesn't look like you've actually added it).

All of the other files (I see 9 .xml files) should be removed before I can merge. When you remove those files and add the preview image, I can add your sheet with our next merge! Let me know if you need any further help.

**Comment by Solarswordsman** [comment]
@micka9fr 
You'll need to take a a screenshot of your character sheet and name it as you have in your `sheet.json` and commit a change that removes the extra .xml files.  You can see those xml files we're talking about if you see the "Files Changed" tab here in the pull request--those are extra files generated by some software you're using and shouldn't be committed to the git repository.

**Comment by micka9fr** [comment]
Hi sorry for to my late answer, my girl is born this previous sunday and this last days was rock'n roll (and maybe the future next days too). So I have add the preview picture. For the 9 xml, I see them in the pull request but I don't see them in the directory of new cyb2k20 character sheet. I don't know where they come. Can I remove them from the pull request whitout damage ?

**Comment by micka9fr** [comment]
Maybe they could come from PhpStorm software... I will delete It.

**Comment by micka9fr** [comment]
Damn !!  I don't know how remove this parasites files.... :-(
Could you help me ?

**Comment by RhOmicron** [comment]
https://github.com/micka9fr/roll20-character-sheets/find/master search for .xml . Trash them.
https://github.com/micka9fr/roll20-character-sheets/ Make new pull request.
This in my mind should work.

**Comment by micka9fr** [comment]
Maybe it s sound good now ?

**Comment by RhOmicron** [comment]
Looks good to me.

**Comment by wing-it** [comment]
Looks ok to me, congratulations on the birth of your daughter!

**Pull request merged**
