### PR TITLE
Chroniques Oubliees: version 4.02

### PR DESCRIPTION
**Pull request by Ulty**
## Changes / Comments
* Add more fine-grained attributes for purse
* Add equipment tab for NPCs.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [x] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
There is a report on missing stats for the sheet, in [this forum thread](https://app.roll20.net/forum/post/9380852/lost-info-chroniques-oubliees-sheet/?pageforid=9383052#post-9383052)

**Comment by Ulty** [comment]
Thank you for reporting the thread, @Anduh !

**Comment by Anduh** [comment]
Did this commit fix the things mentioned in the thread?

**Comment by Ulty** [comment]
> Did this commit fix the things mentioned in the thread?

No, the things mentioned in the thread were already fixed by the previous commit.

**Pull request merged**
