### PR TITLE
[The Between] - new sheet

### PR DESCRIPTION
**Pull request by cbkcook**
Added a new sheet for The Between. It's a Powered by the Apocalypse game.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by nmbradley** [comment]
@cbkcook I just want to check before I approve and merge this: are these playbooks publicly released for free somewhere?

There's a lot of rules text in this submission (i.e. moves, etc) and I can't find any free downloads from the publisher, or indication that they're willing for their rules to be distributed in this way.

Happy to accept this merge if you can point us to a relevant download, or have someone from the Gauntlet reach out to give us the okay.

**Comment by cbkcook** [comment]
It's on DriveThru RPG. https://www.drivethrurpg.com/product/360858/The-Between
If I need to get more than that, I could try to reach out to them.

**Comment by cbkcook** [comment]
They've got a play aid for it in their repository that has the same text, plus more: https://docs.google.com/spreadsheets/d/1swJvxv6hft19txV69UoaosrZD_HL7Ne3k7MitEfl5rk/edit#gid=2124648911

**Comment by nmbradley** [comment]
Perfect. Thank you for humoring us. I'll accept this shortly.

**Pull request merged**
