### PR TITLE
Vampiro - Sozinho na escuridão

### PR DESCRIPTION
**Pull request by jarbascjunior2**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <> (Vampiro sozinho na escuridão)
- The publisher of this game is: <> (101games)
- The name of this game system/family is: <> (Solo10)

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <[   ](https://www.101games.com.br/product-page/vampiro-sozinho-na-escurid%C3%A3o)>
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Review by jarbascjunior2 — COMMENTED** [review]
Ajustei os nomes dos arquivos.

**Comment by jarbascjunior2** [comment]
Change names

**Comment by kfroll20** [comment]
Hello @jarbascjunior2, 

Thank you for your contribution! A couple of things before we can move forward with merging your sheets:

First, we no longer allow `<table>` elements in sheets for purposes of layout. Old sheets are grandfathered in to this requirement, which is why you may see these elements in some existing sheets, but it is enforced on all new sheets for this repo. You'll need to swap these out in favor of other layout methods - more info on why this is can be found [here](https://wiki.roll20.net/Designing_Character_Sheet_Layout).

Second, you have two sheets in this PR. We can only merge one sheet at a time so I recommend you remove one of the sheets from this PR and open a second PR for it. 

Please let me know if you have any questions!

**Comment by jarbascjunior2** [comment]
> Hello @jarbascjunior2,
> 
> Thank you for your contribution! A couple of things before we can move forward with merging your sheets:
> 
> First, we no longer allow `<table>` elements in sheets for purposes of layout. Old sheets are grandfathered in to this requirement, which is why you may see these elements in some existing sheets, but it is enforced on all new sheets for this repo. You'll need to swap these out in favor of other layout methods - more info on why this is can be found [here](https://wiki.roll20.net/Designing_Character_Sheet_Layout).
> 
> Second, you have two sheets in this PR. We can only merge one sheet at a time so I recommend you remove one of the sheets from this PR and open a second PR for it.
> 
> Please let me know if you have any questions!

Thanks, I just finished to ajustments in the issues. I will submit again.

**Review by jarbascjunior2 — COMMENTED** [review]
I do the ajustments. Thank you.

**Comment by jarbascjunior2** [comment]
Thank you, I just do that.

Em ter., 16 de jul. de 2024 às 16:34, Kayla Fischer <
***@***.***> escreveu:

**Comment by jarbascjunior2** [comment]
Hi, i want to know if is just ok to merge it the sheet?
If I need to do something else, let me know please.
Thanks for your time.

Em ter., 16 de jul. de 2024 às 17:46, Jarbas Carneiro junior <
***@***.***> escreveu:

**Comment by NorWhal** [comment]
Hello, @jarbascjunior2 

One last issue that we didn't catch earlier - per our [minimum requirements](https://help.roll20.net/hc/en-us/articles/360037773453-Minimum-Requirements-Best-Practices), we cannot have `<html>` `<body>` or `<head>` tags, since these will cause your sheet not to load in the VTT.

Thanks,
Nora

**Comment by jarbascjunior2** [comment]
thank you, does there exist a manual, how to do that, or I just need to
delete these lines?

Em qui., 18 de jul. de 2024 às 14:12, Nora Cahill ***@***.***>
escreveu:

**Comment by jarbascjunior2** [comment]
I already do that, can you see if I do  alright?

Em qui., 18 de jul. de 2024 às 14:21, Jarbas Carneiro junior <
***@***.***> escreveu:

**Comment by jarbascjunior2** [comment]
Hi. It's everything ok now?

Thanks for the feedback.

**Comment by kfroll20** [comment]
Hello @jarbascjunior2!

Just a couple more tiny things before we can get this merged.
1. Please remove the html tag (line 1) 
2. Please remove the css for the body. We recommend you use the [sandbox](https://wiki.roll20.net/Custom_Sheet_Sandbox) to test your sheet to ensure it will work as expected once merged and published. 

I'll keep an eye out today for any follow up fixes or questions. 
Thank you!

**Comment by jarbascjunior2** [comment]
Thanks I’ll do it now.

Em ter., 23 de jul. de 2024 às 15:44, Kayla Fischer <
***@***.***> escreveu:

**Comment by jarbascjunior2** [comment]
I have already adjusted it.
Thanks for your time and feedback.

Em ter., 23 de jul. de 2024 às 15:49, Jarbas Carneiro junior <
***@***.***> escreveu:

**Comment by jarbascjunior2** [comment]
I hope that everything is okay now.

**Comment by kfroll20** [comment]
Thank you for updating, @jarbascjunior2!

From the code side of things, everything looks good and ready to merge. One last thing that needs to be done is fill out the three fields above.

image

**Comment by jarbascjunior2** [comment]
Thanks I'll do it now.

**Comment by jarbascjunior2** [comment]
I Just do it!

**Comment by jarbascjunior2** [comment]
Please, is it possible to merge it today?

Thanks.

Em qui., 25 de jul. de 2024 às 14:43, Kayla Fischer <
***@***.***> escreveu:

**Comment by kfroll20** [comment]
> Em qui., 25 de jul. de 2024 às 14:43, Kayla Fischer <

Yes! It will take a few minutes to build before you can view it on Roll20. Thank you for your patience and understanding!

**Comment by jarbascjunior2** [comment]
Thank you for your advice and kindness.

Em qui., 25 de jul. de 2024 às 15:14, Kayla Fischer <
***@***.***> escreveu:

**Pull request merged**
