### PR TITLE
New character sheet for Svärd & Svartkonst

### PR DESCRIPTION
**Pull request by zo0ok**
## Changes / Comments

This is a new sheet for Swedish OSR game Svärd & Svartkonst.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by zo0ok** [comment]
I am informed that Character Sheet Validation fails, but I see no "errors below". So I do not know what to fix and if I start changing things I risk breaking things that worked.

I am new here. Please give me a hint.

Thanks.

**Comment by Anduh** [comment]
My comment from your previous PR:

> The validation fails for all new sheet submissions, really only works for PRs updating existing sheets.
> 
> But yes all sheet should use **legacy=true**, as the sheet update haven't been implemented yet. (if you look at any existing sheet, they are using **legacy=true**.
> 
> Everything looks good on a quick skim.
> 
> Jag har bra koll på dehär med roll20 character sheets, och relaterade processerna.
>
> **Suggestion:**
> * using `character_name` instead of `namn` for the character name is a good idea, as then the character name is automatically updated to the character's name as it is seen on the Journal page, and can more easily be used by a linked token.
> * It can be useful to add `@{character_name}` to the roll template, so it's more clear what character does the roll if a person(like the GM) controls several characters. Right now you only see what real person does a roll, not what player character/NPC did it.

**Comment by zo0ok** [comment]
> > Everything looks good on a quick skim.
> > using `character_name` instead of `namn` for the character name
> > It can be useful to add `@{character_name}` to the roll template

Thank you! I updated to character_name and made use of it. That was clearly better.

Now the validation error indicates it is a new sheet that has not yet been added to the approved file.
So perhaps it is good now.

Any suggestions most welcome. This is my first contribution here.

**Comment by Anduh** [comment]
I'd say it's good as well, just wait until it gets reviewed by a human, probably happens in a couple of days. They will manually add the sheet to the `approved.yaml` file.

**Pull request merged**
