### PR TITLE
[Vampire the Masqerade 5th edition] New Dark Ages sheet

### PR DESCRIPTION
**Pull request by chiptotlechris**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by chiptotlechris** [comment]
This is a dark ages version of the V5 character sheet for Vampire the masquerade. All details are in the folder V5-DarkAgesVampire and ahve been tested and validated

**Comment by Anduh** [comment]
What's the reason this "New Dark Ages" thing is submitted as a separate sheet, and not as an enhancement/option to the existing sheet? Is it a separate game, or does it only change a few things? 

Roll20 would likely also ask this on Monday. They try to keep as few sheets as possible in the repo to keep thing easier, and avoid duplicate work, so explaining why this wasn't integrated to the main sheet is likely a good idea to avoid a delay in having the sheet approved.

**Comment by chiptotlechris** [comment]
The Dark ages sheet Changes a number of Graphics and design elements as well as a number of Skill names. Dark ages as a Setting in VtM still has a lot of core similarities, but is considered different enough in game terms.

**Comment by clevett** [comment]
Greetings,

This pull requests is being closed as character sheet failed to meet the requirements laid out in [Building Character Sheets](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository). If you wish to submit the sheet again please update the code and create a new pull requests.

Thank you,

**Pull request closed without merging**
