### PR TITLE
Mongoose Publishing Traveller 2e Official Character Sheet - New Sheet

### PR DESCRIPTION
**Pull request by madbeardman**
# Submission Checklist
## Required

- [X] The pull request title clearly contains the name of the sheet I am editing.
- [X] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X] The pull request makes changes to files in only one sub-folder.
- [X] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: < Traveller 2e  >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: < Mongoose Publishing  > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < Traveller  > _(i.e. Dungeons & Dragons, FATE)_

- [X] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [X] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

This is an official version of the Community Character sheet that's been in use. It now has official Mongoose support including images and logos.

### CODE REVIEW

**Comment by madbeardman** [comment]
@NBrooks-Roll20 - Thanks for letting me know. I've gone back to the dev who has updated this Character Sheet (from the Community version) in the last year. All we wanted to do was to make it an Official character sheet now. Thanks, we shall be in touch.

**Comment by kfroll20** [comment]
> @NBrooks-Roll20 - Thanks for letting me know. I've gone back to the dev who has updated this Character Sheet (from the Community version) in the last year. All we wanted to do was to make it an Official character sheet now. Thanks, we shall be in touch.

@madbeardman, we can just go ahead and switch the existing community sheet to being official without adding a new folder/PR to this repo. Should we go ahead and do that for you?

**Comment by madbeardman** [comment]
@NBrooks-Roll20 - No need. I got the community dev to update this version, as it has the official logo and trademark that the community one isn't allowed to have. 

So please let me know if there are any more issues, thanks - MBM

**Comment by kfroll20** [comment]
@madbeardman, thank you for updating the sheet to exclude tables.

I noticed that you added the new html/css files that exclude the use of tables, however the `sheet.json` still reference the old html and css files. Would you mind deleting the files that are not used in this sheet/PR and updating your `sheet.json` to use the new files?  Once that is done, I will get this merged and published!

**Comment by madbeardman** [comment]
@kfroll20 - I've stepped in and tidied up the files needed. I hope everything is now good. Thank you!

**Pull request merged**
