### PR TITLE
Adding character sheet for FASATrek

### PR DESCRIPTION
**Pull request by SETRusty**
Star Trek RPG by FASA from the 1980's - This character sheet is not 100% complete but I am looking for the ability to preview some of the formatting and calculations in Roll20.

### CODE REVIEW

**Comment by pjbehr87** [comment]
You don't need to include the header, it will actually get stripped out. The css file that you link in the sheet.json is the one that will be included with the sheet.

**Comment by SETRusty** [comment]
Ahhh ... Gotcha! I'll note that for the next rev of the sheet.

Thanks kindly!

SETRusty

**Comment by pjbehr87** [comment]
Also, please change the options in the text editor you are using to use the line ending LF instead of CRLF. The system our servers are running on are unix and expect the standard unix line endings (LF).

**Comment by SETRusty** [comment]
Thanks for the fix. I'll pull down once my GM and I have a look at what we've got. Thanks a bunch for the help here!

SETRusty

**Pull request merged**
