### PR TITLE
New Game (HITOS)

### PR DESCRIPTION
**Pull request by kinower**

### CODE REVIEW

**Comment by kinower** [comment]
I thought it was ok and I closed it, but no. and I have reopened it

**Comment by kinower** [comment]
I have to wait for your to close it?

**Comment by Anduh** [comment]
The PR have to be merged, not just approved. Cassie goes the rounds on Mondays and comments or approves the PRs, and on Tuesdays merges them.

**Comment by kinower** [comment]
ok, then I leave this open to be approved.
Thank you

**Comment by Anduh** [comment]
And merged. You don't close it yourself, it will be closed by cassie automaticly when it's merged

**Comment by kinower** [comment]
ok, thanks

**Comment by kinower** [comment]
hello, it's a mistake, it's an update

**Comment by kinower** [comment]
I can not edit the list

**Comment by clevett** [comment]
Greetings @kinower 

I'm going to close this pull request as it has updates to a different sheet. You can reset your repository to the Roll20 repository then submit a new pull request with just the sheets you want to change. 

Thanks,
Cassie

**Pull request closed without merging**
