### PR TITLE
10/2020 update, last commit try

### PR DESCRIPTION
**Pull request by yagrima**
## Changes / Comments

This time without any translation files...

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Stexinator** [comment]
@yagrima please look at the checkboxes

**Comment by yagrima** [comment]
I am forced to do this commit the sixth time ...

Fixed for magic, functional enhancement for matrix, no changes in aesthetics, no need to preserve data.

**Comment by Stexinator** [comment]
But why? What was the problem the first five times?

**Comment by yagrima** [comment]
Compatibility issues. The first commit had an older timestamp. Afterwards translation files were included as I wasn't aware that only commits via your translation solution are acceptable. It took some iteration to get the information.

**Pull request merged**
