### PR TITLE
3DX New Sheet

### PR DESCRIPTION
**Pull request by Vitones91**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <3DX>  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <Victor Ballogh> _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <3DX> _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] This sheet has been made on behalf of, or by, the game's publisher.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <https://www.sistema3dx.com.br>
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by Vitones91** [comment]
*The publisher of this game is: Victor Ballogh

**Comment by mperes** [comment]
Fala @Vitones91, muito organizado o código da ficha. Show!

**Comment by Vitones91** [comment]
> Fala @Vitones91, muito organizado o código da ficha. Show!

Opaa, muito obrigado @mperes! Espero que esteja tudo certinho para a aprovação.

**Comment by mperes** [comment]
Sim, acabei de publicar.

**Comment by Vitones91** [comment]
> Sim, acabei de publicar.

Não tinha visto, show de bola, valeu!

**Pull request merged**
