### PR TITLE
Tremulus RPG

### PR DESCRIPTION
**Pull request by JBeighel**
## Changes / Comments
Added a sheet for the Tremulus RPG, simply named "Tremulus".  This is another one that is powered by the Apocalypse game engine.  The game's publisher's site is here:
https://realityblurs.com/shop/catalog/setting/tremulus/

This sheet was not added to resolve a bug request or fulfill another user request.
There are no changes to any existing sheets, so no player data needed tested.

To the best of my knowledge/ability this conforms to the character sheets standards.  This is my first attempt at making one, so my apologies in advance for anything I overlooked.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by WallaceMcGregor** [comment]
Thanks for adding the sheet for a great game. You'll make it to allow translations?

**Comment by JBeighel** [comment]
My players found a problem with some of the character attributes, so I'll be in the code anyway.  I read over the documents from roll20 on using i18n for translation, so I'll try to work that in as well.  It doesn't seem complicated, just tedious.  I've never done it before, so hopefully I don't mess it up.

**Comment by clevett** [comment]
Greetings @JBeighel 

You code has been merged but "Tremulus.json" will need to be renamed to sheet.json in order for it to appear in the drop down list.

Thanks,
Cassie

**Comment by JBeighel** [comment]
Sorry about that name, I can change that easily enough.  I'll set up another pull request to get that updated.

Thanks for setting me straight!

**Pull request merged**
