### PR TITLE
[Malefices 4th Ed] New Feature: internationalize sheet

### PR DESCRIPTION
**Pull request by Fahrenholz**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description
Internationalization of previously hard-coded french sheet

### CODE REVIEW

**Comment by Fahrenholz** [comment]
@Le-Pelican Comme on avait dit: La base pour la traduction est faite.

**Comment by NBrooks-Roll20** [comment]
Hi @Fahrenholz! While this PR is waiting for original author response, I was taking a look at your translations, and noticed that on line 676 you wrote `characteristics-title-perception` when you seemed to mean `characteristics-rollname-perception`.

**Comment by NBrooks-Roll20** [comment]
Hi @Fahrenholz, we do need original author approval for this PR, and they haven't responded yet. We'll be closing this PR, but you can re-open when the author is available to approve this.

**Comment by Le-Pelican** [comment]
Bonjour
Désolé je n'avais pas vu les alertes par mail. 
J'approuve cette mise à jour.
Merci

**Review by Le-Pelican — COMMENTED** [review]
Bonjour
Ok pour ces changements

**Pull request closed without merging**
