### PR TITLE
Shadowrun sixth world v.46

### PR DESCRIPTION
**Pull request by jaculpiii**
Worked around roll20 issue with more than 10 rolls causing computed results to not be displayed for spells.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ Y ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ Y ] Is this a bug fix?
- [ N ] Does this add functional enhancements (new features or extending existing features) ?
- [ N ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ NA ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ NA ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Anduh** [comment]
did you intentionally delete the Readme?

**Comment by jaculpiii** [comment]
Yes it was causing the newline issues and is no longer needed so I wanted it gone.  The repo wouldn't let me delete it so I just wiped it's contents.

**Comment by nmbradley** [comment]
@jaculpiii appears that there is a conflict between this branch and the one you submitted prior to this. 

Let me know when you've resolved them and I'll merge it in.

**Comment by jaculpiii** [comment]
> 
> 
> @jaculpiii appears that there is a conflict between this branch and the one you submitted prior to this.
> 
> Let me know when you've resolved them and I'll merge it in.

Fixed the conflict I believe.

**Comment by nmbradley** [comment]
Awesome, thanks! Merged.

**Pull request merged**
