### PR TITLE
Submit New [Chronica Feudalis] sheet

### PR DESCRIPTION
**Pull request by okadus**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <  Chronica Feudalis  >  
- The publisher of this game is: <  Cellar Games, LLC  > 
- The name of this game system/family is: < Chronica Feudalis  > 

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by okadus** [comment]
what can i do to fix the problem ?

**Comment by nmbradley** [comment]
Hi @okadus 

Can you please complete the below sections of the Pull Request so that we can add this to the system?



```The name of this game is: < > 

The publisher of this game is: < > 

The name of this game system/family is: < > ```

**Comment by okadus** [comment]
Of course, I have just completed the requested sections

**Comment by mperes** [comment]
Hey @okadus, how are you doing? I am seeing you have included some translation on your PR, however we try to don't allow translation straight within git pull requests in order to avoid conflict with crowdin. Could you please remove those and update your PR?

**Comment by okadus** [comment]
Hi, 
I tried to do it, I hope it's good. I'm not very good at GitHub.

Thanks for taking the time to handle my request

**Pull request merged**
