### PR TITLE
[Pokemon Tabletop Adventures] Bug fixes

### PR DESCRIPTION
**Pull request by AdrienGAIRE**
Minor bug fixes & changes:
 - Changed the name of "attr_pokemon_HPXmax" to "attr_pokemon_HPX_max" for consistency
 - Changed the name of "attr_Pokemon_HPX" to "attr_pokemon_HPX" for consistency
 - Corrected a bug where nature-related stat where not kept inbetween sheet openings
 - Corrected the roll for damage to include the specificated damage bonus (movedmgbonusXX)
 - Added the "N/A" option in the damage move stat, for non-damaging moves

### CODE REVIEW

**Comment by Anduh** [comment]
I'm sure you're aware that existing games using those stats will "lose" them, and have to be manually re-entered unless you make a sheetworker to migrate the attributes. But it's probably not a problem if there exists only very few players.

Regards, someone who have made the mistake in the past

**Comment by AdrienGAIRE** [comment]
To be honest, this is the first time I try to contribute, so no, this problem kind of flew over my head ^^'
But yeah, my group already had to remake part of their sheets with the last update...

Should I first only do the fixes? (i.e. the last three points)

For the max HP, it shouldn't be a problem as this stat is automatically calculated, but for the current HP, this can be an inconvenience...

**Comment by Anduh** [comment]
Well, I'd suggest to re-submit the pull request without the attribute-namechange until you add a sheet-worker that does the attribute transfer. It' should be relatively simple but I haven't done it myself nor do I really know or understand them yet. And there is another update by someone else, it might be smart to coordinate you efforts with the sheet author.

**Comment by AdrienGAIRE** [comment]
Well, let's do that!

**Pull request closed without merging**
