### PR TITLE
Update prowlersnparagons.html

### PR DESCRIPTION
**Pull request by finderski**
Corrected the Display issue reported on the forums.

## Roll20 Requests

*Include the name of the sheet you made changes to in the title.*

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by finderski** [comment]
Updates in this commit:
Prowlers and Paragon sheet updated to correct a visual discrepancy.

Added an Upgrade warning to the Savage Worlds Tabbed sheet about the upcoming upgrade to support SWADE.

As part of the Savage Worlds Tabbed update, also uploading the background images in preparation for migrating the code to use GitHub instead of my private website (which I'm currently using for hosting R20 character sheet images)

**Comment by finderski** [comment]
Yes, those are intentional.  I submitted the SW changes at a later time and added a comment to the Pull Request. I was hoping to have a separate Pull Request just for the savage worlds stuff, but I guess Git doesn’t work like that… 

Finderski

**Comment by clevett** [comment]
@finderski 

You can do separate pull request by using branching. You can upload a branch to your fork then submit a pull request directly from that branch to the Github repo. You just have to make sure that your master fork then gets updated with the new changes after the Tuesday deploy.

 I don't mind you doing it this way. My apologies for missing the second comment there.

Thanks,
Cassie

**Comment by Anduh** [comment]
https://guides.github.com/activities/hello-world/#branch might explain and illustrate branches well enough

**Pull request merged**
