### PR TITLE
fixing issue in starfinder initiative

### LINKED ISSUE #3049: Starfinder NPC Initiative issue
1) When I roll Init on the NPC section of a character sheet, it always adds a +4 initiative regardless of the modifiers I put in. 
2) the DEX mod is always 0 here even if the dex-bonus is filled in at the lower portion of the sheet.
3) the tiebreaker is always 0.04

### PR DESCRIPTION
**Pull request by makupi**
DEX-bonus was taken from character not npc, edited npc initiative and -bonus' to proper -npc namings
fixes #3049

### CODE REVIEW

**Comment by Acyd69** [comment]
Thanks for catching this. I appreciate the help in correcting it as well. Next time though, please contact me regarding the problem. I maintain a couple of copies of the code for this sheet outside of Github and would likely overwrite changes made by others on a subsequent pull requests.

**Comment by makupi** [comment]
Sure, absolutely no problem. I just didn't know any way to contact you :)
Glad to help, and thanks for the work on the sheet!

**Comment by wing-it** [comment]
@makupi @Acyd69 As mentioned above, there did end up being some conflicts with the section in question. Could one or both of you take a look and resolve those conflicts?

**Comment by makupi** [comment]
@wing-it the conflict seems to be exactly my solution for the npc initiative issue. But i would leave @Acyd69 the final word on this, maybe he want's to change the naming scheme or anything.

**Comment by Acyd69** [comment]
Thank you both. @wing-it please close this pull request without action. I will include the necessary bug fix in next week's pull request. @makupi you can contact me easily on Roll20.net by using the Community Forums. This character sheet has a growing thread at [https://app.roll20.net/forum/post/5576780/starfinder-simple-character-sheet](https://app.roll20.net/forum/post/5576780/starfinder-simple-character-sheet).

**Pull request closed without merging**
