### PR TITLE
Dc heroes megs - bugfix and initiative button

### PR DESCRIPTION
**Pull request by mariusbax**
## Changes / Comments
Second attempt at submitting changes for the DC Heroes MEGS sheet. A small bug-fix where journal entries were not saved and added an initiative roll button.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ x] Is this a bug fix?
- [ x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mariusbax** [comment]
I see that I again have submitted changes to two sheets. I have no idea how the sheet.json and Aventures.css changes happened. Still trying to learn Github. Sorry for this.

**Comment by mperes** [comment]
Dear @mariusbax are you using the command line or the desktop version of git?

**Comment by mariusbax** [comment]
I've been using the desktop version, it seemed safer for a newbie. But I'm not (very) afraid of the command line. 

M

**Comment by mperes** [comment]
Hey @mariusbax, so basically what you want to do is create a new fork of last roll20 sheet master. Once you do that, copy only the files you want from the old repo into this one. Head back to Github App and take a look on the list of changes files before making a a commit and push it to the repo. If there are any other changes not related to the sheet you are working on, right click them and select to undo the changes. Hope that helps ;)

**Pull request closed without merging**
