### PR TITLE
Hero System 6e Heroic: readme updates

### PR DESCRIPTION
**Pull request by Villain1nGlasses**
## Changes / Comments

Created folder for image files used in the readme.
Copied readme images from personal repository.
Changed readme to link to images in new local folder.
Small updates to readme text.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Villain1nGlasses** [comment]
Small fixes to consolidate resources to this repository.
The single sheet graphic still needs to be changed, but I'll wait until the sheet is working in Roll20.

**Comment by nmbradley** [comment]
@Villain1nGlasses Can you edit this PR to list the sheet affected in the title, please?

**Comment by Villain1nGlasses** [comment]
@nmbradley Ok, fixed title. Sorry, I'm still getting used to Github etiquette and procedures.

**Comment by nmbradley** [comment]
No worries, it just allows us to come back and find it in the future if there are any problems. Thanks for fixing!

**Pull request merged**
