### PR TITLE
[Sagas of the Icelanders] Translation enabled

### PR DESCRIPTION
**Pull request by urbaman**
## Changes / Comments

Translation enabled

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
Hello @urbaman there a few issues with your pr:

- When modifying an existing sheet, the sheet's files must remain in the original directory and cannot be moved to a new one.

- Also, the directory containing the sheet's main files (sheet.json, translation.json, html, css and preview image) must be in the root of the repository and cannot be nested inside another directory.

**Comment by urbaman** [comment]
Hi,

I do not understand what you're talking about, could you elaborate please?
Here is a shot of the branch I'm working on and from wich I made the pr.

Immagine

**Comment by mperes** [comment]
Hey @urbaman you are moving the files into a Celerity folder in the root.

**Comment by urbaman** [comment]
Found the problem, I will make it over

**Pull request closed without merging**
