### PR TITLE
Era - the Consortium

### PR DESCRIPTION
**Pull request by kbr-kit**
Era - the Consortium character sheet developed in cooperation with the game creator Ed Jowett

### CODE REVIEW

**Comment by Anduh** [comment]
I see no obvious faults on a quick glance.

But to be on the safe side, it's usually [good practice to avoid white spaces in file- and foldernames.](https://github.com/Roll20/roll20-character-sheets/pull/4224#pullrequestreview-158136014)
At least the "consortium .jpg" might be a smart thing to fix.

Another trivial thing, when adressing css classes in the html file, the "sheet-" prefix isn't strictly needed([official Roll20 sheet example](To be on the safe side, it's usually [good practice to avoid white spaces in file- and foldernames.](https://github.com/Roll20/roll20-character-sheets/pull/4224#pullrequestreview-158136014)
At least the "consortium .jpg" might be a smart thing to fix.)) , as Roll20 automatically add the prefix. No need to change, just a note.

**Comment by kbr-kit** [comment]
Thanks, removed white spaces.

**Comment by kbr-kit** [comment]
Renamed files as requested.

**Comment by clevett** [comment]
Greeting @kbr-kit 

Thanks for the quick response. I apologize but I asked the ***folder*** be renamed rather than the files. :) The files are okay to stay as you have them now.

**Comment by kbr-kit** [comment]
Oh man, my bad, hold on.

**Comment by clevett** [comment]
Awesome. Thank you! Unix appreciates your consideration. ;)

**Comment by kbr-kit** [comment]
Thanks!

**Pull request merged**
