### PR TITLE
[Shadowrun 5thOB] OpenBeta Shadowrun Sheet

### PR DESCRIPTION
**Pull request by Stexinator**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Stexinator** [comment]
What is the error in the failed validation?

**Comment by clevett** [comment]
Sheet validation fails usually when you failed to include a file or the sheet.json is not filled out correctly.

Is this the same sheet as the [Shadowrun Advance](https://github.com/Roll20/roll20-character-sheets/tree/master/Shadowrun5th) sheet?

**Comment by Stexinator** [comment]
Yes, I used the Advanced Sheet as a base

**Comment by mperes** [comment]
Hey @Stexinator, before I merge you PR I would like to ask you what are the key differences between your sheet and the existing Shadowrun 5e sheets. While there have been duplicate public sheets allowed in the past, going forward Roll20 wants to limit this practice.

**Comment by Stexinator** [comment]
@mperes this is based on the Shadowrun 5th Advanced Sheets. It contains experimental features and will contain usability changes in the future. Due to my experiences with the Dark Heresy 2ed Sheet where people changed functionality/usability that produces backlash from the community, I want to provide the possibility to check out and comment on the changes before it goes into the main sheet.

If you got a better way then duplicating and copying the feature after a sufficient test time I am all ears.

**Comment by mperes** [comment]
Hey there @Stexinator, my advice for you is to implement your ideas on top of the existing sheet by using a feature [flag.] (https://martinfowler.com/articles/feature-toggles.html)

**Pull request closed without merging**
