### PR TITLE
Removed suboptimal Sccum & Villainy folder name, added better name, updated files to hopefully fix line endings issues for character sheet submission.

### PR DESCRIPTION
**Pull request by cmcdonald22**

### CODE REVIEW

**Comment by wing-it** [comment]
Hey there!
It's great that you're fixing the line endings on your files, however, at least for the initial merge, that gets fixed automatically. Also, it would be best at this point not to change the folder name. I think I may have already changed it because there were double spaces in there and that was a bit too confusing, but now that everything has been merged and is working it's easiest to keep it as it is.
I saw that you're relatively new to github, so my suggestion would be to delete your current branch and make a new one from the current version of the repository. That's probably the easiest way to make sure that you are completely up to date. That way when you need to make changes, it will be easy to see in the diff. Let me know if you have any other questions, I know github can be confusing.
Also, great job on the sheet, it looks great!

**Comment by cmcdonald22** [comment]
@wing-it Okay, so do I need to resubmit a new pull with the updated line endings back into the old folder? or will this pull be fine?

I wasn't sure how automated the process was and if the information on Roll20 that appeared when looking for games was pulled from the folder name in the repository or somewhere else so I wanted a more accurate name (The game is supposed to be Scum & Villainy but Github web interface did not want to accept default or carroted Ampersands and it resulted in the dash/underscore thing), but if it does't make a difference that's fine.  Just let me know if I need to put in a pull to the old folder or ot at this point so that I dont create more unnecessary pulls for you to go through.

**Comment by joesinghaus** [comment]
If you delete your repository and fork the roll20/roll20-character-sheets repo again, you don't need to submit any more pull requests regarding line endings, because they have already been fixed here.

**Comment by wing-it** [comment]
This is correct, you don't 'need' to do anything else at this point, everything is working. I was just saying to fork it again so if you want to make changes from the sheet, you have a fresh place to start from.

**Pull request closed without merging**
