### PR TITLE
Starfinder HUD V0.041517984312 - Initial Release

### PR DESCRIPTION
**Pull request by Kurohyou**
### Starship Sheet is Live!
* Automatic handling for system statuses.
* Link your starship to your character for easy rolling of ship related skills. Enter character names of those fulfilling each role. Separate multiple entries with a comma. If using an NPC ship, enter skill/npc name to be used followed by +/-X and separate multiple skills/npc names with a comma.

~~### Internal Compendium~~
* ~~There is now an internal compendium of all of the CRB equipment.~~
* ~~Items will be added to your inventory with all stats (including mods) properly configured for the sheet~~
* ~~Weapons will add attacks as well (including parsing of solarion weapon crystals - Weapon crystal attacks display very ugly on the sheet atm)~~

## Changes/Additions to Existing Features
* Ability and Spell fields are now buffable (DC, attack, damage)
* Caster Level is now displayed on the spells sheet, and is buffable (buffing caster level will not affect what spell levels are displayed)
* Encumbrance now applies the appropriate maximum dexterity and ACP effects.

## Bug Fixes
* Attack attribute dropdowns do not default to @{strength} correctly
* NPC initiative is not rolling properly - need to add handling for misc so it equals the init mod - the ability score.
* Saves same as initiative
* Same for acrobatics
* ACP is not included in skill rolls
* Pseudo tabs don't work in chrome

## Known Issues
* There is an issue with how the windows version of chrome handles the sheet's styling. The corner border highlights for sections do not place correctly in Windows Chrome.

## Project Status
* ~~The user's guide will be updated in the next few days.~~ The User's Manual has been updated, and can be found [here](https://docs.google.com/document/d/1jaSnNXShMeOBO-VHxHKN9a8GxJ2zMB44-R8AdKlVzu4/edit?usp=sharing)
* This marks the start of stage 4 of the sheet's development, otherwise known as the beta.
* The sheet has been submitted to the repo. If it is accepted, it should show up as an option in your game settings some time next week (just in time for Valentine's Day).
* A new [Character Sheets Forum Thread](https://app.roll20.net/forum/post/6056886/sf-starfinder-hud-thread-1/?pageforid=6056886#post-6056886) has been created for the Starfinder HUD now that it is moving to a public release. All further updates on the Roll20 Community Forums will be through that thread.
* The Starfinder Github Repository has been reformatted. There is now a production branch (versions of the sheet that have been submitted to the Roll20 repo), and a development branch(WIP code).

### CODE REVIEW

**Comment by wing-it** [comment]
Unfortunately, because Starfinder is a copyrighted system and none of the rules are under an open license, we cannot knowingly publish this sheet if it contains copyrighted material (specifically, this is in reference to the 'Internal Compendium' mentioned above).

Basically, the sheet cannot contain content that contained only in the Player's Handbook or any other copyrighted source, this includes stats for items and monsters and also applies to the rules themselves. This means that any automatic calculations that are based on rules from the PHB are also a copyright violation. If this were a system with an open rule set like Pathfinder, it would be a different story.

Generally, you're free to include anything in the sheet that appears on the published character sheet itself, including any automatic calculations described on the sheet (like armor class and ability modifiers).

I'm really sorry to have to tell you this, you've obviously put a lot of time and effort into these features, and I hate to be the one to let you know you'll need to remove a lot of this stuff.

**Comment by Kurohyou** [comment]
The internal compendium is extremely easy to remove, and I have done so. I knew it was a risk putting it in, but it also wasn't actually a ton of work on my part to do it.
I'm pretty sure that the content included in the internal compendium is in fact covered under the OGL, but I am not really qualified to make that judgement.

I'll try to get in contact with Paizo to get a firm answer one way or the other to see if I can get it back into the sheet.

**Comment by Kurohyou** [comment]
Also, here's the text from the CRB about Product Identity:

> Product Identity: The following items are hereby identified as Product Identity, as defined in the Open Game License version 1.0a, Section 1(e), and are not Open Game Content: All trademarks, registered trademarks, proper nouns (characters, deities, locations, etc., as well as all adjectives, names, titles, and descriptive terms derived from proper nouns), artworks, characters, dialogue, locations, plots, storylines, trade dress, the historical period called the Gap, the term skyfire, and the Drift (the official Open Game Content term for which is “hyperspace”). (Elements that have previously been designated as Open Game Content, or are exclusively derived from previous open game content, or that are in the public domain are not included in this declaration.)

and OGL content:

> Open Game Content: Except for material designated as Product Identity (see above), the game mechanics of this Paizo game product are Open Game Content, as defined in the Open Game License version 1.0a Section 1(d). No portion of this work other than the material designated as Open Game Content may be reproduced in any form without written permission.

Based on that, it seems like equipment is not covered. I've still removed the internal compendium, but would like Roll20's thoughts on where equipment falls in that list of product identity terms/items.

**Comment by wing-it** [comment]
Interesting. I'll escalate this and let you know what gets decided. To clarify, your sheet only had items integrated, correct?

**Comment by Kurohyou** [comment]
Correct. I had plans to do a similar treatment for spells, but wanted to see how the interface worked out for items first.

In the mean time, is the sheet able to be merged since it no longer has the functionality in it.

**Comment by wing-it** [comment]
I'll go ahead and merge this version of the sheet for now, I'll let you know when I hear back about the compendium stuff.

In general though, we recommend against this sort of functionality, especially in a large sheet like this, if for no other reason than performance/sheet size impact. This is adding a couple thousand lines of code to the sheet, which may not seem like too much until you consider that this code is duplicated for every pc/npc in the game, often dozens or even hundreds of times for larger games.

**Comment by Kurohyou** [comment]
Thanks wing-it. And, yes, I'm aware of the potential performance impact, that was one of the things I wanted to get feedback on before doing the spells section.

**Comment by Kurohyou** [comment]
On mobile,so can't edit comments, but had an additional question.

Do you have an ETA on getting it added to the approved.yaml? This is my first character sheet, so not sure of the process.

**Comment by wing-it** [comment]
Generally the approved.yaml gets updated when we perform our weekly site maintenance, which is usually on Tuesday.

**Pull request merged**
