### PR TITLE
Serenity - New Features

### PR DESCRIPTION
**Pull request by WilliamBarkerCoC**
An update to a beautifully crafted sheet by Kizyr and Nico Marrero. New Features: Added roll buttons to Attributes, Derived Traits and Specialties. Automated the -2 Attribute Penalty and allowed for tabulation of Advancement Points. 
This is my first submission so no offence is meant if I've tripped and fallen afoul of rules. This is a requested update to the Serenity sheet on behalf of Leland V. Not a v2 of Serenity. I'm blathering - sorry. Tested under both Chrome and Firefox

# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description
Added roll buttons to Attributes, Derived Traits and Specialties. The only existent buttons were radio buttons for Stuns, Wounds and Shocks.
Automated the -2 Attribute Penalty. Done via a sheetworker to set a flag(AFP) which was added to rolls. E.g. 1d12+1d6 - 2* APF
Allowed for tabulation of Advancement Points: Expanded from total, to total, used and unused (tabulated via sheetworker)
Change background colour to Tan for better visibility.

### CODE REVIEW

**Comment by WilliamBarkerCoC** [comment]
Curious. Is the preview case sensitive to file extensions? I have changed .png to .PNG and will retry,

**Comment by WilliamBarkerCoC** [comment]
In case the problem was two .png files existed (original and new) in the folder, I've removed the original and will try resubmitting. Oh. also in the code review you showed I noticed a cut and paste bug, so, thanks?

**Comment by WilliamBarkerCoC** [comment]
Ok, you've baffled me. Perhaps the answer is hidden the ellipses "or the name does not ...". 
Oh, wait a minute, I'll try resubmitting with the original .png - it won't be as accurate but it will get the coding changes out there. The requester has already playtested which resulted in a further list of changes, so perhaps I'll have divined what went askew by then.

**Comment by WilliamBarkerCoC** [comment]
Help please....

**Comment by BronsonHall** [comment]
Hey @WilliamBarkerCoC 

You had it right, our file system is indeed case sensitive.  I believe the only issue needing to be fixed to remove the Missing Preview File failure is to match file name on sheet.json and the preview image itself.  Currently, that's `"preview: "serenityScreenshot.png","` in your sheet.json and `serenityScreenshot.PNG` as the image's actual file name.

It needs to be `"preview: "serenityScreenshot.png","` and `serenityScreenshot.png` to get the sheet.json to recognize the proper preview image.  Also, you may want to add your name as a second author instead of replacing the current author!

**Comment by WilliamBarkerCoC** [comment]
Going to try to resubmit the pull request, without the _egg on face_ error of omitting the current author (_facepalm_). Wish me luck!

**Comment by WilliamBarkerCoC** [comment]
Help again, please. Fixed the PNG v png (thanks BronsonHall) but how does one go back and undo the horrendous mistake of not putting in the original author?  I am an absolute beginner to "GitHub workflow" and only got this far thanks to GiGs forum posts. Should I be "deleting the branch" and re"fork"ing? Or something else? Sorry to be a bother

**Comment by BronsonHall** [comment]
Hey @WilliamBarkerCoC 

No worries - you can keep the branch, and push a new commit to it that changes the `sheet.json` in the following ways:
1. `"authors": "Vialmada",` should become `"authors": "Nico Marrero, Vialmada",`
2. `"roll20userid": "10517273",` should become `"roll20userid": "581781,10517273",`

If you have an open PR from the branch to Roll20:master, i.e. this one, it'll automatically add any commits/changes that get pushed to that branch.  Iirc GiGs' forum posts generally guide through using Github Desktop?  If you're using that, you'll just make sure you're on the branch, make the changes, and hit "Commit to [Branch Name]", then "Push Origin".  If this PR is open that's all you'll need for the changes to make their way here.  No need to refork, make a new PR or new branch.

**Pull request closed without merging**
