### PR TITLE
Dark Horizons Mechanized Corps - Bugfix

### PR DESCRIPTION
**Pull request by edgardnerNESP**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X] The pull request makes changes to files in only one sub-folder.
- [X] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description
Bugfixs and playtest feedback, changed names of Attributes to reflect gameplay, corrected capitalization bugs, misc improvements on spacing.

### CODE REVIEW

**Comment by NorWhal** [comment]
hey @edgardnerNESP!
You're changing a lot of attribute names here without converting the data from existing sheet. This will have a destructive effect on characters in active campaigns. Once you've got a sheetworker to handle the conversions for this update, this will be good to merge!

**Comment by edgardnerNESP** [comment]
We don't have any active campaigns using this sheet; the only active games
are still private/testing. It turns out the naming convention made no sense
when we play-tested it last night.

**Comment by NorWhal** [comment]
Apologies, I thought this was a public playtest! Thanks for the clarification, I'm approving this sheet

**Comment by edgardnerNESP** [comment]
We are gearing up for public! Thanks a million!

**Pull request merged**
