### PR TITLE
Shaped 2.2.13 - merge conflicts resolved

### PR DESCRIPTION
**Pull request by mlenser**

### CODE REVIEW

**Comment by mlenser** [comment]
FYI in case anyone else comes across the same issue: the merge issue was due patreon being added to the sheet.json

**Comment by pjbehr87** [comment]
Thanks for fixing the merge conflict for me!

**Comment by pjbehr87** [comment]
When you merged it deleted your sheet.json instructions. I went ahead and added them back from a previous commit.

**Comment by mlenser** [comment]
Hey Phil, it was purposeful that the old change log was removed.

**Comment by pjbehr87** [comment]
Oh, okay. Then it just needs "instructions": "". The json was breaking because it was "instructions": , . I'll go ahead and remove the text though.

**Comment by pjbehr87** [comment]
Oh, I think there was a misunderstanding. I wasn't talking about the change log, I was talking about the "instructions" property in the sheet.json. After the last commit it was:
`"instructions": ,`
which is not a proper JSON. Did you mean to delete the text from there, or was that a mistake?

**Comment by mlenser** [comment]
My mistake. It should read: "This sheet is designed for use with D&D 5th edition. It has been designed to match the layout of the D&D 5e Character Sheet."
So without the wiki link.

Thanks! Sorry for the trouble.

**Comment by pjbehr87** [comment]
That's what I thought, and have changed it to, and it's no trouble at all. It was right around where I'm assuming the merge conflict was (because I added the patreon link), so I figure that was the cause. Everything should be correct now. Thanks for all your work on this sheet.

**Comment by mlenser** [comment]
Thanks again Phil

**Pull request merged**
