### PR TITLE
Complete Overhaul Update and Patchwork

### PR DESCRIPTION
**Pull request by Project462**
Completely rewrote the sheet and virtually every single thing in it.

### CODE REVIEW

**Comment by Project462** [comment]
I need to patch the html file, but the edit option is no longer avaliable
in the forked copy. Is this due to the number of lines or do I just need to
wait for the files to update on roll20?

On Dec 5, 2016 3:28 PM, "Phil" <notifications@github.com> wrote:

Merged #2063 <https://github.com/Roll20/roll20-character-sheets/pull/2063>.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/Roll20/roll20-character-sheets/pull/2063#event-882742501>,
or mute the thread

**Comment by pjbehr87** [comment]
The easiest way to make sure your code is up to date is to save your changes elsewhere before completely deleting you branch then forking the main repo again. This will make sure all of your code is completely up to date before you start changing it. Even if you were able to make changes you would definitely get merge conflicts if you didn't update first.

If you're more technically inclined there is a slightly more complicated, but easier to use option. You can also set up your local Git branch to be able to pull from the "upstream" branch (the branch you forked from), and you can find more info about that here: https://help.github.com/articles/configuring-a-remote-for-a-fork/ If you do this you can just pull any changes I, or anyone else, make to the main branch.

**Comment by pjbehr87** [comment]
I just noticed the site I linked didn't fully explain it. You can find a more complete explanation here: http://stackoverflow.com/questions/3903817/pull-new-updates-from-original-github-repository-into-forked-github-repository

**Comment by Project462** [comment]
Mm, I checked and the problem is the file size. PF-Neceros has the same
issue but they are working around it somehow. I can't edit on Github
because my file is over 1MB in size.

**Comment by pjbehr87** [comment]
Ah. I suggest using a rich text editor, Sublime Text is amazing and it's free. Once you make your changes locally, then you can take the file (as long as it has the same file name as the one on GitHub) and just drop it right onto the website page. (just make sure you are in the folder for your sheet before you drop the file) This will overwrite the one on the site and automatically detect the changes you are making like it would if you were making the changes through the in-app editor.

**Comment by Project462** [comment]
Awesome, thank you. I wanted to ask about the Sheet Author tag. Since this
no mere rehash of an existing work anymore, do I qualify now?

**Comment by pjbehr87** [comment]
The tagging is automated, you just have to add your account ID to the list of "roll20userid" in the sheet.json. Once the sheet goes live, later that night a script runs and adds the tag to all of those ids. I'm still working on the PRs right now, so if you want to make a quick PR with that update I can grab it now.

**Comment by Project462** [comment]
Holy moley I never knew I had that written in wrong! Both PR's are up.
Thanks again :D

**Pull request merged**
