### PR TITLE
Negocios Infernales v1.00 - new release

### PR DESCRIPTION
**Pull request by RyanMakesBoardGames**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: < Negocios Infernales >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: < Outland Entertainment > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: < Negocios Infernales > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

Initial v1.00 release of Negocios Infernales character sheet for Roll20

### CODE REVIEW

**Comment by kfroll20** [comment]
Hello @RyanMakesBoardGames, 

Thank you for your valuable contribution to the community sheet repository! We are currently in the process of reaching out to the publisher to verify permissions for publishing this sheet as official. Once we receive confirmation, we will proceed with getting this merged and published.

Thank you for your patience and understanding.

Best regards,
Kayla

**Comment by RyanMakesBoardGames** [comment]
> Hello @RyanMakesBoardGames,
> 
> Thank you for your valuable contribution to the community sheet repository! We are currently in the process of reaching out to the publisher to verify permissions for publishing this sheet as official. Once we receive confirmation, we will proceed with getting this merged and published.
> 
> Thank you for your patience and understanding.
> 
> Best regards, Kayla

Hello @kfroll20 

Thank you for following up. The publisher has not yet received an email from GitHub. You can reach them at help@outlandentertainment.com

Thanks in advance,
Ryan

**Comment by kfroll20** [comment]
> > Hello @RyanMakesBoardGames,
> > Thank you for your valuable contribution to the community sheet repository! We are currently in the process of reaching out to the publisher to verify permissions for publishing this sheet as official. Once we receive confirmation, we will proceed with getting this merged and published.
> > Thank you for your patience and understanding.
> > Best regards, Kayla
> 
> Hello @kfroll20
> 
> Thank you for following up. The publisher has not yet received an email from GitHub. You can reach them at [help@outlandentertainment.com](mailto:help@outlandentertainment.com)
> 
> Thanks in advance, Ryan

Hi Ryan,

A member of our partner relations team reached out but we are following up again to ensure we contacted the right person. Once we get that communication cleared up, I will get this moving along. Thank you for letting us know the publisher hadn't heard from us. To be clear, I/we will not be reaching out via Githhub; a member from our partner relations team will be the one reaching out.

Thank you for your patience and understanding
Kayla

**Comment by kfroll20** [comment]
> > Hello @RyanMakesBoardGames,
> > Thank you for your valuable contribution to the community sheet repository! We are currently in the process of reaching out to the publisher to verify permissions for publishing this sheet as official. Once we receive confirmation, we will proceed with getting this merged and published.
> > Thank you for your patience and understanding.
> > Best regards, Kayla
> 
> Hello @kfroll20
> 
> Thank you for following up. The publisher has not yet received an email from GitHub. You can reach them at [help@outlandentertainment.com](mailto:help@outlandentertainment.com)
> 
> Thanks in advance, Ryan

Ryan,

We received confirmation, thank you so much! We have one small request and then I will get this merged and published as an official sheet. Would it be possible to include a disclaimer in your `sheet.json` regarding some of the images? DriveThruRPG allows you to mark products indicating there is adult content, but we don't have a way of doing that for community sheets.

Thank you! 
Kayla

**Comment by RyanMakesBoardGames** [comment]
> > > Hello @RyanMakesBoardGames,
> > > Thank you for your valuable contribution to the community sheet repository! We are currently in the process of reaching out to the publisher to verify permissions for publishing this sheet as official. Once we receive confirmation, we will proceed with getting this merged and published.
> > > Thank you for your patience and understanding.
> > > Best regards, Kayla
> > 
> > 
> > Hello @kfroll20
> > Thank you for following up. The publisher has not yet received an email from GitHub. You can reach them at [help@outlandentertainment.com](mailto:help@outlandentertainment.com)
> > Thanks in advance, Ryan
> 
> Ryan,
> 
> We received confirmation, thank you so much! We have one small request and then I will get this merged and published as an official sheet. Would it be possible to include a disclaimer in your `sheet.json` regarding some of the images? DriveThruRPG allows you to mark products indicating there is adult content, but we don't have a way of doing that for community sheets.
> 
> Thank you! Kayla

Thank you for pointing that out - I didn't even consider that might be a concern! I've updated sheet.json with the requested information. Please let me know if there's anything else!

Thanks,
Ryan

**Comment by kfroll20** [comment]
> > > > Hello @RyanMakesBoardGames,
> > > > Thank you for your valuable contribution to the community sheet repository! We are currently in the process of reaching out to the publisher to verify permissions for publishing this sheet as official. Once we receive confirmation, we will proceed with getting this merged and published.
> > > > Thank you for your patience and understanding.
> > > > Best regards, Kayla
> > > 
> > > 
> > > Hello @kfroll20
> > > Thank you for following up. The publisher has not yet received an email from GitHub. You can reach them at [help@outlandentertainment.com](mailto:help@outlandentertainment.com)
> > > Thanks in advance, Ryan
> > 
> > 
> > Ryan,
> > We received confirmation, thank you so much! We have one small request and then I will get this merged and published as an official sheet. Would it be possible to include a disclaimer in your `sheet.json` regarding some of the images? DriveThruRPG allows you to mark products indicating there is adult content, but we don't have a way of doing that for community sheets.
> > Thank you! Kayla
> 
> Thank you for pointing that out - I didn't even consider that might be a concern! I've updated sheet.json with the requested information. Please let me know if there's anything else!
> 
> Thanks, Ryan

Perfect, I'll get this merged and published now!

**Pull request merged**
