### PR TITLE
Savage Worlds Tabbed Enhancements

### PR DESCRIPTION
**Pull request by finderski**
## Changes / Comments

Rename Skills - provides the ability for users to change any of the precoded skills to suit their needs.  This was something requested by multiple people in my test game where I do dev work on this sheet.  I'm using a sheet worker to populate the base names using getTranslationByKey to preserve internationalization even though everything will use a named span to display skill names.

Nerves of steel type functionality for Fatigue - another feature requested by people in the test game.

Wealth Modifier field (useful for Shaintar) - another feature requested by people in the test game.

## Roll20 Requests

### CODE REVIEW

**Comment by finderski** [comment]
How do I resolve those? I believe another user made changes, but I don’t know what they are (at least not in detail)...

Thanks,

Rich

**Comment by clevett** [comment]
There is a button in GitHub that says **Resolve conflicts**.  It is found just below these comments. 

Here is a [tutorial about merge conflicts](https://www.atlassian.com/git/tutorials/using-branches/merge-conflicts), though it will likely be more than you need for this.

**Comment by finderski** [comment]
Cool.  Thanks.

Rich

**Comment by clevett** [comment]
Greetings @finderski 

Still pull request still contains merge conflicts so I am unable to approve it. You can find the **Resolve conflicts** button on this page and fix them. It is a very easy system to use and there are only 2.

Thanks,
Cassie

**Comment by finderski** [comment]
Did something happen after I’d managed them? Because I’d done everything (I thought) and hit the Merge button and didn’t get any additional errors… 😕

I’ll take a look and see what I can see, though.

Rich

**Comment by finderski** [comment]
Final two conflicts managed... :-/

**Comment by finderski** [comment]
Conflicts managed…

Rich

**Pull request merged**
