### PR TITLE
Shadowrun6 German v0.4 update

### PR DESCRIPTION
**Pull request by Coolmander**
## Changes / Comments
**Version 0.4** Changes:

**General updates:**

- 	Sheet-Design and CSS updated
- 	New Theme "Darkskin"
- 	New alternate Header, with compact Layout
- 	Wild-Dice rolling now working without using  ability command buttons
- 	Sheetworker optimization and bug fixing by changing Attributes and Skills

**Changes in Tabs:**
- New Character-Tab  
        sections for general Information, Sins and Perks
	Attributes-Tab 
	Style Bug fixes and small redesign
- Skills-Tab 
redesign and new Sections for Knowledge-Skills and Language-Skills
- Combat-Tab 
	redesign and new Sections for Skills and Initiative
	Firearms, selection of Ammo-Type now changing the Ammunition-Modifiers
	new Buttons for Reloading and firering a Weapon
- Magic-Tab 
	Redesign, new basic section for Rituals, Alchemy and Fokis
- New Matrix-Tab
New Sections Initiative, Deck, Skills, Matrix-Actions, Programs, Complex-Forms and Sprites
- New Rigger-Tab
New Sections Initiative, Rigger-Console and Vehicles and Drones
- New Tab Connections
- New Tab Gear
	asic sections for Armor (with calculation for Defenserating), Cyberware and general Gear.
	New Tab Notes for entering multiple Notes
	New Optional Tab for creating Custom Rolls.
Added a Button to generate generic example rolls
- Tab Config
	New Section to Configure short header and the Tabs Magic, Matrix and Rigger, and enabling the Customrolls Tab
	New Section for importing a JSON-export from Genesis-Rpgframework.
	Added Optional Rule for Auto-Successes by hi Defenserating from Armor

The new Update should not lead to datalost for the previeous Versions of this Character Sheet.
Old attributes wasn't changed.

The Update contains many new Entrys in the translation.json and are only complete in German.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by NocFenix** [comment]
@Coolmander, https://jsonlint.com/ is super handy for invalid json issues. Here is an altered version of sheet.json which that website states is valid.:
```
{
	"html": "sheet.html",
	"css": "sheet.css",
	"authors": "Avalia/Coolmander",
	"roll20userid": "7395540",
	"preview": "SR6D-example.png",
	"instructions": "Shadowrun 6th Edition is a English RPG produced and maintained by Catalyst Game Labs (CGL). In the German area it is translated and maintained by Pegasus Spiele.\r\n  Latest Update: \r\n  Version 0.4\r\nGeneral updates:\r\n Sheet-Design and CSS updated\r\n New Theme \"Darkskin \"\r\n New alternate Header, with compact Layout\r\n Wild-Dice rolling now working without using  ability command buttons\r\n Sheetworker optimization and bug fixing by changing Attributes and Skills\r\n\r\n New Character-Tab  \r\n sections for general Information, Sins and Perks\r\n Attributes-Tab \r\n Style Bug fixes and small redesign\r\nSkills-Tab \r\nredesign and new Sections for Knowledge-Skills and Language-Skills\r\nCombat-Tab \r\n redesign and new Sections for Skills and Initiative\r\n Firearms, selection of Ammo-Type now changing the Ammunition-Modifiers\r\n new Buttons for Reloading and firering a Weapon\r\nMagic-Tab \r\n Redesign, new basic section for Rituals, Alchemy and Fokis\r\nNew Matrix-Tab\r\nNew Sections Initiative, Deck, Skills, Matrix-Actions, Programs, Complex-Forms and Sprites\r\nNew Rigger-Tab\r\nNew Sections Initiative, Rigger-Console and Vehicles and Drones\r\nNew Tab Connections\r\nNew Tab Gear\r\n asic sections for Armor (with calculation for Defenserating), Cyberware and general Gear.\r\n New Tab Notes for entering multiple Notes\r\n New Optional Tab for creating Custom Rolls.\r\nAdded a Button to generate generic example rolls\r\nTab Config\r\n New Section to Configure short header and the Tabs Magic, Matrix and Rigger, and enabling the Customrolls Tab\r\n New Section for importing a JSON-export from Genesis-Rpgframework.\r\n Added Optional Rule for Auto-Successes by hi Defenserating from Armor\r\n",
	"legacy": true
}

**Comment by Coolmander** [comment]
Why is the check on Sheet.json failing?

**Comment by NocFenix** [comment]
> Why is the check on Sheet.json failing?

Specifically your instructions have characters in it that are breaking it. The first big ones are the unescaped `"` characters. Then you have some weird large spaces that jsonlint doesn't like.

**Comment by Coolmander** [comment]
Ahh, thanks, havent seen the Problem.

**Comment by Coolmander** [comment]
Finding some issues to fix before releasing the update.

**Pull request closed without merging**
