### PR TITLE
[GURPS] Replaced all instances of the word Fear or fear with the word Fright.…

### PR DESCRIPTION
**Pull request by TankFarmer**
… In GURPS the proper term is Fright or a Fright Check, not fear. Also modified the Fright check macro to replace the word Will wuth the word Fright so it states it is making the roll vs Fright and not vs Will.

Replaced all instances of the word Fear or fear with the word Fright. In GURPS the proper term is Fright or a Fright Check, not fear. Also modified the Fright check macro to replace the word Will wuth the word Fright so it states it is making the roll vs Fright and not vs Will.

### CODE REVIEW

**Comment by Solarswordsman** [comment]
Hi @TankFarmer, while the terminology may need changing, it may be easiest for you to only change the user-visible indicators of the word.  The problem with your changes is that you are changing attribute names, and so the values in those attributes will be lost for current users of the sheet.  You could change the attribute names if you handle retrieving the previous attribute values and updating them to their new attributes via a sheet worker if you really wanted the underlying attribute names to change.

For now I'll close this, but feel free to make a new PR with either of the above modifications (either only change visible verbiage, or make a sheet worker to convert the attribute values).

Thanks!

**Comment by TankFarmer** [comment]
Well I guess that is a problem as I have no idea how to do this vi a sheet worker.So for now I will resubmit and change the user-visible indicators.
Thanks
Tom

    On Tuesday, July 17, 2018, 6:51:32 AM PDT, Jeffrey Lamb <notifications@github.com> wrote:  
 
 
Hi @TankFarmer, while the terminology may need changing, it may be easiest for you to only change the user-visible indicators of the word. The problem with your changes is that you are changing attribute names, and so the values in those attributes will be lost for current users of the sheet. You could change the attribute names if you handle retrieving the previous attribute values and updating them to their new attributes via a sheet worker if you really wanted the underlying attribute names to change.

For now I'll close this, but feel free to make a new PR with either of the above modifications (either only change visible verbiage, or make a sheet worker to convert the attribute values).

Thanks!

**Comment by TankFarmer** [comment]
JeffreyQuick question, if I may ask:Does changing the type of an attribute require any special code changes to retain existing data?
There is an attribute which is restricted to 'value' and I want to change it to 'text'.The current attribute only allows for a numerical entry BUT it needs to allow for several entries plus alpha characters as well.I am not changing the name of the attribute, just its type.Tom

    On Tuesday, July 17, 2018, 6:51:32 AM PDT, Jeffrey Lamb <notifications@github.com> wrote:  
 
 
Hi @TankFarmer, while the terminology may need changing, it may be easiest for you to only change the user-visible indicators of the word. The problem with your changes is that you are changing attribute names, and so the values in those attributes will be lost for current users of the sheet. You could change the attribute names if you handle retrieving the previous attribute values and updating them to their new attributes via a sheet worker if you really wanted the underlying attribute names to change.

For now I'll close this, but feel free to make a new PR with either of the above modifications (either only change visible verbiage, or make a sheet worker to convert the attribute values).

Thanks!

**Comment by Solarswordsman** [comment]
You can change an `<input type="number" name="attr_attributename">` to an `<input type="text" name="attr_attributename">` with no issue, yes.  If it has a default `value`, I would keep it as such.  Note that if you change the input type you might have to do a bit of CSS to make sure the layout remains consistent.

**Comment by TankFarmer** [comment]
JeffreyThank you for the quick answer.All seems fine here, I can make the CSS layout changes as needed, I figured that part out.This is exactly what I needed to know.As you can tell I am rather new at this BUT no one else is making the changes we need so I took it upon myself to give it a try.Thanks again,Tom
    On Tuesday, July 17, 2018, 6:47:38 PM PDT, Jeffrey Lamb <notifications@github.com> wrote:  
 
 
You can change an <input type="number" name="attr_attributename"> to an <input type="text" name="attr_attributename"> with no issue, yes. If it has a default value, I would keep it as such. Note that if you change the input type you might have to do a bit of CSS to make sure the layout remains consistent.

**Pull request closed without merging**
