### PR TITLE
Adding Cortex Prime Tales of Xadia Play Test sheet to master repo

### PR DESCRIPTION
**Pull request by tapiochre**
## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
Hey there @tapiochre, could you remove the .DS_Store file from the root folder of your PR? Thanks for all the work you do!

**Comment by tapiochre** [comment]
> Hey there @tapiochre, could you remove the .DS_Store file from the root folder of your PR? Thanks for all the work you do!

I'm now getting a "You cannot modify files in the root directory." validation comment.

I hope this is resolved, but any advice would be appreciated.

**Comment by mperes** [comment]
Hey there @tapiochre, the easiest way would be creating a new branch from master and copy only the changes you have made to the sheet and make a new PR.

**Comment by tapiochre** [comment]
> Hey there @tapiochre, the easiest way would be creating a new branch from master and copy only the changes you have made to the sheet and make a new PR.

Can I just check is this still an issue?

I can branch and pull - will it make tonights deadline?

**Comment by mperes** [comment]
Yes, your PR is still failing on the not modify root rule, @tapiochre. If you make a new PR I can merge it in a few minutes as I am sitting in the front of the git repo right now ;)

**Comment by tapiochre** [comment]
> Yes, your PR is still failing on the not modify root rule, @tapiochre. If you make a new PR I can merge it in a few minutes as I am sitting in the front of the git repo right now ;)

Ok I'm free to do this now... one min

**Comment by tapiochre** [comment]
New Pull being commited shortly

**Pull request closed without merging**
