### PR TITLE
Created Warhammer 40K Wrath and Glory character sheet

### PR DESCRIPTION
**Pull request by MattBx8**
Created Warhammer 40K Wrath and Glory Character Sheet, based on the Quick Start Rules "Blessings Unheralded". Current version 1.00.

### CODE REVIEW

**Comment by Anduh** [comment]
Nice package, all in one :grin: 
But now in turn you have to tell what .gitattributes files are used for, because I don't know

**Comment by MattBx8** [comment]
Yeah, eventually I get it right.

The desktop github program auto created the .gitattributes file so I thought it was part of the program stuff.

/Matt

**Comment by Anduh** [comment]
Yeah, it seems to have some use in when you move files around  and apply filters or something, nothing needed here as far as I've seen.
Now that you have the sheet on one package, I guess it's as well to close the other pull requests as they aren't needed anymore

**Comment by Solarswordsman** [comment]
@MattBx8, great work getting this into one package.  We have a couple of Wrath and Glory sheets being submitted, so we're doing research into the best solution for getting this game playable on Roll20; we'll get back to you as soon as we have more information on that.

Sorry to keep you on hold for a bit longer!

Jeff

**Comment by Solarswordsman** [comment]
@MattBx8, I am going to merge this into the repository, but for the moment I will not add it to the dropdown list.  Another sheet has been created for this system which seems to have more functionality without any comparative downsides.  If you feel you could improve upon that sheet and collaborate with the author there instead, I encourage you to do so.

Let me know or email team@roll20.net if you have any questions.

Thanks,
Jeff

**Pull request merged**
