### PR TITLE
[Magical-Kitties] update Magical Kitties Save the Day! sheet

### PR DESCRIPTION
**Pull request by edgeworthe**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description

Changes included in this pull request:
- Removed numbers from css that _seem_ to be unnecessary (possibly introduced by copy-paste from Github?)
- Initial migration to the new sanitization settings (pretty much entirely consists of removing the "sheet-" prefix throughout)
- Changed image header to use the image in the Roll20 repository since the specific branch on the Anduh fork no longer seems to be available
- Swapped in internationalization strings throughout the character sheet html (though I'm not sure I did the placeholder items correctly, especially with number fields)

### CODE REVIEW

**Comment by edgeworthe** [comment]
Tagging @Anduh and @apsalari who added the character sheet originally in case they'd like to weigh in on my changes

**Comment by mperes** [comment]
@Anduh and @apsalari, are we good to merge this?

**Comment by edgeworthe** [comment]
I've sent PMs to both of the original authors on Roll20 to see if they're ok with the changes

**Comment by mperes** [comment]
Ok, lets wait until we hear back from either of them.

**Comment by Anduh** [comment]
looks good to me

**Review by Anduh — APPROVED** [review]

**Pull request merged**
