### PR TITLE
Updated HTML, CSS and Preview Image

### PR DESCRIPTION
**Pull request by Project462**
Cleaned up formatting, added a new optional section and fixed buttons.

### CODE REVIEW

**Comment by pjbehr87** [comment]
I'm not sure what happened here, but this PR is trying to add the files to a totally new folder "AD&D%202E%20Revised". (literally with the %20 not a space) It also sees the html and css files as binary instead of text files. What OS is your computer and what editor are you using?

**Comment by Project462** [comment]
Windows 8 and, I'm not using an editor other than roll20's pro account
features. I noticed the 20% thing, but I wasn't sure if that was normal or
not. You can scrap the PR though. I found a bug in the html that I've now
addressed. I've asked for clarafication before on submitting content, but,
in light of this current series of mishaps, how do I properly go about this?

What I did was, create a fork, enter the 2E Revised folder, upload files,
drag/drop the files, commit to master, the initiate a pull request.

I have the github desktop app, but the use of it only confuses me further :/

**Comment by pjbehr87** [comment]
Yeah, forget the desktop app. It's kind of terrible. I'll give you some more specific instructions for what you're trying to do.

So, the process would be:
1. Go to the files [here](https://github.com/Roll20/roll20-character-sheets/tree/master/AD%26D%202E%20Revised), and for each of the HTML and CSS files click the file, then click Raw up at the top. (this will open a new page that is just the code, so it's super easy to copy/paste) Copy all of it and paste it into the Custom Sheet box on Roll20.
2. Make your changes here in this box.
3. When you're ready to upload your changes create a new fork
4. On your fork navigate to the AD&D 2E Revised folder on your new branch. (you're lucky it's near the top :P)
5. Now, you can edit each file right on GitHub. For each of the files you are updating, for example the HTML file: Click the HTML file then up at the top, next to the Raw button, is a pencil. This will let you edit the file right here on the page. Once you've opened the edit box, go and copy all the text from the corresponding file in the Custom Sheet box (Ctrl+A, Ctrl+C) on Roll20 and then select all the text in the edit box and replace it with the text from the Custom Sheet box (Ctrl+A, Ctrl+C).
6. Then add your commit message at the bottom and hit save. This will create a commit for your changes for this file. Now do step 5 and 6 again for any other files you are changing.
7. Now you create the PR. Look at the files it tells you you are changing. These should match what you're expecting and you should see the specific lines you changed.

**Comment by Project462** [comment]
Trying to add the preview image. It keeps creating that 20% folder for it.
Not sure how to get around that. Got my other stuff in there, just, holding
off so I can try to get the picture in there. Thanks by the way. I'm
nitnoid about details and kept messing up without them.

**Pull request closed without merging**
