### PR TITLE
Carbon-2185-Enhanced

### PR DESCRIPTION
**Pull request by vanderweb**
## Changes / Comments

A new enhanced and updated version of the Character Sheet for the game Carbon 2185 by Dragon Turtle Games https://www.dragonturtlegames.com/carbonrpg

The orginal was created before the official release, is has not been updated for a 2 years.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [x] Does the pull request title have the sheet name(s)? Include each sheet name.
- [x] Is this a bug fix?
- [x] Does this add functional enhancements (new features or extending existing features) ?
- [x] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [x] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by vanderweb** [comment]
Added the missing files

**Comment by mperes** [comment]
Hey there @vanderweb, is there any chance you could make your updated on top of the existing sheet? While there have been duplicate public sheets allowed in the past, going forward Roll20 wants to limit this practice. Thanks for all the work you do!

**Comment by vanderweb** [comment]
Yes, I can do that.

**Comment by vanderweb** [comment]
Should I close this request and make a new pull request from the existing carbon-2185 library?

**Comment by vanderweb** [comment]
Closing this and will create a new Pull request using the existing folder.

**Pull request closed without merging**
