### PR TITLE
Added Roll Buttons to The Void Character Sheet

### PR DESCRIPTION
**Pull request by Lockbox313**

### CODE REVIEW

**Comment by IanDominey** [comment]
This should have been rejected.  The layout changes in the CSS break the layout quite badly.  Due to the repetitive nature of a lot of the sheet, I'm changing the generation of the sheet to use pugjs and gulp.  If you want to take a look at https://github.com/IanDominey/roll20-character-sheets/tree/the-void, you can see what I've been doing here.

Would it be possible to revert the merge until the CSS is tidied up?  Thanks for adding the roll buttons btw, I do appreciate that.

**Comment by Lockbox313** [comment]
By the looks of it the css file  is missing the preview I added show how it
should look.  The only css changes I made was to put a table into the
skills to make some sort of sense of them.

**Comment by Lockbox313** [comment]
there is a } missing from the end of ".sheet-rolltemplate-skillRoll table"
 in the css file

**Comment by IanDominey** [comment]
And center is misspelled as centre.

Odd, when I merged the CSS, several widths had changed.

**Comment by Lockbox313** [comment]
Seems during my complete failure to grasp the github desktop app a old version of the css file was committed.  But it if is your intent to redo the css then there is no point in me sending the version I was using in the game  I was running.

Also you may want to take a look at the language skills as it really needs a repeating section, as a lot of characters  have more than one language.  From feedback from my players they had a real problem navigating the really long single column of skills.

**Comment by IanDominey** [comment]
No problem.  I'd love to put a repeating section for languages, my own players had the same feedback.  Problem is, having repeating table rows is impossible (see https://app.roll20.net/forum/post/1297538/repeating-fieldsets-and-tables/?pageforid=1297538#post-1297538. I'd have to redo the skills list to fake tabular layout, which is a real PITA. If you feel up to it, I'd love the help as I don't have too much time to devote.

I've also had feedback about issues with some of the fields being numbers rather than text so I'll probably change that.  Are you comfortable to play around with pug templates? I'm planning on updating the readme to describe the file layout and build process.

**Comment by pjbehr87** [comment]
If one of you can commit the CSS fixes and make a new pull request I will merge it right away.

**Comment by IanDominey** [comment]
@Lockbox313 would you mind commiting the version of the css that is working for you? I don't intend to redo the css, at least not yet.

**Comment by Lockbox313** [comment]
I am not near the computer with the source.  If you look at the first
commit of the css file it looks to be correct. There is a } on line 23 of
the last commit of the css file.  This should fix the majority of the
issues.

**Comment by IanDominey** [comment]
@Lockbox313 if you wanted to discuss ideas for the void sheet, such as how to simplify the long list of skills, feel free to send me a private message on https://app.roll20.net/users/124824/ian-d

**Comment by IanDominey** [comment]
Ok, I'll look into it tomorrow. It's late evening where I am.

**Comment by Lockbox313** [comment]
Ok I committed a fix from my github repository,  not easy on this tiny phone screen.

**Pull request merged**
