### PR TITLE
Migration to Enchanced Character Sheet (GenSheet2.0.html, GenSheet2.0.css, Three additional image folders)

### PR DESCRIPTION
**Pull request by Cacealeos**
## Changes / Comments

Uploaded Three Folders with PNGs, Jpegs, and gifs for animations

- BlueType1
- Particles
- Circles&Borders

Renamed Main Css and HTML to GENSheet2

Css
- Added transition effects for all menus
- Added catalyst theme for each catalyst button
- Added animated background
- Added animated battle button
- Added animated particles

HTML
- Added a battle and health tab by splitting off from the Character tab
- Added custom progress bars for the health tab
- Added Economy collapsable section into battle tab
- Added max values for new prog bars

Json

- Changed the main files and preview png as well as patreon ruleset
- disabled legacy key value

None of the scripts have changed and are identical to before ECS migration but something about the ECS has disabled button scripts in repeating section. Posting on forum, if pull request isn't denied again.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [ ] Does the pull request title have the sheet name(s)? Include each sheet name.
- [ ] Is this a bug fix?
- [ ] Does this add functional enhancements (new features or extending existing features) ?
- [ ] Does this add or change functional aesthetics (such as layout or color scheme) ? 
- [ ] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by Cacealeos** [comment]
For Generation Character Sheet

**Comment by Anduh** [comment]
It's better to overwrite the existing html & css files, the older versions of the sheet is still preserved on github, that's the whole point with using git for version control. Doing it this way only creates unnecessary duplicates & bloat in the repo.

**Comment by nmbradley** [comment]
Hi @Cacealeos 

I think @Anduh is right on this call; please replace the existing files, rather than create new ones.

**Comment by Cacealeos** [comment]
I made them two separate files because the older ones still use the legacy
value in the .json and the newer ones won't work with it. Is there no
precedent for wanting to be able to switch back if needed?

**Comment by nmbradley** [comment]
There's no way to switch between them, so there's no need to have multiple files.

**Comment by Cacealeos** [comment]
Gotcha.

**Pull request closed without merging**
