### PR TITLE
Star wars 5E : NPC layout improvement

### PR DESCRIPTION
**Pull request by BE-Arbiter**
# Submission Checklist
## Required

- [X] The pull request title clearly contains the name of the sheet I am editing.
- [X] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [X] The pull request makes changes to files in only one sub-folder.
- [X] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

# Changes / Description

- Change the layout of the npc sheet to have two columns (like it's Dnd-5 Counterpart)
- Add the possibility to switch between edit and view for the traits. Like the actions

### CODE REVIEW

**Comment by BE-Arbiter** [comment]
@speedreeder @Anduh @Fresnoth For review

**Review by Anduh — APPROVED** [review]
Great update!

So it seems at lest the NPC edit mode is wider now, and moving Actions to new column was a good move.

Don't have any active game with the sheet so didn't check with a complete NPC, but can't imagine making any difference. This is a clear improvement to the sheet.

**Comment by BE-Arbiter** [comment]
Thank you,

As I will master a tcw campaign in a few month I will certainly do more.

**Comment by Anduh** [comment]
If the sheet would be [upgraded from using the Legacy sheet](https://wiki.roll20.net/Legacy_Sheet#Migrating_from_LCS_to_CSE), some things would open up for you, like using [datalist](https://wiki.roll20.net/Character_Sheet_Enhancement#Datalist) could be handy for storing names of Tech and Force power names, giving an autocomplete option for them.

**Comment by comradedangerfloof** [comment]
The text of the actions are aligned to the left and the traits do not display any text other than their name. Also when clicking on the traits to display them in chat, an error occurs. Also the traits are a bit hard to click on. 

image
image

**Comment by BE-Arbiter** [comment]
Will look into this as soon as possible.

**Review by aris-ark — COMMENTED** [review]
Edit: my first time using GitHub so didn't see someone else pointed out this! Thank you for updating that you're working on it! 🙌🏼🙌🏼

Broke NPC sheet completely. Since this update has been pushed out it's essentially made the NPC impossible to use as you cannot change the size, and all the traits are now in the tiniest of fonts and do not show descriptions. When you click on them an error pops up saying no attribute was found for rollbase.

image

image

**Comment by BronsonHall** [comment]
@BE-Arbiter 
If needed I can revert this pr until the problem can be addressed. If you're working on this now or will have a fix pr up soon, just @ me as soon as that's in so I can get it merged.

**Comment by BE-Arbiter** [comment]
Yes, please revert I on travel til sunday :)

**Comment by Anduh** [comment]
My bad, I clearly didn't test this well enough. Should have filled out a more complete NPC and poked around a bit more.

@BE-Arbiter , would it be possible for you to create & share a campaign were other users could help with testing? (IIRC only the game creator can update code if custom character sheet is used, so me creating a game wouldn't help you much)

Enabling character import in the game, others people could import actually used characters with lots of data to the test game, so both you and others could better test things. When I was more active with sheet development, at times I hosted similar test games for other sheets when I did larger updates to sheets.

Sharing campaign link
* If a public invite link results in spammers/bots joining the game, kicking a player will invalidate the old invite link, and a new one is given.
* Alternatively, link you roll20 profile or a forum post here about the test game, and DM the invite to people who contact you

**Comment by BE-Arbiter** [comment]
Nice idea, will do it next week.

**Comment by Anduh** [comment]
Pretty much, but dont do it for roll templates IIRC.

Check these suggetions: https://wiki.roll20.net/Legacy_Sheet#Migrating_from_LCS_to_CSE

**Comment by BE-Arbiter** [comment]
Will check that. For now I will just publish the trait correction.

**Comment by Befall** [comment]
@BE-Arbiter Sorry to bother, starting a SW5e campaign, was looking into NPC sheet issues, and saw your PR and the revert. Did you ever end up continuing work on the original change? Sorry for necropost.

**Comment by BE-Arbiter** [comment]
@Befall  Yes I did finish it, but it's stuck in PR. https://github.com/Roll20/roll20-character-sheets/pull/13282

**Pull request merged**
