### PR TITLE
Revert "Mongoose Traveller 2e: Make Independent sheet and fixes"

### PR DESCRIPTION
**Pull request by pjbehr87**
This doesn't add back the fields that were removed in the previous PR.

### CODE REVIEW

**Comment by Berserker66** [comment]
Yeah, it only makes a new independant 2E sheet. Since there were already 3 PRs reverting back to 1E

**Comment by Berserker66** [comment]
Please Merge https://github.com/Roll20/roll20-character-sheets/pull/2193/commits/df486bcc654e9a7b49521ec5d5baf7228ec8b6bb
Then so that the 2E sheet is up to date.

**Comment by pjbehr87** [comment]
I'll grab the other PR tomorrow, it's too late now to grab it this evening. The thing I was most concerned with is making sure that the "current" sheet wasn't broken for already existing games.

**Comment by Berserker66** [comment]
I'll also leave this reference here:
https://github.com/Roll20/roll20-character-sheets/issues/2194

**Pull request merged**
