### PR TITLE
kill puppies for satan RPG character sheet set

### PR DESCRIPTION
**Pull request by MattBx8**
kill puppies for satan RPG character sheet set, with html, css, image, readme.md and sheet.json.

*Include the name of the sheet you made changes to in the title.*

## Changes

Provide a few comments about what you have changed. 

- If changes fix a bug or resolves a feature request, be sure to link to that issue. 
- For pull request that change multiple sheets please confirm these changes are intentional for all sheets. This will help us catch unintended submissions.
- When updating existing sheets if you are changing attribute names please note what steps you have taken, if any, to assist players in keeping their data.

### CODE REVIEW

**Comment by MattBx8** [comment]
Thanks!

I'll add this on the next revision.

/Matt

**Comment by clevett** [comment]
Greetings @MattBx8 

Character sheets in the Roll20 repo must meet the standards set in [code of conduct for Roll20](https://wiki.roll20.net/Terms_of_Service_and_Privacy_Policy#Play_Nice_Clauses). *kill kittens for satan* is a game that is written to be obscene and profane which is outside of the acceptable for our code of conduct. If you have further questions let me know.

Thanks,
Cassie

**Comment by MattBx8** [comment]
I understand. One person’s dark comedy satire RPG spoofing Vampire: the Masquerade and other 90’s angsty RPGs could be another person’s profane obscenity. No worries.

**Comment by clevett** [comment]
Thanks for understanding.

**Pull request closed without merging**
