### PR TITLE
D&D 2e Simplified: Latest changes

### PR DESCRIPTION
**Pull request by aquaalex**

### CODE REVIEW

**Comment by aquaalex** [comment]
updated

**Comment by clevett** [comment]
Greetings @aquaalex 

This sheet has unfortunately been reverted as it does not meet our guidelines listed in the Github readme. In particular it lacks basic functionality like common rolls. 

Thanks,
Cassie

**Comment by aquaalex** [comment]
The request was for a sheet with no built in scripts or macros or buttons.
But I will add some basic roll buttons. How many buttons will make you
happy?

**Comment by clevett** [comment]
Greetings @aquaalex 

If this was a request for a particular user you could link them your code and if they are a Pro user they can use a Custom Sheet. This repo is available to all of our users site wide so we enforce the guidelines to ensure sheets will appeal to a variety of users.

Thanks,
Cassie

**Comment by aquaalex** [comment]
There have been many discussion on this online and many users that wants
this (not all of them are pro members), I will discuss with them and add
the minimum required roll buttons.
I myself don't want to use this sheet, but as being part of a community
means assisting others I am more than happy to build something that people
want to use.

**Pull request merged**
