### PR TITLE
Tirbes in the Dark sheet updates for v1.2

### PR DESCRIPTION
**Pull request by rivetgeekwil**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [x] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by rivetgeekwil** [comment]
I opened an issue for this, but the sheet does not appear to be updated
within Roll20.

**Comment by davidroll20** [comment]
Hello! Working on a fix here - would you mind checking again to see if it's good now?

**Comment by rivetgeekwil** [comment]
It's still showing 1.0.

**Comment by davidroll20** [comment]
Hi again! I am not 100% sure that this is the issue, but I did notice that some of the images in .css give a 404 when I navigate to them. Might those links need to be different?

**Comment by rivetgeekwil** [comment]
Lemme double check. I had updated them to match the R20 repo vs my own
(which is private). I'll check and if I have to create a new PR to fix.
But the sheet did update to 1.2!

**Pull request merged**
