### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by PhilHoffm**
3rd update. 2/3 translated

### CODE REVIEW

**Comment by vince-roll20** [comment]
I found an issue in the current de.json file (missing quotes around a key)
"damage-macro-desc": Schadensmakro,
however, this PR looks good.  Hopefully this will solve the issues mentioned above.  Thank you for the translation!

**Comment by PhilHoffm** [comment]
Hello.

I’m sorry, that i did not checked my .json correctly.
The next update is checked and has no problems. The translation is about 66% finished.

Greets
Philipp H.

**Comment by vince-roll20** [comment]
No worries.  It's funny what a couple missing quotes will do.  ;-P

**Comment by PhilHoffm** [comment]
new update is uploaded

**Pull request closed without merging**
