### PR TITLE
Mutant Year Zero sheet update

### PR DESCRIPTION
**Pull request by dwarfwing**
## Changes / Comments

Added the additional 3 character and campaign types; now Mutant, Animal, Robot, and Human.
Major graphical update, including dynamic color scheme per character type and powers depending on selected character type.
Added Ark and Zone log tabs and extended the configuration options.
Supporting upgrade from previous 1.12 version through sheetworker.

## Roll20 Requests

Comments are very helpful for reviewing the code changes. Please answer the relevant questions below in your comment.

- [X] Does the pull request title have the sheet name(s)? Include each sheet name.
- [X] Is this a bug fix?
   - Fixes a few bugs in previous version, e.g. Dice Pool not updating the Gear dice and the Rot points display.
- [X] Does this add functional enhancements (new features or extending existing features) ?
   - See above Changes/comments
- [X] Does this add or change functional aesthetics (such as layout or color scheme) ? 
   - See above Changes/comments
- [X] If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
   - Sheet versioning has been implemented, including setting new attributes as well as spellcorrecting old ones, using Forbidden Lands sheet versionator.
- [ ] If this is a new sheet, did you follow [Building Character Sheets standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) ?

If you do not know English. Please leave a comment in your native language.

### CODE REVIEW

**Comment by mperes** [comment]
Dear @dwarfwing, I had to revert your changes due to the fact that your pull request contained changes to translations multiple translations files that were conflicting with files generated to Crowdin. So, to keep things in order, we no longer accept translations submitted outside of Crowdin. To learn more about Crowdin and how to submit translations through Crowdin, please see our article on [How to Become a Translation Volunteer.](https://help.roll20.net/hc/en-us/articles/360058423993-How-to-Become-a-Translation-Volunteer) 
Thanks for all you do!

**Comment by dwarfwing** [comment]
@mperes By mistake I misspelled your shortname with a 'z' at the end. Might be this happens a bit, my name gets misspellt all the time. 

Anyways, thanks for all your help earlier, but it does seem the system ended up in some weird state where the new sheet was updated but in a incomplete state. The sheet HTML and CSS is there, but the translation was not updated and the sheetworkers rely on the translation to work properly. I will report

**Comment by jjake187** [comment]
Is there a time frame on when some of the major errors on this sheet will be fixed?

**Comment by dwarfwing** [comment]
@jjake187 This is dependent on the Roll20 review schedule. Afaik, they review these on a weekly basis, normally Sundays. New pull request is #9064.

**Pull request merged**
