### PR TITLE
[Generic Versatile] New Sheet

### PR DESCRIPTION
**Pull request by random-wizard**
# Submission Checklist
## Required

- [x] The pull request title clearly contains the name of the sheet I am editing.
- [x] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [x] The pull request makes changes to files in only one sub-folder.
- [x] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <Generic Versatile>  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <Homebrew> _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <d20> _(i.e. Dungeons & Dragons, FATE)_

- [x] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [x] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

I wanted a character sheet that is not tied to any one d20 system so I made a very generic one where you can add and name as many attributes and abilities as you want. This helps me when playtesting a new set of homebrew rules that might change as we play.

### CODE REVIEW

**Comment by BronsonHall** [comment]
Hey @random-wizard 

This is a really interesting idea!  Sheets we add to this repo are generally system-specific, to my knowledge we haven't added this generic a tool before.  That said, we're in agreement that there's inherent value to this sheet over just running a game without a character sheet template - we'd just need to decide if this repo's the right place for it, and what it'd have to be called when it's in there.  (calling it d20 SRD might be the way to go?)

I'm raising it to the team in a meeting tomorrow - I'll get back to you about this then. 

Thanks for your patience!

**Comment by random-wizard** [comment]
> This is a really interesting idea! 

Thank you. Let me know if there are ideas about what would make it more acceptable. One idea I was thinking is that if a weapon field had a string that matched a regexp for 1d6+1, 2d8, d100 then I could write some javascript to dynamically link the field to the dice roller.

But if it is rejected, I understand.

**Comment by BronsonHall** [comment]
Hey @random-wizard ,

We've discussed and are good to merge this in - though if you wouldn't mind renaming the sheet folder and references in readme, etc, to something a bit more specific?  "d20 Generic" or something similar should be fine, just to make it clear this is intended for primarily d20 systems.  Once you do that you're good to go!  

Thanks!

**Comment by BronsonHall** [comment]
Don't mind the label changes, just convincing our sheet management system to accept the folder name change :P - merging now!

**Pull request merged**
